### ISSUE TITLE
Unable to assign app role value which is larger than 120 characters. AzureAD console allows values larger than 120 characters.

### ISSUE THREAD

**Issue by clvt-kilic** [hashicorp/terraform-provider-azuread#1005]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Output of terraform -v

Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/azuread v2.33.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
app_role {
          allowed_member_types = [
              "User",
            ] 
          description          = "description" 
          display_name         = "display_name" 
          enabled              = true 
          id                   = "id" 
          value                = "value which cannot be longer than 120 characters"
        }
```

### Debug/panic Output

╷
│ Error: Value must be between 0-120 characters in length
│ 
│   with azuread_application.AWS_GovCloud,
│   on azuread_application.tf line 21, in resource "azuread_application" "AWS_GovCloud":
│   21: resource "azuread_application" "AWS_GovCloud" {
│ 
╵

### Expected Behavior

It is possible to add a value that is longer than 120 characters through the Azure Active Directory console.

### Actual Behavior

When trying to assign a value that is longer than 120 characters through terraform code it gives an error as described above.

### Steps to Reproduce

1. Create an azuread_application resource
2. Create a app_role inside this resource
3. Assign a value larger than 120 characters
4. Perform a terraform plan.

### Important Factoids

N/A

### References

N/A

**Comment by Threpio** [comment]
I understand that longer values can be assigned through the portal - Does anyone know what the limit is?

**Comment by clvt-kilic** [comment]
@Threpio It looks like the limit in the portal is 250 characters. Could this limit of 120 be raised to 250?

![image](https://user-images.githubusercontent.com/125033252/218129403-514e9a06-29dc-4996-8254-514e9280fd55.png)

**Comment by Threpio** [comment]
Yes in theory - The function needs to be looked at to determine where it is used because it is not used solely for this validation.

**Comment by manicminer** [comment]
@clvt-kilic Thanks for reporting. @Threpio is correct, we can expand this. 120 bytes used to be the limit but I guess it got increased at some point!
