### ISSUE TITLE
azuread_administrative_unit call fails in 2.34.0

### ISSUE THREAD

**Issue by chiragmarc** [hashicorp/terraform-provider-azuread#1015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_administrative_unit`

### Terraform Configuration Files

```hcl
data "azuread_administrative_unit" "AAD" {
  display_name = "AAD Users and Groups"
}
```

### Steps to Reproduce

1. `version 2.34.0`
2. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Thanks for reporting this issue. Looking at this closely, this does appear to be a regression in the latest release. We will ship a patch release today containing a fix for this, in the meantime you can pin to v2.33.0 to avoid this issue. Apologies for the inconvenience caused.
