### ISSUE TITLE
azuread_application_pre_authorized fails in v2.34.0 due to missing permissionIds

### ISSUE THREAD

**Issue by AaronCoad** [hashicorp/terraform-provider-azuread#1016]
Hi,

The following resource block works in v2.33.0 but not v2.34.0 with:
_ApplicationsClient.BaseClient.Patch(): unexpected status 400 with OData
error: Request_BadRequest: Expected property 'permissionIds' is not present
on resource of type 'PreAuthorizedApplication'_

```
locals {
  public_member_api_users = {
  user1 = {}
  user2 = {}
  }
  api_scope_ids = [for k, v in module.function.api_scopes : v]
}

resource "azuread_application_pre_authorized" "allowed_apps" {
  for_each              = local.public_member_api_users
  application_object_id = module.function.ad_application_object_id
  authorized_app_id     = azuread_application.external_client[each.key].application_id
  permission_ids        = local.api_scope_ids
}
```

For the moment we have enforced the versioning of the provider in our repository to v2.33.0.
Edit: Fixed markdown for code block.

**Comment by manicminer** [comment]
Thanks for reporting this issue. Looking at this closely, this does appear to be a regression in the latest release. We will ship a patch release today containing a fix for this, in the meantime you can pin to v2.33.0 to avoid this issue. Apologies for the inconvenience caused.
