### ISSUE TITLE
2.34.0 Azure AD provider breaks azuread_group_member

### ISSUE THREAD

**Issue by asifkd012020** [hashicorp/terraform-provider-azuread#1018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

TF Version 1.3.2-bundle-1.0.17
AzureAD Version 2.34.0

### Affected Resource(s)
azuread_group_member

### Terraform Configuration Files

```hcl
resource "azuread_group_member" "members" {
  for_each         = local.test
  group_object_id  = module.group[each.key].id
  member_object_id = module.spn[each.key].id
}

```

### Debug Output

 Error: Provider produced inconsistent result after apply
 
 When applying changes to
 module.adgroupmember.azuread_group_member.members["test"],
 provider "provider[\"registry.terraform.io/hashicorp/azuread\"]" produced an unexpected new value: Root resource was present, but now absent. 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Panic Output

NA

### Expected Behavior

The existing members of the group which were added through previous TFE runs should have been part of the state and the plan should have shown no changes required if there was no change to the members list.

### Actual Behavior

 Error: Provider produced inconsistent result after apply
 
 When applying changes to
 module.adgroupmember.azuread_group_member.members["test"],
 provider "provider[\"registry.terraform.io/hashicorp/azuread\"]" produced an unexpected new value: Root resource was present, but now absent. 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

Our code uses terraform Azure AD provider config as ~>2.0 
There were multiple Azure AD groups deployed and the service principals were added to the groups using azuread_group_member.
The information was part of state until 2.34 was released.
As soon as the new version of Azure AD provider was released and plan executed and the all group members list is removed from the state.
Every time I queue the plan the members are being added to the group.
I have removed the members from the group and re-queue the workspace with 2.34, the plan-1 adds them to the group(which is fine) and when I do second queue of workspace, the plan shows the members need to be added to the group(which are already member of the group).
Pinning the workspace AzureAD provider to =2.33 works fine and requeue doesn't cause the above behaviour.

### Steps to Reproduce

1. Create Azure AD group
2. Create Azure AD application
3. Add the application to group using member resource azuread_group_member
4. Use AzureAD provider 2.34 and try running terraform plan(you should see the app being re-added to the group)
5. Pin the provider to 2.33 and you wont see the same behaviour

**Comment by cvs79** [comment]
It's really broken but this error was already present in previous versions as well. See https://github.com/hashicorp/terraform-provider-azuread/issues/793.

But now it's happening all the time

**Comment by manicminer** [comment]
Thanks for reporting this issue. Looking at this closely, this does appear to be a regression in the latest release. We will ship a patch release today containing a fix for this, in the meantime you can pin to v2.33.0 to avoid this issue. Apologies for the inconvenience caused.
