### ISSUE TITLE
2.34 - Data Source: azuread_group - Incomplete members list

### ISSUE THREAD

**Issue by Ced-Aware** [hashicorp/terraform-provider-azuread#1019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.34.0
```

### Affected Resource(s)

* `azuread_group `

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.34"
    }
  }
}

data "azuread_group" "mixed" {
  display_name     = "A_GROUP_WITH_USERS_SPN_MSI"
  security_enabled = true
}

output "mixed" {
  value = data.azuread_group.mixed.members
}

data "azuread_service_principals" "spn" {
  object_ids     = toset(data.azuread_group.mixed.members)
  ignore_missing = true
}

output "spns" {
  value = data.azuread_service_principals.spn.application_ids
}
```

### Debug Output

If needed, I can provide a debug log, but it will require a thorough sanitization.

### Panic Output

No panic

### Expected Behavior

The member list must include SPN and MSI members.

### Actual Behavior

The data source only returns the users.

### Steps to Reproduce

1. `terraform plan`

### Screenshots

v2.34 - Not OK
![image](https://user-images.githubusercontent.com/111339964/219626259-357f785b-0e1f-4b92-982f-c4a15f271646.png)

v2.33 - OK
![image](https://user-images.githubusercontent.com/111339964/219626879-850a0745-1788-4b47-8d0b-ef3160391cc4.png)

**Comment by manicminer** [comment]
Thanks for reporting this issue and for taking the time to explain in detail. I believe this is a known regression and likely the same issue as reported in #1018. In order to better track this in one location, I'm going to close this one in favor of the earlier reported issue. We intend to have a fix for this merged shortly and a patch release later today. Please subscribe to #1018 for updates. Thanks again.
