### ISSUE TITLE
2.34.0 azuread_user updates on non-changed properties

### ISSUE THREAD

**Issue by HorizonNet** [hashicorp/terraform-provider-azuread#1020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform 1.3.8
AzureAD Provider 2.34.0

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

Normal configuration similar to the example below.

```hcl
resource "azuread_user" "example" {
  user_principal_name = "jdoe@hashicorp.com"
  display_name        = "J. Doe"
  mail_nickname       = "jdoe"
}
```

### Expected Behavior

When upgrading from 2.33.0 to 2.34.0 no change should happen.

### Actual Behavior

Terraform plan shows multiple changes to existing resources, such as claiming that `account_enable` for already enabled accounts should switch from `false` to `true`. Other properties, such as `usage_location`, `city`, etc. are also reported as newly added, even if they have been configured for a longer time already.

When running an apply the following error pops up

```
 UsersClient.BaseClient.Patch(): unexpected status 400 with OData error:
 Request_BadRequest: Invalid value specified for property 'mailNickname' of
 resource 'User'.
```

### Steps to Reproduce

1. Have an existing `azuread_user` resource
2. `terraform apply`

**Comment by manicminer** [comment]
Thanks for reporting this issue. Looking at this closely, this does appear to be a regression in the latest release. We will ship a patch release today containing a fix for this, in the meantime you can pin to v2.33.0 to avoid this issue. Apologies for the inconvenience caused.
