### ISSUE TITLE
Unable to find ID used for importing azuread_directory_role_assignment

### ISSUE THREAD

**Issue by jgschwendswica** [hashicorp/terraform-provider-azuread#1021]
The ID in the import sample of the documentation of the resource azuread_directory_role_assignment looks very strange:
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/directory_role_assignment

Where should I be able to find such an ID?

**Comment by nbaju1** [comment]
You can use [this](https://learn.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0) Microsoft Graph endpoint to get info (ID included) on directory role assignments.

**Comment by jgschwendswica** [comment]
Thanks, that solved my problem
