### ISSUE TITLE
azuread_user: Which Graph API Scopes are needed to destroy/delete a user

### ISSUE THREAD

**Issue by jgschwendswica** [hashicorp/terraform-provider-azuread#1042]
We recently moved from Directory Roles to using Graph API Scopes to grant permissions to our Service Principal used for the terraform deployment.

According to the documentation (https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/user) the SP needs the User.ReadWrite.All Graph API scope (which we granted admin consent for). 

However, during a deletion of a user, we received the following error:
 Error: Deleting user with object ID "b0d3349d-1811-4bec-9f6c-c17268a3823d", got status 403
│ 
│ UsersClient.BaseClient.Delete(): unexpected status 403 with OData error:
│ Authorization_RequestDenied: Insufficient privileges to complete the
│ operation.

Which Graph API Scopes are needed in order to delete a user?

**Comment by nbaju1** [comment]
From the MS Graph docs: "To delete users with privileged administrator roles in delegated scenarios, the app must be assigned the Directory.AccessAsUser.All delegated permission, and the calling user must have a higher privileged administrator role as indicated in [Who can perform sensitive actions](https://learn.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#who-can-perform-sensitive-actions)." Ref: https://learn.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0&tabs=http

Could this be the issue?

**Comment by jgschwendswica** [comment]
Thanks for the answer - Indeed this was the issue.
We were able to solve this issue by granting the service principal the directory role "Privileged Authentication Administrator".
The Graph Scope "UserAuthenticationMethod.ReadWrite.All" would probably do it as well, however, I haven't tested it.
