### ISSUE TITLE
ETA of 2.37

### ISSUE THREAD

**Issue by cedrox** [hashicorp/terraform-provider-azuread#1060]
Hello, do we have ETA for the 2.37 to be released ?

**Comment by manicminer** [comment]
@cedrox Thanks for opening the issue, I appreciate the repeated delay is frustrating. We generally try to keep the GitHub milestone for each version updated with the prospective release date, unfortunately the latest milestone was not updated a couple weeks back when it should have been.

The 2.37.0 release was unfortunately delayed by a few factors, some directly related to the provider and some out of our control. However, we are targeting this week and I have readied the release to go out later today.
