### ISSUE TITLE
v2.37.0 azuread_access_package_assignment_policy can_extend field missing

### ISSUE THREAD

**Issue by tomasmota** [hashicorp/terraform-provider-azuread#1065]
Documentation and first draft in the PR included a can_extend field, which is also in the [docs](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/access_package_assignment_policy#can_extend), but not in the schema: https://github.com/hashicorp/terraform-provider-azuread/blob/5f3f85f716cf0defa6e45173d6cd01fa6d9fe81a/internal/services/identitygovernance/access_package_assignment_policy_resource.go#L48

Because of this my terraform code is erroring out when trying to set this

**Comment by manicminer** [comment]
Thanks for reporting this @tomasmota, apologies for the docs error here - the property is actually called `extension_enabled`. We'll issue a documentation fix for this shortly.
