### ISSUE TITLE
azuread_group onpremises_group_type change appears during terraform plan even if writeback is disabled

### ISSUE THREAD

**Issue by dennis1f** [hashicorp/terraform-provider-azuread#1067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.37.0
``` 

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "aad_groups" {
  for_each = {
    for group in var.Groups :
      "${var.EnvironmentId}_${group.Role}_${group.Scope}" => group
  }

  display_name = "${var.EnvironmentId}_${each.value.Role}_${each.value.Scope}"
  security_enabled = true

  # Trying to get rid of onpremises_group_type change
  writeback_enabled = null
  onpremises_group_type = null

  # This one is an ugly one:
  # https://github.com/hashicorp/terraform-provider-azuread/issues/624
  # https://github.com/microsoftgraph/msgraph-metadata/issues/92
  # So during creation ms automatically adds the executing user as owner
  # However then complains about duplicate ids, because the executing user
  # is one of the owners.
  # Set the flag SkipOwner to true when creating resource and remove the flag again
  # once resource is created.
  owners = setunion(
    var.OwnerIds,
    toset([
      for owner in data.azuread_users.owners.users :
        owner.object_id if each.value.SkipOwner == null || each.value.SkipOwner == false || owner.object_id != data.azuread_client_config.current.object_id
    ])
  )

  members = each.value.Members
}
```

### Debug Output

https://gist.github.com/dennis1f/1eacc03071c3f3886b9d5fd104a2cb3b

### Expected Behavior
No change should show up during terraform plan

### Actual Behavior
I believe #964 introduced a regression when writeback is disabled for a group.
In our environment writeback is disabled: `"writebackConfiguration":{"isEnabled":null,"onPremisesGroupType":null}` response from MSGraph API
However since version 2.37.0 the following change appears during terraform plan.
```
  # azuread_group.aad_groups["xxx"] will be updated in-place
  ~ resource "azuread_group" "aad_groups" {
        id                         = "xxx"
      + onpremises_group_type      = "UniversalSecurityGroup"
        # (20 unchanged attributes hidden)
    }
``` 
It does not matter if and to what values the properties `writeback_enabled` and `onpremises_group_type` are set to.
I believe this change should not appear if `writeback_enabled` property is not set.

### Steps to Reproduce

1. `terraform plan`

### References

* [#964]

**Comment by lra** [comment]
Same issue.

Workaround: applying fixes the drift for us without any impact on the group.

**Comment by davegregoryatperspectum** [comment]
More of an issue for me than Ira -- I get permission denied when I try to apply, so I've had to pin to 2.36 for now.

**Comment by davegregoryatperspectum** [comment]
Also permission denied on creation of a new group with this provider, since it tries to set this property. Admittedly a consequence of my limited permissions, but I'd have struggled to identify the problem if I hadn't seen a drift/update failure earlier in the day

**Comment by ianlistopad-8451** [comment]
The default for the property onpremises_group_type coming from Azure seems to be "", but the [default in the new azuread provider](https://github.com/hashicorp/terraform-provider-azuread/pull/964/files#:~:text=ValidateFunc%3A%20validation.StringInSlice(%5B%5Dstring%7B) is "UniversalSecurityGroup". This causes terraform to always think there is a change on the first run of this provider version.

**Comment by manicminer** [comment]
Thanks for reporting this, and apologies for this regression. There are a couple of issues here. Firstly that configuring group writeback (even disabling it) should only be done when writeback is mentioned in the configuration. Secondly, it's not possible to unset the onpremises group type - this appears to be an API bug and this confusion unfortunately led to the unnecessary default value for this field.

I've opened a PR #1070 which I believe will fix this regression - in the event that writeback is not configured (i.e. all existing configurations prior to this release), groups will be created & updated as before. When writeback is enabled, and an onpremises group type is specified, it will be configured, but subsequently trying to unset `onpremises_group_type` will cause a ForceNew.

This fix is, unfortunately, a breaking change from v2.37.0, but the choice here is unfortunately about breaking the least number of users. We'll issue a patch release v2.37.1 containing this, in the coming hours. If you have created any new groups using v2.37.0, you may have to recreate them. Again, apologies for this - we strive to avoid breaking user configurations in this way but mistakes sometimes happen particularly with a seemingly straightforward but actually complex resource such as this one.

**Comment by lra** [comment]
@manicminer Thanks for the fix, I can't really test yet as the binary does not seem to be available yet:
```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/azuread: no available releases match the given constraints ~> 2.37.1
```
But if we applied our existing `azuread_group` using 2.37.0 to remove the drifts, are we stuck having to recreate our historical groups?

**Comment by tullydwyer** [comment]
https://github.com/hashicorp/terraform-provider-azuread/issues/1067#issuecomment-1512193574

We have around 50 AD groups (with manually added users) stuck in this state, is there a manual fix we can apply other than re-creating the AD groups or the ignore changes block?

**Comment by ianlistopad-8451** [comment]
@manicminer Thanks for the fix, It stopped the drift and since we didn't apply in hopes of a fix, terraform no longer wants to make a change on those groups, Thanks again

**Comment by manicminer** [comment]
@lra and @tullydwyer Unfortunately, yes, this means that you will need to recreate these affected groups or use the `ignore_changes` meta property to suppress the diff. This is due to an API bug which is preventing us from unsetting this field. Assuming the API bug will at some point be fixed, that will enable us to remove the conditional ForceNew which will enable you to remove the `ignore_changes` workaround.
