### ISSUE TITLE
Documentation for azuread_group 'inaccurate'

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azuread#1084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.3.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.37.2
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "security-admin" {
  display_name     = "security-admin"
  security_enabled = true
}
```

### Expected Behavior

I had expected the `assignable_to_role` value to be set to true because my group has `security_enabled = true`

### Actual Behavior

assignable_to_role is set to false

### Steps to Reproduce

1. `terraform apply`

### References

Documentation Page...  

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group#assignable_to_role the docs says

```
assignable_to_role) - (Optional) Indicates whether this group can be assigned to an Azure Active Directory role. Can only be true for security-enabled groups. Changing this forces a new resource to be created.
```

Because my resource has security_enabled set to true i had expected that assignable_to_role would also be true but it's not

If you can, some clarification would be nice.

* #0000

**Comment by manicminer** [comment]
@DevopsMercenary Thanks for opening this issue. I'm not sure how the documentation is inaccurate here? The `is_assignable_to_role` property can only be set to `true` for security-enabled groups, but you must still set it. All boolean properties in Terraform providers default to `false` unless otherwise specified in the documentation.

**Comment by DevopsMercenary** [comment]
Then I would modify the doc, for the second line, from 

> Can only be true for security-enabled groups. Changing this forces a new resource to be created.

to

Can only be set to true for security-enabled groups. Changing this forces a new resource to be created.
