### ISSUE TITLE
Link in documentation is broken for  application_published_app_ids

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azuread#1085]
In 

https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/data-sources/application_published_app_ids.md
the link [unofficial source of application IDs](https://github.com/manicminer/hamilton/blob/main/environments/published.go)
is broken.  I did a basic search and didn't find a new valid location

**Comment by manicminer** [comment]
@DevopsMercenary Thanks for reporting this broken link! We'll update this as soon as possible, but in the meantime the correct link is: https://github.com/hashicorp/go-azure-sdk/blob/main/sdk/environments/application_ids.go
