### ISSUE TITLE
 Error: Deleting access package resource and catalog association

### ISSUE THREAD

**Issue by cedrox** [hashicorp/terraform-provider-azuread#1091]
### Context 
When we try to delete our access package 

### Terraform (and AzureAD Provider) Version
2.37

### Affected Resource(s)

* `azuread_access_package_resource_package_association`

### Terraform Configuration Files
```
resource "azuread_group" "membership_group" {
  display_name     = "TFMembershipGroup"
  security_enabled = true

  members = [
    data.azuread_user.user01.object_id,
    data.azuread_user.user02.object_id,
  ]
}

data "azuread_user" "user01" {
  mail_nickname = "AdeleV"
}

data "azuread_user" "user02" {
  mail_nickname = "AlexW"
}

resource "azuread_group" "elevated_approvers_group" {
  display_name     = "TFElevatedApproversGroup"
  security_enabled = true
}

data "azuread_groups" "security_groups" {
  display_names = ["DATALAKE_RO"]
}

resource "azuread_group" "security_created_group" {
  display_name     = "TFSecurityGroup01"
  security_enabled = true
  
}

# For existing group, spn needs to be owner of the group
data "azuread_group" "security_group" {
  display_name = "DATALAKE_RW"
}

data "azuread_group" "security_group_ro" {
  display_name = "DATALAKE_RO"
}

resource "azuread_access_package_catalog" "test_catalog" {
  display_name = "azuread_access_package_catalog"
  description  = "TestAcc Catalog %[1]d for access assignment policy"
}

resource "azuread_access_package" "test_access_package" {
  display_name = "azuread_access_package"
  description  = "TestAcc Access Package %[1]d for access assignment policy"
  catalog_id   = azuread_access_package_catalog.test_catalog.id
  # resource_role_scope_id = "/providers/Microsoft.Management/managementGroups/00000000-0000-0000-0000-000000000000"
}

resource "azuread_access_package_assignment_policy" "test_access_package_assignment_policy_3" {
  display_name      = "azuread_access_package_assignment_policy_3"
  description       = "TestAcc Access Package Assignnment Policy 3"
  duration_in_days  = 1
  access_package_id = azuread_access_package.test_access_package.id
  requestor_settings {
    scope_type      = "SpecificDirectorySubjects"
    requests_accepted = true
    requestor {
      object_id    = azuread_group.membership_group.object_id
      subject_type = "groupMembers"
    }
  }

  approval_settings {
    approval_required = true
    approval_stage {
      approval_timeout_in_days = 5
      primary_approver {
        object_id    = azuread_group.elevated_approvers_group.object_id
        subject_type = "groupMembers"
      }
    }
  }
}

# List of Approved resources 
resource "azuread_access_package_resource_catalog_association" "example" {
  catalog_id             = azuread_access_package_catalog.test_catalog.id
  resource_origin_id     = azuread_group.security_created_group.object_id
  resource_origin_system = "AadGroup"
  # subject_type           = "groupMembers"
}

resource "azuread_access_package_resource_catalog_association" "access_to_existing_group" {
  catalog_id             = azuread_access_package_catalog.test_catalog.id
  resource_origin_id     = data.azuread_group.security_group.object_id
  resource_origin_system = "AadGroup"
}

resource "azuread_access_package_resource_catalog_association" "access_to_existing_group_ro" {
  catalog_id             = azuread_access_package_catalog.test_catalog.id
  resource_origin_id     = data.azuread_group.security_group_ro.object_id
  resource_origin_system = "AadGroup"
}

resource "azuread_access_package_resource_package_association" "example" {
  access_package_id               = azuread_access_package.test_access_package.id
  catalog_resource_association_id = azuread_access_package_resource_catalog_association.example.id
}
```

### Debug Output

│ Error: Deleting access package resource and catalog association with resource "GUID"@"AadGroup" and catalog id "GUID".
288│
289│ AccessPackageResourceRequestClient.BaseClient.Post(): unexpected status 400
290│ with OData error: InvalidDeleteResourceHasEntitlements: The resource:
291│ {ResourceName} can not be deleted because there are active
292│ entitlements.

### Expected Behavior

terraform destroy all the resources 

### Actual Behavior

When resources are deleted, we have a 400 on the delation of the object **azuread_access_package_resource_package_association**

### Steps to Reproduce

with code below do : 
1. `terraform apply`
2. `terraform destroy`

### Important Factoids

Azure public cloud 
[Proper permission with role and permission ](https://github.com/hashicorp/terraform-provider-azuread/issues/1069)

### References

https://github.com/hashicorp/terraform-provider-azuread/pull/903

**Comment by cedrox** [comment]
Hello @manicminer, 
Did you repro this bug ? Do you know if this is going to be tackle in the next release ? 
Thanks

**Comment by alexwilcox9** [comment]
291│ {ResourceName} can not be deleted because there are active
292│ entitlements.

I have had this error myself but I don't believe it's a bug in the provider. I was unable to delete the resource because there were users with active entitlements on those access packages. Mine was a bit weird though because the portal did not show any active assignments.
It turned out that it was due to a recent deleted user that was still in the deleted users section of AAD. I restored the user, the assignment re-appeared in the portal allowing me to remove it and then I was able to delete the AP

Hope that helps

**Comment by cedrox** [comment]
Having all deployment failing because of 1 manual assignement makes using these features a bit perilous.
Is it possible to check this assignement before deleting it and do a force delete before remove it ?
Thanks

**Comment by cedrox** [comment]
Hello I am also able to confirm that the access package resource and catalog association throw an error without active entitlements when trying to delete a brand new / never used access package...

**Comment by alexwilcox9** [comment]
Always worth using the latest version, although I don't see anything in the changelog that would suggest any changes to this behaviour.

The message about active entitlements come from Azure and Terraform is just presenting them to you. Are you able to delete the unused access package/catalog from the poral or do you get the same error?

**Comment by cedrox** [comment]
I have updated the provider to 2.39. remove the local state. Clean all resource on the portal. Apply / Destroy and same error.
If you have the demo tenant available, I encourage you to apply / destroy this simple code. You will see that this is not working
I have a 403 but my spn is global Admin...

I have 2 error 

╷
│ Error: Deleting access package resource and catalog association with resource "2568976e-31b9-453b-bbb7-4af8ffe90367"@"AadGroup" and catalog id "d712afef-0b20-4fa7-aaa9-21ded87ef45d".
│
│ AccessPackageResourceRequestClient.BaseClient.Post(): unexpected status 400 with OData error: InvalidDeleteResourceHasEntitlements: The resource: TFSecurityGroup01 can not be deleted because there are       
│ active entitlements.
╵
╷
│ Error: Waiting for deletion of access package assignment policy with object ID "67ade50d-dc99-41fe-8d71-1ff90dc1031c"
│
│ retrieving resource: AccessPackageAssignmentPolicyClient.BaseClient.Get(): unexpected status 403 with OData error: UnAuthorized: User is not authorized to perform the operation. Reason: Unauthorized
╵

**Comment by pmatthews05** [comment]
I too am having this problem. When developing it's a bit annoying as I'm having to manually remove the entries in the state file, and manually remove in the portal before deploying again.

I know this isn't a helpful comment, I can supply logs if you like, but it's been covered above. 

I'm using Service Principal with "EntitlementManagement.ReadWrite.All".

It seems to be a problem in the order the resources are deleted in.

**Comment by manicminer** [comment]
Thanks all, since this is surfacing these errors I think we'll look to add a warning note to the provider docs in the meantime.

**Comment by cedrox** [comment]
Hello and thanks @gittyNico, 
For me, you should have a force delete in the API. You cannot fail a complete deployment because there is somebody using the package. You should first delete assignment and then delete the package ?
Thanks

**Comment by cedrox** [comment]
Hello, here's the answer of Microsoft support on the ticket I open few hours ago : 


•	Indeed, for you to be able to [Delete an Access Package](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Faccesspackage-delete%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp&data=05%7C01%7Ccedric.folliot%40microsoft.com%7C5aed03aeb85f474457b008db60fd240b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210412613996790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=trJsaywGlkYpmmLCZeSVyagTSMS5jhq3ygN6WFHjfGU%3D&reserved=0) you need first to guarantee that there are no active assignments.
•	Now, to delete the Access Package Assignments it is true that we do not have a DELETE endpoint for that matter. Instead, you will be able to Delete the Access Package Assignment by adapting the [CREATE Access Package Assignment Request ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fentitlementmanagement-post-assignmentrequests%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp%23example-2-remove-an-assignment&data=05%7C01%7Ccedric.folliot%40microsoft.com%7C5aed03aeb85f474457b008db60fd240b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210412614153011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IaRizwS11vl7yTFylFDbyav3jqAwxMPyNZ4PrzFYARg%3D&reserved=0)to perform an "adminRemove" operation.
o	To get the list of AssignmentIds you can run the [GET ListAssignments](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fentitlementmanagement-list-assignments%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp&data=05%7C01%7Ccedric.folliot%40microsoft.com%7C5aed03aeb85f474457b008db60fd240b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210412614153011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCKXs0HjWwgOr%2F7HnOxKenq8CrIenV9XL5O1BIoYbQM%3D&reserved=0).
Although I understand the solution is a bit confusing in the docs, I personally tested the actions described on the bullet points above and I'm very confident that they will be of good help for you!

Thanks

**Comment by cedrox** [comment]
@manicminer, it seems that this is not be a limitation of graph API. 
@gittyNico, If I try to destroy the access package by api code, I have a successful 204
https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages/{{AccessPackageID}}

![image](https://github.com/hashicorp/terraform-provider-azuread/assets/10764310/5a9532f0-97ed-4c60-bec7-ad18d1e7f699)

If we delete access package, maybe we don't need to delete the association that come with it ? 
If we refer to Microsoft official documentation and what I could test, the only method that we can use is:
https://learn.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&tabs=http
Also maybe we need to mention that there is no active assignement when we try to delete.

Thanks

**Comment by cedrox** [comment]
Thanks for you answer. Can you clarify ? Do you mean that we cannot do full CRUD operations on access package ? You accept that the delete operation is not supported ? Then the workaround is the only way to delete my access package ?

**Comment by cedrox** [comment]
Hello @gittyNico, I ask the support to understand why this method is not in the graph:  https://elm.iga.azure.com/api/v1/accessPackages('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/accessPackageResourceRoleScopes
In the meantime if you have a working exemple of the workaround, it would be great. 
Thanks

**Comment by cedrox** [comment]
Hello, here's the answer of the MS support regarding this endpoint that could confirm that we have MSGraph endpoints available to remove resources from catalogs.

To get to these endpoints we can first check the [relationship that exists between “AccessPackageCatalog” and “AccessPackageResource”](https://learn.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-beta#relationships).
With this relationship in mind, to successfully remove Resources from an Access Package Catalog, we need to perform the following:
•	First, you need to [List the Access Package Catalog Resources](https://learn.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&tabs=http) (ObjectId of catalog can be obtained by running [this call](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-accesspackagecatalogs?view=graph-rest-beta&tabs=http)):
![Call01](https://github.com/hashicorp/terraform-provider-azuread/assets/10764310/2ae66cd1-8f56-449f-b026-e51be06a3855)

•	Afterwards you can successfully [remove the intended resource](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&tabs=http#example-5-create-an-accesspackageresourcerequest-for-removing-a-resource):
![Call02](https://github.com/hashicorp/terraform-provider-azuread/assets/10764310/e869ed19-e534-49f3-9bfa-1e0d196333dd)

**Comment by cedrox** [comment]
Additionally, to be able to [Delete an Access Package](https://learn.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&tabs=http) you need first to guarantee that there are no active assignments.
•	Now, to delete the Access Package Assignments it is true that we do not have a DELETE endpoint for that matter. Instead, you will be able to Delete the Access Package Assignment by adapting the [CREATE Access Package Assignment Request ](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&tabs=http#example-2-remove-an-assignment)to perform an "adminRemove" operation.
o	To get the list of AssignmentIds you can run the [GET ListAssignments](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignments?view=graph-rest-1.0&tabs=http).

It would be a great improvement for the future 

Hope that help

**Comment by alexwilcox9** [comment]
Hey, would any of you be able to see if the solution in my draft PR works for you?

I've given it a go in my environment and seem to be able delete pretty reliably
https://github.com/hashicorp/terraform-provider-azuread/pull/1124
