### ISSUE TITLE
app_role as a separate resource

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azuread#1093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently app_roles are created as an argument block in the `azuread_application` resource.  In scenarios where the application itself needs to be managed elsewhere, it would be useful to be able to use terraform to add and remove app roles indepentently.

### New or Affected Resource(s)

Current resource:
* azuread_application

Proposed new resource:
* azuread_application_app_role

### Potential Terraform Configuration

```hcl

data "azuread_application" "example" {
  display_name = "My First AzureAD Application"
}

resource "azuread_application_app_role" "example" {
    application_id = data.azuread_application.example.id
    allowed_member_types = ["User", "Application"]
    description          = "Admins can manage roles and perform all task actions"
    display_name         = "Admin"
    enabled              = true
    value                = "admin"
}
```

**Comment by DanielFrei64** [comment]
I second this. This would come in handy for managed identities application.
