### ISSUE TITLE
Allow public client flows

### ISSUE THREAD

**Issue by gstevens-kyriba** [hashicorp/terraform-provider-azuread#1102]
The latest version of AAD App Registrations lets you specify "Allow public client flows" - True/False.

![image](https://github.com/hashicorp/terraform-provider-azuread/assets/57924969/d0f74158-8df8-4728-8268-b3db4cac43a8)

Where is this managed by the App module in Terraform?
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application

I don't see it mentioned in the docs?

Thanks

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by manicminer** [comment]
Thanks for raising this issue @gstevens-kyriba. I believe the property you're looking for is [`fallback_public_client_enabled`](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application#fallback_public_client_enabled).

We use GitHub issues for tracking feature requests and bugs in the AzureAD provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get answers to any further questions on the community discussion portal.
