### ISSUE TITLE
Federated credential unable to locate the user assigned managed identity by object id

### ISSUE THREAD

**Issue by smartaquarius10** [hashicorp/terraform-provider-azuread#1106]
Hello,

Getting this error while creating federated credentials. We have tried id, client id and object id but none of them works. What should we pass in application_object_id

`Application with object ID "<object-id>" was not found`

```
azuread={
      source = "hashicorp/azuread"
      version = "2.39.0"
    }

resource "azuread_application_federated_identity_credential" "federated_cred" {
   application_object_id = azurerm_user_assigned_identity.identity_id.principal_id
  display_name          = "mynamespace--sadefault"
  description           = "Federated credential for namespace: mynamespace, service account: sadefault"
  audiences             = ["api://AzureADTokenExchange"]
  issuer                = var.oidc_issuer_url
  subject               = "system:serviceaccount:mynamespace:sadefault"
}
```

**Comment by manicminer** [comment]
Thanks for opening this issue @smartaquarius10. None of the attributes of `azurerm_user_assigned_identity` are usable here, you will need to use a data source to obtain the application object ID. For example:

```terraform
data "azuread_application" "example" {
  application_id = azurerm_user_assigned_identity.example.client_id
}

resource "azuread_application_federated_identity_credential" "example" {
  application_object_id = data.azuread_application.example.object_id
  // ....
}
```

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get answers for any further questions on the community discussion portal. Thanks!

**Comment by smartaquarius10** [comment]
@manicminer thanks 🙂

**Comment by smartaquarius10** [comment]
@manicminer still exactly same error is coming

**Comment by smartaquarius10** [comment]
Resolved after using **azurerm_federated_identity_credential**
