### ISSUE TITLE
cannot create Microsoft 365 group with dynamic membership

### ISSUE THREAD

**Issue by lexum-clementa** [hashicorp/terraform-provider-azuread#1108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform and azuread provider versions
* Terraform 1.3.6
* azuread 2.38.0

### Description
I cannot create a Microsoft 365 group with dynamic membership with Terraform. When I create a group where the property mail_enabled is _true_, the group must be of type _Unified_. The dynamic_membership {} block appears to be ignored completely during creation. I can then change the group to be dynamic using the console; running terraform plan reports no changes to the group, but modifying any property will cause the group to be replaced; I assume the new group would probably not be dynamic.

Steps to reproduce.
* Run the following code.
```
resource "azuread_group" "foo" {
  behaviors = [
    "SubscribeNewGroupMembers", # les événements du groupe sont envoyés par courriel.
    "WelcomeEmailDisabled"
  ]
  description = "Test."
  display_name = "Test Group"
  mail_enabled = true
  mail_nickname = "test.dynamic"
  owners = [
    data.azuread_user.a.object_id
  ]

  security_enabled = false
  types = ["Unified"]
  visibility = "Private"

  dynamic_membership {
    enabled = true
    rule = "(user.accountEnabled -eq True) and (user.companyName -eq \"CompanyName\")"
  }
}
```
This creates a Microsoft 365 group, but the membership will be marked as "Assigned" in the Azure AD console.

* Set the group to use dynamic membership.
* Running `terraform plan` reports no change.
* Put an additional owner in the owners = [] block. Terraform will ask to destroy the resource because the type is apparently of type "DynamicMembership".

```
Terraform will perform the following actions:

  # azuread_group.foo must be replaced
-/+ resource "azuread_group" "foo" {
      - administrative_unit_ids        = [] -> null
      - assignable_to_role             = false -> null
      ~ auto_subscribe_new_members     = true -> (known after apply)
      ~ external_senders_allowed       = false -> (known after apply)
      ~ hide_from_address_lists        = false -> (known after apply)
      ~ hide_from_outlook_clients      = false -> (known after apply)
      ~ id                             = "b0df0415-e66b-420f-9141-492cdfd7cc91" -> (known after apply)
      ~ mail                           = "test.dynamic@tenant.onmicrosoft.com" -> (known after apply)
      ~ members                        = [
          - "0f77393f-5683-43fc-beda-2bd76f8cc5e6",
            #snip lots of ids...
        ] -> (known after apply)
      ~ object_id                      = "b0df0415-e66b-420f-9141-492cdfd7cc91" -> (known after apply)
      + onpremises_domain_name         = (known after apply)
      + onpremises_group_type          = (known after apply)
      + onpremises_netbios_name        = (known after apply)
      + onpremises_sam_account_name    = (known after apply)
      + onpremises_security_identifier = (known after apply)
      ~ onpremises_sync_enabled        = false -> (known after apply)
      ~ owners                         = [
          + "4fe9761a-c3c3-4663-8a86-ae6dc6863eee",
            # (1 unchanged element hidden)
        ]
      + preferred_language             = (known after apply)
      - provisioning_options           = [] -> null
      ~ proxy_addresses                = [
          - "SMTP:test.dynamic@tenant.onmicrosoft.com",
        ] -> (known after apply)
      ~ types                          = [ # forces replacement
          - "DynamicMembership",
            # (1 unchanged element hidden)
        ]
        # (9 unchanged attributes hidden)

      ~ dynamic_membership {
          ~ rule    = "(user.accountEnabled -eq true) and (user.companyName -eq \"CompanyName\")" -> "(user.accountEnabled -eq True) and (user.companyName -eq \"CompanyName\")"
            # (1 unchanged attribute hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I have created a link to an issue which seems related.
### New or Affected Resource(s)

* azuread_group

### References

* #0946

**Comment by kenchan0130** [comment]
@clementa-lexum 

```tf
  types                   = ["Unified", "DynamicMembership"]
```

Specifying also `Unified` as above may work as you expect.
Can you try that?
