### ISSUE TITLE
`azuread_conditional_access_policy` - support for Workload Identities

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azuread#1138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Conditional Access for Workload Identities are now GA by Microsoft. The Azure AD Terraform Provider does not support configuring workload identities yet.

### New or Affected Resource(s)

Unsure if this should be added to `azuread_conditional_access_policy` or if its unique enough for its own resource

### Potential Terraform Configuration

TBC

### References
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/microsoft-entra-workload-identities-now-generally-available/ba-p/3402815

https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/workload-identity

* #0000

**Comment by manicminer** [comment]
Resolved with #1047
