### ISSUE TITLE
`review_type` in `azuread_access_package_assignment_policy` should accept `Manager`

### ISSUE THREAD

**Issue by benjy44** [hashicorp/terraform-provider-azuread#1149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

AzureAD version: 2.40.0

### Affected Resource(s)

* `azuread_access_package_assignment_policy`

### Terraform Configuration Files

```hcl
----
assignment_review_settings {
    enabled                         = true
    review_frequency                = "weekly"
    duration_in_days                = 3
    review_type                     = "Manager"
    access_review_timeout_behavior  = "keepAccess"
}
----
```

### Debug Output
```
Planning failed. Terraform encountered an error while generating this plan.


╷
│ Error: expected assignment_review_settings.0.review_type to be one of [Self Reviewers], got Manager
│ 
│   with azuread_access_package_assignment_policy.this["myPolicy"],
│   on assignment_policy.tf line 1, in resource "azuread_access_package_assignment_policy" "this":
│    1: resource "azuread_access_package_assignment_policy" "this" {
│ 
```

### Expected Behavior

The provider should accept `Manager` as a valid value for `review_type`

### Actual Behavior

The provider fails with the error above

### Important Factoids

Thew return from graph API for an existing resource that has manager enabled looks like this:
```
'accessReviewSettings': {'accessReviewTimeoutBehavior': 'keepAccess',
                          'durationInDays': 80,
                          'isAccessRecommendationEnabled': True,
                          'isApprovalJustificationRequired': True,
                          'isEnabled': True,
                          'recurrenceType': 'quarterly',
                          'reviewerType': 'Manager',
                          'reviewers': [{'@odata.type': '#microsoft.graph.groupMembers',
                                         'description': 'MyGroup',
                                         'id': 'xxx-xxx-xx-xx',
                                         'isBackup': True}],
                          'startDateTime': '2020-09-16T21:59:59.998Z'},

```

### References

Manager is not defined in https://github.com/manicminer/hamilton/blob/main/msgraph/valuetypes.go#L133
nor in https://github.com/hashicorp/terraform-provider-azuread/blob/main/internal/services/identitygovernance/access_package_assignment_policy_resource.go#L239
* #0000

**Comment by tjrobinson** [comment]
It looks like the [Microsoft documentation](https://learn.microsoft.com/en-us/graph/api/resources/assignmentreviewsettings?view=graph-rest-beta#properties) may be the cause of this, as it doesn't list "Manager" as a valid value.

I've opened this PR to get the documentation fixed: https://github.com/microsoftgraph/microsoft-graph-docs/pull/22230
