### ISSUE TITLE
azuread_application: Orphaned TERRAFORM_UPDATE objects

### ISSUE THREAD

**Issue by calebsutton** [hashicorp/terraform-provider-azuread#1151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_application`
* `azuread_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

These objects should have been cleaned up as part of an error handling process.
### Actual Behavior

In certain scenarios, if a deployment fails, the TERRAFORM_UPDATE object is left in AAD.
This clutters up AAD, represents a potential security issue, and can cause issues with future deployments.

### Steps to Reproduce

Try to deploy an application registration with a group as an owner.  It will fail.  Check azure ad for TERRAFORM_UPDATE objects and you should see one that was created but not cleaned up.

There are other scenarios that have caused this in my environment, but the above is one that I have recently verified.

### References

* #0000

**Comment by manicminer** [comment]
Hi @calebsutton, thanks for reporting this. The dangling object you observe having a display name of `TERRAFORM_UPDATE*` is the actual object you defined in Terraform, just with a temporary display name. It is normal practice to leave a failed resource in place when creation fails in Terraform - this normally enables you to inspect it and determine the reason for failure if it's not obvious from the error message. Within the provider, we endeavor to set the resource ID internally as early as possible, this allows Terraform to understand when a resource was partially created with some failure (e.g. tainted) and Terraform should clean this up when the apply is reattempted.

However, I definitely appreciate that it's unintuitive to leave these objects with a temporary display name as this makes it harder to identify and reason about. We have already resolved this for `azuread_group` and you should not see this temporary name for tainted groups except in the exceptional circumstance that the apply operation is killed at the exact point of a single PATCH operation. The `azuread_application` however still needs the same improvement to be made and I'll look to address this asap.

Can you elaborate a little more on the security aspect? For top-level objects like applications or groups, you would normally expect a newly created application/group to have no effective permissions or memberships, and so a dangling object from a tainted resource should in practice pose negligible risk.

**Comment by calebsutton** [comment]
Hi, thanks for the thorough response.

The specific issue we had is that the orphaned TERRAFORM_UPDATE object was causing subsequent runs to fail because the identifierUris value was the same as the application registration we were trying to deploy.

In regards to the security concern.  While I agree that short lived objects pose little risk, orphaned and unmanaged objects have a risk of being co-opted by a bad actor.

**Comment by manicminer** [comment]
Interesting, I'll do some testing as I would have expected the provider to clean those up on the subsequent apply. Should also be able to fix up the display name as I mentioned.
