### ISSUE TITLE
Example code of azuread_access_package_assignment_policy resource does not work

### ISSUE THREAD

**Issue by nguyenanhducs** [hashicorp/terraform-provider-azuread#1161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

- Terraform v1.5.3 on darwin_arm64
- AzureAD v2.40.0

### Affected Resource(s)

* `azuread_access_package_assignment_policy`

### Terraform Configuration Files

```hcl
resource "azuread_group" "example" {
  display_name     = "group-name"
  security_enabled = true
}

resource "azuread_access_package_catalog" "example" {
  display_name = "example-catalog"
  description  = "Example catalog"
}

resource "azuread_access_package" "example" {
  catalog_id   = azuread_access_package_catalog.example.id
  display_name = "access-package"
  description  = "Access Package"
}

resource "azuread_access_package_assignment_policy" "test" {
  access_package_id = azuread_access_package.test.id
  display_name      = "assignment-policy"
  description       = "My assignment policy"
  duration_in_days  = 90

  requestor_settings {
    scope_type = "AllExistingDirectoryMemberUsers"
  }

  approval_settings {
    approval_required = true

    approval_stage {
      approval_timeout_in_days = 14

      primary_approver {
        object_id    = azuread_group.test.object_id
        subject_type = "groupMembers"
      }
    }
  }

  assignment_review_settings {
    enabled                        = true
    review_frequency               = "weekly"
    duration_in_days               = 3
    review_type                    = "Self"
    access_review_timeout_behavior = "keepAccess"
  }

  question {
    text {
      default_text = "hello, how are you?"
    }
  }
}
```

### Expected Behavior

Terraform applies the configuration without any errors.

### Actual Behavior

Terraform throws the following error message:

```
╷
│ Error: Reference to undeclared resource
│ 
│   on test.tf line 18, in resource "azuread_access_package_assignment_policy" "test":
│   18:   access_package_id = azuread_access_package.test.id
│ 
│ A managed resource "azuread_access_package" "test" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on test.tf line 34, in resource "azuread_access_package_assignment_policy" "test":
│   34:         object_id    = azuread_group.test.object_id
│ 
│ A managed resource "azuread_group" "test" has not been declared in the root module.
```

### Steps to Reproduce

1. Save the code as `test.tf`
2. Run `terraform init`
3. Run `terraform plan`

I attempted to open a PR to update the example but encountered a permissions problem when creating a new branch.

**Comment by manicminer** [comment]
Thanks for reporting this @nguyenanhducs, it looks like some of the resources weren't named correctly. Appreciate your attempting a PR for this - you won't be able to push a branch however you should be able to fork the repository and submit a PR from there.

**Comment by nguyenanhducs** [comment]
@manicminer I've created a PR #1162  to fix it. Please review and merge this PR. Thank you!
