### ISSUE TITLE
`azuread_group_member` resource fails to refresh after the ID of the group has changed

### ISSUE THREAD

**Issue by LoicBer** [hashicorp/terraform-provider-azuread#1172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

* terraform 1.5.5, terraform 1.2.9
* azuread 2.39, azuread 2.41

### Affected Resource(s)

* `azuread_group_member`

### Terraform Configuration Files

Two separate modules, with **distinct tfstates**:

*  module1: AAD group using `azuread_group` resource

*  module2: Member of the new AAD group using `azuread_group_member` resource and the `azuread_group` data source 

#### module1: group
```hcl
data "azuread_client_config" "current" {}

resource "azuread_group" "group" {
  display_name     = "sample-group"
  owners           = [data.azuread_client_config.current.object_id]
  security_enabled = true
}
```

#### module2: group member

```hcl
data "azuread_client_config" "current" {}

data "azuread_group" "external_group" {
  display_name = "sample-group"
  security_enabled = true
}

resource "azuread_group_member" "group_member" {
  group_object_id  = data.azuread_group.external_group.id
  member_object_id = data.azuread_client_config.current.object_id
}
```

### Debug Output

After the following sequence:

1. `terraform apply` on module1 (create new AAD group)
2. `terraform apply` on module2 (create new member of the new AAD group)
3. `terraform destroy` and `terraform apply` on module1 (create a new ID for the AAD group)
4. `terraform apply` on module2 (reapply to refresh the new group member)

Terraform apply on module2 gives:

```
$ terraform apply
data.azuread_client_config.current: Reading...
data.azuread_group.external_group: Reading...
data.azuread_client_config.current: Read complete after 0s [id=*********]
data.azuread_group.external_group: Read complete after 1s [id=3d**********]
azuread_group_member.group_member: Refreshing state... [id=4c***********]
╷
│ Error: Retrieving members for group with object ID: "4c**************"
│
│   with azuread_group_member.group_member,
│   on main.tf line 9, in resource "azuread_group_member" "group_member":
│    9: resource "azuread_group_member" "group_member" {
│
│ GroupsClient.BaseClient.Get(): unexpected status 404 with OData error: Request_ResourceNotFound: Resource '4c***************' does not exist or one of its queried reference-property objects are not present.
╵
```

### Expected Behavior

Terraform refresh phase should pass without an error after discovering that the ID of the group has changed.  The resulting plan should indicate that the group member object must be replaced by a new object.

### Actual Behavior

Terraform state refresh fails while trying to query the AAD group with the ID that does not exist anymore.

### Steps to Reproduce

1. `terraform apply` on module1 (create new AAD group)
2. `terraform apply` on module2 (create new group member of the new AAS group)
3. `terraform destroy` and `terraform apply` on module1 (create a new ID for the AAD group)
4. `terraform apply` on module2 (reapply to refresh the new group member)

You can find a simple but complete reproducer repo here: https://github.com/LoicBer/azuread-groupmember-bug

### Important Factoids

We found two dirty workarounds to recover from the failed state, but they are not suitable:

1. Manually editing the tfstate to replace the old ID reference by the new one
2. Running apply without refresh using  `terraform apply -refresh=false`. In this case, the refresh phase is skipped and the azuread_group_member is being succesfully recreated

### References

The issue seems related to:
* #0791

**Comment by LoicBer** [comment]
Maybe this code snippet could be enriched to solve this issue:

https://github.com/hashicorp/terraform-provider-azuread/blob/56735bfad382172126e9d67a965beffc1d927fd9/internal/services/groups/group_member_resource.go#L121-L132

The `groupMemberResourceRead` function does not handle the case where `client.ListMembers` fails with a 404 error because the group is not found. This fails the refresh phase.

Maybe something like in the `groupResourceRead` function below could be done (line 1272) ?

https://github.com/hashicorp/terraform-provider-azuread/blob/56735bfad382172126e9d67a965beffc1d927fd9/internal/services/groups/group_resource.go#L1267-L1278

On this resource, the 404 error is handled by removing the resource from the state. It seems to me that the same logic could be implemented for the group member: if the group is not found during the "list member" call, it means that the group member does not exist and can be removed from the state, right ? Or is it not that simple ?

**Comment by manicminer** [comment]
Thanks for reporting and submitting a fix @LoicBer. I've merged your PR which will be included in the following release next week.
