### ISSUE TITLE
Feature Request: Support for Conditional Access "Authentication Strength"

### ISSUE THREAD

**Issue by nauxliu** [hashicorp/terraform-provider-azuread#1185]
### Description:
I am requesting support for the "Authentication Strength" feature in Conditional Access. Authentication Strength allows admins to specify which combination of authentication methods can be used to access a resource. This helps in ensuring only phishing-resistant methods are available for accessing sensitive resources and giving more flexibility for less sensitive ones.

Reference:
[Microsoft Documentation on Authentication Strengths](https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-strengths)

**Comment by manicminer** [comment]
Thanks for requesting @nauxliu. There is an open PR for this and we hope to add this soon.
