### ISSUE TITLE
azuread_application - updating existing app registration returns 403

### ISSUE THREAD

**Issue by fotto** [hashicorp/terraform-provider-azuread#1203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.42.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

to create new app registration

```hcl
resource "azuread_application" "test_app" {
  description = "Test Application to verify azuread terraform provider"
  display_name = "Test_App_Reg_Via_Terraform"
}
```
to force update of existing app registration (description modified)
```hcl
resource "azuread_application" "test_app" {
  description = "Test Application to verify azuread terraform provider - description updated"
  display_name = "Test_App_Reg_Via_Terraform"
}
```

### Expected Behavior

2nd run of "terraform apply --target azuread_application.test_app" (after changing app description in tf source)  finishes without error and description gets updatd.

### Actual Behavior

```
azuread_application.test_app: Modifying... [id=XXXXX]

...

│ Error: Could not update application with object ID: "XXXXX"
│
│   with azuread_application.test_app,
│   on applications.tf line 12, in resource "azuread_application" "test_app":
│   12: resource "azuread_application" "test_app" {
│
│ ApplicationsClient.BaseClient.Patch(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation.
╵
```

### Steps to Reproduce

preparation
* have terraform project with "azuread" provider
* create application.tf with content
  ```hcl
  resource "azuread_application" "test_app" {
    description = "Test Application to verify azuread terraform provider"
    display_name = "Test_App_Reg_Via_Terraform"
  }
  ```

1.  create app registration using `terraform apply --target azuread_application.test_app`. Assumption: that app doesn't exist, yet
2.  update `description` field of `azuread_application` resource in terraform source
3. re-run `terraform apply --target azuread_application.test_app`

### Important Factoids

IMHO the issue has nothing todo with missing permissions (despite the 403 error) since
updating the app's description using Azure CLI within same session works as expected

```
> az ad app update --id XXXXX --set description="updated via azure cli"
> az ad app show --id XXXXX  |grep description
  "description": "updated via azure cli",
```

### References

* #807 (reported the same error, but claimed it was a permission problem)

**Comment by fotto** [comment]
additional observation:  removal of app registration, i.e.  `terraform destroy --target azuread_application.test_app` , works as expected.

**Comment by sontr-n** [comment]
@fotto Hi, I'm facing this error, Do you have solutions for this besides removing the app registration

**Comment by fotto** [comment]
> @fotto Hi, I'm facing this error, Do you have solutions for this besides removing the app registration

@sontr-n Hi, no I don't have any workaround.  Facing this issue I decided not to use terraform for manage app registrations atm.

**Comment by manicminer** [comment]
If you are receiving a 403 error when trying to manage an application using Terraform, this is unequivocally an API permissions issue. Please refer to the documentation for `azuread_application` for more details on the permissions needed, in particular noting that the calling principal (i.e. your user account or service principal) should be listed as an owner of an application in most cases.

For a simpler implementation, you might also consider using the newly added `azuread_application_registration` resource, and associated virtual resources for managing different aspects of an application registration. The `azuread_application_registration` resource does not directly manage the owners of an application, which makes configuration simpler in the event of importing an existing application.

However, in both cases, the provider uses [the same API](https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http) and will require the same permissions. Note that needed permissions might vary by tenant depending on the security policies your organization might have in place, and if this applies I suggest engaging with your organization's cloud security team (or equivalent) to ensure the necessary permissions are in place.

However, if you have pursued these measures and are still getting a 403 error, please feel free to post a debug log which will contain necessary information for us to help you dig into this further, including the scopes or roles assigned to your principal, and the full request and response to each API call made during the Terraform operation.

**Comment by fotto** [comment]
Hi @manicminer,
many thanks for your response. The `azuread_application_registration` resource type seems to be quite new and wasn't available at the time I raised this issue.

I did a quick test comparison of `azuread_application_registration` and `azuread_application`.
I registred two apps using:

```
resource "azuread_application_registration" "test_app" {
  description = "Test Application created through resource azuread_application_registration"
  display_name = "Test_App_Reg_Via_Terraform"
}

resource "azuread_application" "test_app2" {
  description = "Test Application created through resource azuread_application"
  display_name = "Test_App_Reg2_Via_Terraform"
}
```
and then I updated the `description` of both and re-applied through terraform:

- using the new type `azuread_application_registration` the update of description worked as expected.
- with `azuread_application` I ran into the same issue as before.

It could still be some permission issue, but now I can experiment with the individual `azuread_application_*` resources to track it down.

@sontr-n  Please try out `azuread_application_registration` and the other new `azuread_application_*` resources as workaround

**Comment by fotto** [comment]
I've successfully tested creation and update of app registration using the individual resource.
The following resource types were used:

```
azuread_application_registration
azuread_application_api_access
azuread_application_app_role
azuread_application_optional_claims
azuread_application_owner
azuread_application_permission_scope
azuread_application_redirect_uris
``` 

No 403 errors.

@manicminer :  using the `azuread_application` I still get 403 response on update (despite the fact having "Global Administrator" permissions).
Since using the new resource types seems to work for our purposes it would be OK to not further pursue that issue.

**Comment by manicminer** [comment]
@fotto Thanks for the feedback, much appreciated.

The newly added `azuread_application_registration` resource intentionally doesn't manage the owners property and relies on the API to set it to a best default value. This is likely to vary depending on your particular context - it's likely you'll find that with your successfully created/updated applications that your calling principal is an owner of the resulting application. This can be achieved with the `azuread_application` resource but it's tricky because, again, the default value does vary. Once you've removed yourself as a necessary owner (intentionally or not), you will not longer be able to update that application.

Glad this is working for you with the newer resource! It was a design goal with these new resources to simplify application management, whilst also enabling configuration scenarios that aren't possible with the monolithic `azuread_application` resource. Since this is now working as expected, I don't believe there are any further changes to make here and so I'm going to close this issue as resolved. Please feel free to open additional issues if you encounter potential bugs using these, or any other resources in the provider. Thanks!
