### ISSUE TITLE
Access packages are deployed with disabled policies 

### ISSUE THREAD

**Issue by sujitks** [hashicorp/terraform-provider-azuread#1209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v3.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.42.0
### Affected Resource(s)

azuread_access_package_assignment_policy
* `azuread_XXXXX`

### Terraform Configuration Files

```
resource "azuread_access_package_assignment_policy" "archs_policy" {
  access_package_id = azuread_access_package.app_lz_package_archs.id
  display_name      = "assignment-policy-archs"
  description       = "Access package for LZ assignment policy"
  duration_in_days  = 90

  requestor_settings {
    scope_type = "AllExistingDirectorySubjects"
  }

  approval_settings {
    approval_required = true

    approval_stage {
      approval_timeout_in_days = 14

      primary_approver {
        object_id    = azuread_group.rbac-mgr-group[each.key].object_id
        subject_type = "groupMembers"
      }
    }
  }

  assignment_review_settings {
    enabled                        = true
    review_frequency               = "weekly"
    duration_in_days               = 3
    review_type                    = "Self"
    access_review_timeout_behavior = "keepAccess"
  }

  question {
    text {
      default_text = "Enter your manager's name"
    }
    required = true
  }
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
Access packages should be listed and available to request

### Actual Behavior
Access packages, catalogues and polices are deployed however they are not available in the myaccess portal to request. Policies are deployed with 'Enabled=False'.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by danieldklc** [comment]
I've just found the requests_accepted argument within the requestor_settings block. Setting this to 'true' will enable the policy :)

**Comment by sujitks** [comment]
Yes, @danieldklc. This works and makes the access package enabled. 

![image](https://github.com/hashicorp/terraform-provider-azuread/assets/1211513/2e729e88-d745-40ea-83f7-05e568efdb75)
