### ISSUE TITLE
Unable to configure optional_claims on azuread_application_registration (v2.44)

### ISSUE THREAD

**Issue by JensHeise** [hashicorp/terraform-provider-azuread#1217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v1.6.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.44.0
```

### Affected Resource(s)

* `azuread_application`
* `azuread_application_registration`

### Terraform Configuration Files

```hcl
resource "azuread_application" "redacted" {
  display_name = "redacted"

  optional_claims {
    access_token {
      name                  = "groups"
      essential             = false
      additional_properties = ["sam_account_name"]
    }

    saml2_token {
      name                  = "groups"
      essential             = false
      additional_properties = ["sam_account_name"]
    }

    id_token {
      name                  = "groups"
      essential             = false
      additional_properties = ["sam_account_name"]
    }

    id_token {
      name      = "email"
      essential = false
    }

    id_token {
      name      = "family_name"
      essential = false
    }

    id_token {
      name      = "given_name"
      essential = false
    }

    id_token {
      name      = "preferred_username"
      essential = false
    }
  }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I am trying to migrate my existing Azure AD App registration from `azuread_application` to the more granular `azuread_application_registration` under version 2.44.0. 
I can't seem to find the corresponding resource to the `optional_claims` block inside `azuread_application`.

The search in the codebase seems to suggest that the optional_claims are not configurable as of v2.44.0.
Any hints are highly appreciated! 
Thanks!

### Actual Behavior

N/A

### Steps to Reproduce

N/A

**Comment by manicminer** [comment]
Hi @JensHeise, thanks for reporting this omission. We are planning to add a new granular resource for optional claims in this week's provider release.
