### ISSUE TITLE
Fix import example in documentation for azuread_application

### ISSUE THREAD

**Issue by joonvena** [hashicorp/terraform-provider-azuread#1230]
Currently documentation states that the resource should be imported using pattern:
```
terraform import azuread_application.example 00000000-0000-0000-0000-000000000000
```

It should be instead:
```
terraform import azuread_application.example /applications/00000000-0000-0000-0000-000000000000
```

**Comment by dnisbet** [comment]
I get
` Error: parsing Resource ID "/applications/00000000-0000-0000-0000-000000000000": specified ID ("/applications/00000000-0000-0000-0000-000000000000") is not valid: uuid string is wrong length`

But works without the /applications/ path.

**Comment by manicminer** [comment]
@dnisbet Please ensure you are using the latest version of the provider
