### ISSUE TITLE
Documentation for azuread_application mentiones client_id instead of application_id

### ISSUE THREAD

**Issue by tskrgulja** [hashicorp/terraform-provider-azuread#1241]
Documentation on the following link contains a mistake:
[azuread_application](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application)

It mentions that *client_id* is exported but that attribute does not exist. Instead, it should say *application_id*.

**Comment by irontoby** [comment]
Found this issue because I'm trying to figure out the tons of deprecation warnings my module started throwing without any actual helpful message on how to fix. It looks like they're renaming `application_id` to `client_id`. So check the version of the provider that you're using and update to latest, it should be `client_id`.

**Comment by RockyMM** [comment]
@tskrgulja Actually, this is correct since 2.44.0. You can always change the version of the documentation in the dropdown in the breadcrumb near the top of the page.

**Comment by manicminer** [comment]
Thanks for reporting, as @irontoby says we are renaming `application_id` to `client_id` to improve usability. We will not remove any existing properties or attributes without releasing a new major version (e.g. v3.x) of the providera - although you will see deprecation warnings this is normal and can be deferred until it's convenient to update your configuration.

Per @RockyMM's comment, you can view documentation for all previous versions of the provider if you are not running the latest.

As there is nothing to fix at this time, I'm going to close this issue as unplanned. Please feel free to report any potential bugs you might encounter whilst / after upgrading to the latest version. Thanks!
