### ISSUE TITLE
PIM For Groups support

### ISSUE THREAD

**Issue by callum-stakater** [hashicorp/terraform-provider-azuread#1257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for AzureAD PIM for Groups now that the feature has gone GA:
https://learn.microsoft.com/en-us/entra/fundamentals/whats-new#general-availability---privileged-identity-management-for-groups

there does now appear to be some api as well:
https://learn.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-for-groups-api-overview?view=graph-rest-1.0

**Comment by drdamour** [comment]
hoping for group equivalent to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment  like `azuread_eligable_group_assignment` 

and https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_active_role_assignment

subset of request in #68

**Comment by mverlinden78** [comment]
This would be a very, very welcome addition

**Comment by hales8181** [comment]
Delighted to see a pull request for this work! Does anyone know how long it usually takes once a PR is approved for it to get to production?
