### ISSUE TITLE
hashicorp/azuread provider version 2.46.0 fails if provider hashicorp/azurerm is not explicitly initialized and if a valid Azure subscription is not found

### ISSUE THREAD

**Issue by indranil-chakraborty** [hashicorp/terraform-provider-azuread#1265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azuread_authentication_strength_policy" "example" {
  display_name = "Example Authentication Strength Policy"
  description  = "Policy for demo purposes"
  allowed_combinations = [
    "fido2",
    "password",
  ]
}
```
and 
```hcl

terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = "2.46.0"
    }   
  }
}

provider "azuread" {
  # Configuration options
  client_id     = "0000"
  client_secret = var.client_secret
  tenant_id     = "0000"  
}
```

### Expected Behavior

The plan should have been displayed without any errors.

### Actual Behavior

Saw error as below.
```text
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.
```

### Steps to Reproduce

1. Create a new TF project against a new Azure AD (Entra ID) tenant. Use service principal + secret to authenticate.
2. Attempt to use the provider to provision a resource. See sample code above.
3. Run `terraform plan`. 

Now, even if I go ahead an explicitly add the `azurerm` provider with an empty feature block, I receive an error (albeit a different one). At that point, I choose a dummy subscription ID for the `subscription_id` variable value (because this is an empty tenant with no subscriptions). Then, the error is:

```text
Original Error: populating Resource Provider cache: listing Resource Providers: loading results: unexpected status 404 with error: SubscriptionNotFound: The subscription '20000000-0000-0000-0000-000000000000' could not be found.
```

### References

* #0000

**Comment by manicminer** [comment]
@indranil-chakraborty Thanks for reporting this. The AzureAD provider is completely separate from the AzureRM provider - if you are getting these errors, then you must have an `azurerm_` resource somewhere in your configuration.
