### ISSUE TITLE
Provider crash - azuread_access_package_assignment_policy

### ISSUE THREAD

**Issue by timja** [hashicorp/terraform-provider-azuread#1271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_access_package_assignment_policy`

### Terraform Configuration Files

https://github.com/hmcts/azure-access-packages/tree/20168fae4955f1d214620e2f1f82f9477f76793c/components/access-packages

Plan that fails:
```hcl
# azuread_access_package_assignment_policy.this["self-approval:Non-Production Bastion Server Access"] will be updated in-place
  ~ resource "azuread_access_package_assignment_policy" "this" {
      ~ extension_enabled = false -> true
        id                = "be9136fb-774a-4e95-80ea-068710465516"
        # (4 unchanged attributes hidden)

      ~ approval_settings {
          - requestor_justification_required = true -> null
            # (2 unchanged attributes hidden)
        }

      ~ question {
          - sequence = 1 -> null
            # (1 unchanged attribute hidden)

          - text {
              - default_text = "Include JIRA link in business justification" -> null
            }
        }

        # (1 unchanged block hidden)
    }

```

### Debug Output

https://gist.github.com/timja/3bb3f957751338e0d599f842b5cefaf1

### Panic Output

https://gist.github.com/timja/5561efc8ba2b1c84d830696e7b87fc60

Trimmed version:
```
panic: runtime error: index out of range [0] with length 0

goroutine 458 [running]:
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.expandAccessPackageQuestions({0xc000154600, 0x1, 0x0?})
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/identitygovernance.go:239 +0xe5e
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.buildAssignmentPolicyResourceData({0x1c515b8, 0xc000b16e70}, 0xc00030c880, {0x19b46c0?, 0xc0001c7b00?})
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/access_package_assignment_policy_resource.go:477 +0x572
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.accessPackageAssignmentPolicyResourceUpdate({0x1c515b8, 0xc000b16e70}, 0xc00030c880, {0x19b46c0?, 0xc0001c7b00?})
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/access_package_assignment_policy_resource.go:374 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0004a6540, {0x1c51510, 0xc00032b680}, 0xd?, {0x19b46c0, 0xc0001c7b00})
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This seems to be consistently failing in my environment now, an API is responding with something the provider isn't handling

### References

* #0000

**Comment by timja** [comment]
Manually removing the question on the policy has allowed me to progress from here and the resource now works again.

**Comment by manicminer** [comment]
@timja Thanks for reporting this. It looks like this crash will happen it you specify an empty `text` block, which should be prevented by schema validation. I've opened #1273 to enforce this validation.

**Comment by timja** [comment]
> @timja Thanks for reporting this. It looks like this crash will happen it you specify an empty `text` block, which should be prevented by schema validation. I've opened #1273 to enforce this validation.

Not 100% sure. It was happening when the question was removed, hopefully that PR helps anyway

**Comment by manicminer** [comment]
> Not 100% sure. It was happening when the question was removed, hopefully that PR helps anyway

Interesting, thanks for the clarification. I'll test with this scenario and try to reproduce/mitigate.
