### ISSUE TITLE
azuread_authentication_strength_policy crashing plugin

### ISSUE THREAD

**Issue by iag-lucas-kelly** [hashicorp/terraform-provider-azuread#1272]
Issue creating an authentication policy in azuread 2.45 and 2.46 same error in both versions:

![image](https://github.com/hashicorp/terraform-provider-azuread/assets/143597530/0c45c579-0ec6-4e05-896c-450a97e6c844)
<img width="581" alt="image" src="https://github.com/hashicorp/terraform-provider-azuread/assets/143597530/c313d87f-2411-4352-a6df-cd45dc2ea5fe">

**Comment by iag-lucas-kelly** [comment]
stack trace:
Stack trace from the terraform-provider-azuread_v2.46.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 81 [running]:
github.com/hashicorp/terraform-provider-azuread/internal/services/conditionalaccess.namedLocationDataSourceRead({0x1043cf8, 0xc0006c0000}, 0x0?, {0xdaa220?, 0xc000037200?})
	github.com/hashicorp/terraform-provider-azuread/internal/services/conditionalaccess/named_location_data_source.go:99 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004035e0, {0x1043c50, 0xc0002a9710}, 0xd?, {0xdaa220, 0xc000037200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:795 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0004035e0, {0x1043c50, 0xc0002a9710}, 0xc000730100, {0xdaa220, 0xc000037200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1015 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003de378, {0x1043c50?, 0xc0002a9620?}, 0xc0007ad200)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1237 +0x366
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003c6780, {0x1043c50?, 0xc0002a8e70?}, 0xc000748000)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:699 +0x3de
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xe9a260?, 0xc0003c6780}, {0x1043c50, 0xc0002a8e70}, 0xc0007b1ce0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00026e1e0, {0x1048590, 0xc000470680}, 0xc00064c000, 0xc000431b00, 0x1648bc8, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1358 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc00026e1e0, {0x1048590, 0xc000470680}, 0xc00064c000, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1735 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 8
	google.golang.org/grpc@v1.57.1/server.go:981 +0x145

Error: The terraform-provider-azuread_v2.46.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by manicminer** [comment]
Thanks for reporting this bug @iag-lucas-kelly. It looks like the issue is actually in the `azuread_named_location` data source - I've opened #1274 to fix this.

The cause of the crash is incorrectly handling an empty result from the API, most likely caused by the named location not being found. In the interim, if you fix up your configuration to locate the named location (most likely a typo in the name), you should be able to avoid this crash.
