### ISSUE TITLE
Make it possible to grant consent on API permissions

### ISSUE THREAD

**Issue by karlschriek** [hashicorp/terraform-provider-azuread#1275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have what in my opinion is a very simple use case where I wish to be able to automate the creation of Azure AD Applications and Service Principles, and give the Application MS Graph permissions.

Currently I can do this as follows:

```terraform
resource "azuread_application_registration" "my_app" {
  display_name = "my_app"
}

resource "azuread_application_api_access" "example_msgraph" {
  application_id = azuread_application_registration.example.id

data "azuread_application_published_app_ids" "well_known" {}

data "azuread_service_principal" "msgraph" {
  client_id = data.azuread_application_published_app_ids.well_known.result["MicrosoftGraph"]
}
resource "azuread_application_api_access" "msgraph_permissions" {
  application_id = azuread_application_registration.my_app.id
  api_client_id  = data.azuread_application_published_app_ids.well_known.result["MicrosoftGraph"]

  role_ids = [
    data.azuread_service_principal.msgraph.app_role_ids["Application.ReadWrite.OwnedBy"],
    data.azuread_service_principal.msgraph.app_role_ids["Directory.Read.All"],
  ]
}

```

However, as a next step I have to go into the portal and hit the "Grant Consent" button under the "API Permissions" section of the application. So far I have not been able to find any resources that will allow me to give this consent.

### References

A similar issue is here, https://github.com/hashicorp/terraform-provider-azuread/issues/591, but this deal explicitly with Scopes, and the resulting solution (azuread_service_principal_delegated_permission_grant) is not what is needed for API permissions

**Comment by manicminer** [comment]
Hi @karlschriek, we do support this already, please see the [azuread_app_role_assignment resource](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/app_role_assignment).

Since we already support this feature, I'm going to close this out for now,. but please feel free to open more issues for additional feature requests.

**Comment by karlschriek** [comment]
For anyone else confused by this, here is an example of how to achieve the above.


```terraform
resource "azuread_application_registration" "my_app" {
  display_name = "my_app"
}

resource "azuread_service_principal" "my_sp" {
  client_id = azuread_application.my_app.application_id
}

data "azuread_application_published_app_ids" "well_known" {}

data "azuread_service_principal" "msgraph" {
  client_id = data.azuread_application_published_app_ids.well_known.result["MicrosoftGraph"]
}

locals {
  role_names = [ "Application.ReadWrite.OwnedBy", "Directory.Read.All"]
  role_ids = { for k, v in data.azuread_service_principal.msgraph.app_role_ids : k => v if contains(local.role_names, k) }
}

resource "azuread_application_api_access" "this" {
  application_id = azuread_application_registration.my_app.id
  api_client_id  = data.azuread_application_published_app_ids.well_known.result["MicrosoftGraph"]
  role_ids = [for k, v in local.role_ids : v]
}

resource "azuread_app_role_assignment" "this" {
  depends_on          = [azuread_application_api_access.this]
  for_each            = local.role_ids
  app_role_id         = each.value
  principal_object_id = azuread_service_principal.my_sp.object_id
  resource_object_id  = data.azuread_service_principal.msgraph.object_id
}

```

Note I haven't test whether both `azuread_application_api_access` and `azuread_app_role_assignment` are even necessary or if just `azuread_app_role_assignment` would actually be sufficient. But I can confirm that with only `azuread_application_api_access` the permissions are waiting for consent, whereas adding `azuread_app_role_assignment` (which is actually something that gets added to the service principal, not the application) has the effect of granting conseting.

**Comment by manicminer** [comment]
Just to clarify, the `azuread_application_api_access` is used for configuring API roles to be published by the _application registration_, whereas the `azuread_app_role_assignment` assigns those roles to a service principal. Typically you'd want both, so that they align, but you can assign API roles to a service principal without having the linked application configured for those.
