### ISSUE TITLE
Question Regarding the Use of "application_id" in Examples on Terraform Azure AD Provider Documentation

### ISSUE THREAD

**Issue by gogo25171** [hashicorp/terraform-provider-azuread#1286]
Hello HashiCorp Team,

I hope this message finds you well. I would like to bring up a question regarding the documentation on the following page: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password.

In the examples provided on this page, there is the use of the "application_id" parameter in the definition of the "azuread_service_principal" resource. Here is an excerpt from the example:

```
resource "azuread_service_principal" "example" {
  application_id = azuread_application.example.application_id
}
```

However, when using the Terraform extension for Visual Studio Code (VSCode), it appears that the "application_id" parameter is marked as deprecated. I would like to seek clarification on this matter by asking whether using "application_id" is still recommended despite its deprecated status in the VSCode environment.

Could you confirm whether it is still considered best practice to use "application_id" in this context or if there is a recommended alternative?

Thank you in advance for your time and assistance. Feel free to ask for additional information if needed.

Best regards,

**Comment by kbcz1989** [comment]
@gogo25171 Hello. application_id was deprecated in favor of client_id. Check here:
https://github.com/hashicorp/terraform-provider-azuread/issues/1286
https://github.com/hashicorp/terraform-provider-azuread/releases/tag/v2.44.0
