### ISSUE TITLE
Destroying "azuread_access_package_resource_package_association" throws error "NoGovernanceSku: This feature requires a Microsoft Entra ID Governance Subscription"

### ISSUE THREAD

**Issue by pmatthews05** [hashicorp/terraform-provider-azuread#1288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v1.6.6
azurerm v3.87.0
azuread v2.47.0

### Affected Resource(s)

* `azuread_access_package_resource_package_association`

### Terraform Configuration Files

```hcl
terraform {

}

provider "azurerm" {
    features {}
}

provider "azuread" {}

locals {
    catalog_name = "main-catalog"
    group_name = "Marketing resource"
    mail_name = "markres"
    access_package_name = "Marketing access package"
}

#Create an AD Group
resource "azuread_group" "ad_group" {
  description      = local.group_name
  display_name     = local.group_name
  mail_nickname    = local.mail_name
  mail_enabled     = false
  security_enabled = true
}

#Create an Access Package Catalog
resource "azuread_access_package_catalog" "access_package_catalog" {
  display_name       = local.catalog_name
  description        = local.catalog_name
  externally_visible = true
  published          = true
}

resource "time_sleep" "waiting_ad_group" {
    depends_on = [ azuread_group.ad_group ]
    create_duration = "30s"
}

#Add Group to Catalog
resource "azuread_access_package_resource_catalog_association" "adgroup_to_catalog" {
    depends_on = [ time_sleep.waiting_ad_group ]
    catalog_id = azuread_access_package_catalog.access_package_catalog.id
    resource_origin_system = "AadGroup"
    resource_origin_id = azuread_group.ad_group.object_id
}

#Create an Access Package
resource "azuread_access_package" "access_package" {
    catalog_id = azuread_access_package_catalog.access_package_catalog.id
    display_name = local.access_package_name
    description = local.access_package_name
    hidden = false
}

#Create an Access Package Resource Role
resource "azuread_access_package_resource_package_association" "resource_package_association" {
    access_package_id = azuread_access_package.access_package.id
    catalog_resource_association_id = azuread_access_package_resource_catalog_association.adgroup_to_catalog.id
}
```

### Debug Output
https://gist.github.com/pmatthews05/4b5bb74fa7e27afbdf778b12ecb27f1f

### Expected Behavior
Able to deploy and destroy resources without any error message. This used to work a few months back.

### Actual Behavior

It is able to deploy all resources in the Terraform file. When it comes to destroying (Or destroy due to change), it fails at the "Deleting access package resource and catalog association".

```
azuread_access_package_resource_catalog_association.adgroup_to_catalog: Destroying... [id=861db0b9-478d-41d3-92cd-fd6bf82f812a/defe3d35-9393-4cb9-9df9-546d94cc1114]
azuread_access_package.access_package: Still destroying... [id=65e727c3-22c3-481e-acca-5a2f513bb876, 10s elapsed]
azuread_access_package.access_package: Still destroying... [id=65e727c3-22c3-481e-acca-5a2f513bb876, 20s elapsed]
azuread_access_package.access_package: Destruction complete after 21s

Error: Deleting access package resource and catalog association with resource "defe3d35-9393-4cb9-9df9-546d94cc1114"@"AadGroup" and catalog id "861db0b9-478d-41d3-92cd-fd6bf82f812a".

AccessPackageResourceRequestClient.BaseClient.Post(): unexpected status 400 with OData error: NoGovernanceSku: This feature requires a Microsoft Entra ID Governance subscription. Learn more at
https://aka.ms/entra/identitygovernance.
```
It states it's due to missing Microsoft Entra ID Governance subscription, but it is possible to do, as below in important factoids section I've included a MS Graph PowerShell script that doesn't have the error message.

### Steps to Reproduce
>Note: My tenant is a Development tenant with E5 licenses. This is also happening on our production tenants, but all my testing for this issue report has been done inside a development tenant.

I'm using a Service Principal to run my Terraform this Service Principal has the following Graph API permissions:
Application.ReadWrite.All
AppRoleAssignment.ReadWrite.All
Directory.ReadWrite.All
EntitlementManagment.ReadWrite.All <-- The important one for Access Packages
Group.ReadWrite.All
Sites.FullControl.All
User.Read.All

1. Obtain the ClientID and Secret for the service principal
2. Log into Az Cli with your account.
3. Run the following PowerShell, ensuring you update `$clientId`, `$clientSecret` and `$subscriptionId` https://gist.github.com/pmatthews05/0e4895a2b3a4b6c5753dfb13486de20c
4. After completion, run the following powershell to destroy, ensuring you update `$clientId`, `$clientSecret` and `$subscriptionId` 
https://gist.github.com/pmatthews05/5e02caa2d49c8cb9325ac0b29a2ddfbd

### Important Factoids
This might seem like a simple license issue. However, I'm able to create and destroy the same using MS Graph PowerShell Module. I'm able to achieve the creation and destroy using the same Service Principal. Please update the  `$clientId`, `$clientSecret` and `$tenantId` in the following PowerShell script.
https://gist.github.com/pmatthews05/457791f01e13e336504b096d7318326e

**Comment by rjdecilos** [comment]
Experiencing the same exact thing right now:

```
azuread_access_package.reviewers_group: Destroying... [id=828ef003-9b29-42b3-aeac-97f4feda94d7]
azuread_access_package.reviewers_group: Still destroying... [id=828ef003-9b29-42b3-aeac-97f4feda94d7, 10s elapsed]
azuread_access_package.reviewers_group: Still destroying... [id=828ef003-9b29-42b3-aeac-97f4feda94d7, 20s elapsed]
azuread_access_package.reviewers_group: Destruction complete after 26s
╷
│ Error: Deleting access package resource and catalog association with resource "aca112c8-616c-4327-91a5-da5e875d0180"@"AadGroup" and catalog id "69ea2d11-1dc5-4fbb-9043-ebd707e09b98".
│
│ AccessPackageResourceRequestClient.BaseClient.Post(): unexpected status 400 with OData error: NoGovernanceSku: This feature requires a Microsoft Entra ID Governance subscription. Learn more at
│ https://aka.ms/entra/identitygovernance.
```

**Comment by natilik-mikeguy** [comment]
This appears to have gone away for me today in case anyone else wants to check. I've not had any licensing changes that I'm aware of!

**Comment by pmatthews05** [comment]
@natilik-mikeguy I've just attempted and I'm still getting the Error. I will try again on Monday just in case this is a change that has been made to the tenants, and the roll out hasn't upgraded mine yet.

**Comment by natilik-mikeguy** [comment]
Yeah sorry - I think I've just realised I'm being an idiot. I removed the group manually in the end. The change that succeeded a few minutes ago was adding a new group. I've been ill - blame it on that lol

**Comment by irfanj01** [comment]
Appears to be working as of today. I was getting the same error (on v2.41.0 of the provider) but today I am able to remove catalog resource associations.

**Comment by pmatthews05** [comment]
I can confirm this issue is resolved. I'm able to create and destroy without issue.
