### ISSUE TITLE
Import of azure identifier_uri fails with no object exists with the given id

### ISSUE THREAD

**Issue by papanito** [hashicorp/terraform-provider-azuread#1289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.6.4
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.11.0
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
+ provider registry.terraform.io/hashicorp/azurerm v3.85.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Affected Resource(s)

* `azuread_application_identifier_uri`

### Terraform Configuration Files

```hcl
local {
   api_uris = [ "https://example.net" ]
}

resource "azuread_application_identifier_uri" "uri" {
  for_each       = toset(local.api_uris)
  application_id = azuread_application.ar.id
  identifier_uri = each.value
}

import {
  to = azuread_application_identifier_uri.uri["https://example.net"]
  id = "/applications/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/identifierUris/aHR0cHM6Ly9leGFtcGxlLm5ldC8="
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

According to [azuread_application_identifier_uri | Resources | hashicorp/azuread | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_identifier_uri)

> Application Identifier URIs can be imported using the object ID of the application and the base64-encoded identifier URI, in the following format.

So I have an object which I want to import.

### Actual Behavior

Import just fails

```
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to
│ "azuread_application_identifier_uri.uri[\"https://example.net\"]", the provider detected that no object  
│ exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region   
│ or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

- I verified the application object id `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` which is correct.
- I verified the identifier_uri `https://example.net` and it is present in the object `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

N/A

**Comment by nbaju1** [comment]
Think you have the incorrect b64 encoding of your URI:

Base64 encoding of `https://example.net` results to `aHR0cHM6Ly9leGFtcGxlLm5ldA==`
Base64 encoding of `https://example.net/` results to `aHR0cHM6Ly9leGFtcGxlLm5ldC8=`

**Comment by papanito** [comment]
Interesting, I use `base64 (GNU coreutils) 8.32` and I get different results than @nbaju1 

```
echo https://example.net | base64
aHR0cHM6Ly9leGFtcGxlLm5ldAo=
```
and
```
echo https://example.net/ | base64
aHR0cHM6Ly9leGFtcGxlLm5ldC8K
```
