### ISSUE TITLE
`azuread_users` should support `mail` arg same as `azuread_user`

### ISSUE THREAD

**Issue by wingsofovnia** [hashicorp/terraform-provider-azuread#1297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azuread_user` has a very useful `mail` attribute for making a lookup by user's email implemented in #280. However, its twin `azuread_users` does not have it. It would be great to align those.

### New or Affected Resource(s)

* azuread_users

### Potential Terraform Configuration

```hcl
data "azuread_users" "YYYY" {
  mails = ["YYYY@ZZZZ.com", "TTTT@ZZZZ.com"]
}
```

### References

* #280
* #996

**Comment by Gonkers** [comment]
It looked like this might have been mentioned before in passing here... https://github.com/hashicorp/terraform-provider-azuread/issues/600#issuecomment-930560813

Based on how this works behind the scenes, `mail` and `mail_nicknames` are certainly not the same. This feature would definitely make my life easier.

```hcl
# This finds the user
data "azuread_user" "user_account" {
  mail = "user@example.com"
}

# This does NOT find the user
data "azuread_users" "user_accounts" {
  mail_nicknames = [ "user@example.com"]
}
```
