### ISSUE TITLE
Add "AppProtectionPolicy" to Conditional Access Grant Control

### ISSUE THREAD

**Issue by zach-griffin** [hashicorp/terraform-provider-azuread#1312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the provider does not support the "Require App Protection Policy" grant control. The currently supported "Require approved client app" is being sunset by Microsoft and they are requiring conditional access policies to migrate to the new "Require App Protection Policy" control. I would like to request that we add the AppProtectionPolicy control to supported built_in_controls here: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/conditional_access_policy#built_in_controls

### New or Affected Resource(s)

* azuread_conditional_access_policy

### Potential Terraform Configuration

```hcl
resource "azuread_conditional_access_policy" "sample-policy" {
  display_name = "Sample Policy"
  state        = "enabled"

  conditions {
    client_app_types    = ["All"]

    applications {
      included_applications = ["All"]
    }
    users {
      included_users = ["All"]
    }
  }
  
  grant_controls {
    operator          = "OR"
    built_in_controls = ["appProtectionPolicy"]
  }
}
```

### References

* https://learn.microsoft.com/en-us/entra/identity/conditional-access/migrate-approved-client-app
* https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-policy-approved-app-or-app-protection

**Comment by nbaju1** [comment]
This is already implemented by setting `built_in_controls = ["compliantApplication"]`.

**Comment by zach-griffin** [comment]
@nbaju1 good to know, thanks! We should probably still have that listed in the documentation somewhere though, right?

**Comment by nbaju1** [comment]
@zach-griffin, "compliantApplication" is listed as one of the options for `build_in_controls` in the docs, ref: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/conditional_access_policy#built_in_controls

**Comment by manicminer** [comment]
Thanks for requesting this @zach-griffin. As this seems to now be supported in the provider, I'll close this issue as resolved.
