### ISSUE TITLE
Add support for Dynamic Group membership

### ISSUE THREAD

**Issue by mikkoc** [hashicorp/terraform-provider-azuread#132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to be able to configure dynamic group membership from Terraform:
https://docs.microsoft.com/en-gb/azure/active-directory/users-groups-roles/groups-dynamic-membership

https://docs.microsoft.com/en-gb/azure/active-directory/users-groups-roles/groups-create-rule

(requires an Azure AD Premium P1 license)

### New or Affected Resource(s)

* azuread_group

**Comment by powellbc** [comment]
This really ought to be supported.

**Comment by lukebailey** [comment]
Agreed this is increasingly integral to many Azure AD setups

**Comment by manicminer** [comment]
Hi @mikkoc, thanks for requesting this feature! At the moment we are not in a position to implement support for dynamic group membership rules, as these are [exposed via the Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0#dynamic-membership), for which we do not yet have SDK support. We'll look at implementing this as soon as we are able to do so.

**Comment by sql-dr-watson** [comment]
@manicminer I believe this is all available in Graph API now

**Comment by mcalster** [comment]
Congrats on the major achievement in releasing 2.0 🎉🎉
That paves the road for this feature I assume? Is there a timeline for this feature yet?

**Comment by manicminer** [comment]
This feature is on our roadmap although there are a few large features ahead of it, so we don't have a specific timeframe as yet.
