### ISSUE TITLE
Adding authentication via path-based environment variables as provided by terraform-provider-azurerm

### ISSUE THREAD

**Issue by chancethecoder** [hashicorp/terraform-provider-azuread#1321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AzureAD provider already provides an authentication method based on [environment variables](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_client_secret#environment-variables), which are identical to those used by the AzureRM provider:

* ARM_CLIENT_ID
* ARM_CLIENT_SECRET
* ARM_TENANT_ID

In addition, I suggest that AzureAD should also offer the following file-based authentication methods:

* ARM_CLIENT_ID_FILE_PATH
* ARM_CLIENT_SECRET_FILE_PATH
* ARM_OIDC_TOKEN_FILE_PATH

By offering these options, I expect that both the AzureRM provider and the AzureAD provider can operate with the same system configuration without exposing secret keys in environment variables.

### Potential Terraform Configuration

```bash
$ export ARM_CLIENT_ID_FILE_PATH="/path/to/client_id"
$ export ARM_CLIENT_SECRET="/path/to/client_secret"
$ export ARM_OIDC_TOKEN_FILE_PATH="/path/to/oidc_token"
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#client_id_file_path
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#client_secret_file_path
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#oidc_token_file_path

**Comment by manicminer** [comment]
Hi @chancethecoder, thanks for opening this feature request. The AzureAD provider does actually already support all of these authentication variables, with the same behavior as the AzureRM provider. As such, I'm going to go ahead and close this issue, but thanks again for the suggestion and please feel free to submit additional feature requests.

**Comment by chancethecoder** [comment]
Hi, @manicminer

Thank you for letting me know that this is a feature already provided. I thought it was not supported as it was not specified in the document. Next time, I will create a more meaningful feature request. Thank you.

**Comment by manicminer** [comment]
@chancethecoder Thanks for the headsup, it looks like these aren't called out specifically in the authentication guides. They are listed in the [provider argument reference](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#argument-reference) though, if in doubt that's the best place to go :)
