### ISSUE TITLE
azuread_user: Support for "PasswordNeverExpire" option

### ISSUE THREAD

**Issue by lzadjsf** [hashicorp/terraform-provider-azuread#136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Times to times there is a need to set password never expire for Azure AD user account as it is a service account. It need to applications that still doesn't support latest authentication and authorisation mechanisms. Say, services which requires for LDAP bindings through Azure Active Directory Domain Services.

It can be easily done by PowerShell command:
```
Set-MsolUser -UserPrincipalName <user ID> -PasswordNeverExpires $true
```
By the way, there is a need to perform that kind of task through TF scripts during automatic deployment of service.

### New or Affected Resource(s)

* azuread_user

### Potential Terraform Configuration
```hcl
resource "azuread_user" "example" {
  user_principal_name = "jdo@hashicorp.com"
  display_name        = "J. Doe"
  mail_nickname       = "jdoe"
  password            = "SecretP@sswd99!"
  password_expiration  ="True|False"
}
```

### References

* https://docs.microsoft.com/en-GB/office365/admin/add-users/set-password-to-never-expire?view=o365-worldwide
* https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-policy

**Comment by lzadjsf** [comment]
Hello,

Any news?

**Comment by katbyte** [comment]
Hi @lzadjsf,

Thank you for opening this issue so we can track this feature. As that property is currently not exposed but the SDK this is not on our current roadmap to implement anytime soon.

**Comment by katbyte** [comment]
This might be possible via the additional properties map.. 🤔

**Comment by dbourcet-wiz** [comment]
@katbyte What do you mean by the additionnal properties map? It does interest me.

**Comment by manicminer** [comment]
This is supported by the Azure AD Graph API. I have logged an issue requesting SDK support.

https://github.com/Azure/azure-sdk-for-go/issues/9851

**Comment by alexwilcox9** [comment]
@manicminer for this one would you rather have an attribute called `password_policies` which is a string that can be set to `DisableStrongPassword`, `DisablePasswordExpiration` or `DisablePasswordExpiration, DisableStrongPassword`

Or would you prefer to have two Boolean attributes that we then use to construct the above string to send to the API?

https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties

**Comment by manicminer** [comment]
@alexwilcox9 Given this is an enumeration string with exclusivity rules, it would probably be best implemented as booleans in the provider so we can validate them nicely 👍
