### ISSUE TITLE
azuread_application_app_role always either deletes / recreates the role on each apply

### ISSUE THREAD

**Issue by AlexcFrench** [hashicorp/terraform-provider-azuread#1402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.8.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.51.0
+ provider registry.terraform.io/hashicorp/azurerm v3.107.0

### Affected Resource(s)

azuread_application_app_role

* `azuread_XXXXX`

### Terraform Configuration Files

```
resource "azuread_application" "appreg" {
  display_name = "test123"
}

resource "azuread_application_app_role" "role1" {
  application_id       = azuread_application.appreg.id
  role_id              = "6bd5554f-a935-4e9f-9223-c87a64c22fba"
  allowed_member_types = ["User"]
  description          = "desc"
  display_name         = "displayname"
  value                = "123"
}
```

### Debug Output

https://gist.github.com/AlexcFrench/8303351be3f32ac1fac99df9b618b11f

### Expected Behavior

once applied there should be no changes required on subsequent plan/apply runs

### Actual Behavior

a tf plan / apply creates the role
Another plan / apply deletes the role
Another plan / apply recreates the role

No code changes at any point

### Steps to Reproduce

tf init
tf plan
tf apply
tf plan
tf apply

1. `terraform apply`

### Important Factoids

MAY be related to #1344 ??

### References

* #0000

**Comment by manicminer** [comment]
Thanks for reporting this @AlexcFrench, you are correct that #1344 is related - in fact it's the same issue. Accordingly, I'll close this issue as a duplicate and ask that you subscribe to #1344 for updates, thanks!
