### ISSUE TITLE
azuread_privileged_access_group_eligibility_schedule fails RoleAssignmentRequestPolicyValidationFailed

### ISSUE THREAD

**Issue by akshaykagarwal277** [hashicorp/terraform-provider-azuread#1450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.9.3
azuread v2.53.1

### Affected Resource(s)

* `azuread_privileged_access_group_eligibility_schedule `

### Terraform Configuration Files

```hcl
resource "azuread_privileged_access_group_eligibility_schedule" "pim_eligible_role_assignment" {
  group_id             = var.group_id
  principal_id         = var.principal_id
  assignment_type      = "member"
  permanent_assignment = true
}
```

### Expected Behavior

Should create the new resource.

### Actual Behavior

Plans show the resource will be created. When running Apply, it fails with the below message

`
 Could not create assignment schedule request,
│ PrivilegedAccessGroupEligibilityScheduleRequestsClient.BaseClient.Post():
│ unexpected status 400 with OData error:
│ RoleAssignmentRequestPolicyValidationFailed: The following policy rules
│ failed: ["ExpirationRule"]

`

### Steps to Reproduce

1. `terraform apply`

If I add `duration` parameter, then the resource is deployed, but then it is restricted to only the duration that is mentioned, instead of it being a permanent on.

**Comment by txtmode** [comment]
This is due to a missing group role management policy, you need to do it like this

```
resource "azuread_group_role_management_policy" "this" {
  group_id = var.group_id
  role_id  = "member"

  eligible_assignment_rules {
    expiration_required = false
  }
}

resource "azuread_privileged_access_group_eligibility_schedule" "pim_eligible_role_assignment" {
  group_id             = var.group_id
  principal_id         = var.principal_id
  assignment_type      = "member"
  permanent_assignment = true

depends_on = [azuread_group_role_management_policy.this]
}
```

**Comment by akshaykagarwal277** [comment]
Is there also a way to define the role setting for the user or owner role that is present by default when we enable PIM ?
Like setting MFA required, approvers, etc.
