### ISSUE TITLE
AzureAD v3 - `azuread_conditional_access_policy` property `authentication_strength_policy_id` requires UUID

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azuread#1497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_3.0.0`

### Terraform Configuration Files

```hcl
resource "azuread_conditional_access_policy" "example" {
  display_name = "example"
  state        = "enabled"

  conditions {
    users {
      included_users  = []
      excluded_users  = [break-glass]
      included_groups = [group]
      excluded_groups = []
      included_roles  = []
      excluded_roles  = []
    }

    applications {
      included_applications = ["All"] 
      excluded_applications = []
    }

    platforms {
      included_platforms = ["all"]
      excluded_platforms = []
    }
    
    locations {
      included_locations = ["All"]
      excluded_locations = []
    }

    client_app_types = ["all"]
  } 

  grant_controls {
    operator          = "OR"
    authentication_strength_policy_id =  azuread_authentication_strength_policy.example.id
  }
}
```

### Panic Output

│ Error: expected "grant_controls.0.authentication_strength_policy_id" to be a valid UUID, got /policies/authenticationStrengthPolicies/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx

### Expected Behavior

It should accept the value `/policies/authenticationStrengthPolicies/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`

### Actual Behavior

It tries to validate the string `/policies/authenticationStrengthPolicies/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx` as a UUID, which it is not.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
@bubbletroubles Thanks for the report, we'll get this hotfixed

**Comment by wiebeck** [comment]
I got some errors as well that are probably related:

> Error: parsing ID for `azuread_directory_role_assignment`: uuid string is wrong length

In my state file the `id` definitely is no UUID but `lAPpYvVpN0KRkAEhdxReEIhi2cdseeBHlVb0CtWlFxM-1`

...and...

> Error: parsing ID for `azuread_service_principal_delegated_permission_grant`: uuid string is wrong length

Here the state shows an `id` like `eTzfYY6D4EWc7YpcVr6HY-HcBxbA1fRAi-m92VzNGkg`, so also no UUID.
