### ISSUE TITLE
Azuread provider version > 3 - azurerm_role_assignment referencing azuread_group object ID fails with "object ID should be a GUID"

### ISSUE THREAD

**Issue by MrNewgarden** [hashicorp/terraform-provider-azuread#1505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

+ Terraform v1.9.5 (on darwin_arm64)
+ provider registry.terraform.io/hashicorp/azuread v3.0.1 & 3.0.0
### Affected Resource(s)

* azuread_group.example
* azuread_group.example.id

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

"GUID" is outputted from azuread_group.example.id instead of "/groups/GUID"

### Actual Behavior

azuread_group.example.id = "/groups/GUID"

### Steps to Reproduce

1. `terraform apply`
2. Error "GUID should be alphabetic and numeric only"
3. Output is "/groups/GUID" instead of expected "GUID"
### Workaround
Downgrade provider to < 3.0.0, 2.53.1 for example
terraform state rm azuread_group.example
terraform apply

**Comment by kaplik** [comment]
i would say this is the same issue as this one - https://github.com/hashicorp/terraform-provider-azuread/issues/1500#issuecomment-2380014170

**Comment by manicminer** [comment]
Hi @MrNewgarden, @kaplik is correct, you need to use the `object_id` attribute and not the `id` attribute here.

Since this is working as expected, I'm going to close this so that we can focus on the outstanding bugs reports. Thanks!
