### ISSUE TITLE
v3.0.1 consuming huge amount of memory with pre-existing v.2.53.1 tfstate

### ISSUE THREAD

**Issue by javespru** [hashicorp/terraform-provider-azuread#1514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_3.0.1`
* `terraform 1.9.7`
* 
### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
My terraform configuration files consist of 181 groups with an average of 30 users per group. 
It worked ok with v.2.53.1 of the provider in a VM with 16 GB.
### Debug Output

N/A

### Panic Output

N/A
### Expected Behavior

After upgrading to provider 3.0.1 I added up just **1 user** to any group, run 
1. terraform init --upgrade
2. terraform apply

And the user should be provisioned.
### Actual Behavior

With my original VM where I ran previously (v.2.53.1) the given configuration I got a gRPC error related to lack of memory (I verified with the top command)
If I increase the VM RAM to 128 GB, it takes a while, but in the end, the VM's memory is exhausted.

### Steps to Reproduce

Having a huge configuration of groups and users 180+, migrate the provider from v.2.53.1 to v.3.0.1
1. `terraform apply`

### Important Factoids

N/A

**Comment by javespru** [comment]
My provider file is case is relevant
_terraform {
  required_version = ">= 1.5.1, <= 1.9.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.3"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "3.0.1"
    }

  }

  backend "azurerm" {
    subscription_id      = "XXXXXX"
    resource_group_name  = "easa-comm-rgp-01-seed"
    storage_account_name = "tfseedcom22uqwswrh"
    container_name       = "d4s-seed-common"
    key                  = "d4s-infra/011-group-users.tfstate"
  }

}

provider "azurerm" {
  features {}
  subscription_id = "XXXXXX"
  resource_provider_registrations = "none"
}

provider "azuread" {
  tenant_id = "YYYYYYYY"
}_

**Comment by javespru** [comment]
I tested with a fresh new tfstate v3.0.1 and 1 group with 2 users, and it exhausted 16 GB RAM

test.tf

```
resource "azuread_group" "group-test-01" {
  display_name = "delete-group-test-1212"

  security_enabled = true

  owners = ["27478bc9-e081-4144-9063-xxxx"]
  members = [
    "27478bc9-e081-4144-9063-yyy",
    "250a11b2-0b4b-4b24-adf2-yyy"
  ]
}
```
error message
```
Error: Request cancelled
│ 
│   with azuread_group.group-test-01,
│   on test.tf line 1, in resource "azuread_group" "group-test-01":
│    1: resource "azuread_group" "group-test-01" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
```

**Comment by cohendiego** [comment]
We are noticing this exact same behavior with this latest version of azure_ad provider.

**Comment by donjuanmon** [comment]
Same here, only azuread_group is displaying this behavior for us.

**Comment by jonashoye** [comment]
I already posted this behaviour a few days ago here https://github.com/hashicorp/terraform-provider-azuread/issues/1507

**Comment by javespru** [comment]
Ok, thank you. I will close this issue as duplicated with #1507
