### ISSUE TITLE
Reading azuread_group hangs in plan step after upgrading azuread to v3

### ISSUE THREAD

**Issue by random-user0** [hashicorp/terraform-provider-azuread#1522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform: 1.9.2
azuread: 3.0.2 

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
data "azuread_group" "group-name" {
  object_id = "XXX"
}
```

### Expected Behavior

The `terraform plan` command should complete.

The plan command completes successfully when run with version 2.53.1 of the azuread provider. 

### Actual Behavior

When running the `terraform plan` command, the process hangs on reading the data resource.  

`data.azuread_group.group-name: Still reading... [9m40s elapsed]`

### Steps to Reproduce

1. Update azuread provider to version 3
2. Run `terraform plan`

**Comment by Threpio** [comment]
Hi @random-user0, 

Can you confirm the number of group_members that are in the group? 
(The latest version of the provider has had some issues regarding the sync of groups with large numbers)

**Comment by random-user0** [comment]
@Threpio The group has at least a thousand members. So the issue you mentioned is likely the culprit.
