### ISSUE TITLE
[BUG] Possible issue with Azurerm_role_assignment Principal_ID not parsing properly - adds /servicePrincipal/ before GUID - PLEASE FIX ASAP. 

### ISSUE THREAD

**Issue by leonrob** [hashicorp/terraform-provider-azuread#1553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `3.0.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

It should only parse out the service principal GUID

### Actual Behavior

Instead it parses out the service principal like this:

`"The Principal ID '/servicePrincipals/3d1bc85d-d8a5-43bc-an2Z-6df6f6ed6e6d' `

It adds the /servicePrincipals/

I also had another one this happened on that was /groups/ and /users/

```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" Message="The Principal ID '/servicePrincipals/3d1bc85d-d8a5-43bc-an2Z-6df6f6ed6e6d' is not valid. Principal ID must be a GUID."

  with module.lr-rsmq-redis-standard-prod.azurerm_role_assignment.sp_iam["redacted"],
  on .terraform/../../redacted.tf line 97, in resource "azurerm_role_assignment" "sp_iam":
  97: resource "azurerm_role_assignment" "sp_iam" {
```

Added redacted to sensitive values.

### Steps to Reproduce

A random whitespace change could bring this back up for us. Our existing modules are all impacted. 

1. `terraform apply`

### References

* #0000

**Comment by leonrob** [comment]
For what it's worth it seems like they were trying to fix here
https://github.com/hashicorp/terraform-provider-azuread/pull/1499

**Comment by caracostea** [comment]
I'm also seeing this issue. Apparently the id now has a format like this: `/servicePrincipals/GUID` which is not accepted by the `azurerm` provider.

`Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" Message="The Principal ID '/servicePrincipals/REDACTED_SERVICE_PRINCIPAL_ID_GUID' is not valid. Principal ID must be a GUID."`

We are using the `id` property of the `azuread_service_principal` resource.

**Comment by leonrob** [comment]
> I'm also seeing this issue. Apparently the `id` now has a format like this: `/servicePrincipals/GUID` which is not accepted by the `azurerm` provider.
> 
> `Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" Message="The Principal ID '/servicePrincipals/REDACTED_SERVICE_PRINCIPAL_ID_GUID' is not valid. Principal ID must be a GUID."`
> 
> We are using the `id` property of the `azuread_service_principal` resource.

here's a workaround that could get you by for now

`split("/", each.value.object_id)[length(split("/", each.value.object_id)) - 1]`

**Comment by caracostea** [comment]
Thanks a lot! For now, I've just rolled back to the previous working version, but I will consider this solution if it does not get patched soon.

Do you know of any plan to address this?

**Comment by leonrob** [comment]
> Thanks a lot! For now, I've just rolled back to the previous working version, but I will consider this solution if it does not get patched soon.
> 
> Do you know of any plan to address this?

I do not. My guess is more and more people will start noticing this and reporting it. Hopefully soon

**Comment by manicminer** [comment]
No fix is needed here, the correct attribute to use is `object_id` not `id`

`id` looks like `/servicePrincipals/10000000-2000-3000-4000-500000000000`
`object_id` looks like `10000000-2000-3000-4000-500000000000`
