### ISSUE TITLE
Support oauth2AllowIdTokenImplicitFlow in azuread_application

### ISSUE THREAD

**Issue by rdbartram** [hashicorp/terraform-provider-azuread#163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to be able to support additional properties of app registrations such as oauth2AllowIdTokenImplicitFlow

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "test" {
    name = "test"
    oauth2AllowIdTokenImplicitFlow = true
    ...
}
```

### References

https://docs.microsoft.com/en-gb/azure/active-directory/develop/reference-app-manifest

**Comment by scivm** [comment]
It is already supporting oauth2AllowImplicitFlow.  Is it more then trivial case to enable oauth2AllowIdTokenImplicitFlow?

**Comment by scivm** [comment]
There was this issue in the azure sdk for go.  https://github.com/Azure/azure-sdk-for-go/issues/4478.   It appears that the oauth2AllowIdTokenImplicitFlow is not exposed in the azure sdk for go.   I believe this would need to happen first?

**Comment by rdbartram** [comment]
this should be a rather trivial changed...but as you said, the change needs to happen in the sdk first.

**Comment by katbyte** [comment]
this is still blocked as the SDK still doesn't support `Oauth2AllowIdTokenImplicitFlow` property

**Comment by manicminer** [comment]
It appears the AAD Graph API doesn't support this property either, so it's likely our only option is going to be via MS Graph.
