### ISSUE TITLE
azuread_group: Allow Display Name to be changed

### ISSUE THREAD

**Issue by AdmiralEgg** [hashicorp/terraform-provider-azuread#176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary

Could we allow updates to the display name of an azuread_group resource **without** having to force a new group to be created.

Currently, changing a group name forces the creation of a new group resource. This is an issue if groups have members which aren't managed by Terraform, as on changing the name all group members are lost.

A group name change be changed in the portal, and the 'displayName' property in the Group Entity appears to support Updates, 
https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#group-entity

### New or Affected Resource(s)

* azuread_group

Docs link: https://www.terraform.io/docs/providers/azuread/r/group.html

**Comment by katbyte** [comment]
Hey @AdmiralEgg, it doesn't look like there is anything in the SDK to allow for updating a group name, so sadly this is blocked until msft exposes that functionality.

**Comment by manicminer** [comment]
Related upstream issue: https://github.com/Azure/azure-sdk-for-go/issues/9911

**Comment by nitmatgeo** [comment]
Also will recommend to add another Resource: **azuread_group_owners** similar to [azuread_group_member](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group_member). This will help to configure multiple owners or add/remove owners, otherwise, this is causing an issue when we use CSV files to create groups/owners. 

Please let me know if you require to create a separate request to implement this feature.

**Comment by manicminer** [comment]
@nitmatgeo Thanks for the suggestion, could you open a new issue with this feature request?

**Comment by nitmatgeo** [comment]
@manicminer Sure, please refer to #435. Hope that's fine 👍
