### ISSUE TITLE
Support accessTokenAcceptedVersion in azuread_application

### ISSUE THREAD

**Issue by scivm** [hashicorp/terraform-provider-azuread#188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```
resource "azuread_application" "test" {
    name = "test"
    accessTokenAcceptedVersion = 2
    ...
}
```

Possible values for accesstokenAcceptedVersion are 1, 2, or null. If the value is null, this defaults to 1, which corresponds to the v1.0 endpoint.

### References

https://docs.microsoft.com/en-gb/azure/active-directory/develop/reference-app-manifest

**Comment by scivm** [comment]
This parameter is not yet exposed in the azure sdk for go.   I will go and troll them.  Or maybe fix it there first.

**Comment by scivm** [comment]
It is not even exposed in the Azure API

**Comment by manicminer** [comment]
It doesn't look like there is currentlty support for this property in AAD Graph or MS Graph. I found a related issue requesting support here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/7435

**Comment by manicminer** [comment]
Actually it looks like it might be supported with a different property name on MS Graph: https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-beta

**Comment by imbatman4711** [comment]
We are currently trying to maintain our API users stored in AAD with Terraform. 
It seems that this is a critical feature for this purpose.

If I look at the code, I do not even have an idea how to integrate that feature so I am not able to bring in a sufficient pull request.

But if anyone could pick that up, it would be highly appreciated.

**Comment by manicminer** [comment]
At the moment we don't have a way to utilise MS Graph endpoints, however we are looking at implementing it, and then we'll be able to support this.

**Comment by haodeon** [comment]
For anyone interested, this is how I managed to get it working in terraform

```
  provisioner "local-exec" {
    command = "az rest --method PATCH --uri \"https://graph.microsoft.com/v1.0/applications/${azuread_application.yourapi.id}\" --body '{\"api\":{\"requestedAccessTokenVersion\":2}}' --headers \"Content-Type=application/json\""
  }
```

Most of the credit goes to @SimonWahlin. His blog had 90% of the answer.

**Comment by drdamour** [comment]
@manicminer is this something on target for the AD 2.0 provider?

**Comment by drdamour** [comment]
@haodeon link to blog you mentioned?

**Comment by SimonWahlin** [comment]
Probably a bit late, but I guess this is the post he was referring to:
https://blog.simonw.se/azure-functions-and-azure-ad-authentication

**Comment by GenesisCoast** [comment]
FYI to get @haodeon's solution working I had to do the following:
```
resource "null_resource" "access_token_accepted_version" {
  depends_on = [
    azuread_application.main
  ]
  provisioner "local-exec" {
    command = <<EOF
      az rest \
        --method PATCH \
        --headers "Content-Type=application/json" \
        --uri "https://graph.microsoft.com/v1.0/applications/${azuread_application.main.id}" \
        --body '{"api":{"requestedAccessTokenVersion":2}}'
    EOF
  }
}
```

Otherwise I would get the following error:
```
Error: Error running command 'az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/<object_id>" --body '{"api":{"requestedAccessTokenVersion":2}}' --headers "Content-Type=application/json"': exit status 1. Output: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 16, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 816, in send_raw_request
  File "_collections_abc.py", line 837, in update
ValueError: not enough values to unpack (expected 2, got 1)
To open an issue, please run: 'az feedback'
```

Hopefully this helps someone.

**Comment by blaineross** [comment]
Hey there @GenesisCoast , I think this is what I need but whenever I try and run this I get an error saying I need to perform an AZ login. I modified your example to do an az login call beforehand (see below) but now get an error saying there are insufficient privilges to run the command. Could you share the permissions your service principal has that allows this to run? Cheers

```
resource "null_resource" "access_token_accepted_version" {
  depends_on = [
    azuread_application.appname
  ]
  provisioner "local-exec" {
    command = <<EOF
      az login --service-principal --username ${var.az_client_id} --password ${var.az_client_secret} --tenant ${var.az_tenant_id}
      az rest \
        --method PATCH \
        --headers "Content-Type=application/json" \
        --uri "https://graph.microsoft.com/v1.0/applications/${azuread_application.appname.id}" \
        --body '{"api":{"requestedAccessTokenVersion":2}}'
    EOF
  }
}
```

**Comment by kevinharing** [comment]
You could also use:

`az ad app update --id ${azuread_application.appname.id} --set requestedAccessTokenVersion=2`
