### ISSUE TITLE
Cannot create Microsoft Login capable app registration using azuread_application

### ISSUE THREAD

**Issue by adrianhall** [hashicorp/terraform-provider-azuread#208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.19
├── provider.azuread ~> 0.7.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "appregistration" {
    name                        = "Title"
    reply_urls                  = [ "msauth://foobar.azurewebsites.net/auth" ]
    available_to_other_tenants  = false
    public_client               = true
    type                        = "native"
}
```

### Expected Behavior

App Registrations provide for three settings on who can log in:

* Accounts in this organizational directory only (Default Directory only - Single tenant)
* Accounts in any organizational directory (Any Azure AD directory - Multitenant)
* Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)

I should be able to select which of these I want to choose.

### Actual Behavior

There is no choice provided, and the choice picked is always single tenant.  Once created, there is no ability to select "personal Microsoft accounts" - only single tenant and multi-tenant.

### Steps to Reproduce

1. `terraform apply`

### References

I am actually trying to duplicate the "configure Microsoft Login for authentication" flow documented here: https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-microsoft

**Comment by phenixdotnet** [comment]
Hi, I got the same issue with our terraform and it looks like this provider is using [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) which still use the old graph.windows.net API.

As a workaround I use a script which make a curl PATCH on the MS Graph API:
```bash
GRAPH_API_URL="https://graph.microsoft.com/v1.0"
RESPONSE=$(curl --location --silent --request POST "https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token" \
                --header 'Content-Type: application/x-www-form-urlencoded' \
                --data-urlencode 'grant_type=client_credentials' \
                --data-urlencode 'scope=https://graph.microsoft.com/.default' \
                --data-urlencode "client_id=${clientId}" \
                --data-urlencode "client_secret=${clientSecret}")

ACCESS_TOKEN=`echo ${RESPONSE} | jq -r '.access_token'`

RESPONSE=$(curl -w "%{http_code}" --location --silent --request PATCH "${GRAPH_API_URL}/applications/${appId}" \
                --header 'Content-Type: application/json' \
                --header "Authorization: Bearer ${ACCESS_TOKEN}" \
                --data-raw "{\"signInAudience\": \"AzureADandPersonalMicrosoftAccount\"}")
```

And in tf file
```
resource "null_resource" "MyApp" {
    provisioner "local-exec" {
        command = "${path.module}/patch.sh ...."
   }
}
```
The PATCH operation could be executed multiple time as it change the `signInAudience` only and always to the same value.

Hope this help :)

**Comment by adrianhall** [comment]
The version of Azure SDK for Go the provider is using has access to signInAudience (see https://github.com/Azure/azure-sdk-for-go/blob/090dc0ee4d8d2d60e2a9525774d967a4111a2b0c/services/graphrbac/1.6/graphrbac/models.go#L400) - so this should be doable within the provider.  I'm not set up for Go development right now, but I'll see what I can do.

**Comment by phenixdotnet** [comment]
In fact I tried that but if you set the singInAudience property for create or update operation you got an error from graph.windows.com which say it's a readonly property.

**Comment by worldspawn** [comment]
You must set the token version to 2.

![image](https://user-images.githubusercontent.com/819581/109462676-fb616500-7ab7-11eb-941f-400bae2d3fa8.png)


https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute
