### ISSUE TITLE
Add support for the Identity Governance -> Entitlement Management service within PIM

### ISSUE THREAD

**Issue by jrominesf** [hashicorp/terraform-provider-azuread#218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Azure released a new Entitlement Management feature w/in their Privileged Identity Management service in November 2019.  Provisioning this feature through Terraform would be really valuable.

https://docs.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-overview

### New or Affected Resource(s)

This should be a new feature within azuread

**Comment by manicminer** [comment]
Hi @jrominesf, thanks for requesting this feature! At the moment we are not in a position to implement support for Entitlement Management, as resources for this service are [exposed via the Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta), for which we do not yet have SDK support. We'll look at implementing this as soon as we are able to do so.

**Comment by laughtonsm** [comment]
@manicminer, with the upcoming release of version 2.0 of the AzureAD which supports the Graph API, can we expect this be resolved soon? (Along with wider PIM support?)

**Comment by Ali-Razmjoo** [comment]
It is very much needed. Please consider making it a priority in the backlog.

**Comment by belaie** [comment]
This should be solved relatively quick as this is just another "resource" within Microsoft graph

**Comment by huwjeffries** [comment]
+1 for this feature. We have many 100's of access packages, which are time-consuming and potentially error prone to create by hand. We'd really like this to be managed as infrastructure as code. Thanks.

**Comment by mlomat** [comment]
Any update for this feature?

**Comment by JerimyTate** [comment]
@manicminer any updates on this one?

**Comment by giovannifl** [comment]
any updates on this one?

**Comment by stanleyz** [comment]
Have a look at #903, working on to get this approved.
