### ISSUE TITLE
Support for the appRoleAssignment resource

### ISSUE THREAD

**Issue by Udyrfrykte** [hashicorp/terraform-provider-azuread#230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform Azure AD Provider has no way of granting permissions over Microsoft APIs (in particular Microsoft Graph API and the legacy Azure AD Graph API).

The only process available is to include a `required_resource_access` block in the `azuread_application` resource, for example :
```hcl
resource "azuread_application" "test" {
  name = "test-todelete"

  required_resource_access {
    resource_app_id = "00000002-0000-0000-c000-000000000000" # Azure AD Graph
  
    resource_access {
      id   = "5778995a-e1bf-45b8-affa-663a9f3f4d04" # Directory.Read.All
      type = "Role"
    }
  }
}
```

This process will not grant the Directory.Read.All on the Azure AD Graph API, it only creates a "request" that must then be granted by an admin **User** either through the portal or with `az ad app permission admin-consent`.

This method requires a manual action, and once granted, this manual action actually creates an appRoleAssignment for the application's service principal. But when you remove the `required_resource_access` field from the `azuread_application` and apply again, the appRoleAssignment is not deleted, so the service principal keeps its permissions. These invisible permissions may then cause security issues.

To fix this situation, an `azuread_app_role_assignment` resource could be added to allow Terraform users to manipulate appRoleAssignment directly. This would eliminates the need for manual actions and allow full control from the Terraform configuration.

### New or Affected Resource(s)

* azuread_app_role_assignment [NEW]

### Potential Terraform Configuration

```hcl
resource "azuread_application" "test" {
  name = "test-todelete"
}

resource "azuread_service_principal" "test" {
  application_id = azuread_application.test.application_id
}

resource "azuread_app_role_assignment" "test" {
  principal_id = azuread_service_principal.test.id
  app_id         = "00000002-0000-0000-c000-000000000000" # Azure AD Graph
  app_role_id = "5778995a-e1bf-45b8-affa-663a9f3f4d04" # Directory.Read.All
}
```

### References

An **User** account is needed to manipulate the [resource in the Azure AD Graph API](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#approleassignment-entity). With the new [resource in the Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment) permissions exist for service principals, but the resource is still in beta...

In case the Microsoft Graph API is chosen, this issue could be linked to #193

**Comment by manicminer** [comment]
Hi @Udyrfrykte, as far as I understand, admin consent is a deliberate safety mechanism in place to prevent unchecked profileration of non-delegated API permissions and there is no programmatic way around it for requests originating from a service principal (when you authenticate the provider using an SP). This is documented at https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent and https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent

The CLI and PowerShell cmdlets (and of course the Portal) have options for this, but both require that you authenticate interactively with a user account as far as I know?

**Comment by Udyrfrykte** [comment]
Hi @manicminer, a "real" user is indeed needed to grant consent. At the moment this grant operation can only be done with the CLI (or the PS cmdlets), this can even be automated with a provisioner and some elbow grease in Terraform, as long as you can authenticate with an user account.

This design decision from Azure is perfectly understandable, and I have no problem with it. As I mentioned the current beta of the appRoleAssignment resource in Microsoft Graph API doesn't have this limitation, so maybe Azure changed its mind...

Anyway, the issue is not the need for a manual action or a real user, it is how the permission grant is handled backstage: with the appRoleAssignment entity. This entity can not be manipulated from Terraform, so once created (when you manually grant consent for example) it cannot be revoked. This can cause unexpected security issues as applications keep permissions that does not exist in the Terraform code anymore.

This situation could be improved if we were able to manipulate the appRoleAssignment resource from Terraform, either with the Azure AD legacy API (User account required) or the new Microsoft Graph API.

Does this clarify the intention behind this issue?

**Comment by manicminer** [comment]
@Udyrfrykte Thanks for the clarification, I think I understand. The implementation is interesting and also tricky to administer as the portal falls short in functionality when managing service principals.

Given that we don't yet support MS Graph, I don't think we can handle this sort of case at the moment. However I've marked as a valid feature request for when we are able to. The best workaround seems to be to revoke admin consent for a given scope for the application prior to removing the `required_resource_access`, and this seems to delete the `appRoleAssignment` for the service principal. This assuming a single tenant - if your app is granted in multiple tenants I'm sure there's more involved. Hope this helps!

**Comment by Udyrfrykte** [comment]
Thank you for your answer. Let's hope everything falls into place to allow this provider to use MS Graph!

Another way to identify and remove these appRoleAssignments is through the "Enterprise Application" (apparently the portal name of service principals) section of the Azure AD portal. This section is mostly read-only, but if I remember correctly, you can get a small list of PowerShell commands (to run in a cloud shell for example) that will revoke appRoleAssignments for a service principal.

This was the solution that Azure support offered when we had this issue.

**Comment by xinyi-joffre** [comment]
It looks like this is possible even in the older AD Graph API, but it wasn't added to the azure-rest-api-spec, so that's why it's missing from the azure-sdk-for-go graphrbac package. I was able to get admin consents using this undocumented endpoint:

https://graph.windows.net/<tenant_id>/servicePrincipals/<service_principal_id>/appRoleAssignments?api-version=1.6

{
    "id": "<role_id>",
    "principalId": "<service_principal_id>",
    "resourceId": "<service_principal_id_of_app_with_role_defined>"
}

I can take a look and see if I can PR this into azure-rest-api-spec to unblock this issue in the shorter term, but moving to newer graph would definitely solve this as well in the future!
