### ISSUE TITLE
azuread_group description change should not create a new resource

### ISSUE THREAD

**Issue by trajano** [hashicorp/terraform-provider-azuread#240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.8.0
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "SonarQubeAdministrators" {
  name = "SonarQube Administrators"
  description = "SonarQube Administrators"
  owners = [
      data.azuread_user.it.id,
      data.azuread_user.vp_tech.id,
  ]
}

```

### Expected Behavior

Changing the description only should not create a new resource as the Portal allows changing the text without changing the object ID.

### Actual Behavior

Changing the description only creates a new resource.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
@trajano,

currently the SDK doesn't have an update methold, just create. Until the SDK supports updating group descriptions (maybe the new graph one does) we won't be able to fix this 😞

**Comment by manicminer** [comment]
I've raised an upstream feature request for this, as the current API does support PATCH requests for groups.

Upstream isue: https://github.com/Azure/azure-sdk-for-go/issues/9911
API operation: https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/groups-operations#update-a-group--

**Comment by manicminer** [comment]
Related: https://github.com/terraform-providers/terraform-provider-azuread/issues/176
