### ISSUE TITLE
Support reply_url type Spa on azuread_application

### ISSUE THREAD

**Issue by jorgecarleitao** [hashicorp/terraform-provider-azuread#244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a feature request to extend the `reply_url` on `azuread_application` to allow a brand new type of reply urls implemented in Azure AD called "Spa".

They differ from the traditional "Web" reply urls in that they support OAuth2's PKCE, see [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#prerequisites) on how to change it in the manifest, and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1000) for the discussion on a client. Essentially, reply urls will have two types, "Web" (current) and "Spa" (new addition).

Currently, terraform only supports an array of strings, which represent reply urls of type "Web". We need to extend it to support either an array of strings (for backward compatibility) or an array of maps containing two keys, e.g. "reply_url" and "type", where "type" can only be "Web" or "Spa".

FYI I have validated that changing the type does indeed make PKCE work.

### New or Affected Resource(s)

* `azuread_application`

**Comment by katbyte** [comment]
hey @jorgecarleitao. It doesn't appear support for that is in the SDK at the moment, it only accepts an array of strings.

**Comment by dominik-lekse** [comment]
I have a use case which also depends on the new Spa type.

References:
- Legacy `replyUrls` attribute: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#replyurls-attribute
- New `replyUrlsWithType` attribute: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#replyurlswithtype-attribute

**Comment by dominik-lekse** [comment]
I have created an upstream issue to track this: https://github.com/Azure/azure-rest-api-specs/issues/9617

**Comment by manicminer** [comment]
I doubt this will be supported in AAD Graph as new features are being added to MS Graph.

I've scoured the object references for applications and service principals, and I could only find support for the current/legacy `replyUrls` property,. I don't doubt it will be added at some point.

The provider is not currently able to leverage MS Graph API, however we do plan on moving to it. Hopefully this property will be supported when that time comes.

**Comment by manicminer** [comment]
Supported in MS Graph: https://docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-beta

**Comment by yene** [comment]
@manicminer What would be the right approach if I wanted to generate App registrations with SPA from config. Should I script against the MS graph manually, or is there an abstraction?

**Comment by manicminer** [comment]
@yene Right now you'll need to script this, but we'll have support for SPA configs in the near future.

**Comment by CaptainStealthy** [comment]
@yene I use a post-deploy Azure CLI script to add the SPA config. I can probably find the code and post a snippet if you need it

**Comment by scott-doyland-burrows** [comment]
Hi,

I use this bash script, where the variables are set like this:

```TF_OUT_APPREG_UI_REPLY_URLS="https://url1,https://url2"```
```TF_OUT_APPREG_UI_OBJECT_ID="00000000-0000-0000-0000-000000000000""```

```
ui_reply_urls=`echo "["\"$TF_OUT_APPREG_UI_REPLY_URLS"\"]" | sed  's/,/\",\"/g'`
spa_patch=$(printf '%s\n' "$ui_reply_urls" | jq -c '{"spa":{"redirectUris":.}}')
az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$TF_OUT_APPREG_UI_OBJECT_ID" --headers 'Content-Type=application/json' --body="$spa_patch"
```
