### ISSUE TITLE
data source for OAuthPermissions and/or Azure Common APIs

### ISSUE THREAD

**Issue by rturnbull1977** [hashicorp/terraform-provider-azuread#250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to have data sources/resources created in terraform Azure for OAuthPermissions and/or Azure Common APIs.  Right now:

resource "azuread_application" "example" {
  name = "example"
  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" #Microsoft Graph-https://graph.microsoft.com
    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" #e1fe6dd8-ba31-4d61-89e7-88639da4683d Sign in and read user profile
      type = "Scope"
    }
  }
}

IF the strings of "00000003-0000-0000-c000-000000000000" could be used in a data resource so that you can say something like:

data "azure_api_resource" "graphapi" {
   name = "Microsoft Graph API"
}

data "azure_oauth_permission" "sign-in-and-read" {
  name = "Sign in and read user profile"
}

resource "azuread_application" "example" {
  name = "example"
  required_resource_access {
    resource_app_id = data.azure_api_resource.graphapi.app_id
    resource_access {
      id   = data.azure_oauth_permission.sign-in-and-read.permission_id
      type = "Scope"
    }
  }
}

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by manicminer** [comment]
This has been implemented using a new data source [azuread_application_published_app_ids](https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/data-sources/application_published_app_ids.md) in combination with the [azuread_service_principal](https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/resources/service_principal.md) resource (or data source). Example usage can be found in [the docs for the new data source](https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/data-sources/application_published_app_ids.md).
