### ISSUE TITLE
Add support for pre authorized applications in an Azure AD app registration

### ISSUE THREAD

**Issue by TechWatching** [hashicorp/terraform-provider-azuread#263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for pre authorized applications in an Azure AD app registration. Applications in Azure AD can expose an API with a scope and pre authorize some existing applications on that scope. This generates this kind of json in the application mantifest.

```json
	"preAuthorizedApplications": [
		{
			"appId": "5e3ce6c0-2arf-4285-8s23b-75ee78787346",
			"permissionIds": [
				"434b0aae-77b3-481a-b78f-4dfds29b"
			]
		},
		{
			"appId": "1fec8e78-bce4-4aaf-dsq12b-5451cc387264",
			"permissionIds": [
				"434b0aae-77b3-481a-b78f-4dfds29b"
			]
		}
```

### New or Affected Resource(s)

* azuread_application
* azuread_serviceprincipal

**Comment by daniel-chambers** [comment]
I'd like to comment that I think this should be a separate resource to `azuread_application`. In my case, I have two applications, a SPA and an API. The SPA app depends on the API as a required resource. But the API depends on the SPA as a pre-authorized application. 
Having pre-authorized applications be a separate resource would break this cycle.
