### ISSUE TITLE
azuread_application identifier_uris plans for changes because it wants to change item order in list

### ISSUE THREAD

**Issue by vmignot** [hashicorp/terraform-provider-azuread#273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v0.12.24
+ provider.azuread v0.10.0
```

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "oauth2_proxy" {
  name = "oauth2_proxy-${terraform.workspace}"

  identifier_uris = [
    "https://oauth2proxy.${local.tooling_dns_zone_name}/",
    "https://oauth2proxy.${local.ci_dns_zone_name}/"
  ]
  reply_urls = [
    "https://tooling.${local.tooling_dns_zone_name}/oauth2/callback",
    "https://ci.${local.tooling_dns_zone_name}/oauth2/callback"
  ]

  required_resource_access {
    resource_app_id = "00000002-0000-0000-c000-000000000000" # Azure AD Graph

    resource_access {
      id   = "311a71cc-e848-46a1-bdf8-97ff7156d8e6" # User.Read (Sign in and read user profile)
      type = "Scope"
    }
  }
}

```

### Expected Behavior

A plan following an apply should not display changes. 

### Actual Behavior

But instead, the identifier_uris always wants to change. Heres a `terraform plan`:

```hcl
  # azuread_application.oauth2_proxy will be updated in-place
  ~ resource "azuread_application" "oauth2_proxy" {
        application_id             = "XXXX"
        available_to_other_tenants = false
        homepage                   = "https://oauth2_proxy-prd"
        id                         = "XXXX"
      ~ identifier_uris            = [
          - "https://oauth2proxy.ci.xxx.com/",
            "https://oauth2proxy.tooling.xxx.com/",
          + "https://oauth2proxy.ci.xxx.com/",
        ]
[...]
```

Even after an apply, it will always plan for a change. I think this is a bug in the provider

Thanks in advance!

**Comment by manicminer** [comment]
Hi @vmignot, thanks for reporting this! I believe this is a bug.

The order of app identifier URIs sort of matters because it affects which URI is displayed in the portal. However, it looks like this is an API issue with MIcrosoft, as we are sending them in the exact order in which they're configured, but when you inspect the application afterwards the order has changed seemingly arbitrarily. Each time Terraform wants to correct this, but the order we're sending to the API seems to be ignored. It's possible that the order isn't actually important, and the API behavior is expected, but I'll have to look further into this as the documentation isn't clear.

**Comment by manicminer** [comment]
In the meantime, you can workaround this and silence the permanent diff in your plan either by reordering your configuration to match that of your application, or by adding a `lifecycle` block to ignore changes for that attribute.

**Comment by manicminer** [comment]
After consultation with the service team, we recently changed the `identifier_uris` property from a list to a set. Accordingly, the provider no longer enforces the order of identifier URIs and this bug should now be resolved.
