### ISSUE TITLE
Add support for "mail" lookup

### ISSUE THREAD

**Issue by trajano** [hashicorp/terraform-provider-azuread#280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The following also works so if we had a mail option for the data "azuread_user" this would solve the issue. It should throw an error if it detects that the query will return more than one result.

az ad user list --filter "mail eq 'email@guest.com'"

### New or Affected Resource(s)

* data azuread_user

### Potential Terraform Configuration

```hcl
data "azuread_user" "YYYY" {
  mail = "YYYY@ZZZZ.com"
}
```

### References

* #275

**Comment by manicminer** [comment]
Hi @trajano, I'm looking at adding this and have an untested implementation. However, we're currently unable to test this due to the `mail` field being (a) readonly and (b) only populated for users with an O365 license. I'll look further into this.

**Comment by trajano** [comment]
I'm actually just using the Terraform azuread to help manage my Office 365 installation (rather than an Azure system)

**Comment by trajano** [comment]
Our workaround for now

```
data "azuread_user" "ContractorDevelopers" {
  for_each = merge(
    { for e in csvdecode(file("data/ContractorDevelopers.csv")) : e.Email => "${replace(e.Email, "@", "_")}#EXT#@${var.tenant_domain}" }
  )
  user_principal_name = each.value
}
```

Where the CSV file contains e-mail addresses only. no other fields.
