### ISSUE TITLE
Add support for SPA based application clients using PKCE flow 

### ISSUE THREAD

**Issue by autom8ter** [hashicorp/terraform-provider-azuread#286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for SPA based clients using PKCE flow. PKCE flow is available if "Single-page Application" is selected on the "Authentication" tab of an App Registration in the Azure portal. Here is a screen shot showing a PKCE configuration: 
<img width="1383" alt="Screen Shot 2020-06-23 at 12 55 03 PM" src="https://user-images.githubusercontent.com/47678518/85445658-dabc3500-b550-11ea-9b78-f81b1e1d65fb.png">

The terraform provider is not useable for SPA based clients in its current form.

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "example" {
  name                       = "example"
  homepage                   = "https://homepage"
  reply_urls                 = ["http://localhost:3000/", "http://localhost:3000/callback"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  type                       = "spa"
}
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @autom8ter, thanks for requesting this! It doesn't look like we're able to support SPA reply/redirect URLs at present but we'll revisit this as soon as we are able.

Long explanation: I originally thought this might be an easy implementation with MS Graph, but it looks like support hasn't been added there yet. Tracing the portal, this makes use of AAD Graph to patch the application with the `replyUrlsWithType` property - this isn't documented nor is supported by the SDK, but that's how the portal does it. We'd need to compose a request manually, or wait for SDK support. I've raised an upstream issue https://github.com/Azure/azure-sdk-for-go/issues/10830

**Comment by SvenHamers** [comment]
@manicminer I think it should be possible to implement it.

when i send the following patch request it works

https://graph.microsoft.com/v1.0/applications/<appObjId>

{
    "spa":{"redirectUris":[https://test.com]}
}

**Comment by manicminer** [comment]
@SvenHamers That's great, thanks for reporting a working request with MS Graph 👍

**Comment by patst** [comment]
highly interested in this as well.

As workaround we added this in an `azuread_application` resource:

```
 provisioner "local-exec" {
    command = "az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/${azuread_application.icp-terraform.object_id}' --headers 'Content-Type=application/json' --body '{\"spa\":{\"redirectUris\":[\"http://localhost:4200/index.html\"]}}'"
  }
```

**Comment by Clem-** [comment]
Hi,
I assume that you need to use `lifecycle{ignore_changes}` if you use this workaround as terraform will want to delete the uris added with az CLI?
Thanks

**Comment by Satyricon** [comment]
Any update?

**Comment by simaotwx** [comment]
It looks like this will be supported in #474 so I'm looking forward to a new version. Currently have to change this manually in Azure Portal otherwise the app I deploy doesn't work. Kind of surprised that "web" exists but "spa" did not.
