### ISSUE TITLE
App registration without ID_tokens enabled

### ISSUE THREAD

**Issue by brondum** [hashicorp/terraform-provider-azuread#305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that the TF provider will always enable the ID_Token at 
`AzureAd-> App Registrations -> My App -> Authentication -> Implicit grant`

It would be nice if you could create an App registration with the most secure flow, Authorization Code Flow, for application that dont need the ID tokens.

eg. when `oauth2_allow_implicit_flow` is set to `false`it would not enable id_tokens, this could be managed by a variable it self: `oauth2AllowIdTokenImplicitFlow`.

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "main" {
  name = "main"
  oauth2_allow_implicit_flow = false
  oauth2AllowIdTokenImplicitFlow = false
```

### References

* #163

**Comment by manicminer** [comment]
Hi @brondum, thanks for requesting this feature!

Right now we are unable to configure this due to missing API support. However we are in the process of planning a migration to the newer Microsoft Graph API, and once this is in place we'll be able to implement this.

**Comment by brondum** [comment]
@manicminer Thank you for elaborating on the progress. Please shout out if you need some testing or similar.
