### ISSUE TITLE
azuread_application should not use CustomKeyIdentifer to store the Description field

### ISSUE THREAD

**Issue by nerddtvg** [hashicorp/terraform-provider-azuread#311]
https://github.com/terraform-providers/terraform-provider-azuread/blob/7e62e3ef9ee3e5df37db43f10972e4265d64907a/azuread/helpers/graph/credentials.go#L263-L266

https://github.com/terraform-providers/terraform-provider-azuread/blob/7e62e3ef9ee3e5df37db43f10972e4265d64907a/azuread/resource_service_principal_password.go#L117-L119

https://github.com/terraform-providers/terraform-provider-azuread/blob/7e62e3ef9ee3e5df37db43f10972e4265d64907a/azuread/resource_application_password.go#L120-L122

The `CustomKeyIdentifier` is a binary value that maxes out at 32-bytes. This should not be used according to the [documentation](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0).

The better field for the `description` value is the `displayName` string which is used in the Azure AD Portal to show users a helpful message about the secret's use.

**Comment by manicminer** [comment]
Hi @nerddtvg, thanks for opening this issue. The documentation is different between Microsoft Graph (which you linked) and Azure Active Directory Graph (which is the API we currently use). The AAD Graph API does not expose the `displayName` property, which you can see [here](https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#passwordcredential-type). When specifying the `customKeyIdentifier` attribute, this is exposed in the Portal as the "description" for the credential.

![Screen Shot 2020-08-25 at 17 48 26](https://user-images.githubusercontent.com/251987/91203765-3a72c000-e6fb-11ea-839c-1369adcb0cdf.png)
![Screen Shot 2020-08-25 at 17 49 03](https://user-images.githubusercontent.com/251987/91203854-49597280-e6fb-11ea-96e6-1dec5b6d3ec9.png)

I suspect backend changes between the older API and the newer model as per MIcrosoft Graph. We'll continue to use this field for now, and look at changing it when we have support for the newer API.

Hope this clarifies things!

**Comment by nerddtvg** [comment]
@manicminer 

I think using AAD Graph (after July 2020) is a bad idea. It's going away and is now deprecated so we need to upgrade. Since there aren't many resources or data types with the azuread provider and most would be drop-in replacements, would this be too hard? I don't mind working a PR for this and learning a bit more about it.

I can confirm that adding a client secret with a description on the portal uses the displayName field in MS Graph.

![image](https://user-images.githubusercontent.com/5490719/91204853-43976900-e6ca-11ea-81da-bc64e40e0c65.png)

**Comment by manicminer** [comment]
@nerddtvg Agreed, we're aware of the deprecation (and the eventual switchoff) and this is something we're actively working on. A v1.0 release of this provider is forthcoming which lays some groundwork for introducing additional APIs - much like the AzureRM provider - and following that we'll be working on achieving feature parity with the current API implementation, but interfacing with MS Graph.

Thanks for confirming the `displayName` field, we'll make sure that's changed in the new resource. If you're keen to contribute, keep an eye out for the upcoming release and subsequent MS Graph changes - there will be a lot of work coming up to add new features.

**Comment by yourbuddyconner** [comment]
Just to chime in here, this regression is also present on the `service_principal_password`, just spent some time running in circles figuring it out lol. It is present in the `v1.0.0` version of the azuread provider.

**Comment by manicminer** [comment]
@yourbuddyconner Thanks for the additional info! No need to open a new issue, I've marked this as also affecting the `azuread_service_principal_password` resource.

**Comment by juven-itsapark** [comment]
> Just to chime in here, this regression is also present on the `service_principal_password` resource, just spent some time running in circles figuring it out lol. It is present in the `v1.0.0` version of the azuread provider.
> 
> Fortunately the solution was to unset the `description` field on the resource and things began to work as expected.
> 
> Dropping some search terms for the next poor soul that has to debug this:
> `graphrbac.ServicePrincipalsClient#UpdatePasswordCredentials`
> `One or more properties contains invalid values.`
> `azuread service principal`
> 
> @manicminer please let me know if I should open another issue for this, happy to do so.

Just wanted to mention that removing `description` from `service_principal_password` also solved my issue creating a password (client secret).

**Comment by manicminer** [comment]
@juven-itsapark Thanks for noting that. We'll be able to fix this properly once we have migrated to Microsoft Graph. Out of curiosity, can you paste an error snippet just in case there's something we can do to improve this in the interim?

**Comment by gkman** [comment]
```console
Error: Creating password credentials "afe9d2a6-dd56-5471-cf2f-b4d6067938b9" for service principal with object ID "af3721ea-cebc-4617-a46f-c63ee255c723"

graphrbac.ServicePrincipalsClient#UpdatePasswordCredentials: Failure
responding to request: StatusCode=400 -- Original Error: autorest/azure:
Service returned an error. Status=400 Code="Unknown" Message="Unknown service
error"
Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-04-14T19:05:26","message":{"lang":"en","value":"One
or more properties contains invalid
values."},"requestId":"f170606d-2f35-47e1-85a5-4970f37d1ebd"}}]
```

**Comment by manicminer** [comment]
@gkman have you tried shortening it down to a few alpha chars and building it back up bit by bit? Maybe we can determine if there's a byte it doesn't like, or a new length restriction or something.

**Comment by gkman** [comment]
@manicminer The below is what we've written and we did build it up to find that alpha and whitespace is fine and hits the infamous 32 chat limit and fails with the error posted above.

```hcl
module "service_principal_password" {
  source = "../../atoms/active_directory/service_principal/service_principal_password"

  # https://github.com/hashicorp/terraform-provider-azuread/issues/311
  # 32 char limit
  description          = "Auto gen password stored in KV"
  end_date             = var.password_end_date
  password             = module.password.result
  service_principal_id = module.service_principal.id
}
```
