### ISSUE TITLE
azuread_group new field: is_assignable_to_role

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform-provider-azuread#312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add a new field for enabling a [AD Group ](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group
)to role assignable. > https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/roles-groups-create-eligible

### New or Affected Resource(s)

* azuread_group

### Potential Terraform Configuration

```
resource "azuread_group" "example" {
  name    = "MyGroup"
  ad_role_assignable = true
  members = [
    azuread_user.example.object_id,
    /* more users */
  ]
}
```

**Comment by manicminer** [comment]
Hi @rohrerb, thanks for requesting this feature. It looks like this property is only supported by the MIcrosoft Graph API, which we are in the process of migrating to but not yet in a position to support. We will definitely look at adding this as soon as we are able.

**Comment by Grant-Rc** [comment]
Hey @rohrerb 

Just hit this issue (and many like it before) where you want to automate something but its part of the MS Graph API. I have been keeping an eye on [https://github.com/terraform-providers/terraform-provider-azuread/issues/323](url) witch looks to have a toggle version that might work.

**Comment by kaovd** [comment]
Will take a look at implementing this if not already being pulled in

**Comment by kaovd** [comment]
This is within the SDK so easy to modify the terraform, just checked. 
![image](https://user-images.githubusercontent.com/29356754/123162105-1d686400-d468-11eb-8320-06f5a1b9ac03.png)

![image](https://user-images.githubusercontent.com/29356754/123162066-12153880-d468-11eb-87ef-355b0d8b65a7.png)


Might as well wait till 2.0 to go for a PR though as merge conflicts, at 2.0 all the graph functionality is gonna get work. Imagine this will be on 2.1.0 although milestone says 2.0.0 theres a few things that need to be put in there that are in SDK but covered in the provider. @manicminer are these features gonna be in 2.0 or push back to the 2.1.0 release?
