### ISSUE TITLE
Add azuread_application support for termsOfServiceUrl/privacyStatementUrl

### ISSUE THREAD

**Issue by JulienRavet** [hashicorp/terraform-provider-azuread#320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for "infos" properties of Azure AD applications
```
"info": {
        "termsOfServiceUrl": null,
        "supportUrl": null,
        "privacyStatementUrl": null,
        "marketingUrl": null,
        "logoUrl": null
    },
```

### Affected Resource(s)
* azuread_application

**Comment by manicminer** [comment]
Thanks @JulienRavet for requesting these attributes. These depend on upcoming support for Microsoft Graph and we'll look at adding them once we have that.

**Comment by JulienRavet** [comment]
Hi @manicminer 

The application logo seems to be available in the graph API (even if it's not one one the requested in the issue title :wink:)
https://docs.microsoft.com/fr-fr/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#application-entity 

mainLogo | Edm.Stream | POST, GET, PATCH | The main logo for the application.Notes: not nullable
