### ISSUE TITLE
Provide support for approle outside of resource_service_principal as an independent resource

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-azuread#326]
Much like the excellent work on https://github.com/terraform-providers/terraform-provider-azuread/issues/306 !

Description

I would also like the ability to perform app_roles on a service_principal, without specifying the entire service_principal resources. This is similar to #306 which was fixed in 1.0.0 whereby it is now possible to specify an `azuread_application_app_role` independently of the `azuread_application`

In our AD setup, a service principal for an enterprise application is created for us by another team, and we can only create app_roles on it. We have no permission to be able to create or modify enterprise applications or service_principals on top, but would like to be able to create and assign app_roles to users on preexisting service-principals.

As with many terraform resources, it would be useful if both approaches were possible.

New or Affected Resource(s)

resource_service_principal.go

**Comment by manicminer** [comment]
@gtmtech Thanks for requesting this. Have you tried importing the existing service principal (to avoid duplicating an already existing one)? It might be a useful workaround for you in the meantime.

**Comment by gtmtech** [comment]
@manicminer, yeah I figured this was a method before on #306 as well - as well as putting lifecycle changes ignore on just about every field except approle.

I think what put me off was that we are going through a large enterprise application onboarding process, between different teams, responsible for different areas of AD, and I would constantly be having to terraform import eapps which struck me as a largely manual process as opposed to just using a datasource lookup based on name and resource for the approle which is far more automated. 

I think your workaround would work the odd case here or there though, I had considered it. Would be super nice to have the resource available though

**Comment by manicminer** [comment]
@gtmtech I took a quick look at this, and it seems like the `appRoles` collection returned for service principals is merely from the corresponding application manifest. When I try to patch a service principal directly with app roles I get a 400 error. Do you know if this is supposed to work?

**Comment by gtmtech** [comment]
I'm currently using the shell provider to patch servicePrincipals as a workaround, but yes: - Python code sorry!

```
    service_principal = msgraph.get_app_service_principal()
    ...
    service_principal['appRoles'].append(approle)
    ...
    _r = msgraph.query_ms_graph_request(
      query_object = "servicePrincipals/{0}".format(service_principal['id']),
      auth_header  = auth_header,
      html_method  = "patch",
      html_data    = service_principal
    )
```

Asked a colleague to comment too as he does more stuff on ms-graph-explorer than I do.

**Comment by manicminer** [comment]
@gtmtech Thanks for updating, would you be able to capture the HTTP request and response so we can see what's happening under the hood?

**Comment by jdelforno** [comment]
v1.0 Graph API Added the ability to manipulate Application Roles; https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-1.0

Applies to Update only it seems: https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http

**Comment by manicminer** [comment]
Given that appRoles are a property of the app registration rather than the service principal, I'm going to close this issue for now.

App roles can be configured using the [azuread_application](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application) resource, and any configured roles will reflect in the attributes of the linked service principal.
