### ISSUE TITLE
Manage AD Microsoft 365 groups

### ISSUE THREAD

**Issue by siwon** [hashicorp/terraform-provider-azuread#331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I hope I don't miss this feature.

In the resource `azuread_group` ressource, I don't see the possibility to create a Microsoft 365 group type.
![image](https://user-images.githubusercontent.com/1249874/95875568-70830680-0d72-11eb-9292-15a03b13e19b.png)

Did I miss something?

Thanks a lot.

### New or Affected Resource(s)

* azuread_group

**Comment by manicminer** [comment]
Hi @siwon, many thanks for requesting this feature. There are a couple of blockers on implementing this right now. First is that O365 group metadata is only fully exposed by the Microsoft Graph API, for which we don't yet have support but are [working on](https://github.com/terraform-providers/terraform-provider-azuread/issues/323). The other issue is that whilst testing this, it looks like non-security groups (i.e. O365 groups or mail groups) cannot currently be created via API - it returns a 400 error. This will probably be implemented in time, and we'll look to add support once this is fixed.

**Comment by siwon** [comment]
Wahou ! That was really quick to get an answer ! Thanks a lot :D.

I didn't know the constraints of implementing this feature and I will manage it with the portal.
Do you want me to keep this issue open ?

Thanks again for the feedback.

**Comment by manicminer** [comment]
No problem, by chance I was passing through and looking at some other issues :)

Yes, please keep the issue open so we can track the feature request.

**Comment by manicminer** [comment]
I seem to have missed this one - feature is already merged for 2.0 :D
