### ISSUE TITLE
Application identifier_uris from allows array but does not store array in state

### ISSUE THREAD

**Issue by MarkDordoy** [hashicorp/terraform-provider-azuread#334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform version: 0.12.29
AzureAD provider version : 1.0.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files
```hcl
resource "azuread_application" "example" {
  name                       = "example"
  homepage                   = "https://homepage"
  identifier_uris            = ["https://uri","https://uri2"]
  reply_urls                 = ["https://replyurl"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
  type                       = "webapp/api"
}

resource "azuread_service_principal" "example" {
  application_id               = azuread_application.example.application_id
  app_role_assignment_required = false

  tags = ["WindowsAzureActiveDirectoryIntegratedApp", "WindowsAzureActiveDirectoryCustomSingleSignOnApplication", "WindowsAzureActiveDirectoryGalleryApplicationNonPrimaryV1"]
}
```

### Expected Behavior

I would expect the array of strings allowed for the `identifier_uris` to be stored in state. 

### Actual Behavior

State stores the values and works when only a single value of identifier_uris is set in the application. However when you pass an array terraform state never stores the array. Looking at the backend API, multiple identifier_uris are set on the application, but terraform fails to recognise this and causes it to try and apply again and again.
### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
@MarkDordoy Thanks for reporting. Can you share the output from `terraform apply` that you note is stuck in a persistent diff? `identifierUris` for an application are exposed in the service principal manifest as `servicePrincipalNames` but to my knowledge we don't currently store this in state.

**Comment by MarkDordoy** [comment]
Ive removed anything relating specific to my company and replaced with fake data. 

This is the plan

```hcl
 ~ resource "azuread_application" "application" {
        application_id             = "4bc611ef-7cb1-4ca9-ba0c-5a1f89df4ea0"
        available_to_other_tenants = false
        group_membership_claims    = "None"
        homepage                   = "https://stuff.stuff:443/SAML20/SP"
        id                         = "cc2e8870-214a-49fc-9907-ce88858a9f40"
      ~ identifier_uris            = [
          - "https://stuff1.stuff.com:443/SAML20/SP",
          - "https://stuff2.stuff.com:443/SAML20/SP",
          - "https://stuff3.stuff.com:443/SAML20/SP",
            "https://stuff.stuff.com:443/SAML20/SP",
          + "https://stuff1.stuff..com:443/SAML20/SP",
          + "https://stuff2.stuff..com:443/SAML20/SP",
          + "https://stuff3.stuff..com:443/SAML20/SP"
        ]
        name                       = "stuff"
        oauth2_allow_implicit_flow = false
        oauth2_permissions         = [
            {
                admin_consent_description  = "Allow the application to access stuff on behalf of the signed-in user."
                admin_consent_display_name = "Access stuff"
                id                         = "b72c048e-3a1a-4f43-939d-802f730349ae
                is_enabled                 = true
                type                       = "User"
                user_consent_description   = "Allow the application to access stuff on your behalf."
                user_consent_display_name  = "Access stuff"
                value                      = "user_impersonation"
            },
        ]
        object_id                  = "a465caf7-c81c-4df1-b0ce-4b98dd9bbb37"
        owners                     = [
            "a465caf7-c81c-4df1-b0ce-4b98dd9bbb35",
        ]
        prevent_duplicate_names    = false
        public_client              = false
      ~ reply_urls                 = [
            "https://blah1.com:443/SAML20/SP/ACS",
            "https://blah2.com:443/SAML20/SP/ACS",
            "https://blah3.com:443/SAML20/SP/ACS",
            "https://blah4.com:443/SAML20/SP/ACS",
        ]
        type                       = "webapp/api"

        app_role {
            allowed_member_types = [
                "User",
            ]
            description          = "App Role managed by Terraform - Default Access"
            display_name         = "Default"
            id                   = "f8c80df0-54db-56d8-3b2b-d97b016ea256"
            is_enabled           = true
            value                = "Default"
        }
    }
```

This is the apply:
```
module.stuff.azuread_application.application: Modifying... [id=cc2e8870-214a-49fc-9907-ce88858a9f40]
module.stuff.azuread_application.application: Modifications complete after 2s [id=cc2e8870-214a-49fc-9907-ce88858a9f40]
```
As you can see, i was wrong in saying the spn is not storing state, the issue does infact appear to be with the application not storing state. I'll update the title of this issue to correctly detail problematic resource

**Comment by MarkDordoy** [comment]
Not sure if im doing this right as im still learning go, but here is maybe a fix: https://github.com/terraform-providers/terraform-provider-azuread/pull/335

**Comment by manicminer** [comment]
@MarkDordoy Thanks for clarifying! This is a known issue (reported in #273) where the [AAD Graph] API unfortunately rearranges `identifierUris` arbitrarily.

We had considered making this attribute a set but, although undocumented, a couple of things are inferred from the order. One example is visible in the Portal, if you set multiple identifier URIs, the first one is the one used on the "Expose an API" pane, both for that specific field and for the displayed fully-qualified scopes. I don't believe this issue occurs with MS Graph so when we move to that API, a list will still be appropriate. Moving from a list to a set, back to a list would represent two breaking changes.

**Comment by NestorRV** [comment]
Is there any update on this? Thanks!

**Comment by manicminer** [comment]
Hi @MarkDordoy, this will be fixed in the next major version of the provider

**Comment by NestorRV** [comment]
Hi @manicminer when is the version 2.0 estimated to arrive?

**Comment by manicminer** [comment]
@NestorRV We can't give an exact date but it's close. Please subscribe to #323 for updates, thanks!
