### ISSUE TITLE
Support for Conditional Access policies

### ISSUE THREAD

**Issue by manicminer** [hashicorp/terraform-provider-azuread#348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ability to configure conditional access policies.

### New or Affected Resource(s)

* azuread_conditional_access_policy

### References

* Depends on #323
* https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta

**Comment by Satak** [comment]
Is there any ETA for this resource support?

**Comment by manicminer** [comment]
@Satak This is on our roadmap to visit after the v2.0 release, although it's yet to be determined which release it's likely to make and exactly what can be supported.
