### ISSUE TITLE
azuread_service_principal - Improved UX for tags (was: Missing Visible to Users Interface)

### ISSUE THREAD

**Issue by Ravenzmynd** [hashicorp/terraform-provider-azuread#354]
It appears that the ability to set the "Visible to users" flag is missing in the terraform when creating an azuread_application.  We are attempting to create a service principal for use in automation, (and can do so thank you!); however, this is not an application we need nor would want to have show up in the O365 applications listing as it isn't pertinent to the user base, but only leveraged for the operations team.  

For now we have to manually compensate in the portal or drop out of the terraform in favor an "az cli" command.  A clunky solution at best from our patterns and practices.

Can this be addressed at some point please? Is there something we are missing or a reason why this property isn't allowed for from the Terraform perspective?

Thanks!

_Screenshot for the property in the azure portal_ 
<img width="490" alt="Screenshot 2020-11-12 071539" src="https://user-images.githubusercontent.com/6886386/98951496-8e4da380-24b7-11eb-979a-fa63717e5264.png">

**Comment by manicminer** [comment]
Hi @Ravenzmynd, thanks for requesting this feature. I haven't been able to locate this property in the API references, neither for [Azure AD Graph](https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference) nor [Microsoft Graph](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta). Do you have a working 'az cli' command for this? It may help in identifying the property.

**Comment by Ravenzmynd** [comment]
I am unable to locate this flag as well.  Wondering if this is supported outside the console/portal at all at this point? :/

**Comment by manicminer** [comment]
I'm going to mark this as blocked until we can determine whether any API support for this property exists.

**Comment by asiantuntija-asiantuntija** [comment]
Toggling setting on portal adds/removes tag called HideApp.

Hide app:

```
~$ az ad sp update --id f5f6ecff-8661-4726-a83f-8e7db8aa068f --add tags "HideApp"
```


"Unhide" app:

```
~$ az ad sp show --id f5f6ecff-8661-4726-a83f-8e7db8aa068f --query tags
[
  "HideApp",
  "WindowsAzureActiveDirectoryIntegratedApp"
]

~$ az ad sp update --id f5f6ecff-8661-4726-a83f-8e7db8aa068f --remove tags 0
[
  "WindowsAzureActiveDirectoryIntegratedApp"
]
```

For PowerShell example see https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/hide-application-from-user-portal .
