### ISSUE TITLE
data (all azuread): should be case insensitive

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform-provider-azuread#369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Much like #246 please make `data` lookups for all `azuread` resources case insensitive, meaning make `name`, `names`, `display_name`, `user_principal_name`, `user_principal_names` and such case-insensitive.

Keep `resource` case sensitive to avoid breaking change.

> **_Personal Note_** If accepted, this approach should be adopted for all future `data` resources on all `providers`.

### New or Affected Resource(s)

* azuread_user
* azuread_users
* azuread_groups
* azuread_application
* azuread_service_principal

### Potential Terraform Configuration

**Technically, no change is needed.** Since `data` lookup is case-sensitive, everyone already provides case-sensitive value, whose behavior won't change.

However, if someone needs to `data` a resource that has been made case-sensitive by someone else (like Azure AD Admin), he could dramatically simplify his code. Consider following setup with `env="dev"`, `project="jupyter"` and `azuread_application named Jupyter-Dev`:

This does not work:
```
data "azuread_application" "jupyter" {
  name = "${var.project}-${var.env}"
}
```
> **_Error_**: DisplayName for Applications matching "displayName eq 'jupyter-dev'" does not match("Jupyter-Dev"!="jupyter-dev")
> on dev/jupyter/main.tf line 37, in data "azuread_application" "jupyter":
  37: data "azuread_application" "jupyter" {

Workaround:
```
locals {
  env_case = {
    dev = "Dev"
    prod = "Prod"
  }
  project_case = {
    jupyter = "Jupyter"
    saturn = "Saturn"
    moon = "Moon"
  }
}
data "azuread_application" "jupyter" {
  name = "${local.project_case[var.project]}-${local.env_case[var.env]}"
}
```

### References

* #246

**Comment by manicminer** [comment]
Hi @Tbohunek, thanks for opening this issue. Whilst I agree it makes sense in some cases to have case insensitive matching for some data source attributes, despite the API filters being case sensitive, we'd have to consider this on a per attribute (or per data source) basis to reduce the risk of introducing breaking changes.

I won't close this issue, but if you can update it to pick out specific properties you'd like to be looked at that would be super useful. Or we can focus on the `user` data source since that's the one with the example properties you mentioned?

Please note that any case insensitivity changes would only be potentially made for data sources and not for resources, which must remain case sensitive.

**Comment by Tbohunek** [comment]
Hello @manicminer thanks for such a prompt response!

> ... if you can update it to pick out specific properties you'd like to be looked at that would be super useful. Or we can focus on the `user` data source since that's the one with the example properties you mentioned?

I think it's quite obvious based on how `data` works and what attribute they require, but here you go
```
data "azuread_user" "example" {
  user_principal_name = "user@hashicorp.com" # this attribute needs to be case-insensitive
}
data "azuread_users" "users" {
  user_principal_names = ["kat@hashicorp.com", "byte@hashicorp.com"] # this attribute needs to be case-insensitive
}
data "azuread_application" "example" {
  name = "My First AzureAD Application" # this attribute needs to be case-insensitive
}
data "azuread_service_principal" "example" {
  display_name = "my-awesome-application" # this attribute needs to be case-insensitive
}
data "azuread_groups" "groups" {
  names = ["group-a", "group-b"] # this attribute needs to be case-insensitive
}
data "azuread_group" "example" {
  name = "A-AD-Group" # this attribute needs to be case-insensitive
}
```

> Please note that any case insensitivity changes would only be potentially made for data sources and not for resources, which must remain case sensitive.

Like I said myself: 
> Keep `resource` case sensitive to avoid breaking change.

**Comment by manicminer** [comment]
Thanks, my first thought is that for attributes that have uniqueness, and that is determined by Azure case-insensitively, we can look at reflecting that in the provider - these would be `azuread_user.user_principal_name` and `azuread_group.name`.

What is your use case for application and service principal display names? Those are not uniquely identified by that attribute so I'm not sure if there's enough benefit to offset the potential for breaking existing configurations.

**Comment by Tbohunek** [comment]
Some companies separate duties and so the DevOps team cannot write Azure AD. That's another team, who sometimes decides to do by themselves: They create an app for you with different case than specified.

DevOps is often fine with that because they don't have CICD yet. The issue comes when they get it, and they want to parametrize thigs like `env`, which they do lowercase, but the AAD Application has uppercase etc.


What I see as an issue is that Azure AD allows you to create multiple Applications with same name and same case. However, this doesn't work already anyway:

I just created two applications: `bot-dev` and `BOT-dev`.
Following code returns following errors:
```
data "azuread_application" "bot" {
  name = "bot-dev"
}
data "azuread_application" "botcase" {
  name = "BOT-dev"
}
```
> **_Error_**: found multiple Applications matching "displayName eq 'bot-dev'"
>  on dev/bot/main.tf line 33, in data "azuread_application" "bot":
>  33: data "azuread_application" "bot" {

>**_Error_**: found multiple Applications matching "displayName eq 'BOT-dev'"
>  on dev/bot/main.tf line 36, in data "azuread_application" "botcase":
>  36: data "azuread_application" "botcase" {

So technically it doesn't work already anyway even if the `data "azuread_application" {}` is case-sensitive, and so making it case-insensitive would not break it any further, but it would solve the issue described above where there is just one Application, but with different case than common variables used throughout the code.

What do you think of that @manicminer?

**Comment by manicminer** [comment]
@Tbohunek Thanks for testing that. Since it looks like the odata filter is matching insensitively on application displayNames I think it probably makes sense for us to do the same. Particularly as you noted, we have sanity checking to make sure we don't return the wrong object when >1 is found.

**Comment by Tbohunek** [comment]
Hi @manicminer any evolution here? :)

**Comment by manicminer** [comment]
@Tbohunek This will make it into v2.0 as it's a breaking change for the relevant data sources

**Comment by Tbohunek** [comment]
Thanks @manicminer I'm looking forward to getting ETA on v2.0. ❤️ 
However, where do you see the breaking change? Case-insensitive data sources won't find less than sensitive ones.

**Comment by manicminer** [comment]
No they but they might find more, which I admit is an outside case but I've seen some interesting configurations 🙂

Also we are not accepting changes into the v1.x series now unless they are bug fixes.
