### ISSUE TITLE
group_membership_claims shouldn't be a string

### ISSUE THREAD

**Issue by sioakim** [hashicorp/terraform-provider-azuread#375]
According to the [TF documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application):
group_membership_claims - (Optional) Configures the groups claim issued in a user or OAuth 2.0 access token that the app expects. Defaults to SecurityGroup. Possible values are None, SecurityGroup, DirectoryRole, ApplicationGroup or All.

But it is not a string - it can have multiple values:
From Terraform plan for a resource I imported:
group_membership_claims    = "SecurityGroup, DirectoryRole" -> "SecurityGroup"

Looking at the [MS documentation](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#add-group-claims-to-tokens-for-saml-applications-using-sso-configuration) we can see that through the Enterprise Applications settings the option is actually a Radio button which would make sense for the current Terraform implementation.

![image](https://user-images.githubusercontent.com/7794827/102870719-5716ce80-4435-11eb-8a25-791d003faa34.png)

But through App Registrations the same option is actually multiple choice:

![image](https://user-images.githubusercontent.com/7794827/102870608-28005d00-4435-11eb-9c7d-c7d288c1a64c.png)

Hence I think this setting should be a different type in Terraform.

**Comment by manicminer** [comment]
Hi @sioakim, thanks for opening this issue. The API accepts this property as a string value, which is why it's represented as such in the provider. Have you tried specifying a comma-delimited string?

**Comment by sioakim** [comment]
Yes when I use the comma separated I get:

Error: expected group_membership_claims to be one of [All None SecurityGroup DirectoryRole ApplicationGroup], got SecurityGroup, DirectoryRole

BUT when I import from state it comes in as mentioned above as:
group_membership_claims = "SecurityGroup, DirectoryRole" (comma seperated)

**Comment by manicminer** [comment]
@sioakim Ah yes, replying in haste I forgot about the validation for that property, sorry about that.

Unfortunately the current SDK doesn't support setting combinations like this, and it appears that both the current API and the upcoming MS Graph API have the same limitation. This means we'll need API support before we'll be able to support different combinations of security/non-security groups, inferred groups and directory roles.

It's interesting though that multiple membership claim types are read back if you set them in the portal, I'll look into this further.
