### ISSUE TITLE
azuread_user: Imported user password is replaced

### ISSUE THREAD

**Issue by xlz-jgoutin** [hashicorp/terraform-provider-azuread#377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
resource "azuread_user" "test" {
  user_principal_name = "test@example.com"
  display_name        = "Test"
  password            = "passw0rd!"
}
```

### Expected Behavior

When importing an already existing user and applying, the imported user password should not be modified.

### Actual Behavior

The user password is enforced to the value defined by `password` on the first `apply` that run just after the `import`.

This breaks already existing user login. The administrator needs to explain user its password changed and ask to change it.

### Steps to Reproduce

1. `terraform import azuread_user.my_user 00000000-0000-0000-0000-000000000000`
2. `terraform apply`

### Example output

``` 
$ terraform import azuread_user.my_user bc235b9d-ed8c-466c-8d01-b882267fa707

azuread_user.test: Importing from ID "bc235b9d-ed8c-466c-8d01-b882267fa707"...
azuread_user.test: Import prepared!
  Prepared azuread_user for import
azuread_user.test: Refreshing state... [id=bc235b9d-ed8c-466c-8d01-b882267fa707]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform
```

``` 
$ terraform plan

azuread_user.test: Refreshing state... [id=bc235b9d-ed8c-466c-8d01-b882267fa707]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azuread_user.test will be updated in-place
  ~ resource "azuread_user" "test" {
      + force_password_change = false
        id                    = "bc235b9d-ed8c-466c-8d01-b882267fa707"
      + password              = (sensitive value)
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by manicminer** [comment]
Hi @xlz-jgoutin, thanks for raising this issue. This looks likely due to the `password` property not having the Computed flag. We could potentially look at changing this, although this would be a breaking change and so if we did that, it would only make it into the next major version of the provider.

**Comment by jilgue** [comment]
+1

**Comment by manicminer** [comment]
@jilgue please could you vote with a reaction thumbs up rather than a comment as this helps us to gauge demand and reduce notification clutter, thanks!

**Comment by jilgue** [comment]
@manicminer sorry, I didn't read all community notes, I delete the comment.

**Comment by xlz-jgoutin** [comment]
For an unknown reason, Terraform now wants to reset the password of all my already managed users.

```hcl
  # azuread_user.azw_users["<removed_sensitive_value>"] will be updated in-place
  ~ resource "azuread_user" "azw_users" {
      + city                           = ""
      + country                        = ""
        id                             = "<removed_sensitive_value>"
      + immutable_id                   = ""
      + mobile                         = ""
      + onpremises_sam_account_name    = ""
      + onpremises_user_principal_name = ""
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ password                       = (sensitive value)
      + physical_delivery_office_name  = ""
      + postal_code                    = ""
      + state                          = ""
      + street_address                 = ""
        # (13 unchanged attributes hidden)
    }
```
All these users are Terraform managed for some months, and this worked well until today.
This is with hashicorp/azuread v1.4.0. Using an older version like v1.2.2 or v1.3.0 does not help.

Following `ignore_changes` does not help in this case:
```hcl
lifecycle {
    ignore_changes = [password]
  }

lifecycle {
    ignore_changes = all
  }
```
I am totally stuck because of this.

**Comment by manicminer** [comment]
@xlz-jgoutin Have you made any other changes recently? If you inspect the state, do those affected users have the correct password there?

**Comment by xlz-jgoutin** [comment]
After some tests, I found that the issue only occurs with Terraform 0.15.0, but not with Terraform 0.14.10.

I didn't change this configuration for a while. I just applied it 2 weeks ago to add a new user (Added by changing a list in a "tfvars") and it worked perfectly. In fact, only the Terraform version changed.

The state looks like this:
```json
 {
    "account_enabled": true,
    "city": "",
    "company_name": "<removed_sensitive_value>",
    "country": "",
    "department": "<removed_sensitive_value>",
    "display_name": "<removed_sensitive_value>",
    "force_password_change": false,
    "given_name": "<removed_sensitive_value>",
    "id": "<removed_sensitive_value>",
    "immutable_id": "",
    "job_title": "<removed_sensitive_value>",
    "mail": "<removed_sensitive_value>",
    "mail_nickname": "<removed_sensitive_value>",
    "mobile": "",
    "object_id": "<removed_sensitive_value>",
    "onpremises_sam_account_name": "",
    "onpremises_user_principal_name": "",
    "password": "wTYKJFVMMcQZLzSr",
    "physical_delivery_office_name": "",
    "postal_code": "",
    "state": "",
    "street_address": "",
    "surname": "<removed_sensitive_value>",
    "usage_location": "<removed_sensitive_value>",
    "user_principal_name": "<removed_sensitive_value>"
}
```
For all users, the state value of "password" perfectly match the state value of the "random_password.result" used to generate it.

This seems to not be fully related to the original GitHub Issue, do you want I open a separate issue?

**Comment by manicminer** [comment]
@xlz-jgoutin That's great, it helps narrow it down a lot. I agree it would be good to open a new issue for this - you can link to this one for context. Thanks!
