### ISSUE TITLE
azuread_group_member: show group and memeber name in the plan

### ISSUE THREAD

**Issue by ppanyukov** [hashicorp/terraform-provider-azuread#390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using `azuread_group_member` in `v1.3.0` of the provider (currently latest), the terraform plan is not very helpful as it shows only object IDs, which are meaningless to those reviewing the plan.  Consider this example:

```hcl
data "azuread_group" "parent-group" {
  display_name = "parent-group"
}

data "azuread_group" "child-group" {
  display_name = "child-group"
}

resource "azuread_group_member" "parent-group_child-group" {
  group_object_id  = data.azuread_group.parent-group.id
  member_object_id = data.azuread_group.child-group.id
}
```

The plan for this currently would look like this:

```hcl
Terraform will perform the following actions:

  # azuread_group_member.parent-group_child-group will be created
  + resource "azuread_group_member" "parent-group_child-group" {
      + group_object_id  = "f1e3d466-5687-4682-aa95-9bafae2f2f86"
      + id               = (known after apply)
      + member_object_id = "c6a0b72f-b263-4379-bc84-b17e59de27fa"
    }
```

Clearly this is less than ideal because when I look at this plan, I've no idea what becomes a member of what :) 

### Desired output

It would be helpful if `display_name` of the group and member were shown during the plan, e.g. like so:

```hcl
Terraform will perform the following actions:

  # azuread_group_member.parent-group_child-group will be created
  + resource "azuread_group_member" "parent-group_child-group" {
      + group_object_id     = "f1e3d466-5687-4682-aa95-9bafae2f2f86"
      + group_display_name  = "parent-group"
      + id                  = (known after apply)
      + member_object_id    = "c6a0b72f-b263-4379-bc84-b17e59de27fa"
      + member_display_name = "child-group"
      + member_kind         = "group"
    }
```

### New or Affected Resource(s)

* azuread_group_member

**Comment by manicminer** [comment]
Hi @ppanyukov, thanks for requesting.

I agree this would be a useful addition. However the rendering of a plan is performed by Terraform core and not by providers, and it's not possible for a provider to inject attributes in the plan. Computed fields are shown with the placeholder value `(known after apply)`, and other properties must be specified in your configuration in order to surface in the plan.

**Comment by ppanyukov** [comment]
Hmm, this is rather very unfortunate. Any suggestions how this can be addresses anywhere?

**Comment by manicminer** [comment]
I'd suggest trying to tackle this in your configuration as much as is feasible. For example (unless you are using a loop construct) you can be quite explicit with your resource labels.

You might consider raising a [core](https://github.com/hashicorp/terraform) feature request to garner discussion.

**Comment by ppanyukov** [comment]
Hey @manicminer , you mentioning labels and modules gave me an idea. I've created a module which works with loops and  produces output like this:

```hcl
# module.aad_group_members.azuread_group_member.group["member_group_1 to target_group_name"]:
resource "azuread_group_member" "group" {
    group_object_id  = "11111111-5687-4682-aa95-9bafae2f2f86"
    id               = "11111111-5687-4682-aa95-9bafae2f2f86/member/11111111-b263-4379-bc84-b17e59de27fa"
    member_object_id = "11111111-b263-4379-bc84-b17e59de27fa"
}

# module.aad_group_members.azuread_group_member.user["user1@myorg.com to target_group_name"]:
resource "azuread_group_member" "user" {
    group_object_id  = "11111111-5687-4682-aa95-9bafae2f2f86"
    id               = "11111111-5687-4682-aa95-9bafae2f2f86/member/11111111-c18a-404b-8f76-97df7439c2c6"
    member_object_id = "11111111-c18a-404b-8f76-97df7439c2c6"
}
```

What do you think?  :) 

For anyone facing the same issue, check it out here: https://github.com/ppanyukov/Terraform.Modules/tree/main/azure/aad_group_members

**Comment by manicminer** [comment]
@ppanyukov That's a great implementation, and well documented! You could publish that on the TF Registry ;)

**Comment by manicminer** [comment]
As this UX enhancement can't be achieved in the provider, and @ppanyukov has an elegant DSL workaround, I'm going to close this one for now. If this is a strongly needed feature, I'd suggest as per above raising a feature request in Terraform Core to spark further discussion. Thanks!
