### ISSUE TITLE
data source azuread_group needs to filter by type

### ISSUE THREAD

**Issue by rlaveycal** [hashicorp/terraform-provider-azuread#391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have multiple groups with the same name due the integration of Windows AD with Azure AD. Thus we have a group `foo` of types `Security` and `Microsoft 365`.

When using the azuread_group data source to look up by display name the wrong group (in my case) is returned. Adding the option to set the desired group type would solve this

### New or Affected Resource(s)

* azuread_group

### Potential Terraform Configuration

```hcl
data "azuread_group" "foo" {
  display_name = "foo"
  group_type    = "security"
}
```

**Comment by manicminer** [comment]
Hi @rlaveycal, thanks for requesting. I thought that groups can be both security and mail enabled? Do you have multiple groups having the same, one used for security and the other for mail/office?

**Comment by rlaveycal** [comment]
yes, one is a security group created in Windows AD (Source = `Windows server AD`). The other was created by Teams (Source = `Cloud`). Obviously not ideal but such is life.

**Comment by manicminer** [comment]
@rlaveycal This functionality has been merged and will be released later this week.
