### ISSUE TITLE
Import documentation for azuread_service_principal_password is unconsistent

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform-provider-azuread#392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Version 1.3.0

### Affected Resource(s)

* `azuread_service_principal_password`

### Issue description

Import example code id 
```
terraform import azuread_service_principal_password.test 00000000-0000-0000-0000-000000000000/11111111-1111-1111-1111-111111111111
```

However the note below states
```
This ID format is unique to Terraform and is composed of the Service Principal's Object ID, the string "password" and the Password's Key ID in the format {ServicePrincipalObjectId}/password/{PasswordKeyId}.
```

The example does not match the note.

**Comment by manicminer** [comment]
@BzSpi Thanks for reporting! We'll fix this up shortly.
