### ISSUE TITLE
Allow or deny certain domains on active directory on Azure

### ISSUE THREAD

**Issue by divyavmnair** [hashicorp/terraform-provider-azuread#398]
Can you please explain how we can do B2BManagementPolicy(Allow or deny certain domains on active directory on Azure) with Microsoft Graph api

**Comment by manicminer** [comment]
@divyavmnair This issue tracker is for tracking bugs and feature requests for the Terraform AzureAD provider and is not intended for general questions about related topics. As such I'm going to close this issue as off-topic, I recommend you pursue your question via an appropriate mailing list or forum. Thanks!
