### ISSUE TITLE
azuread_application fails when run from a user assigned managed identity

### ISSUE THREAD

**Issue by devlincashman** [hashicorp/terraform-provider-azuread#399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform 0.13.6
AzureAD 1.3.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
# Create Application
resource "azuread_application" "example" {
  display_name = "example"
}

# Create Service Principal linked to the Application
resource "azuread_service_principal" "example" {
  application_id = azuread_application.example.application_id
}

# Generate random password to be used for Application password (client secret)
resource "random_password" "example" {
  length  = 32
  special = true
}

# Create Application password (client secret)
resource "azuread_application_password" "example" {
  application_object_id = azuread_application.example.object_id
  value                 = random_password.example.result
  end_date_relative     = "17520h" # expire in 2 years
}

# Create role assignment for Service Principal
resource "azurerm_role_assignment" "contributor" {
  scope                = data.azurerm_subscription.main.id
  role_definition_name = "Contributor"
  principal_id         = azuread_service_principal.example.id
}
```

### Expected Behavior

Create application.

### Actual Behavior

azuread_application.main: Creating...

Error: Could not create application

graphrbac.ApplicationsClient#Create: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
Status=400 Code="Unknown" Message="Unknown service error"
Details=[{"odata.error":{"code":"Request_InvalidRequestUrl","message":{"lang":"en","value":"Request
url was invalid. The request should be like /tenantdomainname/Entity or
/$metadata. Tenant domain name can be any of the verified, unverified domain
names or context id."}}}]

### Steps to Reproduce

Run the example create-for-rbac with a user assigned managed service identity.

* #0000

**Comment by devlincashman** [comment]
There is an issue with the azurerm_client_config where it cannot pull the tenant id when you run as a user assigned managed identity. I am wondering if there is a similiar issue here where it is unable to pull the tenant id, therefore messing up the API url.

**Comment by manicminer** [comment]
Hi @devlincashman, are you specifying the tenant ID in your provider block (or via the `ARM_TENANT_ID` environment variable)? I believe you have to specify it because the metadata endpoint does not return the tenant ID, so it's not possible to determine automatically.

**Comment by devlincashman** [comment]
Thanks @manicminer that got me past the error. However I am now getting a new error, which I'm not finding much info on.

`azuread_service_principal.main: Creating...

Error: Could not create service principal

graphrbac.ServicePrincipalsClient#Create: Failure responding to request:
StatusCode=403 -- Original Error: autorest/azure: Service returned an error.
Status=403 Code="Unknown" Message="Unknown service error"
Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-02-11T23:25:55","message":{"lang":"en","value":"When
using this permission, the backing application of the service principal being
created must in the local
tenant"},"requestId":""}}]`

The user assigned managed identity has the following Azure Ad Graph API permissions:
Application.ReadWrite.All
Directory.ReadWrite.All

These were all granted with admin so they show up as admin consent in the portal gui after setting. However I cannot use the az cli admin-consent command so I am not sure if there is some missing permission there? Either way the error message being mispelled as well is very strange.

**Comment by manicminer** [comment]
There could be a few different things going on. However it's first worth noting that the AzureAD provider only supports managing service principals with an associated application - this is unfortunately an API limitation we are bound by - and this could be the cause of your error.
