### ISSUE TITLE
AzureADAndPersonalMicrosoftAccount

### ISSUE THREAD

**Issue by mixxit** [hashicorp/terraform-provider-azuread#408]
@RobertvBraam thanks for confirming. In that case I think we'll close this PR. For Microsoft Graph, there will likely be a new Application resource as the semantics are sufficiently different. We are readying a v1.0 release of the provider at the moment (see #298), and once that is done we'll continue working on an MS Graph implementation.

_Originally posted by @manicminer in https://github.com/hashicorp/terraform-provider-azuread/issues/309#issuecomment-678509284_

Hi @manicminer and @RobertvBraam 

I was trying to set this audience value today and came across your issue #309 - I see it was waiting for provider 1.0 which i see was merged

Is a patch to support this now possible?

**Comment by manicminer** [comment]
Hi @mixxit, we can't support this just yet due to the API semantics as mentioned in #309, but it will land in the next major version of the provider in the near future. We'll keep this issue open as a feature request for this property in the interim. Thanks!

**Comment by OvervCW** [comment]
Will this be supported soon now that 1.5.0 is available with the `use_microsoft_graph = true` configuration?

**Comment by manicminer** [comment]
We've added the `sign_in_audience` property in v1.5.0, although it currently only supports the `AzureADMyOrg` and `AzureADMultipleOrgs` values in order to maintain compatibility with the older API. We'll support the `AzureADandPersonalMicrosoftAccount` and `PersonalMicrosoftAccount` values in v2.0.
