### ISSUE TITLE
In `/docs/resources/application.md`, sample shell script is unnecessarily PowerShell-specific

### ISSUE THREAD

**Issue by CraigStuntzWillowTree** [hashicorp/terraform-provider-azuread#409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In `/docs/resources/application.md`, there is the following note:

> -> **Note:** Documentation on `resource_app_id` values for Microsoft APIs can be difficult to find, but you can use the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az_ad_sp_list) to find them. (e.g. `az ad sp list --display-name "Microsoft Graph" | select-string '"appid"' -cont 10`)

That script is PowerShell-specific (`select-string` does not exist in other shells), but it doesn't have to be that way. A better script would be:
```bash
az ad sp list --display-name "Microsoft Graph" --query '[].{appDisplayName:appDisplayName, appId:appId}'
```
...which works in any shell
### New or Affected Resource(s)

* `azuread_application`

**Comment by manicminer** [comment]
Hi @CraigStuntzWillowTree, thanks for the suggestion. I've added this in #417
