### ISSUE TITLE
azuread_group: Support for AzureAD B2B user invitations (guests)

### ISSUE THREAD

**Issue by daniel-simpson** [hashicorp/terraform-provider-azuread#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Building on [this comment](https://github.com/terraform-providers/terraform-provider-azuread/issues/36#issuecomment-462155004), I would like to be able to add guest users to a group using AzureAD B2B.

My use case for this is a clean separation of concerns between user authentication (handled in a separate tenant) and authorization (RBAC on groups).  There are Microsoft Graph APIs available for:
- [Get User in Tenant](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0)
- [Add user to tenant (via invitation)](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0)
- [Delete user from tenant](https://docs.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0)

The main part I can't get my head around is whether or not this would require an `azuread_guest` resource type or if we can infer it using the first snippet below.

If we don't need a new `azuread_guest` resource type, the side effect of extra guest users in this tenant is mitigated by the fact that once removed from all groups, the invited guest's permissions are effectively zero, though I'm aware that in Terraform we don't like things to be implicit 😄 

### New or Affected Resource(s)

* azuread_group
* (Optional) azuread_guest

### Potential Terraform Configuration

```hcl
resource "azuread_group" "mygroup" {
  name = "MyGroup"
  # owners = ["foo.bar@example.com"]
  # members = ["foo.bar2@example.com"]
  guests = ["externalAadUser@test.onmicrosoft.com"]
}
```

OR

```hcl
resource "azuread_guest" "guest_invite" {
  email = "test@mail.com"
}

resource "azuread_group" "mygroup" {
  name = "MyGroup"
  members = ["${azuread_guest.guest_invite.id}"]
}
```

### References

* Depends on #8 (merged)
* Original comment on #36

**Comment by a138076** [comment]
Would be very interested in this functionality!

**Comment by daniel-simpson** [comment]
Just an FYI but I have started implementing this feature but am partially blocked due to the above linked issue (invitations API not available in Azure SDK for Go)

**Comment by dansanabria** [comment]
wonder if there's an update on this ?

**Comment by CodingAnarchy** [comment]
Wanted to note for our desired use case, we want the `azuread_guest` without concern for groups. We can use groups if that's how it is implemented, but mainly we just need to invite a guest user and assign them roles, which would be great if we can do it all via Terraform.

**Comment by yuri-tieto** [comment]
Any update on this one?

**Comment by angeloedades** [comment]
Hi guys, just wanted to add - this feature would be really useful in helping me manage users in code. Is there a rough timeline that we can expect some progress? I know from the previous update that the API required is not avialable in Go. Have you guys reached out to Microsoft?

**Comment by angeloedades** [comment]
Hi Issue Followers,

If this feature is something that you would like make sure to vote on https://github.com/hashicorp/terraform-provider-azuread/issues/307 too

**Comment by manicminer** [comment]
Thanks @angeloedades. When I opened the other issue I forgot there already was one, but now they both have upvotes we'll keep them both open 👍

**Comment by angeloedades** [comment]
Thanks @manicminer - just to give a bit more background as to why I am 100% in on this feature - I manage a few Azure tenants and the majority of them use B2B users as guests. This feature would immensely help me manage guest users better rather than writing some custom mechanism to issue invites

**Comment by bridgepate** [comment]
Please add this feature

**Comment by KoenR3** [comment]
Same here, we have a lot of B2B users that need to be managed.  Currently we cannot add the management to Terraform and we have to leave the environment for this, which is a shame.

**Comment by manicminer** [comment]
This functionality has been merged with #401, which adds a `user_type` property to the `azuread_user` resource - you should then be able to add guest users as group members.

**Comment by bridgepate** [comment]
Thanks.

**Comment by manicminer** [comment]
Unfortunately we need to revert the support for this property as the API appears very broken, more info in #413

We'll keep this issue closed and supercede it with 307 since that's focused on the invitations API in MS Graph. This feature is prominently on our roadmap and we'll be implementing it as soon as we are able.

**Comment by manicminer** [comment]
For group member support, I would suggest looking up guest users with the [azuread_user](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/user) data source, which supports user principal names in the format `user_guestcorp.com#EXT#@invitingtenant.net`. You will need to create these users out of band for now.
