### ISSUE TITLE
[azuread_service_principal_password] Impossible to import existent password of Service Principal

### ISSUE THREAD

**Issue by JeremyBouchet** [hashicorp/terraform-provider-azuread#419]
Hello,

I want import the password of my Service Principal in terraform.tfstate file but that don't works.
I have an existent Service Principal and an existent password which is linked to this one.

### Terraform (and AzureAD Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/datadog/datadog v2.22.0
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/random v2.3.1

### Affected Resource(s)

module.aks_02.azuread_service_principal_password.velero

### Terraform Configuration Files

```hcl
data "azuread_service_principal" "velero" {
  # Service Principal "mySP"
  application_id       = "690d4d49-0c97-4222-8f12-9d32a9ed5e67"
}

resource "azuread_service_principal_password" "velero" {
  service_principal_id = data.azuread_service_principal.velero.application_id
  value                 = "XXXXX"
  end_date             = "2050-01-01T01:02:03Z"
}
```

### Debug Output

**Error: Cannot import non-existent remote object
While attempting to import an existing object to
azuread_service_principal_password.velero, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.**

### Expected Behavior

That the password of my Service Principal  let imported in my terraform.tfstate file

### Actual Behavior

Terraform returns me above error.

### Steps to Reproduce

1. Delete my subfolder ".terraform" on my Terraform project
2. `terraform init`
3. `terraform plan`
2. `terraform import module.aks_02.azuread_service_principal_password.velero "17551cc9-546f-4a47-8118-e0a28b0b5e82/password/29961ed0-2dc5-4a42-b28c-ca178c32497d"`

The value "17551cc9-546f-4a47-8118-e0a28b0b5e82" is the object ID of my Service Principal
The value "29961ed0-2dc5-4a42-b28c-ca178c32497d" is the Application ID of my Service Principal

**Comment by JeremyBouchet** [comment]
Hello @manicminer ,

I wrote bad information for "The value "29961ed0-2dc5-4a42-b28c-ca178c32497d" is the Application ID of my Service Principal".

I just fix my comment.

In my AAD I really have the value "29961ed0-2dc5-4a42-b28c-ca178c32497d" for the ID of the secret of my Service Principal.

For information I have always the problem.

regards,

**Comment by manicminer** [comment]
@JeremyBouchet Are you sure you created a service principal password and not an application password?

**Comment by JeremyBouchet** [comment]
Hello @manicminer,

Indeed in my initial Terraform code I forgot to declare the resource "azuread_application".
Thanks to your [post](https://github.com/hashicorp/terraform-provider-azuread/issues/421#issuecomment-811473564) with the [Azure article](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) about the difference between an Azure Application and an Azure Service Principal.

I integrated my resource "azuread_application" in addition to "azuread_service_principal".

Below my final code :

```hcl
data "azuread_application" "velero" {
  # Service Principal "DAS-SP-LBN_Velero-AD-App-int-clu02" (This "Application" object is present in "Azure AD" service and under "App registrations")
  application_id = "690d4d49-0c97-4222-8f12-9d32a9ed5e67"
}

data "azuread_service_principal" "velero" {
  # Service Principal "DAS-SP-LBN_Velero-AD-App-int-clu02" (This "Application" object is present in "Azure AD" service and under "Enterprise Applications")
  application_id          = "690d4d49-0c97-4222-8f12-9d32a9ed5e67"
}

...

# I use the password of the secret of Service Principal
`velero_sp_secret = "xxxxxx"`

```

All works fine.
Thanks
