### ISSUE TITLE
A default scope (user_impersonation) is created for azuread_application even with explicitly instructed not to

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform-provider-azuread#424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "myapp" {
  display_name               = local.myapp_name
  identifier_uris            = ["https://mytenant.onmicrosoft.com/${local.myapp_name}"]

  oauth2_permissions = []
}
```

### Expected Behavior

According to the documentation providing an empty array should create no scopes in app registration.

### Actual Behavior

`user_impersonation` scope is created when running apply for the first time. After running apply once again terraform finds out of it and tries to delete the scope, but it fails (everything is a success but scope does not get deleted).

### Steps to Reproduce

1. `terraform apply` - creates an app with the dummy scope that should not be present
2. `terraform apply` - tries to delete the scope that was created in step 1, reports success but scope is not deleted
3. `terraform apply` - same as step 2 forever

**Comment by manicminer** [comment]
Hi @ilya-git, thanks for reporting this bug. I believe this is already reported at #340 and is related to #328.

This is a Terraform SDK issue which we are planning to address in the next major version v2.0 of the AzureAD provider. Unfortunately we cannot resolve this beforehand as it requires a breaking change to the schema of affected resources.
