### ISSUE TITLE
Application identifier_uris no longer supports URNs and string values that are not considered a URL

### ISSUE THREAD

**Issue by MarkDordoy** [hashicorp/terraform-provider-azuread#425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform: v0.13.4
azuread_provider  ≥  1.2.0

### Affected Resource(s)

* `azuread_application `

### Terraform Configuration Files

```hcl
resource "azuread_application" "application" {
  name    = "hello_world"
  homepage     ="http://helloworld"
  identifier_uris = ["urn:uuid:41055901-ff51-46ee-bcf8-c37d0c3e484b"]
  reply_urls     = ["https://helloworld/acs/reply"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  type  = "webapp/api"
}
```

### Debug Output

```
Error: URL has no host

  on ../src/tf/modules/tf-azuread-saml/main.tf line 11, in resource "azuread_application" "application":
  11:   identifier_uris            = var.identifier_uris
```

### Expected Behavior

Both AzureAD UI and the Microsoft Graph happily accept a string for the EntityID/Identifier_uris. Any value (providing it is unique across the tenant) should be accepted and was up until and including version 1.1.1. 

### Actual Behavior

When using something other than a url format, terraform throws an error of `URL has no host` and it doesnt even tell you  what host/application has the issue. 

### Steps to Reproduce

1. `terraform apply`

### References

I believe the issue is shown via this line of code: https://github.com/hashicorp/terraform-provider-azuread/blob/v1.2.2/internal/validate/url.go#L57-L63 and is caused by this: https://github.com/hashicorp/terraform-provider-azuread/blob/v1.2.2/internal/validate/url.go#L46 

We currently use this provider to setup and create app registrations and enterprise apps used for SAML. We use this for both internal and external apps and cannot force a 3rd party to switch from a random string or URN to a url. 

I've spoken to @manicminer via slack about this issue and he should have some understanding of it.

**Comment by buffer51** [comment]
Interestingly, there is some suggestion that URN are supported: https://github.com/hashicorp/terraform-provider-azuread/blob/251c86db8ec89d1f1faaa83044aaf6fb69a60885/internal/validate/url.go#L21-L23

I can't follow the entire logic of the code, but it seems that the reuse of code between some metadata that is meant to be actual URLs (e.g. login & logout URLs) vs metadata that can be URIs including URNs is the issue.

One solution could be to check the scheme earlier in the method, to be able to parse URNs & URLs differently. Or to split the code altogether.
