### ISSUE TITLE
Add support for publicClient

### ISSUE THREAD

**Issue by czmirek** [hashicorp/terraform-provider-azuread#436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for the `publicClient` property [described in the MS Graph docs](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0). This should be possible after moving this provider to MS Graph.

```json
{
   "publicClient": {
      "redirectUris": [ "http://example.com" ]
   }
}
```

Right now, only the web redirectUris are supported.

```json
{
    "web": {
        "redirectUris": [ "http://example.com"],
    }
}
```

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "app" {
  display_name = "My application"
  public_client {
     redirect_uris = [ "http://example.com" ]
  }
}
```

**Comment by manicminer** [comment]
Thanks for requesting @czmirek, we'll look to add this in v2.0 as it requires an incompatible schema change.
