### ISSUE TITLE
The `metadata_host` provider attribute is deprecated and will be removed in version 2.0

### ISSUE THREAD

**Issue by teodor-kostadinov** [hashicorp/terraform-provider-azuread#437]
hey all,

Since updating to version 1.5.0, we have started seeing the following warnings: 

```
 Warning: Deprecated Attribute
│
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on _generated_global_providers.tf line 26, in provider "azuread":
│   26: provider "azuread" {
│
│ The `metadata_host` provider attribute is deprecated and will be removed in
│ version 2.0
```

https://github.com/hashicorp/terraform-provider-azuread/blob/e9f389f73d419c94cb9bf036f38878877b0439db/internal/provider/provider.go#L90

We are not defining the metadata_host attribute on the provider block or setting its corresponding environment variable. 

It is not something that's bugging us massively, but it would be nice to not have it showing up in our pipelines until v2 is released.

**Comment by manicminer** [comment]
Thanks for reporting @teodor-kostadinov. We'll aim to fix this asap as on top of being annoying, it can also mask other deprecation warnings.
