### ISSUE TITLE
azuread - support Microsoft Graph Api in addition to Azure AD Graph Api

### ISSUE THREAD

**Issue by kamakay** [hashicorp/terraform-provider-azuread#443]
Dear TF members,

I would ask for the support of __Microsoft Graph API__ in addition to __Azure AD Graph API__  (Azure AD Graph API will be disconinued by the end of june 22).

The current doc such us for the __azuread_user__ the doc states _"If you're authenticating using a Service Principal then it must have permissions to Read directory data within the __Windows Azure Active Directory API__ ."_

Do you have a plan for this adoption ?

**Comment by kaovd** [comment]
This change recently went in as of 1.5.0, see the changelogs and docs for how to use. Azure Ad / the old api will be dropped eventually

**Comment by kamakay** [comment]
Thanks, I was reading again the doc for 1.5.0 release ant it states "Windows Active Directory API"
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/user

As far as I undersand MS Graph API are in beta support, so we need to stay tuned.

Thanks again for the info.

R

**Comment by manicminer** [comment]
Hi @kamakay, thanks for making this request! @kaovd is correct, our initial beta support for Microsoft Graph was recently released and will be followed by a GA release in the near future. As this is currently in beta, not all of the docs have been updated yet with relevant details such as API permissions, however you can find an overview of the changes in the [Migration Guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph) (including new API permissions for MS Graph).

When enabling beta support for MS Graph, all resources and data sources will be managed via MS Graph, however some requests will still be made to the AAD Graph API so it's important that you don't remove your existing app permissions just yet.

As this is currently being tracked in #323, I'm going to close this as a duplicate, but please be sure to subscribe to #323 for further updates. Thanks!
