### ISSUE TITLE
azuread_application_password start/end date

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azuread#447]
The upgrade guide state that `start_date` and `end_date` will become readonly as they are not supported by AAD, however the [documentation](https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http) for addpassword shows that these fields are still available?

**Comment by manicminer** [comment]
Hi @hbuckle, thanks you are correct - this was down to an SDK bug and will be fixed in v1.5.1 this week
