### ISSUE TITLE
required_resource_access failing with "Role" type

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform-provider-azuread#449]
My azuread_application works fine with just "Scope" types for graph api, but when I add a "Role" type for an app, it fails with the error below. I checked the plan file and the IDs I'm using are correct. The terraform is here. I am not specifying the "public_client" flag as I saw that issue raised previously and removed it. I'm using 1.5.0 of AzureAD provider, and 0.15.3 of Terraform.

```hcl
resource "azuread_application" "tagetik" {
display_name = lower("gfp-${var.environment_name}-tagetik-wjntest")
type = "native"
reply_urls = ["https://tagetik-dev.gfp.swissre.com/tagetikcpm"]
available_to_other_tenants = false
oauth2_allow_implicit_flow = true
owners = [for value in data.azuread_user.ad_app_owners: value.object_id]
required_resource_access {
resource_app_id = local.graph
resource_access {
id = local.graph_email
type = "Scope"
}
resource_access {
id = local.graph_open_id
type = "Scope"
}
resource_access {
id = local.graph_profile
type = "Scope"
}
resource_access {
id = local.graph_user_read
type = "Scope"
}
}
required_resource_access {
resource_app_id = data.azuread_application.reporting_cycle_service.application_id
resource_access {
id = local.rcs_submission_state_read
type = "Role"
}
}
}
```

```
Error: Updating Application with object ID "2915be5b-e696-4780-8b76-380d79ecb7ce"
│
│ with azuread_application.tagetik,
│ on tagetik_service_principal.tf line 1, in resource "azuread_application" "tagetik":
│ 1: resource "azuread_application" "tagetik" {
│
│ graphrbac.ApplicationsClient#Patch: Failure responding to request:
│ StatusCode=400 -- Original Error: autorest/azure: Service returned an
│ error. Status=400 Code="Unknown" Message="Unknown service error"
│ Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-05-31T09:18:49","message":{"lang":"en","value":"Property
│ requiredResourceAccess.resourceAccess is
│ invalid."},"requestId":"bb3fd667-5721-47df-9d26-45c50dacf772","values":[{"item":"PropertyName","value":"requiredResourceAccess.resourceAccess"},{"item":"PropertyErrorCode","value":"GenericError"}]}}]
```

**Comment by manicminer** [comment]
Hi @waynejnicklin, thanks for reporting this error. I believe this is due to `type = "native"` for your referencing application - there are legacy API constraints for "native" / "public client" applications that restrict what other properties can be included in the manifest such as identifierUris and I believe role-type API permissions.

This will be fixed in v2.0 of the provider when we will be migrating away from the legacy API, unfortunately there is no interim workaround other than removing `type = "native"` from your application resource and also ensuring that `public_client` is set to `false`.

**Comment by waynejnicklin** [comment]
Ah OK... so that sounds like an easy fix then... I just remove "native" which I think will make no difference anyway as it's deprecated?

Thank you!

**Comment by manicminer** [comment]
In the provider, setting `type = "native"` implies `public_client = true`, which to my knowledge translates to the `isFallbackPublicClient` field (called "Allow public client flows" in the portal). You may or may not need this.
