### ISSUE TITLE
New Resource for Authorized client applications for Oauth 2 permission scope

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azuread#451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

kinda surprised i didn't see another request for this yet, so maybe i'm missing it in the docs or the name in another request.  This is assigning permissions scopes to specific authorized clients.  The main benefit being supporting Azure.Identity's visual studio provider to work.

This is the area here
![image](https://user-images.githubusercontent.com/1514496/121071443-2f21ea00-c78d-11eb-9ae9-81e3409b6786.png)

### New or Affected Resource(s)

* azuread_application_oauth2_permission_authorized_client

### Potential Terraform Configuration

```hcl

resource "azuread_application" "example" {
  name = "example"
}

resource "azuread_application_oauth2_permission_scope" "example1" {
  application_object_id      = azuread_application.example.id
  admin_consent_description  = "Administer the application 1"
  admin_consent_display_name = "Administer 1"
  enabled                    = true
  type                       = "User"
  user_consent_description   = "Administer the application 1"
  user_consent_display_name  = "Administer 1"
  value                      = "administer1"
}

resource "azuread_application_oauth2_permission_scope" "example2" {
  application_object_id      = azuread_application.example.id
  admin_consent_description  = "Administer the application 2"
  admin_consent_display_name = "Administer2"
  enabled                    = true
  type                       = "User"
  user_consent_description   = "Administer the application 2"
  user_consent_display_name  = "Administer2"
  value                      = "administer2"
}

azuread_application_oauth2_permission_authorized_client "example"
{
    client_id = "872cd9fa-d31f-45e0-9eab-6e460a02d1f1"
    scope_ids = [
       azuread_application_oauth2_permission_scope.example1.id,
       azuread_application_oauth2_permission_scope.example2.id,
    ]
}
```

assuming the api follows the gui which lets you assign many at one:
![image](https://user-images.githubusercontent.com/1514496/121072259-33023c00-c78e-11eb-8157-e24fce96dc2e.png)

if it's just 1 to 1, then scope_ids would be scope_id...and in such a case, it'd be nice to be able to nest multiple of these under a authorized_clients block in azuread_application_oauth2_permission_scope

**Comment by manicminer** [comment]
Hi @drdamour, thanks for requesting this! This is a Microsoft Graph specific feature that will be possible to implement once we reach v2.0. I'm not sure whether this could make it into v2.0 specifically, or a subsequent 2.x release, but we can definitely consider it.

In the API schema, this is actually a different property than oauth2PermissionScopes (`oauth2_permission_scope` block in Terraform) so my initial thoughts are that the configuration might look like this:

```hcl
resource "azuread_application" "example" {
  display_name = "example-app"

  api {
    pre_authorized_application {
      application_id = azuread_application.other_app.application_id
      permission_ids = ["uuid1", "uuid2"]
    }
    pre_authorized_application {
      application_id = azuread_application.further_app.application_id
      permission_ids = ["uuid3", "uuid4"]
    }
  }
}
```

With the potential to introduce this in a new resource, e.g. `azuread_application_pre_authorized_application`

WDYT?

**Comment by drdamour** [comment]
@manicminer i guess...you sure it's not related to the oauth2_permission_scope stuff...those are the things i get to choose from in the portal web gui IME.

**Comment by manicminer** [comment]
@drdamour Alas it is a separate feature even though in the portal you can find them on the same page

**Comment by drdamour** [comment]
@manicminer get it, was more saying its about oauth2 not general api, but i see the scope properties are oauth specific but nothing else

**Comment by sdaggulakr** [comment]
Please remove me from all these mails.


Sandeep Daggula
Supply Chain DevOps Engineer
Technology & Digital | The Kroger Co.
cell: 567.333.6789

***@***.***D76F32.DEFB2D50]
