### ISSUE TITLE
applicationTemplateId field is missing in azuread_application

### ISSUE THREAD

**Issue by padma33** [hashicorp/terraform-provider-azuread#458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Terraform Configuration Files

```hcl
resource "azuread_application" "azuread-application-list" {
  name                       = random_string.globalrandom1.result
  homepage                   = "valid_url"
  available_to_other_tenants = false
  application_template_id = "ID_AWS"
  

}
```

### Debug Output

Unable to provide application_template_id while trying to create enterprise application in azure portal with AWS app type
Below is the error that i received on terraform apply 
Error: Unsupported argument
│ 
│   on azure-role-definition.tf line 27, in resource "azuread_service_principal" "azuread-service-principal":
│   27:   applicationTemplateId = "xxxx-xxxx-xxxx-xxxx"
│ 
│ An argument named "applicationTemplateId" is not expected here.

### Expected Behavior

It should be supporting applicationTemplateId field which is a mandatory param while creating azure Active directory Service Principal in Azure portal via terraform 

### Actual Behavior

applicationTemplateId field is not identified by terraform

### Steps to Reproduce

Create Enterprise application with AWS template in Active directory via terraform 
Below is my terraform file
resource "azuread_application" "azuread-application-list" {
  name                       = random_string.globalrandom1.result
  homepage                   = "valid_url"
  available_to_other_tenants = false
  application_template_id = "ID_AWS"
  

}

resource "azuread_service_principal" "azuread-service-principal" {
  application_id = azuread_application.azuread-application-list.application_id
}

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @padma33, thanks for requesting this feature! Although I have not yet looked into this in depth, this appears to be a combination of the attribute you requested on the `azuread_application` resource, `application_template_id` and another operation/resource for instantiating gallery applications.

We will be able to look at adding this functionality once we have completed our current transition to Microsoft Graph and the provider has reached the next major version (v2). This work is underway right now and you can track progress in #323.

API refs:
- https://docs.microsoft.com/en-us/graph/api/resources/application
- https://docs.microsoft.com/en-us/graph/api/applicationtemplate-instantiate
