### ISSUE TITLE
Accessing application/service principal passwords before provider 2.0

### ISSUE THREAD

**Issue by uipo78** [hashicorp/terraform-provider-azuread#460]
I'm using version 1.5.0 of the provider and I'm trying to access the password of a service principal I just created. However, that doesn't currently seem to be an attribute exported by either the [service principal](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal#attributes-reference) or [service principal password](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password#attributes-reference) resource.

I saw this in the migration documentation:
> The value field [of the service principal resource] will become read-only as Azure Active Directory no longer accepts user-supplied password values. Passwords will instead be auto-generated by Azure and will be exported as attributes by the resource.

Does this mean that we'll need to wait for version 2.0 of the provider before we'll be able to access passwords from a service principal resource?

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by manicminer** [comment]
Hi @uipo, thanks for reporting this. Have you tried with v1.5.1 (released 2 days ago)? There were a few bugs in the app / SP password implementations in v1.5.0

**Comment by katlimruiz** [comment]
I have an additional problem to this, even if the value would be exported, do you know how can I get the value from the run?

I mean I am using TF Cloud, and I can create the secret, but then I need to insert it in my newrelic configuration, and I don't have direct access to it.

**Comment by manicminer** [comment]
@katlimruiz The password is still exported via the `value` attribute, afaik you should be able to [access this in TFC](https://www.terraform.io/docs/cloud/api/state-version-outputs.html) if you make it an output variable?

**Comment by manicminer** [comment]
@uipo78 When using MS Graph password value is set by Azure, and Terraform saves it to state as the `value` attribute. So you can access the value like this:

```hcl
resource "azuread_application_password" "test" {
  application_id = azuread_application.test.application_id
}

output "application_password" {
  value = azuread_application_password.test.value
}
```

(the same for `azuread_service_principal_password`)

**Comment by katlimruiz** [comment]
Thanks for the answer. Thats half way the issue.

Now how can I see the password so I can use it. You see the sp password is
the client secret, therefore I need to get the original value to insert it
as my credentials in external services. For instance, to create a Azure
Service Connection where I have to put clientid and clientsecret.

And from what I've seen, it seems the output is printed redacted or as
(sensitive value).

Kat Lim Ruiz
CTO
Juntoz.com

**Comment by manicminer** [comment]
@katlimruiz In that case I believe you will be able to obtain more direct support by emailing TFC Support as it sounds like this is more of a general question of obtaining Sensitive values from your state?

**Comment by katlimruiz** [comment]
thanks you are right
