### ISSUE TITLE
azuread_user after terraform upgrade wants to overwrite null fields with empty strings

### ISSUE THREAD

**Issue by cthulhu** [hashicorp/terraform-provider-azuread#468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
resource "azuread_user" "Jane_Doe" {
  user_principal_name   = "jane.doe@email.com"
  display_name          = "Jane Doe"
  mail_nickname         = "jane.doe"
  force_password_change = true
}
```

### Expected Behavior

The plan should be green

### Actual Behavior

The plan contains changes on fields that were not set via terraform and had value null, also some are deprecated.

```hcl
~ resource "azuread_user" "Jane_Doe" {
      + city                           = ""
      + company_name                   = ""
      + country                        = ""
      + department                     = ""
      + given_name                     = ""
        id                             = "XXX"
      + immutable_id                   = ""
      + job_title                      = ""
      + mobile                         = ""
      + mobile_phone                   = ""
      + office_location                = ""
      + onpremises_immutable_id        = ""
      + onpremises_sam_account_name    = ""
      + onpremises_user_principal_name = ""
      + physical_delivery_office_name  = ""
      + postal_code                    = ""
      + state                          = ""
      + street_address                 = ""
      + surname                        = ""
}
```

### Steps to Reproduce

Upgrade from terraform 0.14.11 to terraform 1.

1. `terraform apply`

### Important Factoids

For some users, it forces password change as well.

### References

* #0000

**Comment by cthulhu** [comment]
Looks like all those fields were added with this commit: https://github.com/hashicorp/terraform-provider-azuread/commit/11bf980477c3c54990d75c08cdaa0a0d3b545582#diff-9d5dc9c90ad31cdf18d557edf350d28e1df684059ef5cd5d9cb09ab2c5e01d67

**Comment by manicminer** [comment]
Hi @cthulhu, thanks for reporting this. I have tried to reproduce by applying the sample config using TF 0.14.11, then upgrading to 1.0.0, but this is the output I got (which was expected):

```
22:03:30 [:~/tmp/azuread-issue-468] 1 % terraform apply
azuread_user.Jane_Doe: Refreshing state... [id=db95b632-6886-49d3-a230-6d7d856c79de]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azuread_user.Jane_Doe has been changed
  ~ resource "azuread_user" "Jane_Doe" {
      + given_name            = "Janey"
        id                    = "db95b632-6886-49d3-a230-6d7d856c79de"
      + surname               = "Does"
        # (15 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
22:03:38 [:~/tmp/azuread-issue-468] % terraform apply
azuread_user.Jane_Doe: Refreshing state... [id=db95b632-6886-49d3-a230-6d7d856c79de]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

(second apply also shown for completeness)

Have you tried applying this plan with a test user? All the fields shown in your plan are Computed so if they are not specified in your configuration, they should not be updated in AAD.

**Comment by cthulhu** [comment]
Hi @manicminer! Thank you for your response!  I did apply fields drift on the test user and it looks like it didn't change anything in AzureAD. So perhaps it's safe to apply it to all the users we manage via terraform. Will close this ticket.
