### ISSUE TITLE
Data Source to get Gets Object IDs or Application IDs for multiple Service Principals i.e. azuread_service_principals

### ISSUE THREAD

**Issue by nitmatgeo** [hashicorp/terraform-provider-azuread#471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Similar to [azuread_service_principal](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/service_principal), we require something new like `azuread_service_principals` just like we have for [azuread_users](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users). This will help to pass list of SPNs and retrieve their Object IDs as a list.

### New or Affected Resource(s)
* azuread_service_principals

@manicminer your views please :) If approved, I think this could be pretty easy for your team if it could be almost replication similar to `azuread_users`.

**Comment by manicminer** [comment]
Hi @nitmatgeo, thanks for the feature request. This seems like it would be a reasonable addition. I'm curious to learn more about your use case, if you're able to give a little more detail?

**Comment by nitmatgeo** [comment]
Hey @manicminer really appreciate your support; I am in the process of creating some automation to manage IAM & RBAC in Azure using Terraform by integrating data in CSV files. I am also eagerly awaiting v2.1.0 😸 Currently, I could achieve most of it especially with users & groups. 
Only thing am yet to achieve are-
1. https://github.com/hashicorp/terraform-provider-azuread/issues/452
2. https://github.com/hashicorp/terraform-provider-azuread/issues/435
3. I am planning to extend it to SPN as well; _this #471 is 1 step towards it_.

For instance, one of my objective is that I want to add SPN as a member to a group and my file will have Type specified as SPN or User or Group and based on the type, I create a lookup to assign respective objectID as member to group. Please let me know if you require further information.

**Comment by manicminer** [comment]
Thanks for the additional context. That makes sense - I was imagining something where you'd be sourcing an external list of service principals :)
