### ISSUE TITLE
Please support knownClientApplications

### ISSUE THREAD

**Issue by thecodetinker** [hashicorp/terraform-provider-azuread#477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I need to set `knownClientApplications` in an Azure AD application manifest, but it appears this is not currently possible.

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "example" {
  display_name     = "example"
  identifier_uris  = ["api://example-app"]
  known_client_applications = [azuread_application.myapi.application_id]
}
```

### References

* https://github.com/hashicorp/terraform/issues/24748

**Comment by manicminer** [comment]
Hi @thecodetinker, thanks for requesting this feature. There is a PR open #474 that adds this functionality, which is due to be released soon in v2.0 of the provider.

**Comment by thecodetinker** [comment]
Hi - thank you, appreciate the quick turnaround on that. 

I'm not sure how long v2.0 will be, or when we'll be able to migrate to it. Any chance of a back-port to v1?

**Comment by manicminer** [comment]
v2.0 is due for release soon, but there unfortunately won't be a backport to v1 - in general we only backport security fixes but in this case it's not compatible anyway

**Comment by thecodetinker** [comment]
Ok no worries, I'll make do with `az ad app update` for now.
