### ISSUE TITLE
Time based password rotation for azuread_application_password and azuread_service_principal_password

### ISSUE THREAD

**Issue by rikribbers** [hashicorp/terraform-provider-azuread#480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In provider version 2 azuread_application_password and azuread_service_principal_password will no longer support setting the value of the secret. 

However I would like to have a mechanism to rotate the password periodically. Currently we do this like this with a random value:

```hcl
resource "time_rotating" "example" {
  rotation_days = 1
}

resource "random_id" "password" {
  keepers = {
    # Generate a new password each time time rotates
    rotation = time_rotating.example
  }
  byte_length = 8
}

resource "azuread_service_principal_password" "password" {
  service_principal_id = azuread_service_principal.sp.object_id
  # 10 days valid; rotated every day
  end_date_relative = "240h"
  value =random_id.password.hex
}
```

### New or Affected Resource(s)

* azuread_application_password 
* azuread_service_principal_password

### Potential Terraform Configuration

```hcl

resource "time_rotating" "password" {
  rotation_days = 1
}

resource "azuread_service_principal_password" "password" {
  service_principal_id = azuread_service_principal.sp.object_id
  # 10 days valid; rotated every day
  end_date_relative = "240h"
  keepers = {
    # Generate a new password each time time rotates
    rotation = time_rotating.password
  }
}

```

### References
Original inspired by this blog post:

* https://dev.to/antoinega/rotate-on-a-periodic-basis-using-terraform-gn5

**Comment by manicminer** [comment]
Hi @rikribbers, thanks for the suggestion. This seems like a very reasonable addition given that `value` can no longer be used to inject new passwords to enable rotation. In principle this should be straightforward to add.
