### ISSUE TITLE
azuread_application v2.0 Error: missing expected [ when attempting to read state created by v1.6.0

### ISSUE THREAD

**Issue by conzyor34** [hashicorp/terraform-provider-azuread#484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
$ terraform -v
Terraform v1.0.0
on linux_amd64
+ provider registry.localhost.com/local/azuread v2.0.0
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
```

The v2.0 `azuread` provider was compiled from `main`.

### Affected Resource(s)

* `azuread_application`

#### Before

```hcl
terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = ">= 1.6.0"
    }     
  }
}

resource "azuread_application" "app_registration" {
  display_name = "test-app-registration"
  identifier_uris = ["https://website.company.com/"]
  sign_in_audience = "AzureADMyOrg"

  web {
    homepage_url = "https://website.company.com"
    redirect_uris = [
      "http://localhost/auth/redirect",
      "https://website.company.com/auth/redirect"
    ]

    implicit_grant {
      access_token_issuance_enabled = false
    }
  }
}
```

#### After Upgrade to v2.0

```hcl
terraform {
  required_providers {
    azuread = {
      source = "registry.localhost.com/local/azuread"
      version = ">= 2.0.0"
    }
  }
}

resource "azuread_application" "app_registration" {
  display_name = "test-app-registration"
  identifier_uris = ["https://website.company.com/"]
  sign_in_audience = "AzureADMyOrg"

  web {
    homepage_url = "https://website.company.com"
    redirect_uris = [
      "http://localhost/auth/redirect",
      "https://website.company.com/auth/redirect"
    ]

    implicit_grant {
      access_token_issuance_enabled = false
    }
  }
}
```

### Debug Output

https://gist.github.com/conzyor34/bba0541e90f1fce4fc657668f10478fc

### Expected Behavior

`No changes. Your infrastructure matches the configuration.`

### Actual Behavior

```
Error: missing expected [

  with azuread_application.app_registration,
  on main.tf line 10, in resource "azuread_application" "app_registration":
  10: resource "azuread_application" "app_registration" {
```

### Steps to Reproduce

1. `terraform init` with v1.6.0 provider
2. `terraform apply`
3. Update `required_providers` block to refer to local compiled v2.0 provider
4. `terraform init -upgrade`
5. `terraform apply`

**Comment by conzyor34** [comment]
This appears to be an issue with the v2.0 provider reading state created by the v1.6.0 provider. I have included the state file in the gist linked in the "Debug Output" section of the issue report above.

**Comment by manicminer** [comment]
Hi @conzyor34, thanks for trying out the latest build and reporting this. I'll take a proper look at this tomorrow and try to reproduce 👍

**Comment by conzyor34** [comment]
I don't totally understand what's going on, but it's getting hung up on the following in the v1.6.0 state file:

```
group_membership_claims: ""
```

It's supposed to be a Set in the v2.0 provider, but was allowed to be a String in the v1.6.0 provider. Is a state updater required?

**Comment by manicminer** [comment]
@conzyor34 That's great thanks, you're correct it looks like we're missing a state migration for this field as the attribute type will be changing in v2

**Comment by conzyor34** [comment]
I found another one of these; The `public_client` attribute changes from List in v1.6.0 to Set in v2.0.0. It results in the same `Error: missing expected [`. Would you prefer I open separate issues?
