### ISSUE TITLE
Error when import exisiting azuread_service_principal

### ISSUE THREAD

**Issue by AmudaPalani** [hashicorp/terraform-provider-azuread#486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azuread_service_principal

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior

Error: Cannot import non-existent remote object

While attempting to import an existing object to
azuread_service_principal.consumer_sp, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Steps to Reproduce

1. `terraform import azuread_service_principal.test <object_id>`

### References

* #0000

**Comment by manicminer** [comment]
Hi @AmudaPalani, thanks for reporting this issue. Can you confirm that you are specifying the correct UUID for the service principal object ID? i.e. Portal > Azure Active Directory > Enterprise Applications > yourServicePrincipal > Object ID

**Comment by AmudaPalani** [comment]
Yes, confirmed the object ID of my service principal.
