### ISSUE TITLE
azuread_application needs schema migration for public_client attribute: Bool in v1.6.0 to List in v2.0.0

### ISSUE THREAD

**Issue by conzyor34** [hashicorp/terraform-provider-azuread#494]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When upgrading provider version to v2.0.0, state created by v.1.6.0 fails to be read properly because the `public_client` attribute has changed types.

### Terraform (and AzureAD Provider) Version

```
$ terraform -v
Terraform v1.0.0
on linux_amd64
+ provider registry.localhost.com/local/azuread v2.0.0
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
```

The v2.0 `azuread` provider was compiled from `main`.

### Affected Resource(s)

* `azuread_application`

#### Before

```hcl
terraform {
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = ">= 1.6.0"
    }     
  }
}

resource "azuread_application" "app_registration" {
  display_name = "test-app-registration"
  identifier_uris = ["https://website.company.com/"]
  sign_in_audience = "AzureADMyOrg"

  web {
    homepage_url = "https://website.company.com"
    redirect_uris = [
      "http://localhost/auth/redirect",
      "https://website.company.com/auth/redirect"
    ]

    implicit_grant {
      access_token_issuance_enabled = false
    }
  }
}
```

#### After Upgrade to v2.0

```hcl
terraform {
  required_providers {
    azuread = {
      source = "registry.localhost.com/local/azuread"
      version = ">= 2.0.0"
    }
  }
}

resource "azuread_application" "app_registration" {
  display_name = "test-app-registration"
  identifier_uris = ["https://website.company.com/"]
  sign_in_audience = "AzureADMyOrg"

  web {
    homepage_url = "https://website.company.com"
    redirect_uris = [
      "http://localhost/auth/redirect",
      "https://website.company.com/auth/redirect"
    ]

    implicit_grant {
      access_token_issuance_enabled = false
    }
  }
}
```

### Expected Behavior

Not an error.

### Actual Behavior

```
Error: missing expected [

  with azuread_application.app_registration,
  on main.tf line 10, in resource "azuread_application" "app_registration":
  10: resource "azuread_application" "app_registration" {
```

### Steps to Reproduce

1. `terraform init` with v1.6.0 provider
2. `terraform apply`
3. Update `required_providers` block to refer to local compiled v2.0 provider
4. `terraform init -upgrade`
5. `terraform apply`

**Comment by manicminer** [comment]
@conzyor34 Thanks for reporting and thanks for the PR  🎸
