### ISSUE TITLE
New resource azuread_application_platform

### ISSUE THREAD

**Issue by channaj** [hashicorp/terraform-provider-azuread#501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, platform configuration is implemented as part of the `azuread_application` resource. There seems to be scenarios - I have come across at least one - where this is not ideal. When configuring a `nativeClient` platform, in some (probably most) cases we need to know the application (client) id of the Azure AD Application in order to be able to configure redirect uris (please see `ms-appx-web:` uri below)

If we have `azuread_application_platform` as an independent resource (as mentioned in the potential configuration) we'll be able to solve the above problem. This would also be better aligned with the concept of "Platform configurations" of Azure AD Application.

### New or Affected Resource(s)

* azuread_application
* azuread_application_platform

### Potential Terraform Configuration

```hcl
resource "azuread_application" "example" {
...
}

resource "azuread_application_platform" "web" {
  application_object_id = azuread_application.example.object_id
  type = "web"
  
  homepage_url  = "https://app.example.net"
  logout_url    = "https://app.example.net/logout"
  redirect_uris = ["https://app.example.net/account"]

  implicit_grant {
    ...
  }
}

resource "azuread_application_platform" "public_cient" {
  application_object_id = azuread_application.example.object_id
  type = "publicClient"
  
  redirect_uris = [
      "https://login.microsoftonline.com/common/oauth2/nativeclient"
      "ms-appx-web://microsoft.aad.brokerplugin/${azuread_application.example.application_id}"
  ]
}
```

### References

* https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-windows-desktop#step-1-register-your-application
* https://docs.microsoft.com/en-us/graph/api/resources/publicclientapplication?view=graph-rest-1.0
* https://docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-1.0

**Comment by manicminer** [comment]
Thanks for the suggestion @channaj. Needing to know the application ID is something that has come up in a couple of different contexts and we'll look to solve this.

**Comment by mausv** [comment]
Any update on this?
