### ISSUE TITLE
Authorization_RequestDenied during service principal creation

### ISSUE THREAD

**Issue by flisak-robert** [hashicorp/terraform-provider-azuread#504]
Hi,
I am having trouble with creating a service principal using the azuread terraform provider (hashicorp/azuread v1.6.0). Here is the code:
```
provider "azuread" {
}

resource "azuread_application" "app" {
    display_name = "app"
    identifier_uris  = ["api://localhost"]
}

resource "azuread_service_principal" "sp" {
    application_id = azuread_application.app.id
}
```
Application is created just fine, but when I try to create the service principal, I get the error: `Could not create service principal`

```
graphrbac.ServicePrincipalsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown"
│ Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-07-27T10:06:32","message":{"lang":"en","value":"When using this permission,
│ the backing application of the service principal being created must in the local tenant"}
```

I have the correct permissions, I am not using a service principal along with terraform. Service principal creation works via az cli:
`az ad sp create-for-rbac --name app` everything works fine here.

What could be the issue?

**Comment by manicminer** [comment]
Hi @flisak-robert, you will need to use the `application_id` attribute of your application resource and not the `id` attribute.

**Comment by manicminer** [comment]
@flisak-robert As this is more of a usage question, I'm going to close this issue for now. 

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). If you believe you have found a bug in the provider, or if you have a feature request that isn't already covered by an existing issue, please feel free to open another issue using one of our issue templates. Thanks!
