### ISSUE TITLE
azuread_application_oauth2_permission_scope optional properties are required

### ISSUE THREAD

**Issue by Dan-Bai** [hashicorp/terraform-provider-azuread#506]
*user_consent_display_name* and *user_consent_description* are optional in documentation but required during deployment.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v0.15.0
azuread v1.6.0

### Affected Resource(s)

* azuread_application_oauth2_permission_scope

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Should have created resource without error

### Actual Behavior

Error on missing properties

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @Dan-Bai, thanks for reporting this documentation issue!

I believe this will be resolved in the upcoming 2.0m release of the provider. This discrepancy seems to have stemmed from the API migration from AAD Graph to Microsoft Graph, where the two APIs have different validation. I have tested with the latest build (*caveat noted below) and both properties appear to be actually optional with the new API.

* Caveat: I tested using the `azuread_application` resource, which operates in much the same way in terms of applying permission scopes. In the next release, the `azuread_application_oauth2_permission_scope` resource will no longer be available and scopes must be configured from within the `azuread_application` resource. I recommend consulting our [Upgrade Guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph) for more details before upgrading to the next (major) release.

As this appears to be resolved in the latest version, which is scheduled for release in the next few days. I'm going to close this issue. Thanks again for reporting this, it was helpful for us to double check this.
