### ISSUE TITLE
azuread_service_principal_certificate doesn't upload a certificate to service principal

### ISSUE THREAD

**Issue by mrshiva** [hashicorp/terraform-provider-azuread#510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.2 on linux_amd64

### Affected Resource(s)

+ provider registry.terraform.io/hashicorp/azuread v1.6.0

### Terraform Configuration Files

```hcl
resource "azuread_application" "this" {
  display_name               = "Batch Key Vault Access"
  homepage                   = "https://batch.mydomain.com"
  identifier_uris            = ["https://batch.mydomain.com"]
  reply_urls                 = ["https://batch.mydomain.com"]
  available_to_other_tenants = false
}

resource "azuread_service_principal" "this" {
  application_id               = azuread_application.this.application_id
  app_role_assignment_required = false
}

resource "azuread_service_principal_certificate" "this" {
  service_principal_id = azuread_service_principal.this.id
  type                 = "AsymmetricX509Cert"
  value                = filebase64("${path.module}/my_pub.pem")
  end_date             = "2022-09-23T05:00:00Z"
}
```

### Panic Output
no crash logs

### Expected Behavior

to see the service principal certificate on Portal inside - App registration -> APP NAME ->Certificates & secrets

### Actual Behavior

There is no certificate added for Application on the Portal, but 'terraform apply' completed.
I can see certificate, If I check with az cli command: az ad sp show

### Steps to Reproduce

1. `terraform apply`

module.batch_certificate.azuread_service_principal_certificate.this: Creating...
module.batch_certificate.azuread_service_principal_certificate.this: Still creating... [10s elapsed]
module.batch_certificate.azuread_service_principal_certificate.this: Creation complete after 12s

### References

* #0000

**Comment by manicminer** [comment]
Hi @mrshiva, thanks for reporting!

I believe you may want to use the `azuread_application_certificate` resource as that corresponds to the Portal UI you describe (Azure AD > App Registrations > Certificates and Secrets). If you are creating a single tenant application, you should be able to use application certificates (as opposed to service principal certificates) seamlessly - however if you are creating a multi-tenant application there are other considerations. [This docs article](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) is a useful reference when working out which object type to use in different contexts. There is actually no portal UI for service principal certificates, which can add to the confusion between app registrations and service principals as the lines between them are often blurred.

As this is more of a usage question, I'm going to close this one for now. However if I have misunderstood your report, or if this doesn't resolve your issue, please feel free to comment further and we can look into it further. Thanks!
