### ISSUE TITLE
Feature Request: datasource all_users_datasource.go 

### ISSUE THREAD

**Issue by Threpio** [hashicorp/terraform-provider-azuread#512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For work I am currently treating our AAD setup as the single source of truth for the user base/permissions and group ownership. I would like to be able to fetch all of the users in the AAD to utilise the permissions already defined when I create other non AAD setup users (for example: Pagerduty). 

I would like for there to be a datasource list of users that can be iterated through to include their basic information such as userPrincipleName, email, phoneNumber and groups they are a part of.

This functionality of listing is available through the CLI and API. I would be able to use local_exec to obtain this information but this is not best practices and I would much prefer to allow terraform to handle this information for me. 

### New or Affected Resource(s)

To be created:
```
internal/services/users/all_users_datasource.go
internal/services/users/all_users_datasource_test.go
```

### Potential Terraform Configuration

```hcl
data "azuread_all_users" "users" {}
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @Threpio, thanks for requesting this!

Have you considered using the `azuread_groups` data source? It has a `members` attribute, so you could use a high level group containing all the users you wish to manage and discover their object IDs that way?

**Comment by Threpio** [comment]
@manicminer - I have created a working branch on my fork and confirmed it works for my needs.

Thanks for your speedy comment though. I want to have a catch all as-well and want to move away from a global group in our AAD setup in the future. 

I just need to write some tests and I will create the PR.

Am I to create the documentation for this data source aswell? I know some other providers have automated documentation and don't want to duplicate my effort. (Happy to do it otherwise)

**Comment by Threpio** [comment]
@manicminer - We did consider developing it as an extension as the azuread_users datasource but figured that the majority of the times that we use that datasource we DO NOT want a result that is not queried to be returned. So for us it means that if we mis-configure the datasource then it can look to be correct even when not filtered. (Happy to be overrule in this for the greater project)

 - It could be deigned as a `all_users` flag against the `azuread_users` datasource but I can't see how the `only-one-of` functionality for those inputs would work additionally with a boolean flag?
