### ISSUE TITLE
Can't import Service Principal Password

### ISSUE THREAD

**Issue by seboss666** [hashicorp/terraform-provider-azuread#514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```shell
$ terraform version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azuread_service_principal_password`

### Terraform Configuration Files

```hcl
resource "random_string" "password_velero" {
  length = 32
  # Do not use special chars which can make Velero fail cloud-credentials secret
  # special = false
}

resource "azuread_application" "velero" {
  display_name               = format("velero-ad-app-%s", var.environment)
  available_to_other_tenants = true
}

resource "azuread_service_principal" "velero" {
  application_id = azuread_application.velero.application_id
}

resource "azuread_service_principal_password" "velero" {
  service_principal_id = azuread_service_principal.velero.id
  value                = random_string.password_velero.result
  end_date             = "2050-01-01T01:02:03Z"

  # wait 30s for server replication before attempting role assignment creation
  provisioner "local-exec" {
    command = "sleep 30"
  }
}
```

### Debug Output

```shell
$ terraform import azuread_service_principal_password.velero 00000000-1111-2222-3333-444444444444/password/5555-6666-7777-8888-999999999999
azuread_service_principal_password.velero: Importing from ID "00000000-1111-2222-3333-444444444444/password/5555-6666-7777-8888-999999999999"...
╷
│ Error: resource azuread_service_principal_password doesn't support import
│ 
│ 
╵
```

### Expected Behavior

Documentation says we can import an existing service principal password with an updated path. I have the path in a previous tfstate from a code I'm not reusing (unmaintained for almost two years, too much work to put into).

### Actual Behavior

The message you see above, where it says that password can't be imported. If this is indeed not importable anymore, documentation should already warns about it.

### Steps to Reproduce

1. `terraform apply`

### References

Provider documentation : https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password#import

**Comment by manicminer** [comment]
Hi @seboss666, thanks for reporting this documentation bug. You are correct, the docs should reflect that this resource no longer supports importing (along with the `azuread_application_password` resource. Unfortunately this didn't make it into the last release but we have ensured the docs are correct in this regards for v2.0, which is planned for release very soon.

Unfortunately due to a limitation with the Terraform Registry, we cannot update the docs outside of a provider release, so this will only reflect on the website once v2.0 is out. In the meantime, you can access the most up to date docs in this repo, e.g. https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/resources/service_principal_password.md
