### ISSUE TITLE
After changing (adding/removing) owners from JSON file and running pipeline. Terraform is not updating AD Group

### ISSUE THREAD

**Issue by bkCloudGuy** [hashicorp/terraform-provider-azuread#517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

1.6.0

### Affected Resource(s)

* `azuread_group`
* `azuread_groups`
* `azuread_users`

### Terraform Configuration Files

```
# Query members IDs defined as owners in JSON file
data "azuread_users" "members_owners" {
  user_principal_names = var.appzone_config.rbac.owners
}
# Query members groups IDs defined as groups owners in JSON file
data "azuread_groups" "groups_owners" {
  display_names = var.appzone_config.rbac.owners_groups
}
# Query members of each members groups defined as groups owners in JSON file
data "azuread_group" "group_owners" {
  for_each = toset(var.appzone_config.rbac.owners_groups)
  display_name = each.value
}
## Flattening the members from the different groups
locals {
  members = distinct(flatten([
    for s in data.azuread_group.group_owners : [
      for m in s.members : {
        item = m
      }
    ]
  ]))
}
# Create Azure AD Group - App Zone LTD Owner
resource "azuread_group" "ad_group_appzone" {
  display_name            = format("%s_%s_%s_LtdOwner", var.provisioner_settings.rbac.ad_group_prefix, var.subscription_data.appzone_config.name, var.appzone_config.name)
  description             = lookup(var.provisioner_settings.rbac, "group_description", "Managed by XXX. Only group membership can be managed manually.")
  owners                  = concat(data.azuread_users.members_owners.object_ids, var.acf_owners_id, local.members[*].item)
  members                 = concat(data.azuread_users.members_owners.object_ids, data.azuread_groups.groups_owners.object_ids)
  prevent_duplicate_names = true
  depends_on = [
    data.azuread_users.members_owners
  ]
}
```
JSON File looks like below

```
{
    "version": "1.0.0",
    "appzone": {
        "type": "rg",
        "location": "westeurope",
        "subscription_id": "1243245435-123123-323-333-323123",
        "subscription_name": "contoso-shared-dev-eu-subs",
        "management_lock": false,
        "prevent_destroy": true
    },
    "rbac": {
        "owners": [
            "testuser1@contoso.eu",
            "testuser2@contoso.eu",
            "testuser3@contoso.eu"
        ],
        "owners_groups": [
            "Contoso_SysOps"
        ],
        "group_assignments": {
            "Reader": "3333-3385-48ef-bd42-f606fba81ae7"
        }
    }
}
```

### Expected Behavior

Update Azure AD group (add or remove) with new owners

### Actual Behavior

First time when i run pipeline with code it does everything correct so creates azure ad group with members and owners as it should. However when for example i want then remove a user from members and I do it in JSON file and rerun pipeline, that change is not reflected in AD group and pipeline ends successfully saying that no changes is needed.

### Steps to Reproduce

1. `terraform apply`

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

**Comment by manicminer** [comment]
Hi @bkCloudGuy, thanks for reporting this. I believe we have resolved this bug in the upcoming version 2.0 of the provider.
