### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by deep-cognite** [hashicorp/terraform-provider-azuread#526]
I am waiting to use the `single_page_application` block which was added in this PR https://github.com/hashicorp/terraform-provider-azuread/pull/474 about a month ago. However, I cannot see any releases done with these changes anywhere. 

So when will the release come to reflect those changes? :)

**Comment by alexwilcox9** [comment]
That PR is under the v2.0.0 milestone which you can see here:
https://github.com/hashicorp/terraform-provider-azuread/milestone/16

As you'll see there it has a due date of 26th August. This is no guarantee though, treat it more like a "no earlier than" date

Hope that helps!

**Comment by deep-cognite** [comment]
Thank you for the prompt reply, @alexwilcox9! :)
