### ISSUE TITLE
azuread_client_config data source not returning tenant ID

### ISSUE THREAD

**Issue by ned1313** [hashicorp/terraform-provider-azuread#530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.0.1

### Affected Resource(s)

* `azuread_client_config`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
      azuread = {
      source = "hashicorp/azuread"
      version = "~> 2.0"
    }
  }
}

data "azuread_client_config" "current" {}

output "current" {
  value = data.azuread_client_config.current
}
```

### Expected Behavior

The `azuread_client_config` data source should return the client_id, id, object_id, and tenant_id.

### Actual Behavior

The output from the data source is as follows (IDs redacted with Xs):

```
current = {
  "client_id" = ""
  "id" = "--XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  "object_id" = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  "tenant_id" = ""
  "timeouts" = null /* object */
}
```

The tenant_id field is blank.

### Steps to Reproduce

1. `az login` # use CLI auth
2. `terraform apply -auto-approve`

### Important Factoids

Using standard public Azure environment.

### References

* #0000

**Comment by manicminer** [comment]
Hi @ned1313, thanks for reporting this. I've determined the root cause of this bug, which is due to in-process cashing that we recently introduced to speed up Azure CLI authentication but has inadvertently introduced this bug (which also affects the client ID). We should have a fix out soon.
