### ISSUE TITLE
 Error: URI has no host when upgrading to v2.0 of azuread provider

### ISSUE THREAD

**Issue by enorlando** [hashicorp/terraform-provider-azuread#532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

+ Terraform v0.15.5
+ provider registry.terraform.io/hashicorp/azuread v2.0.1

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "xxx" {
  display_name     = "xxx"
  sign_in_audience = "AzureADMyOrg"
  identifier_uris = [
    "xxx.com/a/xxx.com",
    "http://xxx1234",
    "http://xxx123",
    "http://xxx",
  ]

  web {
    homepage_url = "https://xxx"
    redirect_uris = [
      "https://xxx/",
      "https://xxx/*/",
    ]

    implicit_grant {
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = true
    }
  }

  api {

    oauth2_permission_scope {
      admin_consent_description  = "Allow the application to access xxx on behalf of the signed-in user."
      admin_consent_display_name = "Access xxx"
      enabled                    = true
      id                         = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      type                       = "User"
      user_consent_description   = "Allow the application to access xxx on your behalf."
      user_consent_display_name  = "Access xxx"
      value                      = "user_impersonation"
    }
  }


  app_role {
    allowed_member_types = ["User", ]
    description          = "Default Organization"
    display_name         = "Default Organization"
    enabled              = true
    id                   = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  }

  app_role {
    allowed_member_types = ["User", ]
    description          = "msiam_access"
    display_name         = "msiam_access"
    enabled              = true
    id                   = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  }
}
```

### Debug Output
Terraform output is:

```
│ Error: URI has no host
│ 
│   with azuread_application.xxx,
│   on apps.tf line 1252, in resource "azuread_application" "xxx":
│ 1252:   identifier_uris = [
│ 1253:     "xxx.com/a/xxx.com",
│ 1254:     "http://xxx1234",
│ 1255:     "http://xxx123",
│ 1256:     "http://xxx",
│ 1257:   ]
```

### Expected Behavior

The set of user-defined URIs (Entity ID/s) should be added to the application within the AAD tenant

### Actual Behavior

Error: URI has no host is thrown 

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by manicminer** [comment]
Hi @enorlando, thanks for reporting this. Whilst this may have worked in previous version of the provider using the legacy API, unfortunately the newer API does not support redurect URIs without a scheme. The URI `xxx.com/a/xxx.com` in your config will need to be expanded to `https://xxx.com/a/xxx.com` in order for the API to accept it as a valid redirect URI.

**Comment by manicminer** [comment]
Hi @enorlando, thanks for reporting this. This validation was introduced in version 1.2 of the provider as identifier URIs are supposed to be valid URIs with a limited set of supported schemes:

![Screenshot 2021-08-31 at 13 05 44](https://user-images.githubusercontent.com/251987/131499790-50bb4ff0-0574-49c4-ab8e-ef759cc2045d.png)

Whilst the API does not enforce this, the portal does. In some use cases, setting an invalid identifier URI (e.g. without a scheme) will work, but it's also known to break other configurations (e.g. for multitenant apps, the scheme is mandatory). We are following Azure documentation on this and accordingly it's unlikely that we'll remove this validation, since it can cause other issues with app configuration.

**Comment by enorlando** [comment]
Hi @manicminer, thanks for your reply. The issue is not with changing the Application ID URI but the Identifier (Identity ID) within the Basic SAML configuration:
![image](https://user-images.githubusercontent.com/42361577/131581801-d4bd1191-9122-4498-ada5-121f0e7e3415.png)

It allows you to set unique user-defined URIs (Entity ID/s) to the application within your AAD tenant. This was not an issue with previous versions of the provider as `identifier_uris` was not a requirement for creating SSO based apps

**Comment by manicminer** [comment]
Thanks @enorlando, I suspected you might be trying to effect the SAML entity ID. Whilst Azure AD does copy these values between the app registration and service principal, they are separately configurable values and so we unfortunately can't support this scenario via the `identifier_uris` property.

We'd like to be able to separately support configuring a service principal for SAML, but unfortunately there is no API support right now.

**Comment by enorlando** [comment]
Thanks @manicminer. When running terraform plan it errors with 
```
│ Error: URI has no host
│ 
│   with azuread_application.xxx,
│   on apps.tf line 1252, in resource "azuread_application" "xxx":
│ 1252:   identifier_uris = [
│ 1253:     "xxx.com/a/xxx.com",
│ 1254:     "http://xxx1234",
│ 1255:     "http://xxx123",
│ 1256:     "http://xxx",
│ 1257:   ]
```
The URI that it complains about is **"xxx.com/a/xxx.com"**. 

If I remove this item from the list of URIs in the ` identifier_uris `block, 

``` 
 identifier_uris = [
    "http://xxx1234",
    "http://xxx123",
    "http://xxx",
  ]
```

it wants to delete it from the list so i assume you can remove this type of validation and allow URIs in the ` identifier_uris ` block without the need to have prefixed http, https etc?


```
  # azuread_application.xxx will be updated in-place
  ~ resource "azuread_application" "xxx" {
        id                             = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
      ~ identifier_uris                = [
          - "xxx.com/a/xxx.com",
            # (3 unchanged elements hidden)
        ]
        # (15 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by manicminer** [comment]
As mentioned, the validation was introduced in v1.2 per Azure documentation/guidelines and I don't think we'll be removing it. `xxx.com/a/xxx.com` is not a valid URI per the documentation.
