### ISSUE TITLE
Error: Expected URI to have a scheme of: http, https when upgrading to v2.0 of azuread provider

### ISSUE THREAD

**Issue by enorlando** [hashicorp/terraform-provider-azuread#533]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.15.5
provider registry.terraform.io/hashicorp/azuread v2.0.1

### Affected Resource(s)

* `azuread_application `

### Terraform Configuration Files

```hcl
resource "azuread_application" "xxx" {
  display_name                   = "xxx"
  sign_in_audience               = "AzureADMyOrg"
  fallback_public_client_enabled = true

  web {
    redirect_uris = [
      "ms-appx-web://Microsoft.AAD.BrokerPlugin/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    ]

    implicit_grant {
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = true
    }
  }

  required_resource_access {
    resource_app_id = var.xxx["xxx"]

    resource_access {
      id   = var.xxx["xxx"]
      type = "Scope"
    }
  }

  required_resource_access {
    resource_app_id = var.xxx["xxx"]

    resource_access {
      id   = var.xxx["user_impersonation"]
      type = "Scope"
    }
  }

}
```

### Debug Output
Terraform output is:
```
│ Error: Expected URI to have a scheme of: http, https
│ 
│   with azuread_application.xxx,
│   on apps.tf line 6103, in resource "azuread_application" "xxx":
│ 6103:     redirect_uris = [
│ 6104:        "ms-appx-web://Microsoft.AAD.BrokerPlugin/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
│ 6105:     ]
```

### Expected Behavior

The set of user-defined redirect URIs should be added to the application within the AAD tenant

### Actual Behavior

 Error: Expected URI to have a scheme of: http, https is thrown

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by manicminer** [comment]
Hi @enorlando, thanks for reporting this validation issue. I believe #540 should fix this. As an aside, I believe the URI in your config may need to be in the `public_client` block as opposed to the `web` block ([source](https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-dotnet-native-uwp-wam/active-directory-dotnet-native-uwp-wam/))? Regardless, the validation issue affects both properties and should be addressed in the linked PR.

**Comment by r-gunasekaran** [comment]
It doesn't work with Mobile App registrations too, as that uses different URI format for different platform (iOS/Android) as explained in this [microsoft document](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-app-registration#interactive-authentication).
