### ISSUE TITLE
Still Broken: Could not remove initial owner from service principal with object ID:

### ISSUE THREAD

**Issue by jtravell** [hashicorp/terraform-provider-azuread#546]
The following error is being thrown when we use the azuread provider just now today, despite [a fix reportedly having been merged into the production release several hours ago](https://github.com/hashicorp/terraform-provider-azuread/blob/v2.1.0/CHANGELOG.md).  

    Could not remove initial owner from service principal with object ID:

 The full error message is:  

    2021-09-02T14:17:52.745-0700 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
    ╷
    │ Error: Could not remove initial owner from service principal with object ID: "service-principal-object-id"
    │
    │   with module.ad-admin.azuread_service_principal.appRegistrationSP,
    │   on ..\..\..\..\modules\ad-admin\active-directory.tf line 82, in resource "azuread_service_principal" "appRegistrationSP":
    │   82: resource "azuread_service_principal" "appRegistrationSP" {
    │
    │ ServicePrincipalsClient.BaseClient.Get(): Get
    │ "https://graph.microsoft.com/beta/tenant-id/servicePrincipals/service-principal-object-id/owners/guid-alpha-numeric-string/$ref?%24select=id%2Curl":
    │ GET
    │ https://graph.microsoft.com/beta/tenant-id/servicePrincipals/service-principal-object-id/owners/guid-alpha-numeric-string/$ref?%24select=id%2Curl
    │ giving up after 9 attempt(s)
    ╵
    2021-09-02T14:17:52.777-0700 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
    2021-09-02T14:17:52.777-0700 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
    2021-09-02T14:17:52.779-0700 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
    2021-09-02T14:17:52.804-0700 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azuread/2.0.1/windows_amd64/terraform-provider-azuread_v2.0.1_x5.exe pid=24548
    2021-09-02T14:17:52.804-0700 [DEBUG] provider: plugin exited  

The command that triggers the error is:  

    terraform apply -auto-approve -parallelism=1  -var="instanceName=tfBackend-myOrg" -var-file="C:\path\to\keys.tfvars"  

The contents of `keys.tfvars` mentioned in the preceding command are:  
    
    tenantId="value-redacted"
    clientId="value-redacted"
    clientSecret="value-redacted"
    
The code that the above command runs includes a call to a module and a module.  

The call to the module is:  

    module "module-name" {
      source = "..\\..\\..\\..\\modules\\module-name"
      tenantId             = var.tenantId
      clientId             = var.clientId
      clientSecret         = var.clientSecret
      instanceName         = var.instanceName
    }

    ##Input variables.  The client referred to is an App Registration.
    variable "tenantId" { }
    variable "clientId" { }
    variable "clientSecret" { }
    variable "instanceName" { }

    output "application_id" { value = module.module-name.application_id }
    output "appId" { value = module.module-name.appId }

The module code called by the above is:  

    variable "tenantId" { }
    variable "clientId" { }
    variable "clientSecret" { }
    variable "instanceName" { }

    output "application_id" { value = azuread_application.appRegistration.application_id }
    output "appId" { value = azuread_service_principal.appRegistrationSP.application_id }

    ######################################################################
    ### Providers 
    ######################################################################

    #Configure terraform
    terraform {
      required_providers {
        azuread = {
          source  = "hashicorp/azuread"
          version = "2.0.1"
        }
      }
    }
  
    # Configure the Microsoft Azure Active Directory Provider
    provider "azuread" {
      tenant_id       = var.tenantId
      client_id       = var.clientId
      client_secret   = var.clientSecret
    }

    ######################################################################
    ### Identity Resources
    ######################################################################

    # Create an application
    resource "azuread_application" "appRegistration" {
      display_name = var.instanceName
      app_role {
        allowed_member_types  = ["User", "Application"]
        description           = "Admins can manage roles and perform all task actions"
        display_name          = "Admin"
        value                 = "administer"
        id                    = "1b19509b-32b1-4e9f-b71d-4992aa991967"
      }
    }

    data "azuread_client_config" "test" {}

    # Create a service principal
    resource "azuread_service_principal" "appRegistrationSP" {
      application_id = azuread_application.appRegistration.application_id
    }

    resource "azuread_service_principal_password" "appRegistrationSP_pwd" {
      service_principal_id = azuread_service_principal.appRegistrationSP.id
    }

Running `terraform -version` results in:  

    Terraform v1.0.5
    on windows_amd64
    + provider registry.terraform.io/hashicorp/azuread v2.0.1

The roles assigned to the `clientId` used to run the terraform command above include:

    Subscription: Owner
    Active Directory: Global Administrator

Note:  This is the same bug as [#529](https://github.com/hashicorp/terraform-provider-azuread/issues/529) but we were instructed twice in that thread to open a new bug report if we discover any further errors with this matter.

It seems that the fix was not actually integrated into the release.  

When can this matter be resolved?

**Comment by manicminer** [comment]
@jtravell it looks like you haven't upgraded the provider?

![Screenshot 2021-09-03 at 09 45 21](https://user-images.githubusercontent.com/251987/131977519-493ba669-2d82-47c5-8c5c-25d691139dd2.png)

**Comment by jtravell** [comment]
@manicminer   Why would you say that?  

We very clearly have the following:  

    terraform {
      required_providers {
        azuread = {
          source  = "hashicorp/azuread"
          version = "2.0.1"
        }
      }
    }  

We are NOT using any `terraform.rc`, so that the provider should be what automatically gets downloaded from the official `hashicorp/azuread` whenever `terraform init` gets run on a remote machine that does not have a local registry.  

We just ran this again right now, and got the same failure as above in the OP.

**Comment by manicminer** [comment]
@jtravell The latest version is 2.1.0 not 2.0.1
