### ISSUE TITLE
Feature Request: Group and User App Role Assignment

### ISSUE THREAD

**Issue by Tailzip** [hashicorp/terraform-provider-azuread#549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Assign user or group an app role to a Entreprise Application (Service Principal).

### New or Affected Resource(s)

* azuread_group
* azuread_user

### Potential Terraform Configuration

```hcl
resource "azuread_group" "example" {
  display_name     = "example"
  owners           = [<owner_object_id>]
  security_enabled = true

  app_role {
    role_id     = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    resource_id = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
  }
}
```

```hcl
resource "azuread_user" "example" {
  user_principal_name = "jdoe@hashicorp.com"
  display_name        = "J. Doe"
  mail_nickname       = "jdoe"
  password            = "SecretP@sswd99!"

  app_role {
    role_id     = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    resource_id = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
  }
}
```

### References

* [Restrict your Azure AD app to a set of users in an Azure AD tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users)
* [Assign users and groups to an enterprise application](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/assign-user-or-group-access-portal)
* [Quickstart: Assign users to an application](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-assign-users)
* [Grant an appRoleAssignment for a service principal](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=http)

**Comment by manicminer** [comment]
Hi @Tailzip, thanks for requesting this! Is this the same as https://github.com/hashicorp/terraform-provider-azuread/issues/164?

**Comment by Tailzip** [comment]
Oh yes it is, totally missed it 😅
