### ISSUE TITLE
azuread v2.x auth error

### ISSUE THREAD

**Issue by peeeeecho** [hashicorp/terraform-provider-azuread#558]
I want to refer to azuread_user in data source using azuread 2.0 (microsoft graph).
However, as soon as I use azuread2.x, authentication (Azure CLI) doesn't work.
It did not occur before azuread 1.6 (not mictosoft graph).

【Error】
│ Error: building client: unable to parse claims in access token: illegal base64 data at input byte 631
│
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 22, in provider "azuread":
│   22: provider "azuread" {

【Code】
``` terraform {
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.75.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.1.0"
    }
  }
}

＃## Configure the Microsoft Azure Provider
provider "azurerm" {
  subscription_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  features {}
}

provider "azuread" {
    use_msi   = false
    use_cli   = true
    tenant_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}

data "azuread_domains" "example" {
  only_initial = true
}

data "azurerm_client_config" "my_conf" {}

data "azuread_user" "admins_operation" {
  object_id           = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

**Comment by manicminer** [comment]
Hi @peeeeecho, thanks for reporting this bug. I believe I know where this error stems from, however I'll need some more information in order to try and reproduce this. What is your Azure CLI version? i.e. the output from `az version`

**Comment by peeeeecho** [comment]
Hi @manicminer 

Thank you for your response.
The version is 2.27.0.
#Actually, I use Azure cloud shell.

```
az version
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",    
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",      
    "ssh": "0.1.5",
    "virtual-wan": "0.2.6"       
  }
}

**Comment by peeeeecho** [comment]
I ran the following command before running terraform.
As a result, I was able to confirm that it works well.

#I don't know if there is a causal relationship

```
az rest --method get --url https://graph.microsoft.com/v1.0/users/xxx@xxx.com

**Comment by peeeeecho** [comment]
I tried rebooting Cloud Shell and trying again.
Then it failed with the following error...

I am confused...😣
I suspect that the "Cloud Shell" is the cause.

```
│ Error: building client: unable to obtain access token: running Azure CLI: exit status 1: ERROR: Tenant shouldn't be specified for Cloud Shell account
│
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 22, in provider "azuread":
│   22: provider "azuread" {

**Comment by peeeeecho** [comment]
I tried it on a Local PC (Windows) and it worked fine.

The version of az cli installed on your Local PC.

```
{
   "azure-cli": "2.28.0",
   "azure-cli-core": "2.28.0",
   "azure-cli-telemetry": "1.0.6",
   "extensions": {}
}

**Comment by manicminer** [comment]
@peeeeecho Thanks, unfortunately we don't have a way to automatically test providers in Cloud Shell, so these compatibility issues come up from time to time as changes are made to Cloud Shell. Please note however, we don't recommend running TF in that environment as it is prone to memory issues - and running out of memory in the middle of an apply is nontrivial to recover from.

That said, I'm not sure why you got the original decoding error, but I suspect a malformed access token produced by az-cli in your cloud shell. The second error is what I'm able to reproduce and I believe I know why it's occurring. Fixing it reliably may prove difficult as we'd need to detect when Cloud Shell is the host environment. There are probably various signatures if one pokes around, but environment variables seems like a sensible way to go. Can you confirm if the `AZUREPS_HOST_ENVIRONMENT` is set in your cloud shell?

**Comment by peeeeecho** [comment]
@manicminer 

Thanks, 
The AZUREPS_HOST_ENVIRONMENT set in the cloud shell is:
"AZUREPS_HOST_ENVIRONMENT=cloud-shell/1.0"


We also confirmed that the following error pattern is output when executing TF in Cloud shell.
```
│ Error: building client: unable to obtain access token: running Azure CLI: exit status 1: ERROR: Tenant shouldn't be specified for Cloud Shell account
│
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on main.tf line 22, in provider "azuread":
│   22: provider "azuread" {
│
╵

**Comment by moriyoshi** [comment]
It suddenly stops working for me too and the problem is very annoying:

The output of `az version` is:
```
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

I don't run terraform on Cloud Shell.

**Comment by moriyoshi** [comment]
I modified the source code in the following way and parsed the token with PyJWT to successfully get the valid claim.  I suspect this is a bug in github.com/manicminer/hamilton/auth.
```
diff --git a/internal/clients/client.go b/internal/clients/client.go
index dc7c1b41..11820561 100644
--- a/internal/clients/client.go
+++ b/internal/clients/client.go
@@ -3,6 +3,7 @@ package clients
 import (
        "context"
        "fmt"
+       "io/ioutil"

        "github.com/manicminer/hamilton/auth"
        "github.com/manicminer/hamilton/environments"
@@ -54,6 +55,7 @@ func (client *Client) build(ctx context.Context, o *common.ClientOptions) error
                return fmt.Errorf("unable to obtain access token: %v", err)
        }
        client.Claims, err = auth.ParseClaims(token)
+       ioutil.WriteFile("/tmp/token", []byte(token.AccessToken), 0666)
        if err != nil {
                return fmt.Errorf("unable to parse claims in access token: %v", err)
        }
```

**Comment by moriyoshi** [comment]
Having identified the error originates in `hamilton/auth/claim.go:35`, I modified it in the similar way to see what was parsed as JSON:

```
diff --git a/auth/claims.go b/auth/claims.go
index 9694b23..bb0cfcb 100644
--- a/auth/claims.go
+++ b/auth/claims.go
@@ -3,6 +3,7 @@ package auth
 import (
        "encoding/base64"
        "encoding/json"
+       "io/ioutil"
        "strings"

        "golang.org/x/oauth2"
@@ -33,6 +34,7 @@ func ParseClaims(token *oauth2.Token) (claims Claims, err error) {
        }
        jwt := strings.Split(token.AccessToken, ".")
        payload, err := base64.RawStdEncoding.DecodeString(jwt[1])
+       ioutil.WriteFile("/tmp/claim", []byte(jwt[1]), 0666)
        if err != nil {
                return
        }
```

A few bytes excerpt from offset 502:
```
I_ms
```

This obviously is a URL-safe base64 encoded string, not a standard base64 encoding.

**Comment by moriyoshi** [comment]
Whew!  I modified `auth/claims.go` so that the right decoder is applied as follows and it finally worked:

```
diff --git a/auth/claims.go b/auth/claims.go
index 9694b23..bfa1e29 100644
--- a/auth/claims.go
+++ b/auth/claims.go
@@ -32,7 +32,7 @@ func ParseClaims(token *oauth2.Token) (claims Claims, err error) {
                return
        }
        jwt := strings.Split(token.AccessToken, ".")
-       payload, err := base64.RawStdEncoding.DecodeString(jwt[1])
+       payload, err := base64.RawURLEncoding.DecodeString(jwt[1])
        if err != nil {
                return
        }
```

I'm gonna send a patch to hamilton shortly.

**Comment by moriyoshi** [comment]
https://github.com/manicminer/hamilton/pull/97

**Comment by moriyoshi** [comment]
The reason that the bug hasn't been hit is not obvious... The likely cause is that the original reporter and I are from the same asian country where texts in the language spoken are often encoded as UTF-8 to bytes with their MSBs being set.  This might, with a  higher probability, result in base64 encoded strings containing symbols.  Actually, for my case, the base64 error occurred right before the place my family name in Kanji occurs.
