### ISSUE TITLE
Set owners on azuread_service_principal resources

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform-provider-azuread#561]
In my terraform code, I set four owners, one of which is the user account under which the deployment pipeline is running.
In the "plan" file, for an app with those four owners already set, it always tries to remove the user under which the deployment pipeline is running. The other three are left unaffected.

```
~ resource "azuread_service_principal" "service_principal" {
        id                           = "***"
      ~ owners                       = [
          - "<the object id of my deployment user>",
            # (3 unchanged elements hidden)
        ]
        tags                         = []
        # (17 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

I'm using the latest Azure 2.1.0, which according to the release notes, fixed an issue with incorrectly assigning owners... but it's still a problem for me.

Wayne

**Comment by manicminer** [comment]
Hi @waynejnicklin, thanks for reporting. Please can you share a minimal configuration to reproduce the persistent diff you are seeing? I did some testing now but didn't observe this with the following basic configuration (authenticating as a user via Azure CLI auth).

```terraform
data "azuread_client_config" "test" {}

resource "azuread_application" "test" {
  display_name = "aaa-owners-test"
}

resource "azuread_service_principal" "test" {
  application_id = azuread_application.test.application_id
  owners = [
    data.azuread_client_config.test.object_id,
    "bf1508ad-4b4b-441b-9680-ffe4996f3bdc",
    "bdf4f64a-309a-4f6c-918f-69231972b59c",
    "6fb9c41b-f742-484b-afc7-977ad1a3aa1d",
  ]
}
```

**Comment by waynejnicklin** [comment]
Sure, so I have a locals variable, with a set of owner email addresses:

locals {
    sp_owners = toset([
        "x@x.com",
        "y@y.com",
        "z@z.com",
        var.tech_user_name
        ])
}

The tech_user is the user that is running the deployment.

Then a data source to get the object ids:

data "azuread_user" "sp_owners" {
    for_each = local.sp_owners
        user_principal_name = each.value
}

Then this in the SP config:

    owners                       = [for value in data.azuread_user.sp_owners: value.object_id]

-

Note that this works perfectly fine for the azuread_application, exactly the same method is used.

Wayne

**Comment by waynejnicklin** [comment]
Sorry, I think this was my mistake... I will close the issue.
