### ISSUE TITLE
Azure VM Creation Option - Is the "Login with Azure AD" option available through Terraform?

### ISSUE THREAD

**Issue by Dragonsong3k** [hashicorp/terraform-provider-azuread#566]
This option is out of preview and available for Windows VMs. I don't see how to set it in azurerm_virtual_machine

![image](https://user-images.githubusercontent.com/18618111/132871773-03886d20-c57c-41dd-b6d4-bc8c0f21bf2c.png)

Thanks!

**Comment by Dragonsong3k** [comment]
I see the newer azurerm_windows_virtual_machine has more capabilities. It also includes an identity block.

However, I dont think the types refer to the Login with AzureAD options.

**Comment by kaovd** [comment]
Hi - This is a different provider that would be responsible for enabling this option, please make an issue here instead https://github.com/hashicorp/terraform-provider-azurerm/issues
