### ISSUE TITLE
Keepers field should be documented azuread_service_principal_password

### ISSUE THREAD

**Issue by nikolaifa** [hashicorp/terraform-provider-azuread#570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The field 
* Keepers

should be documented as an argument https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password
and not just within an example

### New or Affected Resource(s)

azuread_service_principal_password

* #0000

**Comment by manicminer** [comment]
Thanks for spotting this omission @nikolaifa! This will be added in the next release.
