### ISSUE TITLE
urn redirect uris

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azuread#575]
I have an application which uses `urn:ietf:wg:oauth:2.0:oob` as the redirect uri. Using 2.0 I get a validation error:

```
Error: URI has no host

  on resource-ad.tf line 80, in resource "azuread_application" "cluster_console":
  80:     redirect_uris = ["urn:ietf:wg:oauth:2.0:oob"]
```

Is this format no longer supported in MSGraph?

**Comment by manicminer** [comment]
Hi @hbuckle, with some quick testing it seems like URNs are supported for web redirect URIs, but not public client or SPA redirect URIs. We can amend the validation in the provider to reflect this.
