### ISSUE TITLE
Import Existing User, Show > File, Plan fails, Password is required.

### ISSUE THREAD

**Issue by jdelforno** [hashicorp/terraform-provider-azuread#582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output

`
│ Error: Missing required argument
│ 
│   on users.tf line 2, in resource "azuread_user" "testUser": 
│    2: resource "azuread_user" "testUser" {
│ 
│ The argument "password" is required, but no definition was found.
`

### Expected Behavior

User resource should be treated as already existing as it's in the state file.
Plan should be successful.

### Actual Behavior

Plan failed, with the error above.

### Steps to Reproduce

1. Create user in Azure AD
2. Run: terraform import <userName> <objectID>
3. Run: terraform show -nocolor temp.tf
4. Copy the specific resource out of temp.tf into main.tf
5. Run: terraform plan

### Important Factoids

Preexisting environment.

### References

* #0000

**Comment by manicminer** [comment]
Hi @jdelforno, thanks for raising this issue. This bug has been fixed in newer versions of the provider. Please update your provider to the latest version (v2.3.0 at time of writing) and you should no longer experience this error. Thanks!
