### ISSUE TITLE
Conditional Access - `sign_in_frequency` ignored

### ISSUE THREAD

**Issue by alexwilcox9** [hashicorp/terraform-provider-azuread#587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.3.0
```

### Affected Resource(s)

* `azuread_conditional_access_policy`

### Terraform Configuration Files

```hcl
resource "azuread_conditional_access_policy" "test" {
  display_name = "acctest-CONPOLICY-1"
  state        = "disabled"

  conditions {
    applications {
      included_applications = ["All"]
      excluded_applications = ["00000004-0000-0ff1-ce00-000000000000"]
    }
    users {
      included_users = ["All"]
      excluded_users = ["GuestsOrExternalUsers"]
    }
    client_app_types = ["all"]
    locations {
      included_locations = ["All"]
      excluded_locations = ["AllTrusted"]
    }
    platforms {
      included_platforms = ["android"]
      excluded_platforms = ["iOS"]
    }
    sign_in_risk_levels = ["medium"]
    user_risk_levels    = ["medium"]
  }

  grant_controls {
    operator          = "OR"
    built_in_controls = ["mfa"]
  }

  session_controls {
    sign_in_frequency                         = 10
    sign_in_frequency_period                  = "hours"
  }
}
```

### Expected Behaviour
A policy with a session timeout of 10 hours should be created

### Actual Behaviour
The policy is created but the sign in frequency settings are omitted

### Steps to Reproduce

1. `terraform apply`
2. Check policy in Azure portal

### References
![image](https://user-images.githubusercontent.com/38583982/134336723-dc27c2ed-d552-46b4-8a62-9bfffae9a1d9.png)

Sorry to be back with another bug, just spotted this one today. Running a plan after the apply shows nothing to be done however if you go and set the value in the portal (say to 11 hours) Terraform will see there is a difference and correct it

**Comment by manicminer** [comment]
Hi @alexwilcox9, I did some testing and as far as I can tell, the correct request is being sent and even confirmed in the response - whether for POST (i.e. creating the policy) or PATCH (i.e. updating a policy) requests.

This is the same problematic field that I raised upstream in https://github.com/microsoftgraph/msgraph-metadata/issues/93. I'm inclined to believe this an API bug with the handling of this field.

**Comment by enorlando** [comment]
@manicminer I am getting something similar where I am updating the `included_applications` argument in the `applications` block of an existing CA policy in terraform and when I run a plan it notices the change however if I try and apply, I get the following error

```
╷
│ Error: Could not update conditional access policy with ID: "xxx"
│ 
│   with azuread_conditional_access_policy.scg-mfa-for-apps,
│   on conditional-access-policies.tf line 240, in resource "azuread_conditional_access_policy" "scg-mfa-for-apps":
│  240: resource "azuread_conditional_access_policy" "scg-mfa-for-apps" {
│ 
│ ConditionalAccessPolicyClient.BaseClient.Patch(): unexpected status 400 with OData error: BadRequest: 1019: SignInFrequency type is invalid. It must be a valid hour or day. For examples, please see API
│ documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-1.0.
```

**Comment by ToniCipriani** [comment]
> @manicminer I am getting something similar where I am updating the `included_applications` argument in the `applications` block of an existing CA policy in terraform and when I run a plan it notices the change however if I try and apply, I get the following error
> 
> ```
> ╷
> │ Error: Could not update conditional access policy with ID: "xxx"
> │ 
> │   with azuread_conditional_access_policy.xx-xx-xx-xxx,
> │   on conditional-access-policies.tf line 240, in resource "azuread_conditional_access_policy" "xx-xx-xx-xxx":
> │  240: resource "azuread_conditional_access_policy" "xx-xx-xx-xxx" {
> │ 
> │ ConditionalAccessPolicyClient.BaseClient.Patch(): unexpected status 400 with OData error: BadRequest: 1019: SignInFrequency type is invalid. It must be a valid hour or day. For examples, please see API
> │ documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-1.0.
> ```

Seeing the same issue with the current 2.8.0 Provider. Only workaround is to destroy and reapply the policy.

**Comment by manicminer** [comment]
As best I can tell, the issue with 400 responses for `signInFrequency` is an API bug which, as I noted earlier, is reported upstream at https://github.com/microsoftgraph/msgraph-metadata/issues/93

**Comment by alexwilcox9** [comment]
Hi @manicminer hope you had a good holiday!

Deployed some new policies today and noticed the sign in frequency was set correctly! Normally I go in and change it myself to align with the code
Not entirely sure when this was fixed but if you see the same correct behaviour I think we can close this off :)

**Comment by enorlando** [comment]
Hi @manicminer 
Seems to be working where I am able to now update the included_applications in the `applications` block of an existing CA policy without error

**Comment by manicminer** [comment]
@alexwilcox9, @enorlando Thanks for testing and reporting, I'll do some testing around this and also see whether this allows us to stop forcing a new resource for changes to `sign_in_frequency`

**Comment by manicminer** [comment]
Alas it would appear the API is still broken when updating session controls, so the conditional ForceNew will have to stay for now.
