### ISSUE TITLE
A new resource to assign scopes (delegated oauth permissions) for an application

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform-provider-azuread#591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider has a new resources now that is called `azuread_app_role_assignment`. It is now possible to grant app role assignments, but it does not seem to work with scopes. As [this](https://github.com/hashicorp/terraform-provider-azuread/issues/230) issue mentions, we can only create "request" for the required access using `required_resource_access`. And while it does now work for type "Role", there is still now way that I have found to do the same for the "Scope" (I have tried with `azuread_app_role_assignment` and it fails).

```hcl
required_resource_access {
  resource_app_id = "00000003-0000-0000-c000-000000000000"

  resource_access {
    id   = "7427e0e9-2fba-42fe-b0c0-848c9e6a8182" # offline_access
    type = "Scope"
  }

  resource_access {
    id   = "37f7f235-527c-4136-accd-4a02d197296e" # openid
    type = "Scope"
  }
}
```

### New or Affected Resource(s)

* azuread_scope_assignment [NEW]

### Potential Terraform Configuration

```hcl
resource "azuread_scope_assignment" "test" {
  principal_id = azuread_service_principal.test.id
  app_id         = "00000003-0000-0000-c000-000000000000" # Microsoft Graph
  scope_ids    = ["37f7f235-527c-4136-accd-4a02d197296e"] # openid
}
```

It seems that `azuread_application_pre_authorized` can be used for this purpose, but it did not work for me in the case of Microsoft graph with this error:

> Application with object ID "MsGraph.ObjectId" was not found

### References

* https://github.com/hashicorp/terraform-provider-azuread/issues/230
* https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest

**Comment by dvdvorle** [comment]
`pre_authorized` also doesn't work in B2C tenants, so there's another use case.

**Comment by ilya-git** [comment]
That's actually the case for us! We use B2C, I forgot to mention that as that is probably why it does not work, thanks for noting

**Comment by dvdvorle** [comment]
Hi @manicminer, I'm pretty sure there already is programmatic access to this feature. Please take a look at the [oAuth2PermissionGrant resource type](https://docs.microsoft.com/en-us/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0).

I currently use this module as a workaround, as if it's said resource in the title of this issue:
```hcl
variable "resource_service_principal_object_id" {
  type = string
}

variable "client_service_principal_object_id" {
  type = string
}

variable "scope" {
  type = string
}

variable "azure_config_dir" {
  type = string
}

resource "null_resource" "consent" {
  triggers = {
    resource = var.resource_service_principal_object_id
    client   = var.client_service_principal_object_id
    scope    = var.scope
  }

  provisioner "local-exec" {
    command     = <<-GRANTCONSENTCMD
      az rest --method POST \
        --uri 'https://graph.microsoft.com/v1.0/oauth2PermissionGrants' \
        --headers 'Content-Type=application/json' \
        --body '{
          "clientId": "${self.triggers.client}",
          "consentType": "AllPrincipals",
          "resourceId": "${self.triggers.resource}",
          "scope": "${self.triggers.scope}"
        }'
      GRANTCONSENTCMD
    interpreter = ["bash", "-c"]
    environment = {
      AZURE_CONFIG_DIR = var.azure_config_dir
    }
  }
}
```

p.s. coming from the OIDC spec, I very much dislike the MS API terminology. `clientId` and `resourceId` should be the client's and resource's appId, not their principals' objectIds.. if this abstraction could make it into this new resource that'd be great ;-)

**Comment by dvdvorle** [comment]
Thanks @ilya-git, that's what I was using before! But that command still uses the old aad graph api under the hood. The resource I linked to is part of the newer ms graph api, so I think that's what @manicminer was looking for.

**Comment by manicminer** [comment]
@dvdvorle Thanks! I stand corrected 🙇 

In that case, marking this is a feature request and we'll be happy to implement this :)
