### ISSUE TITLE
GroupsClient - invalid query filter clause specified for property 'displayName'

### ISSUE THREAD

**Issue by petr-stupka** [hashicorp/terraform-provider-azuread#592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform - v1.0.0
AzureAD  - v2.4.0

### Affected Resource(s)

* `azuread_resource_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "group" {
  display_name            = var.display_name
  description             = var.description
  owners                  = var.owners
  prevent_duplicate_names = true

  security_enabled = true

  lifecycle {
    ignore_changes = [
      members,
    ]
  }
}
```

### Panic Output

`terraform -apply`

```hcl
│ Error: could not check for existing application(s): unable to list Groups with filter "displayName eq ''": GroupsClient.BaseClient.Get(): unexpected status 400 with OData error: Request_UnsupportedQuery: Unsupported or invalid query filter clause specified for property 'displayName' of resource 'Group'.
│ 
│   with module.azuread_group.group,
│   on .terraform/modules/azuread_groups/module.tf line 1, in resource "azuread_group" "group":
│    1: resource "azuread_group" "group" {
```

### Expected Behavior

Terraform should check if the resource exist, if not create it

### Actual Behavior

The variable map looks like this (calculated values):

```hvl
dev-management-reader      = {
  description  = (known after apply)
  display_name = (known after apply)
  key          = "dev-management-reader"
  owners       = []
  role         = "reader"
  scope        = (known after apply)
}
```

The display name contain `(known after apply)` value (it is a value in the map, so for_each) is not affected by unknown values.
However provider is trying to find the  `""` resource in AAD

### Steps to Reproduce

Using the configuration above

1. `terraform -apply` using the provided map

### Important Factoids

I'm not sure if this is behavior of the new provider as it worked fine with the old provider.

**Comment by manicminer** [comment]
Hi @petr-stupka, thanks for reporting this. In v2 we added some more functionality at plan time, and I believe this is due to the display name being sufficiently variable that Terraform doesn't know the value at plan time. We should be able to resolve this, although in such cases the `prevent_duplicate_names` check will only happen at apply time.
