### ISSUE TITLE
azuread_directory_role provider panics when directory role is misspelled

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azuread#593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
```

### Affected Resource(s)

* `azuread_directory_role`

### Terraform Configuration Files

```hcl
resource "azuread_directory_role" "directory_reader" {
  display_name = "Directory Reader" # Misspelled -- should be "Directory Readers"
}
```

### Debug Output

Please contact me for full debug output, I've obscured the GUIDs, but should still be useful:

https://gist.github.com/kensykora/6356743ebeaf51f2155959de6641c611

### Panic Output

https://gist.github.com/kensykora/6356743ebeaf51f2155959de6641c611

### Expected Behavior

An error occurs during apply time that indicates the role was not found. Really I'd prefer this to be a data resources but I'll just leave it at that :)

### Actual Behavior

provider panic

### Steps to Reproduce

1. Create main.tf file above
1. `terraform apply`

**Comment by manicminer** [comment]
Hi @kensykora, thanks for reporting this crash! I've opened a PR with mitigation to prevent this which will make it into next week's release.

I agree this would be preferable as a data source. However because directory roles need activating before use, we're unfortunately unable to reliably implement this as a data source.
