### ISSUE TITLE
azuread_directory_role causes crash if display_name is incorrect

### ISSUE THREAD

**Issue by jlaundry** [hashicorp/terraform-provider-azuread#598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.4.0

### Affected Resource(s)

* `azuread_directory_role`

### Terraform Configuration Files

```hcl
resource "azuread_directory_role" "example" {
  display_name = "Does Not Exist"
}
```

### Debug Output

https://gist.github.com/jlaundry/fc6477d0bbe14aafcc29865ac664e530

### Expected Behavior

Resource should fail to create with an error that the requested display_name did not exist.

### Actual Behavior

```
│ Error: Request cancelled
│
│   with azuread_directory_role.example,
│   on main.tf line 13, in resource "azuread_directory_role" "example":
│   13: resource "azuread_directory_role" "example" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-azuread_v2.4.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe84547]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
Hi @jlaundry, thanks for taking the time to report this crash! This was reported earlier in #593 and a fix was merged in #594 which will be included in the next release of the provider.

As this is a duplicate, and a fix is on the way, I'm going to close this for now. Please feel free to open any other issues if you encounter bugs or problems, your contribution is highly appreciated. Thanks!

**Comment by manicminer** [comment]
Duplicates #593

**Comment by jlaundry** [comment]
Sorry for the duplicate @manicminer, I must've searched with an Open filter...

Keep up the good work!
