### ISSUE TITLE
azuread_service_principal - null value for 'tags'

### ISSUE THREAD

**Issue by petr-stupka** [hashicorp/terraform-provider-azuread#601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform - v1.0.0
AzureAD - v2.4.0

### Affected Resource(s)

* `azuread_service_principal`

### Terraform Configuration Files

```hcl
resource "azuread_service_principal" "spn" {
  application_id               = azuread_application.app.application_id
  app_role_assignment_required = false
  owners                       = var.owners

  features {
    enterprise_application = false
    gallery_application    = false
  }
}
```

### Panic Output

```hcl
│ Error: Could not create service principal
│ 
│   with module.blueprint_service_principals.module.service_principals["test"].azuread_service_principal.spn,
│   on .terraform/modules/blueprint_service_principals.service_principals/module.tf line 31, in resource "azuread_service_principal" "spn":
│   31: resource "azuread_service_principal" "spn" {
│ 
│ ServicePrincipalsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: A null value was found for the property named 'tags', which has the expected type
│ 'Collection(Edm.String)[Nullable=False]'. The expected type 'Collection(Edm.String)[Nullable=False]' does not allow null values.
```

### Expected Behavior

since the features block is specified, null on tags should be accepted

![image](https://user-images.githubusercontent.com/18548253/134899326-f51da938-0e57-449d-97f5-09a89c8958b3.png)

### Actual Behavior

see Panic Output

### Steps to Reproduce

`terraform apply`

1. `terraform apply`

### Important Factoids

none

**Comment by manicminer** [comment]
Hi @petr-stupka, thanks for reporting this! This is definitely a bug in the provider - we are not setting the tags correctly when all `features` are disabled. The fix in #602 should resolve this.
