### ISSUE TITLE
User-assigned managed identity stopped working in v2

### ISSUE THREAD

**Issue by ruial** [hashicorp/terraform-provider-azuread#604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

- v2.x+
- v1.5+ with use_microsoft_graph = true

### Affected Resource(s)

* Authentication with user-assigned managed identity, when a VM has 2+ user-assigned managed identities

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.4.0"
    }
  }
}

provider "azuread" {
  client_id                 = "<managed_identity_client_id>"
  tenant_id                 = "<azure_tenant_id>"
  use_msi                   = true
}

resource "azuread_group" "group" {
  display_name = "test"
  security_enabled = true
}
```

### Debug Output

```
│ Error: building client: unable to obtain access token: MsiAuthorizer: failed to request token from metadata endpoint: received HTTP status 400
│ 
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on provider.tf line 5, in provider "azuread":
│    5: provider "azuread" {
```

### Expected Behavior

Terraform v1.x is able to authenticate using a specific user-assigned managed identity, v2.x should also.

### Actual Behavior

Unable to use user-assigned managed identities because the client_id is not used in https://github.com/hashicorp/terraform-provider-azuread/blob/main/vendor/github.com/manicminer/hamilton/auth/msi.go so it only works for system-assigned managed identities or when the VM has only 1 user assigned managed identity. I also confirmed this by sniffing the HTTP trafic:

```
v2.x (not using client_id, new graph api)
GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fgraph.microsoft.com%2F HTTP/1.1

v1.x (using client_id correctly, old graph api)
GET /metadata/identity/oauth2/token?api-version=2018-02-01&client_id=<client_id>&resource=https%3A%2F%2Fgraph.windows.net%2F HTTP/1.1
```

This behaviour worked correctly in v1.x because when the client_id was specified, it was sent as a query parameter to the azure instance metadata service, but is no longer being sent, causing the error 400 with the following message:

```
Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request
```

### Steps to Reproduce

1. Create user-assigned managed identity
2. Give Graph API permissions to the managed identity (has to be through CLI https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-cli%2Ccommand-line#grant-access-to-microsoft-graph )
3. Assign 2 different managed identities to a VM
4. Replace the <client_id> and <tenant_id>
5. Terraform init and plan

### Important Factoids

NA

### References

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/managed_service_identity#using-a-user-assigned-identity

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token

**Comment by manicminer** [comment]
Hi @ruial, thanks for reporting and for the detailed analysis. We'll look to resolve this!
