### ISSUE TITLE
myapp://auth B2C Proxy IEF Redirect Uri blocked by validation

### ISSUE THREAD

**Issue by OmnipotentOwl** [hashicorp/terraform-provider-azuread#606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

- v2.x+

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "b2c_ProxyIdentityExperienceFramework" {
  display_name                   = "ProxyIdentityExperienceFramework"
  sign_in_audience               = "AzureADMyOrg"
  fallback_public_client_enabled = true
  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000"
    resource_access {
      id   = "37f7f235-527c-4136-accd-4a02d197296e"
      type = "Scope"
    }
    resource_access {
      id   = "7427e0e9-2fba-42fe-b0c0-848c9e6a8182"
      type = "Scope"
    }
  }

  required_resource_access {
    resource_app_id = azuread_application.b2c_IdentityExperienceFramework.application_id
    resource_access {
      id   = random_uuid.b2c_IdentityExperienceFramework_user_impersonation_scope.result
      type = "Scope"
    }
  }
  public_client {
    redirect_uris = [
      "myapp://auth"
    ]
  }

  provider = azuread.b2c
}
```

### Expected Behavior

B2C Public Client Redirect Uri which is valid in the portal should be accepted as valid by the provider's validation.

### Actual Behavior

Error: URI must have a trailing slash when there is no path segment

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

Azure AD B2C Tenant

### References

* similar to #575
* https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy#register-the-proxyidentityexperienceframework-application

**Comment by manicminer** [comment]
Hi @OmnipotentOwl, thanks for raising this! I've opened a PR to correct this validation discrepancy.
