### ISSUE TITLE
Sample on Microsoft Graph API

### ISSUE THREAD

**Issue by kgangasani** [hashicorp/terraform-provider-azuread#609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

Looking for samples on how to use Microsoft's Azure AD Graph API in terraform. 
For UserGroup CRUD operations.

Thanks,
Krishna

**Comment by manicminer** [comment]
Hi @kgangasani, thanks for opening this issue. The AzureAD Terraform Provider no longer uses the [Azure Active Directory Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api) and instead uses the [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/overview). If you are new to the provider, I suggest [reading the documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs) and [checking out our Learn tutorial](https://learn.hashicorp.com/tutorials/terraform/azure-ad).

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get more answers on the community discussion portal.
