### ISSUE TITLE
Nesting is currently not supported for groups that can be assigned to a role

### ISSUE THREAD

**Issue by noampc** [hashicorp/terraform-provider-azuread#651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

* `Terraform v1.0.9`
 * `AzureAD Provider 2.7.0`

### Affected Resource(s)

* `azuread_group`
* `azuread_group_member`

### Terraform Configuration Files

```hcl
resource "azuread_group" "member_group" {
  display_name            = "member_group"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}

resource "azuread_group" "outer_group" {
  display_name            = "outer_group"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}

resource "azuread_group_member" "example" {
  group_object_id  = azuread_group.outer_group.id
  member_object_id = azuread_group.member_group.id
}
```

### Debug Output
`GroupsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: Nesting is currently not supported for groups that can be assigned to a role.
│ paramName: Members, paramValue: , objectType: Microsoft.Online.DirectoryServices.Group`

### Expected Behavior

Needs to add one AD group to another AD group. This works from the Azure portal/API but not in terraform.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @noampc, thanks for reporting this! I have done some testing with the Graph Explorer and with the Portal and it seems like this is actually not supported? Can you confirm how you were able to do this outside of Terraform?

![Screenshot 2021-11-18 at 14 43 13](https://user-images.githubusercontent.com/251987/142436994-ae8c0e95-cfbd-438f-a813-a18ee968c64b.png)

![Screenshot 2021-11-18 at 14 42 13](https://user-images.githubusercontent.com/251987/142437001-645bcf78-6e24-4898-bcaf-a2cdb9203428.png)

**Comment by manicminer** [comment]
@noampc As this looks like a platform limitation rather than a problem with the provider, I'm going to close this issue for now. Please feel free to comment further if I have missed some context from your report, but at the moment as I mentioned in my earlier reply, it looks like nested role-assignable groups are not supported by Azure AD at this time.
