### ISSUE TITLE
azuread_group API permission issue in documentation

### ISSUE THREAD

**Issue by TheBlackMini** [hashicorp/terraform-provider-azuread#657]
After updating to provider 2.x and trying to create a group and getting the below error constantly. 

```
GroupsClient.BaseClient.Post(): unexpected status 403 with OData error:
Authorization_RequestDenied: Insufficient privileges to complete the
operation.
```

I ended up stumbling across this forum entry.

https://discuss.hashicorp.com/t/insufficient-privileges-when-trying-to-create-azuread-group-azuread-2-0-1/28866

Which pointed me to the below tables being out of date for the provider. I'm not sure if this is the only permission missing though.

>https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/guides/service_principal_configuration.md
>https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/guides/microsoft-graph.md

If you try to create a group with ```assignable_to_role = true``` then the account you are using requires an additional permission (RoleManagement.ReadWrite.Directory).

## Old Table
<html>
<body>

Resource(s) | Role Name(s)
-- | --
data.azuread_application <br /> data.azuread_service_principal | Application.Read.All
data.azuread_domains | Domain.Read.All
data.azuread_group <br /> data.azuread_groups | Group.Read.All
data.azuread_user <br /> data.azuread_users | User.Read.All
azuread_application <br /> azuread_application_certificate <br /> azuread_application_password <br />azuread_service_principal <br />azuread_service_principal_certificate <br />azuread_service_principal_password | Application.ReadWrite.All
azuread_group <br /> azuread_group_member | Group.ReadWrite.All
azuread_user | User.ReadWrite.All

</body>
</html>

## New Table
<html>
<body>

Resource(s) | Role Name(s)
-- | --
data.azuread_application <br /> data.azuread_service_principal | Application.Read.All
data.azuread_domains | Domain.Read.All
data.azuread_group <br /> data.azuread_groups | Group.Read.All
data.azuread_user <br /> data.azuread_users | User.Read.All
azuread_application <br /> azuread_application_certificate <br /> azuread_application_password <br />azuread_service_principal <br />azuread_service_principal_certificate <br />azuread_service_principal_password | Application.ReadWrite.All
azuread_group <br /> azuread_group_member | Group.ReadWrite.All <br /> ```RoleManagement.ReadWrite.Directory```
azuread_user | User.ReadWrite.All

</body>
</html>

**Comment by manicminer** [comment]
Hi @TheBlackMini, thanks for reporting this documentation discrepency. The permissions tables in the v2 upgrade guide, and the guide on configuring a principal, are intentionally incomplete for brevity - there is a note beneath each table suggesting to consult the documentation page for the particular resource to get the latest permissions.

However, this permission is indeed missing from the [azuread_group](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group) page, so we'll update this to note the RoleManagement.ReadWrite.Directory role is required when using the `assignable_to_role` property. Thanks!
