### ISSUE TITLE
Known_client_applications being ignored in azuread_application api block

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform-provider-azuread#662]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform version: 0.15.14
AzureAd version: 2.8.0

### Affected Resource(s)

azuread_application

### Terraform Configuration Files

```hcl
resource "azuread_application" "app_registration" {
  for_each     = local.auth_apps
  display_name = each.value.auth_app_registration_name
  owners       = [data.azurerm_client_config.current.object_id, "8c8548e3-2007-461e-b807-9fefbdeb82d2"]
  # Making this change because of:
  # https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#october-2021
  # And .cloud.fiserv.net is our verified domain in AAD
  # identifier_uris         = ["https://${each.key}.azurewebsites.net"]
  identifier_uris         = ["https://${each.value.auth_app_registration_name}.cloud.fiserv.net"]
  prevent_duplicate_names = "true"
  # sign_in_audience = "AzureADandPersonalMicrosoftAccount"
  web {
    homepage_url  = "https://${each.key}.azurewebsites.net"
    redirect_uris = each.value.add_redirect_uri ? ["https://${each.key}.azurewebsites.net/.auth/login/aad/callback"] : []
    # redirect_uris = ["https://${each.key}.azurewebsites.net/.auth/login/aad/callback"]
    implicit_grant {
      id_token_issuance_enabled = "true"
    }
  }
  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" # Microsoft Graph
    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" # User.Read.All Delegated
      type = "Scope"
    }
  }
  api {
    known_client_applications = [
      "ae56f2de-4db1-4883-9422-5132ac9945dd",
    ]
    oauth2_permission_scope {
      admin_consent_description  = "Allow the application to access {each.key} on behalf of the signed-in user."
      admin_consent_display_name = "Access-${each.key}"
      enabled                    = true
      id                         = random_uuid.expose_api.result
      type                       = "User"
      user_consent_description   = "Allow the application to access example on your behalf."
      user_consent_display_name  = "Access-${each.key}"
      value                      = "user_impersonation"
    }
  }
  dynamic "app_role" {
    for_each = each.value.app_roles
    content {
      allowed_member_types = ["User", "Application"]
      description          = "Admins can manage roles and perform all task actions"
      display_name         = app_role.value.app_role_name
      enabled              = true
      id                   = random_uuid.api_roles["${each.key}-${app_role.value.app_role_name}"].result
      value                = app_role.value.claims_role_value
    }
  }
  depends_on = [local.apps]
}
```

### Expected Behavior

The application specified should have been added as below
![image](https://user-images.githubusercontent.com/47507148/141656482-320314cd-36d2-47bb-816d-57afade970fc.png)

### Actual Behavior
The applications are not being added

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
Hi @Divya1388, thanks for raising this issue. Are you perhaps looking for the [azuread_application_pre_authorized](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_pre_authorized) resource? The `known_client_applications` property is different and is used for [bundling/combining consent](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#gaining-consent-for-the-middle-tier-application) for more than one application at once.

**Comment by manicminer** [comment]
@Divya1388 As this seems to be more of a usage question, I'm going to close this issue for now so that we can concentrate on bug reports and feature requests. Please feel free to comment further if I have misunderstood your report, or if you have any other information to add. Thanks!
