### ISSUE TITLE
azuread_group does not remove the last member from an AD group

### ISSUE THREAD

**Issue by arsalan-ahmad** [hashicorp/terraform-provider-azuread#664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.9.0
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
# This group previously had member "f9aad831-3d2d-4760-9545-9369a89f5cab" defined, I am updating with no members to remove this last member.
resource "azuread_group" "example" {
  display_name     = example-group
  security_enabled = true

  members = []
}
```
### Terraform Plan Output
```hcl
# Terraform states it will perform the following action which is removal of member "f9aad831-3d2d-4760-9545-9369a89f5cab":
azuread_group.example will be updated in-place
  ~ resource "azuread_group" "example-group" {
        id                      = "8730dc22-acb3-4c9b-85df-5da09c4bd011"
      ~ members                 = [
          - "f9aad831-3d2d-4760-9545-9369a89f5cab",
        ]
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Debug Output

```
# No DELETE is found in the trace:
https://gist.github.com/arsalan-ahmad/51665c79dd0cf1e3ec0041d3fb41c651
```

### Panic Output

No panic output, terraform states everything completed successfully.

### Expected Behavior

The last member from the AD group should be deleted, result should be empty AzureAD group with no members.

I also tested removing the final member from an AzureAD group directly in AzureAD to ensure there was no product limitation but that works just fine, you are able to have a group with no members in it and if you create a group with members in it you are able to remove all members.

### Actual Behavior

1. If a azuread_group has multiple members, you can successfully remove all but one member. There will always be one member which remains even though the terraform configuration has none.
2. If the azuread_group has a single member, you can remove it from the terraform configuration and also apply without failure however no DELETE action is triggered for the final member. This means in AzureAD Group that member still exists. In all subsequent terraform plans you will see one member being removed as there are none defined in the terraform configuration, apply will be successful however the member will not be deleted from the AzureAD group.

### Steps to Reproduce

1. Create an `azuread_group` resource with multiple members defined.
2. `terraform apply`
3. Remove all members from the the `azuread_group` resource.
3. `terraform apply`

The group should remain and all members should be removed.

The group remains and all but 1 user is removed. That last user cannot be deleted via terraform although the plan shows it will remove it.

### Important Factoids

Nothing of note.

### References

* #0000

**Comment by manicminer** [comment]
Hi @arsalan-ahmad, thanks for raising this. Unfortunately this is by design of the API and is known and [noted in the documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group#argument-reference) for this resource:

![Screenshot 2021-11-18 at 00 35 57](https://user-images.githubusercontent.com/251987/142317310-cfb70149-e169-475b-bf41-cc1ec6b5d9d7.png)

**Comment by arsalan-ahmad** [comment]
Hi @manicminer Thank you for the prompt reply. 

I did wonder if this was related to the owners limitation which is documented in the docs you referenced however this raises some questions;

1. The docs states "a group cannot be without an `owner` therefore the principal being used to execute terraform is given owner." This is fine and I am not trying to remove this.
2. The behaviour I have noted is solely for the removal of `members` and not `owners`. I also tried adding another owner to the group and running the `terraform plan` & `terraform apply` again but it does not remove the last `member`.
3. The member in question is not the service principal being used to execute terraform but an individual user.
4. We were able to successfully remove the final member from the azuread group directly in azuread. As I understand it, a group can exist without a member, and I can also create an empty group with no members.
5. From the terraform trace I provided in the gist, it seems like no DELETE request is submitted to the azuread API by terraform for the final member of a group, but when there are multiple members you can see DELETE requests to the azuread API in the terraform trace.

Please could you provide some clarity on this. Maybe I am missing something.

Thanks again!

**Comment by manicminer** [comment]
Hi @arsalan-ahmad, thanks for the clarification and apologies, I misread your initial report as being about removal of owners. I also missed your gist link nestled in the code block there. Sorry about this confusion!

After digging further, I can confirm that this is definitely a bug which was being missed by our acceptance testing. I've opened a PR #666 to address this and we'll look to get this released soon.

Thanks again for reporting this, and for the level of detail provided, and again sorry that I misread your bug report.

**Comment by arsalan-ahmad** [comment]
Thank you very much @manicminer for the quick release on this! I have given it a quick test and it seems to have fixed my issue :) Will report back if there is anything else.

Thanks again @manicminer!
