### ISSUE TITLE
403 forbidden error when attempting to provision azuread_application

### ISSUE THREAD

**Issue by asos-alastairwilkins** [hashicorp/terraform-provider-azuread#665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform version: 1.0.11
AzureAD Provider version: 2.9.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "azuread_app" {
  display_name     = "example-ad-app-registration"
  sign_in_audience = "AzureADMyOrg"
  owners           = [var.pipeline_sp_id] # <-- This is the spn of the principal used to execute Terraform commands in pipeline
}
```

### Debug Output

https://gist.github.com/asos-alastairwilkins/e1db8343c77d253ed71a40359f50f262

### Expected Behavior

Terraform creates an Azure AD app registration with the SPN set as an owner.

### Actual Behavior

Azure AD returns a 403 Forbidden saying: 
`ApplicationsClient.BaseClient.Post(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation`

### Steps to Reproduce

1. Create azuread_application resource as defined above.
2. `terraform apply`

### Important Factoids

The SPN used to create this resource has the role `Application.ReadWrite.OwnedBy`.
Per the [azuread_application documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application) it states:

![image](https://user-images.githubusercontent.com/79162634/142286729-23e6789f-c19b-4607-9e5a-d5337c3eac05.png)

In earlier versions of the provider (e.g. 1.6.0 as a working example), we are able to provision an app registration exactly the same with no issue, using the same SPN.

Based on this, I would expect the provider to be able to create this resource. Please can clarification be provided if we are doing something wrong or have misunderstood the documentation?

**Comment by manicminer** [comment]
Hi @asos-alastairwilkins, I would suggest double checking the owner ID and that it does match the object ID of the SP used by Terraform. This is exposed as the `object_` attribute by the azuread_client_config data source.

Please also ensure that you have read the [2.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph) as there are breaking changes in v2.0 of the provider including a move to use Microsoft Graph which requires different app roles than the former AAD Graph API.


If you are certain the correct object ID is being passed, and that your application permissions are correct, please capture and post a [debug log](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing) and we'll be happy to check it!

**Comment by asos-alastairwilkins** [comment]
Yes, I can confirm the owner ID does match the SP used by Terraform.

Here is the permission it has:
![image](https://user-images.githubusercontent.com/79162634/142388650-7273b8a1-680d-4338-a231-df03639b2c8a.png)

The permissions page you link above shows `azuread_application` requiring ReadWriteAll, yet the documentation page on `azuread_application` contradicts this?

Please confirm which it is

![image](https://user-images.githubusercontent.com/79162634/142388808-3c7c9599-6201-484b-ae2c-50f00da2b5de.png)

**Comment by manicminer** [comment]
@asos-alastairwilkins Thanks for confirming. It looks like you haven't added permissions for Microsoft Graph - your screenshot shows "Windows Azure Active Directory" which is the old API :)

**Comment by asos-alastairwilkins** [comment]
D'oh. Thanks for letting me know. Will get the ReadWrite.OwnedBy from Graph added and try again - Sorry for the confusion, appreciate the quick response.
