### ISSUE TITLE
Support for creating custom AAD roles

### ISSUE THREAD

**Issue by jayendranarumugam** [hashicorp/terraform-provider-azuread#667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_role_definition

### Potential Terraform Configuration

```hcl
resource "azuread_role_definition" "example" {
  name        = "my-custom-role"
  description = "This is a custom role created via Terraform"

  permissions = [
   "microsoft.directory/applicationPolicies/allProperties/read",
   "microsoft.directory/applicationPolicies/allProperties/update"

  ]
}
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @jayendranarumugam, thanks for requesting support for custom AAD roles. Unfortunately we're unable to implement this at the moment as the required functionality is only available via a private endpoint on the deprecated AAD Graph API. We will need to wait for support to be added to Microsoft Graph.

I've marked this feature request as blocked for now, but we'll revisit once API support is available with a view to adding this. Thanks!

**Comment by kratkyzobak** [comment]
Does missing API apply to assigning scoped directory roles too? There is possibility in portal to assign Directory role (Built-In) to ObjectId scoped to only part of directory (currently searching for assigning App Administrator for group to specific applications only)

**Comment by kaovd** [comment]
Just watching this issue, appears API support is now availiable in at least beta 
https://docs.microsoft.com/en-us/azure/active-directory/roles/custom-create#create-a-role-with-the-microsoft-graph-api
