### ISSUE TITLE
Conditional Access - add Device Filter conditions to tf file argument syntax

### ISSUE THREAD

**Issue by josefismael** [hashicorp/terraform-provider-azuread#669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Conditional Access Device filter conditions are now GA, but resource documentation does not include the argument syntax for this condition. CA policies with this condition defined are returned when executing an import, however this block is missing from the result.

### New or Affected Resource(s)

`azuread_conditional_access_policy`

### Potential Terraform Configuration

```hcl
device_filter {
            mode = [
                "Exclude",
            ]
            filter = [
                "Device.isCompliant -eq True -or device.trustType -eq 'ServerAD'",
            ]
        }
```

### References
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-condition-filters-for-devices#filter-for-devices-graph-api

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/conditional_access_policy#attributes-reference

* #0000

**Comment by manicminer** [comment]
Thanks for requesting this @josefismael, we'll look to add it as soon as we can. Thanks!
