### ISSUE TITLE
azuread_application_app_role is not documented

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-azuread#678]
`azuread_application_app_role` was created in response to https://github.com/hashicorp/terraform-provider-azuread/issues/306 and https://github.com/hashicorp/terraform-provider-azuread/issues/150 and available since v1.0.0

However it is not documented and does not appear in the docs (see https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application)

**Comment by gtmtech** [comment]
I since found that it's been removed in v2.0.0, so that's why.

**Comment by manicminer** [comment]
Hi @gtmtech, that's correct, this resource was removed in v2.0
