### ISSUE TITLE
azuread_invitation - doesn't send email to user

### ISSUE THREAD

**Issue by Bhodges94** [hashicorp/terraform-provider-azuread#682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azuread_invitation resource doesn't send an email invitation to the user. This means I have to manually send it from the azure portal.

**Comment by manicminer** [comment]
Hi @Bhodges94, the invitation email is sent by Azure and not something the provider handles. I have just tested and it works fine for me. I would suggest checking your email logs etc, and if you're certain that no message is delivered to your mail server at all, I would contact Azure support to investigate.

**Comment by Bhodges94** [comment]
Well I tested with a hotmail account and corporate account and both resulted in no email. I've checked the AD audit logs and can see that the invite external user was success.

Like I said, it works if I do it manually from the portal but not when using the Terraform azuread provider. 

Here's the code I'm using:

resource "azuread_invitation" "user-creation" {
  for_each            = {for user in local.users:  user.mail => user}
  user_display_name   = each.value.display_name
  user_email_address  = each.value.mail
  user_type           = "Member"
  redirect_url        = "https://portal.azure.com"
  }

Which results in the user being created but no invitation being sent.

**Comment by manicminer** [comment]
@Bhodges94 You'll need to include a `message` block in your configuration, as shown in the [documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/invitation#example-usage) :)

**Comment by Bhodges94** [comment]
Thanks @manicminer I will give it a try. Would be nice if the documentation said that it was required. It should be made mandatory because without it, the user doesn't get invited.

**Comment by Bhodges94** [comment]
this worked btw, someone really needs to update the documentation

**Comment by manicminer** [comment]
Hi @Bhodges94, thanks for reporting back. We do already include examples both with and without a message in the docs, and the description for the `message` block does already state

> If this block is omitted, no message will be sent

Glad you were able to get it working! :)

**Comment by Bhodges94** [comment]
Yeah and that message is stupid. What's the point in doing it if no message will be sent.

**Comment by manicminer** [comment]
> Yeah and that message is stupid. What's the point in doing it if no message will be sent.

@Bhodges94 There are lots of reasons why someone may wish to customize or omit the message, which is why both the service and the provider expose this functionality.

There doesn't appear to be anything further to add to this resolved user issue, so we'll lock this for now. Please feel free to open another issue if you encounter a bug with the provider, or if you have a feature request.
