### ISSUE TITLE
azuread_application custom redirect_uris for "Mobile and Desktop applications"

### ISSUE THREAD

**Issue by Va55ago** [hashicorp/terraform-provider-azuread#683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v1.0.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.11.0
```

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "service_fabric_client" {
  display_name = "Service Fabric Client"
  
  public_client {
    redirect_uris = ["urn:ietf:wg:oauth:2.0:oob"]
  }

  required_resource_access {
    resource_app_id = "00000002-0000-0000-c000-000000000000"
    resource_access {
      id   = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"
      type = "Scope"
    }
  }
}
```

### Expected Behavior

A redirect uri should be added to the Authentication tab, under the "Mobile and Desktop application" section of the App Registration.

In the App Registration manifest, this would appear as:
```json
"replyUrlsWithType": [
  {
    "url": "urn:ietf:wg:oauth:2.0:oob",
    "type": "InstalledClient"
  }
],
```

### Actual Behavior

│ Error: URI has no host

### Important Factoids
It is possible to add custom redirect URIs of this type using the Azure Portal.

### References
I am, ultimately, attempting to setup a service fabric cluster that utilises AzureAD authentication. I am following [this guide](https://techcommunity.microsoft.com/t5/azure-paas-blog/use-azure-portal-to-enable-aad-authentication-for-service-fabric/bc-p/3008534#M297), but trying to automate those tasks using terraform.

**Comment by manicminer** [comment]
Hi @Va55ago, thanks for reporting this! It looks like our validation for public client redirect URIs was disallowing URNs, which as you point out should be allowed. I've opened a PR to address this, the fix will go out in the next weekly release of the provider. Thanks!

**Comment by Va55ago** [comment]
Can confirm that this is now working as expected. Many thanks for the quick turnaround.
