### ISSUE TITLE
Getting Could not disable OAuth2 Permission Scopes for application error

### ISSUE THREAD

**Issue by Uvindu96** [hashicorp/terraform-provider-azuread#687]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
- Terraform version v0.14.6
- AzureAD Provider version  2.10.0

### Affected Resource(s)

* `azuread_application`

### Description 
I have upgraded the `azuread` version from 1.2.2 to 2.10.0, after updating the azuread version, in the Terraform plan I got the following diff for my current AD application.

```
module.scale-set-agents-dev-ops-ad-application.azuread_application.ad_application will be updated in-place
  ~ resource "azuread_application" "ad_application" {
        id                             = "eefd183e-b750-4356-aa9e-ef9dda7da48b"
      ~ oauth2_permission_scope_ids    = {
          - "user_impersonation" = "df5995fd-88a2-4db7-8a45-d0460f0c92da"
        } -> (known after apply)
      ~ owners                         = [
          + "2075ede2-f555-41ac-8eb2-f842a9f9e3ad",
        ]
        tags                           = []
        # (13 unchanged attributes hidden)

      - api {
          - known_client_applications      = [] -> null
          - mapped_claims_enabled          = false -> null
          - requested_access_token_version = 1 -> null

          - oauth2_permission_scope {
              - admin_consent_description  = "Allow the application to access asgardeo-perf-scale-set-agents-ad-application on behalf of the signed-in user." -> null
              - admin_consent_display_name = "Access asgardeo-perf-scale-set-agents-ad-application" -> null
              - enabled                    = true -> null
              - id                         = "df5995fd-88a2-4db7-8a45-d0460f0c92da" -> null
              - type                       = "User" -> null
              - user_consent_description   = "Allow the application to access asgardeo-perf-scale-set-agents-ad-application on your behalf." -> null
              - user_consent_display_name  = "Access asgardeo-perf-scale-set-agents-ad-application" -> null
              - value                      = "user_impersonation" -> null
            }
        }

      - web {
          - redirect_uris = [] -> null

          - implicit_grant {
              - access_token_issuance_enabled = false -> null
              - id_token_issuance_enabled     = true -> null
            }
        }
        # (4 unchanged blocks hidden)
    }
```

When I apply these changes, I'm getting the follwoing error, 

```
Error: Could not disable OAuth2 Permission Scopes for application with object ID "eefd183e-b750-4356-aa9e-ef9dda7da48b"

  on .terraform/modules/scale-set-agents-dev-ops-ad-application/application.tf line 14, in resource "azuread_application" "ad_application":
  14: resource "azuread_application" "ad_application" {

disabling OAuth2 Permission Scopes for Application with object ID
"eefd183e-b750-4356-aa9e-ef9dda7da48b": ApplicationsClient.BaseClient.Patch():
unexpected status 403 with OData error: Authorization_RequestDenied:
Insufficient privileges to complete the operation.

```
I have already tried with assigning the `Application Administrator` and `Cloud Application Administrator` AD roles to my AD user. but still I'm getting the same error, Any thought on this ? Following are my AD app terraform configuration, really appreciate your help on this, thanks !

```
data "azuread_client_config" "client_config" {}

resource "azuread_application" "ad_application" {
  display_name                = join("-", [var.project, var.environment, var.app_name])
  owners                      = [data.azuread_client_config.client_config.object_id]
  lifecycle {
    create_before_destroy = true
  }
}
module "scale-set-agents-dev-ops-ad-application" {
  source      = "/home/uvindu/asgardio-prd/azure-terraform-modules/modules/azuread/Application"
  app_name    = var.scale_set_agents_dev_ops_ad_application_name
  environment = var.environment
  project     = var.project
}
````

**Comment by manicminer** [comment]
Hi @Uvindu96, thanks for reporting this and sorry you are experiencing this difficulty when upgrading the provider.

There are a few things to bear in mind when upgrading from a 1.x to 2.x release, these are covered in our [Upgrade Guide](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph). I note that in your diff the `user_impersonation` scope is set to be removed - you may wish to consider adding this to your configuration if you need it, as in 1.x releases this was implicit but in 2.x it must be explicitly configured.

In terms of permissions, unfortunately we can't help debug permissions beyond advising the generic directory and/or API roles that are needed. Although I do believe you should be able to make these changes having the `Application Administrator` role, you _may_ need to either (manually) add yourself as an owner of the application, or grant the `Global Administrator` role. Unfortunately, configurations and effective permissions do vary between tenants and also depend on whether you are a guest (invited) user or not (more details are available in the official documentation on [Azure AD roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference) and [effective default permissions](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/users-default-permissions)). I'm assuming that you're using Azure CLI authentication - if you are using service principal authentication then you'll need to configure new API roles for your application/service principal as detailed in our upgrade guide.

We use GitHub issues for tracking feature requests and bugs in the provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html) or in our community Slack group (details in the project readme). Accordingly I'm going to close this issue for now, but if you believe you have encountered a bug, please feel free to comment further with a [debug log](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing) and I'll be happy to look into this further. Thanks!
