### ISSUE TITLE
DelegatedPermissionGrantsClient.BaseClient.Post(): unexpected status 409 with OData error: Request_MultipleObjectsWithSameKeyValue: Permission entry already exists.

### ISSUE THREAD

**Issue by xplor-liviuelama** [hashicorp/terraform-provider-azuread#690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.10
+ provider registry.terraform.io/hashicorp/azuread v2.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.79.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tfe v0.26.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8

### Affected Resource(s)

* `azuread_service_principal_delegated_permission_grant`

### Terraform Configuration Files

input map
```hcl
well_known = {
  MicrosoftGraph = {
    scope = [
      "User.Read",
      "User.Read.All",
    ]
    role = [
      "User.Read.All",
      "Directory.Read.All",
    ]
  }
  AzureActiveDirectoryGraph = {
    scope = [
      "User.Read",
      "User.Read.All",
      "Directory.Read.All",
    ]
    role = [
      "Directory.Read.All",
    ]
  }
}
```

code:
```hcl
resource "azuread_service_principal_delegated_permission_grant" "well_known" {
  for_each = {
    for app in local.azuread_application_well_known_permission_grant : "${app.well_known}_${replace(app.permission, ".", "")}" => app if length(app) != 0 && app.type == "scope"
  }

  resource_service_principal_object_id = azuread_service_principal.well_known[each.value.well_known].object_id
  claim_values                         = [each.value.permission]
  service_principal_object_id          = azuread_service_principal.app[each.value.app].object_id
}
```

terraform plan output for the 3 resources that fail:
```hcl
# module.iam.azuread_service_principal_delegated_permission_grant.well_known["AzureActiveDirectoryGraph_DirectoryReadAll"] will be created
  + resource "azuread_service_principal_delegated_permission_grant" "well_known" {
      + claim_values                         = [
          + "Directory.Read.All",
        ]
      + id                                   = (known after apply)
      + resource_service_principal_object_id = "98c6fef9-4646-4e8d-8dde-14d1f120ddc9"
      + service_principal_object_id          = "76eb6d4b-ba45-4cda-a918-7dc2310dd3e0"
    }

  # module.iam.azuread_service_principal_delegated_permission_grant.well_known["AzureActiveDirectoryGraph_UserReadAll"] will be created
  + resource "azuread_service_principal_delegated_permission_grant" "well_known" {
      + claim_values                         = [
          + "User.Read.All",
        ]
      + id                                   = (known after apply)
      + resource_service_principal_object_id = "98c6fef9-4646-4e8d-8dde-14d1f120ddc9"
      + service_principal_object_id          = "76eb6d4b-ba45-4cda-a918-7dc2310dd3e0"
    }

  # module.iam.azuread_service_principal_delegated_permission_grant.well_known["MicrosoftGraph_UserReadAll"] will be created
  + resource "azuread_service_principal_delegated_permission_grant" "well_known" {
      + claim_values                         = [
          + "User.Read.All",
        ]
      + id                                   = (known after apply)
      + resource_service_principal_object_id = "f31b6f66-c3b0-40a4-b926-d6f2863aa2ed"
      + service_principal_object_id          = "76eb6d4b-ba45-4cda-a918-7dc2310dd3e0"
    }
```

### Debug Output

debug for the 3 resources that fail: https://gist.github.com/xplor-liviuelama/a088d3f06d88ff9c3b1f57f538d033f7

### Expected Behavior

The expectation is to create 5 delegated permission grants as per the input

### Actual Behavior

Only 2 grants are executed and the other 3 are failing with the error from the title.
To confirm they don't exist this is the output from cli:
az ad app permission list-grants --id 76eb6d4b-ba45-4cda-a918-7dc2310dd3e0
[
  {
    "clientId": "76eb6d4b-ba45-4cda-a918-7dc2310dd3e0",
    "consentType": "AllPrincipals",
    "expiryTime": "9999-12-31T23:59:59.9999999",
    "objectId": "S23rdkW62kypGH3CMQ3T4Pn-xphGRo1Ojd4U0fEg3ck",
    "odatatype": null,
    "principalId": null,
    "resourceId": "98c6fef9-4646-4e8d-8dde-14d1f120ddc9",
    "scope": "User.Read",
    "startTime": "0001-01-01T00:00:00"
  },
  {
    "clientId": "76eb6d4b-ba45-4cda-a918-7dc2310dd3e0",
    "consentType": "AllPrincipals",
    "expiryTime": "9999-12-31T23:59:59.9999999",
    "objectId": "S23rdkW62kypGH3CMQ3T4GZvG_Oww6RAuSbW8oY6ou0",
    "odatatype": null,
    "principalId": null,
    "resourceId": "f31b6f66-c3b0-40a4-b926-d6f2863aa2ed",
    "scope": "User.Read",
    "startTime": "0001-01-01T00:00:00"
  }
]

and how it looks like in Azure AD:
![image](https://user-images.githubusercontent.com/87041909/144528305-24af3e81-144a-48f1-8d37-857352e9465b.png)

### Steps to Reproduce

1. Nothing special, just follow the resource documentation

### References

* #681  -  this might be related but not sure. I'm not even seeing the resource so I can't try to import.

**Comment by manicminer** [comment]
Hi @xplor-liviuelama, thanks for raising this. I believe the reason you're seeing a 409 error is because each delegated permission grant represents the scopes for a unique set comprising the service principal, the resource service principal, and the user(s) for which the grant is given. In other words, rather than creating a grant for each scope, you'll need to create a single grant per service principal containing all the scopes being granted.

i.e. going from this:

```hcl
resource "azuread_service_principal_delegated_permission_grant" "well_known" {
  for_each = {
    for app in local.azuread_application_well_known_permission_grant : "${app.well_known}_${replace(app.permission, ".", "")}" => app if length(app) != 0 && app.type == "scope"
  }

  resource_service_principal_object_id = azuread_service_principal.well_known[each.value.well_known].object_id
  claim_values                         = [each.value.permission]
  service_principal_object_id          = azuread_service_principal.app[each.value.app].object_id
}
```

to this:

```hcl
resource "azuread_service_principal_delegated_permission_grant" "well_known" {
  resource_service_principal_object_id = azuread_service_principal.well_known[each.value.well_known].object_id
  claim_values                         = [for app in local.azuread_application_well_known_permission_grant : app.permission if length(app) != 0 && app.type == "scope"]
  service_principal_object_id          = azuread_service_principal.app[each.value.app].object_id
}
```

which should yield a plan that looks more like this:

```shell
Terraform will perform the following actions:

  # azuread_service_principal_delegated_permission_grant.test will be created
  + resource "azuread_service_principal_delegated_permission_grant" "well_known" {
      + claim_values                         = [
          + "Directory.AccessAsUser.All",
          + "Directory.Read.All",
          + "Directory.ReadWrite.All",
          + "Group.Read.All",
          + "Group.ReadWrite.All",
          + "Member.Read.Hidden",
          + "Policy.Read.All",
          + "User.Read",
          + "User.Read.All",
          + "User.ReadBasic.All",
        ]
      + id                                   = (known after apply)
      + resource_service_principal_object_id = "3f1aea63-01f0-4a1e-aa17-0a997ae8caa1"
      + service_principal_object_id          = "9e9707ca-429d-465d-adc0-4ad7400ccdb3"
    }
```

In the approach you've described, a grant assignment is likely being created for the first scope for a given service principal / resource service principal combination, with a 409 being returned for the other scopes. It should work if you ensure that all the scopes are in the same grant. Hope this helps!

**Comment by xplor-liviuelama** [comment]
hey @manicminer. Thanks for the direction. That has solve the problem indeed. I had to modify my locals to manipulate the data i needed and pass a list to the claim_values. Pretty easy since I already had it in a list, just a matter of splitting delegated grants vs application grants (this one does want a grant at a time).
