### ISSUE TITLE
Ability to use OIDC federated credentials

### ISSUE THREAD

**Issue by ndrone-kr** [hashicorp/terraform-provider-azuread#691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_application_federated
* azuread_service_principal_federated

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Satak** [comment]
This would be great addition indeed and adds lot of security in Azure. Please implement.

**Comment by chrisst** [comment]
I just set up a federated credential against a azuread_application that is already managed with Terraform, so I think you will only need the `azuread_service_principal_federated ` resource

API reference: https://docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta
Other relevent docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
