### ISSUE TITLE
make tools fails on darwin/arm64

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-azuread#694]
Following the instructions on developing the provider, the first step- `make tools` failed on darwin/arm64 on a fresh clone:

```
$ make tools
==> installing required tooling...
...
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH || $GOPATH)"/bin v1.32.0
golangci/golangci-lint info checking GitHub for tag 'v1.32.0'
golangci/golangci-lint info found version: 1.32.0 for v1.32.0/darwin/arm64
make: *** [tools] Error 1
```

I fixed this by upgrading `golangci` to the lastest version on https://github.com/hashicorp/terraform-provider-azuread/pull/693

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gtmtech** [comment]
#693  is now merged, will close

**Comment by manicminer** [comment]
Sorry, happy trigger finger on my part there :D
