### ISSUE TITLE
Support external email for mail enabled groups

### ISSUE THREAD

**Issue by andyshinn** [hashicorp/terraform-provider-azuread#719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to support creating mail enabled groups that allow external email as shown in the image.

![image](https://user-images.githubusercontent.com/315485/150011953-129bd9de-e6e8-4c07-92a8-9304335a35d7.png)

### New or Affected Resource(s)

* azuread_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azuread_group" "my_mail_group" {
  display_name       = "My Mail Group"
  mail_enabled       = true
  mail_nickname      = "my-mail-group"
  types              = ["Unified"]
  visibility         = "Private"
  external_senders = true

  behaviors = ["WelcomeEmailDisabled", "SubscribeNewGroupMembers"]

  members = ["713748e0-1f3b-4582-96cc-5ea0a9f647ca",]
  owners = ["713748e0-1f3b-4582-96cc-5ea0a9f647ca",]
}
```

### References

The API appears to support this at https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http as the `allowExternalSenders` request body parameter.

**Comment by manicminer** [comment]
Hi @andyshinn, many thanks for requesting this feature. It looks like this should be a straightforward addition, I'll take a look at adding this soon.

**Comment by andyshinn** [comment]
Super dope. Really quick turn around. Thanks for making Azure AD easy to work with through automation :)

**Comment by andyshinn** [comment]
Dang, it looks like this doesn't actually work via the API. On https://docs.microsoft.com/en-us/graph/known-issues#groups it mentions:

> There is currently an issue that prevents setting the allowExternalSenders property of a group in a POST or PATCH operation, in both /v1.0 and /beta.

Any idea if there is a public issue tracking this that can be followed or any other information on it?

**Comment by manicminer** [comment]
Hi @andyshinn, can you confirm where you are looking to verify the setting (i.e. the source of the screenshot in your original message)?

I've tried it out now, and accounting for some delay since changes to Azure AD are not synchronous, the setting appears to work for me? After setting `external_senders_allowed = true` using Terraform, the API returns the correct setting and it's also reflected in the M365 Admin Center - see the following screenshots.

![Screenshot 2022-01-30 at 22 08 57](https://user-images.githubusercontent.com/251987/151719986-eb810efe-124c-44ba-9c97-f5df677abf82.png)

![Screenshot 2022-01-30 at 22 09 33](https://user-images.githubusercontent.com/251987/151719992-7ba818ab-80f5-4091-99da-0f1dfcf00a79.png)

**Comment by andyshinn** [comment]
Interesting. I am getting a 403. Maybe it is a specific permission required? I have the following API permissions for the application:

- Group.Create
- Group.Read.All
- Group.ReadWrite.All
- GroupMember.Read.All
- User.Read.All

**Comment by manicminer** [comment]
Ah, alas these new properties for unified groups are only supported with delegated authentication - which for the TF provider translates to Azure CLI authentication. They unfortunately don't work when authenticating with app roles (i.e. as a service principal).

I don't know if/when this will get fixed, nor whether these's a public issue tracking this, but I will try to raise it with the service team at my next opportunity.
