### ISSUE TITLE
azuread_service_principal_password special characters

### ISSUE THREAD

**Issue by maxarndt** [hashicorp/terraform-provider-azuread#720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have multiple dev teams with lots of pipelines using Azure services like Container Registries and AKS for CI/CD purpose. The pipelines use service principals to authenticate which are managed with this Terraform provider. 
The last time new passwords have been created for our service principals some pipelines failed in their next run. The reason has been that for the first time password were starting with a `-` character. This is of course a problem in the way the pipelines were written. Nearly every pipeline seen uses a syntax like `az login --service-principal -p "$someVar" -u "foo" -t "bar"` which exits with an error if the value of the variable starts with a `-`  because `az` interprets it as an additional parameter. I'm aware that fixing the syntax in all of our pipelines would solve this issue but unfortunately this is a really cumbersome job in a distributed environment.
But because in our case we are centrally managing the service principal generation and distribution I wonder if a feature like _don't use special characters in general_ or _don't let password start with a `-`_ could be implemented?

It looks like [Microsoft Graph API (servicePrincipal: addPassword)](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-1.0&tabs=http) is used to set and obtain a new password:
https://github.com/hashicorp/terraform-provider-azuread/blob/75c017a1c0d61d9a30d359b155e7a639eff1f777/vendor/github.com/manicminer/hamilton/msgraph/serviceprincipals.go#L401

But the API doesn't seem to offer such an option. 
What looks weird is that passwords have been generated where e.g. 4 out of the first 6 digits are identically with another password generated in the same run. But that's probably not an issue of this Terraform provider.

Does anyone has thoughts on this issue?

We currently use `v2.11.0` of this provider.

### New or Affected Resource(s)

* azuread_service_principal_password

### Potential Terraform Configuration

```hcl
resource "azuread_service_principal_password" "example" {
  service_principal_id = azuread_service_principal.example.object_id
  password_contains_special_chars = false
}
```

**Comment by manicminer** [comment]
Hi @maxarndt, thanks for raising this. As you noted, it's no longer possible to have any control over client secrets / password credentials for applications or service principals, as these are now generated by the API with no option to affect the complexity.

This has had a few side effects as generated passwords are occasionally incompatible with existing scripts, or at time even with other Azure services. Unfortunately, there is nothing we can do to alleviate this and this is entirely within the control of the API. As you indicated, updating scripts to accommodate and/or escape special chars is now the only way to reliably handle these passwords.

Accordingly, as there is unfortunately nothing we can do here, I'm going to close this for now. You might want to consider raising a support ticket or feature request directly with Azure although I suspect working around this will be your fastest way forward. Thanks again for raising this.
