### ISSUE TITLE
azuread_conditional_access_policy - included_platforms = ["unknownFutureValue"] - BadRequest: 1007: Incoming ConditionalAccessPolicy object is null or does not match the schema of ConditionalAccessPolicy type

### ISSUE THREAD

**Issue by ithahn** [hashicorp/terraform-provider-azuread#730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.16.0
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0

### Affected Resource(s)

azuread_conditional_access_policy

### Terraform Configuration Files

```
resource "azuread_conditional_access_policy" "deny-blocked-countries" {
  display_name = "DENY BLOCKED COUNTRIES"
  state        = "disabled"

  conditions {
    client_app_types    = ["browser", "mobileAppsAndDesktopClients"]

    applications {
      included_applications = ["All"]
    }

    locations {
      included_locations = [azuread_named_location.blocked-countries.id]
    }

    platforms {
      included_platforms = ["unknownFutureValue"]
    }

    users {
      included_users = ["GuestsOrExternalUsers"]
    }
  }

  grant_controls {
    operator          = "OR"
    built_in_controls = ["block"]
  }
}
```

### Debug Output

 Error: Could not update conditional access policy with ID: "xxxxxxxx"
│
│   with azuread_conditional_access_policy.deny-blocked-countries,
│   on deny-blocked-countries.tf line 1, in resource "azuread_conditional_access_policy" "deny-blocked-countries":
│    1: resource "azuread_conditional_access_policy" "deny-blocked-countries" {
│
│ ConditionalAccessPoliciesClient.BaseClient.Patch(): unexpected status 400 with OData error: BadRequest: 1007: Incoming ConditionalAccessPolicy object is null or does not match the schema of ConditionalAccessPolicy type.
│ For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-1.0.

### Expected Behavior

The use of unknownFutureValue on included_platforms should leave it unconfigured in the ca policy.

### Actual Behavior

unknownFutureValue is not accepted.

### Steps to Reproduce

Use the code above. It will fail on new creation of a ca policy as well as on an update of exisiting ca policy.

**Comment by manicminer** [comment]
Hi @ithahn, thanks for raising this. I have been able to reproduce this error and this unfortunately looks to be an API bug rather than a bug in the provider. I would suggest raising this in an Azure support ticket or via any account contacts you may have, as this behavior is contrary to the service documentation. Accordingly, as there is nothing for us to do right now, I'm going to close this one as an upstream issue. Thanks again for reporting this.
