### ISSUE TITLE
Add azuread_service_principal_token_signing_certificate to simplify certificate management

### ISSUE THREAD

**Issue by dhohengassner** [hashicorp/terraform-provider-azuread#732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure API provides a method (addTokenSigningCertificate) to create a self signed certificate for a service principal: https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api#create-a-signing-certificate

This option avoids managing a certificate by yourself and is currently not supported via terraform.

### New or Affected Resource(s)

* azuread_service_principal_token_signing_certificate

### References

https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api#step-4-configure-a-signing-certificate

This is a different request than https://github.com/hashicorp/terraform-provider-azuread/issues/410 because I do not want to manage the certificate myself.

**Thanks for your feedback!**

**Comment by manicminer** [comment]
Hi @dhohengassner, thanks for requesting this feature! Looking through the linked walkthrough, it looks like a few additional pieces are needed here?

- New resource for token signing certificates
- New resource for claims mapping policies (a community member is already working on this)
- Support for the preferredTokenSigningKeyThumbprint field for service principals

Does this look right to you?

**Comment by dhohengassner** [comment]
@manicminer thanks that is exactly what I had in mind :+1: 

I will try to come up with PRs for that. Thanks for the feedback

**Comment by dhohengassner** [comment]
created a PR to add support for the preferredTokenSigningKeyThumbprint field for service principals

https://github.com/manicminer/hamilton/pull/151

**Comment by dhohengassner** [comment]
@manicminer Experimented today with certification creation on service principal.

It seems the Graph API supports adding a certificate but there is no option to remove them. I can see the generated keys and passwords but I cannot remove them via `removePassword` or `removeKey` calls. In case `addtokensigningcertificate` is called it will add a new cert to the principal.

Ref: https://docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate

I am able to remove the certs on Enterprise apps but this is using a different internal API.

Therefore I would suggest not create an own terraform resource for that feature. Instead use an optional field on the `azuread_service_principal` called `token_signing_certificate_name`. If a name is set it will create a cert and update the `preferred_token_signing_key_thumbprint` computed field of the resource. `token_signing_certificate_name` would be a ForceNew field to avoid creating multiple certificates in case of an update.

Does that make sense for you? Or do you prefer having a seperate resource for the created certificate.

**Comment by manicminer** [comment]
Hi @dhohengassner, thanks for looking into it. That's unfortunate - using ForceNew as a workaround on the service_principal resource may be an option, but I'd like to reach out first and find out whether that API might be expanded with full CRD support that we can make a proper resource of it.

**Comment by dhohengassner** [comment]
Hey @manicminer good idea!
I will create a PR with the workaround using ForceNew as temp solution I can test.

So I understood right that you will contact Microsoft to ask for a new API feature?
Thank you for all the help with that!

**Comment by dhohengassner** [comment]
@manicminer this PR should be ready for a review.

Is there anything missing?  
Thanks

**Comment by NEViLLLLL** [comment]
Is it planned to add this functionality?
