### ISSUE TITLE
Feature parity between data service_principal and service_principals

### ISSUE THREAD

**Issue by gkman** [hashicorp/terraform-provider-azuread#735]
I can provide more info upon request. It becomes an issue when getting back `data.azuread_service_principals` gives me back very different data and in a very different format than a call to `data.service_principal` especially in the case of something like `object_id` which is often the reason for doing a data lookup to begin with.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @gkman, thanks for requesting this! Could you elaborate a little on the fields that might be missing from either the data source or the resource?

For `object_id`, this should be set correctly for both the ads and the resource - the only difference is that the day source allows this to also be set by the user as a way of identifying the service principal to look up.

There are in fact a few differences like this between the data source and the resource. These are out of necessity, for example there are cases where we must use a Set instead of a List in the resource, but doing the same in the data source would reduce its functionality.

**Comment by manicminer** [comment]
Apologies, I seem to have misread your message - I see you're asking about `data.service_principal` vs `data.service_principals`. Any further info you could provide would be great, thanks!

**Comment by gkman** [comment]
## Premise for work

Sure sure, let me also give you my situation that makes me even care. So I work with a few teammates and we write modules for our SWEs to use, and we try to write them in a steamlined enough way that they have as little to worry and know about `terraform` or the providers as possible. So we wrote and AD lookup module that accepts a list of `"principal_names"` and we do a data look up on `azuread_groups`, `azuread_service_principals`, and `azuread_users` with the `return_all = true` with the idea that we `setintersect` the returns against the variable list passed into our module, and we build a custom map on any that have no match. The output from our module allows users to be able to not have to do as much work finding `principal_id` or `object_id` of whatever they want to do `role_assignments` on whether that be for a service with its own RBAC or with one using AzureAD RBAC.

## Feature reasoning

Well in this way when we do a `azuread_service_principals` lookup we get back something like:

```hcl
data "azuread_service_principals" "self" {
  return_all = true
}

{
  "application_ids" = tolist([
    "9e133cac-5238-4d1e-aaa0-d8ff4ca23f4e",
    "4fbc3d67-18e4-4d5c-aba9-9db70cb68702",
    ...
  ])
  "display_names" = tolist([
    "Conferencing Virtual Assistant",
    "Microsoft Approval Management",
    ...
  ])
  "id" = "serviceprincipals#dzH1zN2wWxK9aw9rnnH7btdXCKE="
  "ignore_missing" = false
  "object_ids" = tolist([
    "000ca5ac-d71a-410d-b666-0ad1c49f439b",
    "001180c1-56ac-4683-b5e8-52050a3c1d3d",
    ...
  ])
  "return_all" = true
  "service_principals" = tolist([
    {
      "account_enabled" = true
      "app_role_assignment_required" = false
      "application_id" = "9e133cac-5238-4d1e-aaa0-d8ff4ca23f4e"
      "application_tenant_id" = "f8cdef31-a31e-4b4a-93e4-5f571e91255a"
      "display_name" = "Conferencing Virtual Assistant"
      "preferred_single_sign_on_mode" = ""
      "saml_metadata_url" = ""
      "service_principal_names" = tolist([])
      "sign_in_audience" = "AzureADMultipleOrgs"
      "tags" = tolist([])
      "type" = "Application"
    },
    {
      "account_enabled" = true
      "app_role_assignment_required" = false
      "application_id" = "65d91a3d-ab74-42e6-8a2f-0add61688c74"
      "application_tenant_id" = "f8cdef31-a31e-4b4a-93e4-5f571e91255a"
      "display_name" = "Microsoft Approval Management"
      "preferred_single_sign_on_mode" = ""
      "saml_metadata_url" = ""
      "service_principal_names" = tolist([
        "https://approvalmanagement.activedirectory.windowsazure.com",
        "65d91a3d-ab74-42e6-8a2f-0add61688c74/approvalmanagement.activedirectory.windowsazure.com",
      ])
      "sign_in_audience" = "AzureADMultipleOrgs"
      "tags" = tolist([])
      "type" = "Application"
    },
  ]
}
```

By comparison when we do a single lookup we get back something like this

```hcl
data "azuread_service_principal" "self" {
  display_name = "company-app"
}

"company-app" = {
  "account_enabled" = true
  "alternative_names" = tolist([])
  "app_role_assignment_required" = false
  "app_role_ids" = tomap({})
  "app_roles" = tolist([])
  "application_id" = "REDACTED ID"
  "application_tenant_id" = "REDACTED ID"
  "description" = ""
  "display_name" = "company-app"
  "feature_tags" = tolist([
    {
      "custom_single_sign_on" = false
      "enterprise" = false
      "gallery" = false
      "hide" = false
    },
  ])
  "features" = tolist([
    {
      "custom_single_sign_on_app" = false
      "enterprise_application" = false
      "gallery_application" = false
      "visible_to_users" = true
    },
  ])
  "homepage_url" = ""
  "id" = "REDACTED ID"
  "login_url" = ""
  "logout_url" = ""
  "notes" = ""
  "notification_email_addresses" = tolist([])
  "oauth2_permission_scope_ids" = tomap({})
  "oauth2_permission_scopes" = tolist([])
  "object_id" = "REDACTED ID"
  "preferred_single_sign_on_mode" = ""
  "redirect_uris" = tolist([])
  "saml_metadata_url" = ""
  "saml_single_sign_on" = tolist([])
  "service_principal_names" = tolist([])
  "sign_in_audience" = "AzureADMyOrg"
  "tags" = tolist([])
  "timeouts" = null /* object */
  "type" = "Application"
  }
```

I have no expectation for `data.azuread_service_principals` to return exactly what `data.azure_group` does, but in the list of `service_principal` objects return for `data.azuread_service_principals` I would expect it to contain `object_id` since that is the primary value for handling RBAC assignments.

Now to be clear I have come up with a fun work around which gets the job done, but it would be pretty nice to just be able to use the power that is already in the `data.azuread_service_principals`.

```hcl
data "azuread_service_principals" "self" {
  return_all = true
}

data "azuread_service_principal" "self" {
  for_each = setintersection(data.azuread_service_principals.self.display_names, var.principal_names)

  display_name = each.key
}
```

As a side note, this issue exists in `data.azuread_groups` as well. But I figured I would see what you all think about one example before hitting you with several requests. I also would totally understand if the API usage under the hood makes my request somewhat unreasonable or upstream limited. Hope this helps, happy to either get more detailed or be more step by step specific.

**Comment by manicminer** [comment]
@gkman That's great, thanks so much for clarifying! I hadn't realized that `object_id` was left out of the results object in these data sources. We can definitely add `object_id`, and potentially other important fields where they make sense. You are correct however, it's not feasible to include every field as per the singular data source equivalent, as it could feasibly snowball for someone looking up a very large list of objects.

**Comment by gkman** [comment]
@manicminer just having those keys things in the map like the `object_id` will be a tremendous improvement to me so that's all good!

**Comment by gkman** [comment]
@manicminer thanks again!
