### ISSUE TITLE
Support identity synchronization/provisioning

### ISSUE THREAD

**Issue by AndreasSko** [hashicorp/terraform-provider-azuread#744]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to configure [AzureAD Synchronization](https://docs.microsoft.com/en-us/graph/api/resources/synchronization-overview?view=graph-rest-beta) via Terraform. Adding the necessary secret and creating a job would already be enough for our use case. 
I would be happy to work in this if the idea looks good :slightly_smiling_face: 

### New or Affected Resource(s)

* azuread_synchronization_job
* azuread_synchronization_secret

This could potentially be extended with data sources for templates and schemas, but I think those two resources should already provide a good basis.

### Potential Terraform Configuration

```hcl
resource "azuread_synchronization_secret" "this" {
  service_principal_id = azuread_service_principal.this.id

  credentials {
    key   = "BaseAddress"
    value = "user@domain.com"
  }
  credentials {
    key   = "SecretToken"
    value = "password-value"
  }
}

resource "azuread_synchronization_job" "this" {
  service_principal_id = azuread_service_principal.this.id
  template_id          = "BoxOutDelta"
  state                = "paused" 
}
```

#### Graph API Endpoints:
* [Synchronization](https://docs.microsoft.com/en-us/graph/api/resources/synchronization-overview?view=graph-rest-beta)
* [Add Secret](https://docs.microsoft.com/en-us/graph/api/synchronization-synchronization-secrets?view=graph-rest-beta)
* [Job](https://docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjob?view=graph-rest-beta)

**Comment by JoostvDoorn** [comment]
I'll be able to work on this, we use this to automatically provision the Azure Databricks SCIM Provisioning Connector. I'll pick this up in a few days.
