### ISSUE TITLE
Azure AD: Service principal reply and identifier url feature needed

### ISSUE THREAD

**Issue by saran-fadv** [hashicorp/terraform-provider-azuread#746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Threpio** [comment]
I believe that these two data points are within the resource already. Can this be closed?

Is it that this is not found in the data source and that is what is needed to be added?

**Comment by manicminer** [comment]
@saran-fadv Please can you confirm if you're looking to configure these values, or look them up (i.e. reference them). If the latter, as @Threpio mentions we already support these attributes on both the resource and data source for service principals.

**Comment by manicminer** [comment]
I'm going to close this one out due to inactivity. If there is continued interest in this request, please feel free to reply and we'll happily re-open it, but at this time there's unfortunately not enough information to proceed with a feature request. Thanks!
