### ISSUE TITLE
Occasionally azuread_service_principal_delegated_permission_grant unexptected status 404

### ISSUE THREAD

**Issue by dvdvorle** [hashicorp/terraform-provider-azuread#748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

- terraform 1.1.5
- azuread 2.17.0

### Affected Resource(s)

* `azuread_service_principal_delegated_permission_grant`

### Terraform Configuration Files

```hcl
resource "azuread_service_principal_delegated_permission_grant" "fusionshell_ms_graph" {
  service_principal_object_id          = azuread_service_principal.socrates_fusionshell_v2.object_id
  resource_service_principal_object_id = data.azuread_service_principal.msgraph.object_id
  claim_values                         = [local.microsoft_graph.scopes.openid.value, local.microsoft_graph.scopes.offline_access.value]
}

```

### Debug Output

```hcl
 # module.authentication.module.b2c[0].azuread_service_principal_delegated_permission_grant.fusionshell_ms_graph will be created
  + resource "azuread_service_principal_delegated_permission_grant" "fusionshell_ms_graph" {
      + claim_values                         = [
          + "offline_access",
          + "openid",
        ]
      + id                                   = (known after apply)
      + resource_service_principal_object_id = "a81e0a33-f5ab-4b03-a47a-a61b670d2530"
      + service_principal_object_id          = (known after apply)
   }

... snip ...

╷
│ Error: Retrieving Delegated Permission Grant with ID "Mw6NLRPyi0mhEqkR5spv1jMKHqir9QNLpHqmG2cNJTA"
│ 
│   64: resource "azuread_service_principal_delegated_permission_grant" "fusionshell_ms_graph" {
│ 
│ DelegatedPermissionGrantsClient.BaseClient.Get(): unexpected status 404
│ with OData error: Request_ResourceNotFound: Resource
│ 'Mw6NLRPyi0mhEqkR5spv1jMKHqir9QNLpHqmG2cNJTA' does not exist or one of its
│ queried reference-property objects are not present.
╵

```

### Expected Behavior

Not an error

### Actual Behavior

Error, retry fixed it.

### Steps to Reproduce

Hard to reproduce.

**Comment by manicminer** [comment]
Hi @dvdvorle, thanks for reporting this. I believe this is a consistency related bug, related to #699. We should hopefully be able to implement a workaround for this.

**Comment by manicminer** [comment]
@dvdvorle If you are able to try and reproduce this (I understand that's tough given the intermittent behavior) and capture the failure in a [debug log](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing), that would be super helpful in determining where and how this error happens. Thanks!

**Comment by dvdvorle** [comment]
Thanks @manicminer, I've added logging to our CI/CD. Hopeful I'll be able to provide you with a debug log.

Appreciate the work you do 👍

**Comment by dvdvorle** [comment]
So far it hasn't happened again, but still monitoring.

**Comment by dvdvorle** [comment]
Hi, I haven't been able to reproduce this. We'll keep the logs enabled but will stop actively looking for this particular error in failed runs.
