### ISSUE TITLE
conditional access custom controls (Preview)

### ISSUE THREAD

**Issue by rismoney** [hashicorp/terraform-provider-azuread#751]
Is it possible to configure this through terraform, even through a workaround?  I believe it is simply a JSON document.   I didn't see anything in this provider to accomplish that.  

Thanks for any insight!

**Comment by manicminer** [comment]
Hi @rismoney, thanks for the query. Custom Controls for Conditional Access are not supported in the provider at this time. There is no public API for this as Microsoft has not made this feature available outside of the Azure Portal. Please feel free to open a feature request using our issue template if you'd like this to be added to the provider once API support is made available. Thanks!
