### ISSUE TITLE
Scope/Role validation for magic string "User" is wrong

### ISSUE THREAD

**Issue by mickeder** [hashicorp/terraform-provider-azuread#755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.19.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "random_uuid" "test" {}

resource "azuread_application" "test" {
  display_name     = "test"
  sign_in_audience = "AzureADMyOrg"

  app_role {
    allowed_member_types = ["User"]
    description          = "Test"
    display_name         = "Test"
    id                   = random_uuid.test.result
    enabled              = true
    value                = "User"
  }
}
```

### Panic Output

```
│ Error: Value cannot have the string value "User"
│ 
│   with azuread_application.test,
│   on azuread.tf line 121, in resource "azuread_application" "test":
│  121: resource "azuread_application" "test" {
```

### Expected Behavior

No issues with deploying `azuread_application` with `app_role.value` set to "User".

### Actual Behavior

Provider versions prior to v2.19.0 worked fine, now the scope/role validation for magic string "User" makes it impossible to deploy resources which were perfectly fine before...

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

@manicminer There is **NO error** when creating App role with value "User" in Azure Portal. However, the issue reported in #721 is reproducible when trying to create a second App role with **the same value** (doesn't matter if it's "User" or "Cow" or whatever). My guess is the root cause of #721 was someone adding App role with value "User" manually in Azure Portal, and then trying to add the same role with Terraform...
Furthermore, [official Microsoft documentation](https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-beta#properties) does not show any evidence of "magic strings".

### References

* #721

**Comment by manicminer** [comment]
@mickeder Thanks for reporting, we'll issue a hotfix shortly.

**Comment by StefanSchoof** [comment]
Okay, this is curios. I can still reproduce this in the affected app. Portal and tf brings the same error.

But on a new created app, I can use "User". Looks like my app is somehow damaged.

Sorry, that I did not double checked and caused you this trouble. 😞
