### ISSUE TITLE
empty saml_metadata_url of azuread_service_principal

### ISSUE THREAD

**Issue by igory-bwr** [hashicorp/terraform-provider-azuread#758]
Hi guys
I've deployed an AzureAD application and trying to get saml_metadata_url as output for a further federation. But it's provided with empty string value. What did I do wrong? 

```
resource "azuread_application" "this" {
  display_name    = local.app_name
  ...
}

resource "azuread_service_principal" "this" {
  application_id = azuread_application.this.application_id
}

output "saml_metadata_url" {
  value = azuread_service_principal.this.saml_metadata_url
}
```
I'd be appreciated to any ideas. 
BR

**Comment by isarns** [comment]
My workaround for that:
`output "metadata_url" {
    value = "https://login.microsoftonline.com/${var.tenant_id}/federationmetadata/2007-06/federationmetadata.xml?appid=${azuread_service_principal.this.application_id}"
}`

**Comment by igory-bwr** [comment]
@isarns Oh, yeah... Thanks a lot! I have just updated `${var.tenant_id}` with `${azuread_service_principal.this.application_tenant_id}` and it works well.

**Comment by manicminer** [comment]
Hi, thanks for reporting this. Most of the attributes for a service principal, including this one, are populated by the API and we have no direct control over the value. I've tried a few different configurations and have found the same thing, that `saml_metadata_uri` is empty. I'm not certain of the exact configuration or logic that would cause this to be populated, however this is a config and/or API issue and accordingly I'm going to close this for now. If there is some handling within the provider that is not working as expected for this property, please let us know and we can re-open the issue for a deeper look. Thanks!
