### ISSUE TITLE
Data Source: azuread_service_principal lookup by display_name has no support for duplicate display_names

### ISSUE THREAD

**Issue by JelleBroekhuijsen** [hashicorp/terraform-provider-azuread#761]
When using the code below the output only shows one of the 2 service principals in my tenant. Both principals have the same `display_name`. The datasource does not provide any hint or warning that multiple results exist. The datasource `azuread_service_principals` does have this support (it shows an error when multiple principals with the same `display_name` exist). 

```terraform
# Configure Terraform
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.15.0"
    }
  }
}

# Configure the Azure Active Directory Provider
provider "azuread" {
  tenant_id = "14fd3200-****-****-****-150a95ddb6c4"
}

provider "azurerm" {
  features {}
}

data "azuread_service_principal" "example" {
  display_name = "some-service-principal"
}

output "test" {
    value = data.azuread_service_principal.example.application_id
}
```

**Comment by manicminer** [comment]
Hi @JelleBroekhuijsen, thanks for raising this. The error is raised by design, if we were to simply pick one of the matching principals there would be a lack of consistency between refreshes as you could not guarantee the same one would be chosen each time. In this scenario you'd need to look up the principal by another unique attribute; either the object ID or application/client ID. Do you think there is a better way to handle this?

**Comment by JelleBroekhuijsen** [comment]
@manicminer I'm unsure if you read my issue correctly or maybe I'm misunderstanding you. There are 2 providers: `azuread_service_principal` and `azuread_service_principals`. The 2nd does indeed throw an error when multiple instances of the same `display_name` exist however the 1st (`azuread_service_principal`) does not notify the user of the existence of multiple instances of the service principal with the same `display_name`. It's the inconsistency between these providers and the lack of notification that is the issue.

**Comment by manicminer** [comment]
@JelleBroekhuijsen Thanks for the clarification, that makes sense. The `azuread_service_principal` (singular) data source should be throwing an error in that case. I'll look into it and issue a fix where necessary.
