### ISSUE TITLE
AzureAD Government Cloud - Wrong graph URL

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform-provider-azuread#764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.1.7
on linux_amd64

### Affected Resource(s)

* `data "azuread_user"`

### Terraform Configuration Files

```hcl
provider "azuread" {
  alias           = "ad"
  subscription_id = var.subscription_id
  use_microsoft_graph = true
  environment = "usgovernmentl4"
}

data "azuread_user" "synapse_aad_admin" {
  count = length(var.synapse_aad_admin_user) > 0 ? 1 : 0

  user_principal_name = var.synapse_aad_admin_user
}
```

### Debug Output
```
│ Error: Retrieving user with object ID: "627ccf7e-e17e-44a7-84f9-87031d60dea9"
│
│   with data.azuread_user.synapse_aad_admin[0],
│   on users.tf line 1, in data "azuread_user" "synapse_aad_admin":
│    1: data "azuread_user" "synapse_aad_admin" {
│
│ UsersClient.BaseClient.Get(): Get "https://graph.microsoft.com/beta//users/627ccf7e-e17e-44a7-84f9-87031d60dea9": http: RoundTripper implementation (*retryablehttp.RoundTripper) returned a nil
│ *Response with a nil error
```

### Expected Behavior

Wrong graph url is used based on the azuread provider "environment" being set to usgovernmentl4.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

az cloud show
"management": "https://management.core.usgovcloudapi.net/",
"mediaResourceId": "https://rest.media.usgovcloudapi.net",
**"microsoftGraphResourceId": "https://graph.microsoft.us/",**

### References

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/microsoft-graph#authentication-and-national-clouds
https://devblogs.microsoft.com/microsoft365dev/new-microsoft-graph-endpoints-in-us-government-cloud/

**Comment by rohrerb** [comment]
These are the providers we are using:

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.19.1
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

I removed the two properties and the same error exists for azuread.

```
│ UsersClient.BaseClient.Get(): Get "https://graph.microsoft.com/beta//users?%24filter=userPrincipalName+eq+%27brrohrer%27": http: RoundTripper implementation (*retryablehttp.RoundTripper) returned a    
│ nil *Response with a nil error```

**Comment by manicminer** [comment]
@rohrerb Please can you post a reproducible configuration and I'll be happy to look into it further. The config above is for an earlier version of the provider and if I attempt to repro this with my own minimal config, it works as expected. Thanks!

**Comment by ieelleme** [comment]
Did you set an environment variable to usgovernment?

I was having this issue, set the environment variable, re-init, and it worked for me.
`$env:ARM_ENVIRONMENT="usgovernment"`

Terraform version = "v1.1.8"
azuread version = "= 2.20.0"

Reference: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs
See "Argument Reference"
