### ISSUE TITLE
Cannot create Conditional Access Policy with platform linux

### ISSUE THREAD

**Issue by soohonlee** [hashicorp/terraform-provider-azuread#777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.1.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.21.0

### Affected Resource(s)

* `azuread_conditional_access_policy`

### Terraform Configuration Files

```hcl
resource "azuread_conditional_access_policy" "block_unknown_platforms" {
  display_name = "block access when using using unknown platforms"

  conditions {
    users {
      included_users  = ["All"]
    }

    applications {
      included_applications = ["All"]
    }

    locations {
      included_locations = ["All"]
    }

    platforms {
      included_platforms = ["all"]
      excluded_platforms = [
        "android",
        "macOS",
        "iOS",
        "windows",
        "linux"
      ]
    }

    client_app_types = ["all"]

  }

  grant_controls {
    built_in_controls = [
      "block"
    ]
    operator = "OR"
  }

  state = "enabledForReportingButNotEnforced"
}

```

### Expected Behavior

The terraform plan should have produced an output similar to the below output which is produced when I comment out the platform linux:

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # azuread_conditional_access_policy.block_unknown_platforms will be created
  + resource "azuread_conditional_access_policy" "block_unknown_platforms" {
      + display_name = "block access when using using unknown platforms"
      + id           = (known after apply)
      + state        = "enabledForReportingButNotEnforced"

      + conditions {
          + client_app_types = [
              + "all",
            ]

          + applications {
              + included_applications = [
                  + "All",
                ]
            }

          + locations {
              + included_locations = [
                  + "All",
                ]
            }

          + platforms {
              + excluded_platforms = [
                  + "android",
                  + "macOS",
                  + "iOS",
                  + "windows",
                ]
              + included_platforms = [
                  + "all",
                ]
            }

          + users {
              + included_users = [
                  + "All",
                ]
            }
        }

      + grant_controls {
          + built_in_controls = [
              + "block",
            ]
          + operator          = "OR"
        }
    }


Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

The below error was produced.

╷
│ Error: expected conditions.0.platforms.0.excluded_platforms.4 to be one of [all android iOS macOS unknownFutureValue windows windowsPhone], got linux
│
│   with azuread_conditional_access_policy.block_unknown_platforms,
│   on 2302_DGSTD302_tests.tf line 24, in resource "azuread_conditional_access_policy" "block_unknown_platforms":
│   24:         "linux"
│

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The conditionalAccessPlatforms resource in the Azure Graph API v1.0 now supports the value Linux as noted in the below reference.

### References

* https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessplatforms?view=graph-rest-1.0

**Comment by manicminer** [comment]
@soohonlee Thanks for reporting, we'll add this in tomorrow's provider release.
