### ISSUE TITLE
data.azuread_application unable to retrieve Microsoft Graph API with display name "Microsoft Graph"

### ISSUE THREAD

**Issue by GFPhillips** [hashicorp/terraform-provider-azuread#780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.10
on windows_amd64

* provider registry.terraform.io/hashicorp/azuread v2.21.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "azuread_application" "microsoft_graph_api" {
  display_name = "Microsoft Graph"
}

```

### Expected Behavior

No error, terraform should be able to retrieve the application using the display name "Microsoft Graph"

### Actual Behavior

The below error was produced.

╷
│ Error: Application not found
│ 
│   with data.azuread_application.microsoft_graph_api,
│   on main.tf line 1, in data "azuread_application" "microsoft_graph_api":
│   1: data "azuread_application" "microsoft_graph_api" {
│ 
│ No applications found matching filter: "displayName eq 'Microsoft Graph'"
╵

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I am running this against Azure B2C tenant. I am able to retrieve other applications in the tenant (created by us) without issues.

### References

* #0000

**Comment by manicminer** [comment]
@GFPhillips Thanks for reporting this. Can you confirm, whether you have created an application in that tenant and named it "Microsoft Graph"?

If you are looking for the service principal for the 1st-party Microsoft Graph app as published by Microsoft, then you'll need the `azuread_service_principal` data source instead. You can look up a service principal by display name, or for improved accuracy, by application ID (client ID).

```hcl
# Look up by display name
data "azuread_service_principal" "msgraph-by-name" {
  display_name = "Microsoft Graph"
}

# Look up by application ID
data "azuread_application_published_app_ids" "well_known" {}

data "azuread_service_principal" "msgraph-by-clientid" {
  application_id = data.azuread_application_published_app_ids.well_known.result.MicrosoftGraph
}
```

**Comment by GFPhillips** [comment]
Hi @manicminer , thanks for the quick reply and sample. - yep I meant the 1st party app

I have tested and this returns the correct source and can retrieve the expected attributes.

Closing
