### ISSUE TITLE
azuread_group resource creation crashes

### ISSUE THREAD

**Issue by trinka-battelle** [hashicorp/terraform-provider-azuread#796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0

### Affected Resource(s)

* `azuread_group'

### Terraform Configuration Files

```hcl
resource "azuread_group" "users" {
  display_name = "${var.deployment_id}-users"
  mail_nickname = "${var.deployment_id}-users"
  mail_enabled = true
  security_enabled = true
  types = ["Unified"]
  
  owners = [
    data.azuread_client_config.current.object_id
  ]
}
```

### Panic Output

```
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azuread_v2.22.0_x5 plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 29 [running]:
github.com/hashicorp/terraform-provider-azuread/internal/helpers.WaitForUpdateWithTimeout({0xe24ae8, 0xc000079440}, 0x1bf08eb000, 0xc0004a2cd8)
        github.com/hashicorp/terraform-provider-azuread/internal/helpers/consistency.go:77 +0x1a9
github.com/hashicorp/terraform-provider-azuread/internal/services/groups.groupResourceCreate({0xe24ae8, 0xc000079440}, 0xc0005b8b80, {0xbf72a0, 0xc0000b3500})
        github.com/hashicorp/terraform-provider-azuread/internal/services/groups/group_resource.go:618 +0x102d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004408c0, {0xe24b20, 0xc000016960}, 0xd, {0xbf72a0, 0xc0000b3500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004408c0, {0xe24b20, 0xc000016960}, 0xc000424b60, 0xc0005b8a00, {0xbf72a0, 0xc0000b3500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0x9ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000209cb0, {0xe24a78, 0xc00001cc80}, 0xc0004b1130)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003d6820, {0xe24b20, 0xc000016090}, 0xc0005a02a0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xcc1ae0, 0xc0003d6820}, {0xe24b20, 0xc000016090}, 0xc000078a20, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e8c0, {0xe33a48, 0xc0001b51e0}, 0xc0004fb0e0, 0xc000437ec0, 0x137a500, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00022e8c0, {0xe33a48, 0xc0001b51e0}, 0xc0004fb0e0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-azuread_v2.22.0_x5 plugin crashed!
```

### Expected Behavior

Should have produced a mail enabled security group.

### Actual Behavior

Plugin crashed

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running in a Azure Government

### References

* #0000

**Comment by martinhelgesen** [comment]
Same thing happens to me. Same message.
Running in regular Azure, no government
Running on MacBook Pro M1

resource "azuread_group" "reader" {
  display_name       = "PIM.${var.TEAM_AD_PREFIX}.READER"
  mail_enabled       = true
  mail_nickname      = "PIM-${var.TEAM_AD_PREFIX}-READER"
  security_enabled   = true
  types              = ["Unified"]
  assignable_to_role = true
}


 The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-azuread_v2.22.0_x5 plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 76 [running]:
github.com/hashicorp/terraform-provider-azuread/internal/helpers.WaitForUpdateWithTimeout({0x102e689e8, 0x140000813e0}, 0x1bf08eb000, 0x14000117bc0)
        github.com/hashicorp/terraform-provider-azuread/internal/helpers/consistency.go:77 +0x204
github.com/hashicorp/terraform-provider-azuread/internal/services/groups.groupResourceCreate({0x102e689e8, 0x140000813e0}, 0x14000097a00, {0x102d52720, 0x1400019ae00})
        github.com/hashicorp/terraform-provider-azuread/internal/services/groups/group_resource.go:618 +0x10f8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140004048c0, {0x102e68a20, 0x140004af200}, 0x14000097a00, {0x102d52720, 0x1400019ae00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140004048c0, {0x102e68a20, 0x140004af200}, 0x140002a4dd0, 0x14000097880, {0x102d52720, 0x1400019ae00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0xa4c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000dcb0, {0x102e68978, 0x140002aa940}, 0x140004a88c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140003b6780, {0x102e68a20, 0x140004ae7e0}, 0x140002480e0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x102e18ac0, 0x140003b6780}, {0x102e68a20, 0x140004ae7e0}, 0x14000080600, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000ae8c0, {0x102e75ac8, 0x140004921a0}, 0x140002ade60, 0x140003f9f50, 0x103389560, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x140000ae8c0, {0x102e75ac8, 0x140004921a0}, 0x140002ade60, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x140004a2520, 0x140000ae8c0, {0x102e75ac8, 0x140004921a0}, 0x140002ade60)
        google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0

Error: The terraform-provider-azuread_v2.22.0_x5 plugin crashed!

**Comment by manicminer** [comment]
Hi @trinka-battelle, @martinhelgesen, thanks for reporting this. It looks like this is the same issue as #812. Whilst this issue was opened first, I've opened a PR to close the other issue and so I'll mark this as a duplicate. We should have a fix out for this bug in this week's release.
