### ISSUE TITLE
Unable to remove redirectUri that is used as the defaultRedirectUri

### ISSUE THREAD

**Issue by PG-TwinsFan** [hashicorp/terraform-provider-azuread#799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
For an existing SAML application created via Terraform where the redirect_uri is updated results in the following error: "Unable to remove redirectUri that is used as the defaultRedirectUri". This causes the Terraform apply to fail.

### Affected Resource(s)

* `azuread_application`

### Expected Behavior

Add the updated redirect_uri before removing the old entry

### Actual Behavior

Attempts to remove the redirect_uri before adding the updated/new entry

### Steps to Reproduce

1. Create an azuread_application with a single redirect_uri and attempt to update it via a TF plan/apply.

**Comment by manicminer** [comment]
Hi @PG-TwinsFan, thanks for reporting this. I'm unable to reproduce this with a simple configuration, could you kindly provide a minimal config to reproduce this error from the API and I'll look further to see how we can resolve it. Thanks!

**Comment by PG-TwinsFan** [comment]
@manicminer Looks like this only occurs if the only redirect_uri is somehow changed to default:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/60155853/173565320-987ed350-cbf0-4b4e-8e41-2a2b8c973e1c.png">

When the redirect_uri is set to default a change to it via Terraform looks like:
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azuread_application.example has been changed
  ~ resource "azuread_application" "example" {
      + group_membership_claims        = []
        id                             = ""
      + owners                         = []
        tags                           = []
        # (13 unchanged attributes hidden)






        # (6 unchanged blocks hidden)
    }
  # azuread_service_principal.this has been changed
  ~ resource "azuread_service_principal" "this" {
      + alternative_names             = []
        id                            = ""
      + notification_email_addresses  = []
      + owners                        = []
        tags                          = [
            "WindowsAzureActiveDirectoryCustomSingleSignOnApplication",
            "WindowsAzureActiveDirectoryIntegratedApp",
        ]
        # (16 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to
these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azuread_application.example will be updated in-place
  ~ resource "azuread_application" "example" {
        id                             = ""
        tags                           = []
        # (15 unchanged attributes hidden)






      ~ web {
          ~ redirect_uris = [
              - "https://app.example.net/account",
              + "https://app.example.net/account/test",
            ]

            # (1 unchanged block hidden)
        }
        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azuread_application.example: Modifying... [id=]
╷
│ Error: Could not update application with object ID: ""
│ 
│   with azuread_application.example,
│   on main.tf line 1, in resource "azuread_application" "example":
│    1: resource "azuread_application" "example" {
│ 
│ ApplicationsClient.BaseClient.Patch(): unexpected status 400 with OData error: Request_BadRequest: Unable to remove redirectUri that is used as the defaultRedirectUri.
```
So while I cannot recreate it strictly via Terraform, if the configuration is changed outside of Terraform, it cannot update it.

**Comment by manicminer** [comment]
@PG-TwinsFan That makes sense - it looks like you are configuring SSO related settings for the Service Principal. This is not yet supported in Terraform due to lack of API support offered by Azure. Unfortunately there isn't a workflow we can support here, I would suggest using `ignore_changes` to have Terraform ignore the out-of-band changes that are caused by working in the portal here.
