### ISSUE TITLE
Conditional Access Policies should not require "grant_controls"

### ISSUE THREAD

**Issue by g-psantos** [hashicorp/terraform-provider-azuread#801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0

### Affected Resource(s)

- `azuread_conditional_access_policy`

### Terraform Configuration Files

```terraform
resource "azuread_conditional_access_policy" "limit_session_duration" {
  display_name = "Limit Session Duration for All Users"
  state        = "enabled"

  conditions {
    client_app_types = ["all"]
    applications { included_applications = ["All"] }

    users {
      included_users  = ["All"]
    }
  }

  session_controls {
    sign_in_frequency        = "30"
    sign_in_frequency_period = "days"
  }
}
```

### Expected Behavior

The above should produce a Conditional Access Policy that simply requires users to sign-in every 30 days. This is possible to achieve through the Azure Portal.

### Actual Behavior

The provider flags the configuration as invalid because it does not have a `grant_controls` block:

```hcl
│ Error: Insufficient grant_controls blocks
│
│   on X.tf line 1, in resource "azuread_conditional_access_policy" "limit_session_duration":
│  176: resource "azuread_conditional_access_policy" "limit_session_duration" {
│
│ At least 1 "grant_controls" blocks are required.
```

### Steps to Reproduce

1. `terraform apply`

### Workaround

Note also that one can make this work by including a "blank" block (see below) **_but_** you then get eternal Terraform drift after the first `apply` (see below also):

```terraform
grant_controls {
  operator          = "OR"
  built_in_controls = []
}
```

```terraform
  # azuread_conditional_access_policy.limit_session_duration will be updated in-place
  ~ resource "azuread_conditional_access_policy" "limit_session_duration" {
        id           = "redacted"
        # (2 unchanged attributes hidden)


      + grant_controls {
          + built_in_controls = []
          + operator          = "OR"
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by manicminer** [comment]
Hi @g-psantos, thanks for requesting this. Unfortunately we require the `grant_controls` block due to API constraints that do not seem to similarly affect the portal. I will circle back on this and see if maybe the API behavior has changed so that we are able to make this optional.

**Comment by manicminer** [comment]
I have tried creating a CA policy without grant controls, in the following combinations (as well as omitting it altogether), but each time still getting a `1032: ConditionalActionPolicy validation failed due to InvalidControls.` error.

```json
{
  "grantControls": {},
}
```
```json
  "grantControls": null,
```

**Comment by tpidor** [comment]
Hi, we're also trying to create policy with only session controls but no grant controls.

My terraform module snippet -

```
  grant_controls {
    operator                      = each.value.properties.grantControls.operator
    built_in_controls             = each.value.properties.grantControls.builtInControls
    terms_of_use                  = try(each.value.properties.grantControls.termsOfUse, [])
    custom_authentication_factors = try(each.value.properties.grantControls.customAuthenticationFactors, [])
  }

  dynamic session_controls {
    for_each = try(each.value.properties.sessionControls,null) == null ? [] : [each.value.properties.sessionControls]
    content {
      application_enforced_restrictions_enabled = try(session_controls.value.applicationEnforcedRestrictionsEnabled, null)
      cloud_app_security_policy                 = try(session_controls.value.cloudAppSecurityPolicy, null)
      persistent_browser_mode                   = try(session_controls.value.persistentBrowserMode, "always")
      sign_in_frequency                         = try(session_controls.value.signInFrequency, null)
      sign_in_frequency_period                  = try(session_controls.value.signInFrequencyPeriod, null)
    }
  }
```

These are the values from the input config to try as workaround -
```
        "grantControls" :  {
            "operator"  : "OR",
            "builtInControls"   :["unknownFutureValue"]
        },
        "sessionControls" :  {
            "applicationEnforcedRestrictionsEnabled": "true",
            "cloudAppSecurityPolicy"                : "monitorOnly",
            "signInFrequency"                       : "23",
            "signInFrequencyPeriod"                 : "hours",
            "persistentBrowserMode"                 : "never"
        }
```

But got this error during Terraform Apply -
```
  # module.cap.azuread_conditional_access_policy.azcap["12345"] will be updated in-place
  ~ resource "azuread_conditional_access_policy" "azcap" {
        id           = "ce45e31a-e04e-4f7d-b6e5-fe27f5d5263f"
        # (2 unchanged attributes hidden)


      ~ grant_controls {
          ~ built_in_controls             = [
              - "approvedApplication",
              + "unknownFutureValue",
            ]
            # (3 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.cap.azuread_conditional_access_policy.azcap["12345"]: Modifying... [id=ce45e31a-e04e-4f7d-b6e5-fe27f5d5263f]

Error: Could not update conditional access policy with ID: "ce45e31a-e04e-4f7d-b6e5-fe27f5d5263f"

  with module.cap.azuread_conditional_access_policy.azcap["12345"],
  on ../modules/cap/main.tf line 12, in resource "azuread_conditional_access_policy" "azcap":
  12: resource "azuread_conditional_access_policy" "azcap" {

ConditionalAccessPoliciesClient.BaseClient.Patch(): unexpected status 400
with OData error: BadRequest: 1007: Incoming ConditionalAccessPolicy object
is null or does not match the schema of ConditionalAccessPolicy type. For
examples, please see API documentation at
https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-1.0.
```

If you got some workaround to only specify session controls with irrelevant grant controls or no grant controls at all, please advise. Thanks in advance.

**Comment by manicminer** [comment]
This is unfortunately an API validation issue that we cannot work around. The API does not support some configurations that are valid in the portal.

**Comment by gh05ted** [comment]
Is it possible to have this re-evaluated? Microsoft API documentation does not show the grantControls property as being required: https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-1.0

**Comment by gh05ted** [comment]
Can we get the Terraform documentation updated for this? The built_in_controls block is required, but having a defined value under it is not required. This enables session controls to be used without requiring any grant controls. Working example:

grant_controls {
  operator          = "AND"
  built_in_controls = []
}

**Comment by IdahoVandal** [comment]
> Can we get the Terraform documentation updated for this? The built_in_controls block is required, but having a defined value under it is not required. This enables session controls to be used without requiring any grant controls. Working example:
> 
> ```
> grant_controls {
>     operator          = "AND"
>     built_in_controls = []
> }
> ```

Leaving the values as empty does allow you to manage the policy but every plan/apply considers the policy as changed.
```
- grant_controls {
  - built_in_controls = [] -> null
  - operator          = "AND" -> null
}
```
We also had to add ignore_changes to the resource lifecycle.
```hcl
lifecycle {
  ignore_changes = [
    grant_controls,
  ]
}
```
