### ISSUE TITLE
Support for OIDC Authentication

### ISSUE THREAD

**Issue by rhyspaterson** [hashicorp/terraform-provider-azuread#803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With version 1.2 of Terraform and version 3.7 of the azurerm provider now released and both supporting OIDC for authentication, it would be great to port this functionality and leverage this in the azuread provider, too. For example, I can now provision the relevant infrastructure on the azurerm side via OIDC authentication. But if during this deployment I want to reference an Azure AD group via the azuread provider, I cannot adopt the same authentication approach.

### New or Affected Resource(s)

The authentication components within the `azurerm` provider.

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  use_oidc = true
}
```

### References

* https://github.com/hashicorp/terraform-provider-azurerm/pull/16555

**Comment by Satak** [comment]
Would be great to get that PR merged. Exited to use OIDC with AAD provider too :-)
