### ISSUE TITLE
userprincipalname cannot be changed for a user

### ISSUE THREAD

**Issue by QuduSEC** [hashicorp/terraform-provider-azuread#811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
# Configure the Microsoft Azure AD Provider
provider "azuread" {
    tenant_id = var.aad_tenant_id
}

# Retrieve domain information
data "azuread_domains" "default" {
  only_initial = true
}

# Load users
locals {
  domain_name = data.azuread_domains.default.domains.0.domain_name
  users       = csvdecode(file("${path.module}/data/users.csv"))
}

# Manage users

resource "azuread_user" "users" {
  for_each = { for user in local.users : user.id => user }

  user_principal_name = format(
    "%s%s@%s",
    substr(lower(each.value.first_name), 0 , 1),
    lower(each.value.last_name),
    local.domain_name
  )

  password = format(
    "%s%s%s!",
    lower(each.value.last_name),
    substr(lower(each.value.first_name), 0 , 1),
    length(each.value.first_name)
  )
  force_password_change = true

  display_name = "${each.value.first_name} ${each.value.last_name}"

  department   = each.value.department
  job_title    = each.value.job_title
}

```

### Expected Behavior

user_principal_name will change, the user will not be deleted and created for this, the object id will be saved

### Actual Behavior

Changing user_principal_name causes the user object to be deleted and a new one created

### Steps to Reproduce

1.  Create file users.csv
```
id,first_name,last_name,department,job_title
0001,Bob,Great,Cybersec Team,SecOps
0002,Steven,Great,DevOps Team,DevOps Team Lead
```
2. `terraform apply`
3. Change first_name for a user with id 0001
```
id,first_name,last_name,department,job_title
0001,Nick,Great,Cybersec Team,SecOps
0002,Steven,Great,DevOps Team,DevOps Team Lead
```
4. `terraform apply` or `terraform plan`

or simple change domain_name

### Important Factoids

1. user_principal_name can be changed in the portal without re-creation
3. this operation is normal, because the company's domain may change

### References

* #0000

**Comment by manicminer** [comment]
Thanks for requesting this @QuduSEC, I have opened #815 to permit changing the UPN.
