### ISSUE TITLE
Error "panic: interface conversion: interface {} is nil, not bool" when creating Microsoft 365 Groups

### ISSUE THREAD

**Issue by epomatti** [hashicorp/terraform-provider-azuread#812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```bash
$ terraform --version
Terraform v1.2.2
on linux_amd64
```

```hcl
azuread = {
  source  = "hashicorp/azuread"
  version = "2.22.0"
}
```

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.22.0"
    }
  }
}

resource "azuread_group" "default" {
  display_name     = "MyGroup"
  security_enabled = true
  mail_enabled     = true
  mail_nickname    = "MyGroup"
  types            = ["Unified"]
}
```

### Debug Output

https://gist.github.com/epomatti/078aeabbf4e5cdd085d24a5e3b42ecdd

### Panic Output

No panic was produced.

### Expected Behavior

Group should be created without erros.

### Actual Behavior

Group seems to be created succesfully, but the Terraform CLI fails with the reported error.

![image](https://user-images.githubusercontent.com/6530769/171527367-3a31995f-9ed1-4653-9483-a3eeb877aa62.png)

### Steps to Reproduce

```bash
az login
terraform init
terraform apply -auto-approve
```

### Important Factoids

None.

### References

None.

**Comment by manicminer** [comment]
Thanks for reporting this crash @epomatti, I have opened #816 to address this.
