### ISSUE TITLE
Saml Claims in azure ad application

### ISSUE THREAD

**Issue by Bazilbrush** [hashicorp/terraform-provider-azuread#821]
Having issues with saml claims and how to represent them in HCL
In azure console, in enterprise application > single sign-on >attributes and claims section the claims are represented as more of a key/value pair, e.g. 
https://aws.amazon.com/SAML/Attributes/SessionDuration    "14400"
with respective fields named Name/Namespace and Source attribute
How does the source attribute value translate into HCL  in the resource? 
To check how the claims are structured in terraform we tried using the data source for the ad application. We pulled an existing app into state which has a set of known claims, but the additional claims block returns an empty list. Is that normal behaviour? 

After going over the docs only this structure made sense, but additional properties doesn't like the assigned value.
```
 saml2_token {
             name = "https://aws.amazon.com/SAML/Attributes/RoleSessionName"
             essential = true
             source = "user"
             additional_properties = ["user.assignedroles"]
         }
```
I hope someone can help me with understanding this

**Comment by manicminer** [comment]
Hi @Bazilbrush, Enterprise Applications are actually Service Principals and are not the same thing as Applications. SAML configuration for SPs (Enterprise Apps) is unsupported at this time due to lack of API support offered by Azure.
