### ISSUE TITLE
Fixed Azure Bug where no Owners assigned when creating Gallery Applications

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-azuread#834]
Sorry for raising this as a bug, more of an informational 

Hi @manicminer - I have gotten Microsoft to fix an Azure bug whereby when you instantiate a Gallery App through the graph API applications/instantiate, you don't get any Owners assigned. This was different to when you do it in the portal.azure website where if you instantiate a Gallery App, you do get owners assigned. Microsoft have told me they have rolled this out across all Azure tenants now.

Now Owners are assigned properly through the Graph API it means that creating Gallery Apps only requires the more limited Application.ReadWrite.OwnedBy permission, rather than the Application.ReadWrite.All permission. 

This unblocks me finalising the work on #679 , which I now aim to complete very shortly

**Comment by manicminer** [comment]
Hi @gtmtech, thanks for the headsup. I'm not seeing any corresponding entry in the [changelog](https://developer.microsoft.com/en-us/graph/changelog/?search=&filterBy=Applications) though?

**Comment by gtmtech** [comment]
I had a response from Microsoft:

```
Hi Geoff,

I’ve had a response from the devs, unfortunately there isn’t any public confirmation of this bug fix in the changelog. I’ve pestered them to see if they can get something published and will let you know if there’s an update.
```

I will update you if there's a further update to me.
