### ISSUE TITLE
Changing the password for a user does not work: UsersClient.BaseClient.Patch(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation. 

### ISSUE THREAD

**Issue by mllab-nl** [hashicorp/terraform-provider-azuread#835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

v1.2.2

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

resource "azuread_user" "test" {
...
  password            = "xxxx"
...

}

### Debug Output

PATCH /beta/xxxxx/users/4e0e34c8-3311-48d3-9635-4419bd8da5d4 HTTP/1.1
Host: graph.microsoft.com
User-Agent: HashiCorp Terraform/1.2.2 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azuread/dev Hamilton (Go-http-client/1.1) pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 725
Accept: application/json; charset=utf-8; IEEE754Compatible=false
Content-Type: application/json; charset=utf-8
Odata-Maxversion: 4.0
Odata-Version: 4.0
Accept-Encoding: gzip

{"accountEnabled":true,"ageGroup":null,"city":null,"companyName":null,"consentProvidedForMinor":null,"country":null,"department":null,"displayName":"test1","employeeId":null,"employeeOrgData":{"costCenter":"","division":""},"employeeType":null,"faxNumber":null,"givenName":"test1","id":"4e0e34c8-3311-48d3-9635-4419bd8da5d4","jobTitle":null,"mailNickname":"test1","mobilePhone":null,"officeLocation":null,"otherMails":[],"passwordPolicies":null,"passwordProfile":{"forceChangePasswordNextSignIn":false,"password":"xxxx"},"postalCode":null,"preferredLanguage":null,"showInAddressList":false,"state":null,"streetAddress":null,"surname":"test1","usageLocation":null,"userPrincipalName":"test1@xxxxx.onmicrosoft.com"}

PATCH https://graph.microsoft.com/beta/xxxxx/users/4e0e34c8-3311-48d3-9635-4419bd8da5d4
Request ID: 3e46047c-c701-a3f5-be6b-e21fd7ba02e8

HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Cache-Control: no-cache
Client-Request-Id: 4e27bc0e-322c-4ac9-9a57-c3f38e9b6a2d
Content-Type: application/json
Date: Fri, 01 Jul 2022 14:36:24 GMT
Deprecation: Thu, 17 Feb 2022 23:59:59 GMT
Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,Users&from=2022-02-01&to=2022-03-01>;rel="deprecation";type="text/html"
Request-Id: 4e27bc0e-322c-4ac9-9a57-c3f38e9b6a2d
Strict-Transport-Security: max-age=31536000
Sunset: Sat, 30 Apr 2022 23:59:59 GMT
Vary: Accept-Encoding
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"AM1PEPF000105B6"}}
X-Ms-Resource-Unit: 1

10a
{"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2022-07-01T14:36:25","request-id":"4e27bc0e-322c-4ac9-9a57-c3f38e9b6a2d","client-request-id":"4e27bc0e-322c-4ac9-9a57-c3f38e9b6a2d"}}}
0

### Expected Behavior

Password updated

### Actual Behavior

apply fails with an error. Next apply detects no changes

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Authentication using 
provider "azuread" {
  client_id     = "xxx"
  client_secret = "xxx"
  tenant_id     = "xxx"
}

App registration has all possible permissions including documented 
User.ReadWrite.All or Directory.ReadWrite.All
 

### References
Is this possible with Service principal ? 
https://docs.microsoft.com/nl-nl/graph/api/user-update?view=graph-rest-beta&tabs=http

* #0000

**Comment by manicminer** [comment]
Hi @mllab-nl, thanks for raising this. This is more of an Azure usage question since it relates to permissions, which the provider has no control over. The permissions requried when updating various user properties can vary depending on the determined seniority of the user being amended, and whether or not application permissions are support for that property. To the best of my knowledge, passwords can be changed by an application (e.g. service principal) with sufficient privileges.

Since this is more of a usage question, I would encourage you to direct your question towards Azure Support or perhaps the [MS Graph Tech Community Group](https://techcommunity.microsoft.com/t5/microsoft-graph/bd-p/OfficeGraph). Thanks!

**Comment by mllab-nl** [comment]
@manicminer Don`t you think it would be helpful to a broad audience to describe currently known  limitations/details in the documentation of the provider ? 
https://github.com/hashicorp/terraform-provider-azuread/blob/main/docs/resources/user.md
if you know a way to make password change work using a Service Principal authentication, could you please share it. 
Anyway would be helpful to have as much info in the docs as possible, probably with some statements you make here as well. 
So that it would be easier for people to find there way. 
Thank you !

**Comment by manicminer** [comment]
@mllab-nl Whilst we try to make our documentation as useful as possible, it is infeasible for us to track and document these specifics of API behavior as they relate to permissions on a per-property basis, particularly as they have a tendency to change without notice.
