### ISSUE TITLE
Support for user principal names in azuread group owner parameter

### ISSUE THREAD

**Issue by arne21a** [hashicorp/terraform-provider-azuread#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The /[azuread](https://github.com/aztfmod/terraform-azurerm-caf/tree/main/modules/azuread)/[groups](https://github.com/aztfmod/terraform-azurerm-caf/tree/main/modules/azuread/groups) module only supports owners via object id.
For my use case it would be nice to be able to reference user principal names instead.

I will provide a pull request with a proposal.

### New or Affected Resource(s)/Data Source(s)

azuread_group

### Potential Terraform Configuration

```hcl
group_key = {
    name                   = "name"
    description            = "description"
    prevent_duplicate_name = true
    owners = {
      user_principal_names = ["foo@mail.com", "baz@mail.com"]
    }
  }
```

**Comment by tombuildsstuff** [comment]
Transferring to the `azuread` provider since this is an AzureAD request

**Comment by manicminer** [comment]
Hi @arne21a, thanks for requesting this. Whilst I agree that there's a potential UX improvement in enabling this, I doubt we'll implement this for a couple of reasons. The first is that the UPN is mutable, whereas the object ID is not. This can lead to unexpected results and further complications around ordering operations when for example a UPN is changed for a user. The second reason is that the provider is intentionally organized on a code level into discreet packages as much as possible, and I'm personally not sure this justifies importing/instantiating the Users API client in the groups package.

Accordingly, I'm going to close this for now but if you feel there is a wider benefit beyond convenience that I haven't considered, please feel free to comment further. Thanks!

**Comment by arne21a** [comment]
Thanks for reviewing my request. 
This feature derived from the idea that other modules have interfaces for other resources referenced by key and lz_key.
This module has no such interface. That means that you will need to add object_ids to your "infrastructure as data" tfvars files.
It feels like missing the point of IaD having to get object_ids from cli or ansible to add those to the config.

Also your azuread_groups_membership implementation and your own docs already support or mention this.
```
azuread_groups_membership = {
  workload_developer = {
    members = {
      user_principal_names = [
        ...
     ]
```
In my thinking, that's just consistent with the other related ressources.

**Comment by arne21a** [comment]
I just realized my issue was moved to the provider repo.
I am not requesting to add this feature to the terraform provider! I just want to add a feature to the azure caf module.
[This is my PR to implement this in caf](https://github.com/aztfmod/terraform-azurerm-caf/pull/1248)
Not sure how this ended up here, did I mess up?
