### ISSUE TITLE
Changing display_name parameter value during second terraform apply results in force replacement of the resource in azuread_application_password

### ISSUE THREAD

**Issue by ccsandhanshive** [hashicorp/terraform-provider-azuread#848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
terraform 1.0.0
azuread 2.20.0

### Affected Resource(s)

* `azuread_application_password`

### Debug Output
```
$ terraform apply
*************.this["***********"]: Refreshing state... [id=*********************/password/a74dd7fc-4a83-4ef1-87a2-02a04dda37f7]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # *************.this["*********"] must be replaced
-/+ resource "azuread_application_password" "this" {
      + display_name          = "trial" # forces replacement
      ~ end_date              = "2024-07-18T15:50:21Z" -> (known after apply)
      ~ id                    = "*******************/password/a74dd7fc-4a83-4ef1-87a2-02a04dda37f7" -> (known after apply)
      ~ key_id                = "a74dd7fc-4a83-4ef1-87a2-02a04dda37f7" -> (known after apply)
      ~ start_date            = "2022-07-18T15:50:21Z" -> (known after apply)
      ~ value                 = (sensitive value)
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions in workspace "**********"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

********************.this["***************"]: Destroying... [id=****************/password/a74dd7fc-4a83-4ef1-87a2-02a04dda37f7]
********************.this["*************"]: Still destroying... [id=******************/pa...d/a74dd7fc-4a83-4ef1-87a2-02a04dda37f7, 10s elapsed]
********************.this["****************"]: Still destroying... [id=****************/pa...d/a74dd7fc-4a83-4ef1-87a2-02a04dda37f7, 20s elapsed]
*****************.this["***************"]: Destruction complete after 21s
*******************.this["******************"]: Creating...
*****************.this["**************"]: Creation complete after 5s [id=***************/password/03e41f39-0349-410d-ae97-38ce9aa29f17]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

```

### Expected Behavior
 - Changing display_name parameter should not force a new resource to be created during second terraform apply ( performing terraform apply after resource creation )
 - If it is an expected behaviour then in terraform document it should be mentioned to avoid confusion

### Actual Behavior
Terraform recreate resource in terraform apply command if any change detected in display_name parameter

### Steps to Reproduce

1. `terraform apply`
2. Change the value of display_name parameter
3. terraform apply

### References

* #0000

**Comment by Threpio** [comment]
The `display_name' part of the schema for this resource currently has `ForceNew: true` set and so the resource will be re-created if this is changed.

I am not 100% sure if this is intentional - I will dig a bit and see if Azure actually requires the resource to be re-created if the display name is changed or if this can be set to false.

https://github.com/hashicorp/terraform-provider-azuread/blob/bf65f5d71a5f080a7006b3a1d34f4af74903adad/internal/services/applications/application_password_resource.go#L63

**Comment by ccsandhanshive** [comment]
Are there any updates on this?

**Comment by Threpio** [comment]
Sorry for not writing @ccsandhanshive.

Neither the Portal nor the PWSH library lets you change the display_name of the `application_password`.

I will add a pr to update the docs to reflect that it forces a re-creation.

**Comment by manicminer** [comment]
Thanks for the docs fix @Threpio. Closing this one for now as looks like a documentation issue rather than a bug.
