### ISSUE TITLE
How to realistically use azuread_invitation?

### ISSUE THREAD

**Issue by timon-michel-scopevisio** [hashicorp/terraform-provider-azuread#851]
I'm currently trying to implement the "azuread_invitation" resource to invite a user if it not already exists.

I managed to get it working like this:
```hcl
locals {
  external_users: ["test@test.com"]
}

data "azuread_users" "all" {
  return_all = true
}

resource "azuread_invitation" "guests" {
  for_each = {
    for username in local.external_users:
        username => username
    if !contains(data.azuread_users.all.users.*.mail, username)
  }

  user_email_address = each.key
  redirect_url       = "https://example.com"
}
```

This way if the specified user in `locals.external_users` is not found in AD, an invitation is created. If i, however run another time without changing the code, it tries to delete the user as it is now invited into the organization.
If i delete the "invitation" using terraform, it deletes the whole user instead:
https://github.com/hashicorp/terraform-provider-azuread/blob/bf65f5d71a5f080a7006b3a1d34f4af74903adad/internal/services/invitations/invitation_resource.go#L233

I understand that the "invitations" endpoint of MS Graph is POST-Only so there is no real way to "delete" an invitation. But deleting the whole user instead is not what i expected. How can i create an invitation without deleting the freshly invited user afterwards?

There is probably no ideal solution to this as Microsoft will probably not change their API for this - so is there any workaround? I would be fine with Terraform just making the invitation a "submit-and-forget".

**Comment by manicminer** [comment]
Hi @timon-michel-scopevisio, thanks for raising this. We understand the implementation of the azuread_invitation resource is limiting and we have plans to improve this by incorporating invite functionality into the azuread_user resource instead. This should allow for more robust user maangement - guest, member, invited, or homed - or a combination of these!

Whilst there is no specific ETA at this time, this is on our roadmap and is being tracked in #650.
