### ISSUE TITLE
In azuread_group rule parameter of 'dynamic membership' block is required but in terraform documentation it is marked as 'Optional'

### ISSUE THREAD

**Issue by MayuriD89** [hashicorp/terraform-provider-azuread#857]
**Terraform (and AzureAD Provider) Version**

- Terraform v1.0.0
- Azuread Plugin Version v2.20.0

**Affected Resource**

- azuread_group

**Expected Behavior**

- azuread_group resource should get successfully created even if rule parameter from 'Dynamic membership' block is not specified.

**Actual Behavior**

- terraform throws following error if 'rule' parameter is not specified -

           
![image](https://user-images.githubusercontent.com/71746353/182677267-62f3a067-30b0-4f7e-bc4c-e185f7e66209.png)

        
- Seems like terraform documentation provides a wrong information 'rule' parameter is 'Required' and this should be updated in future releases.

**Steps to Reproduce**

- terraform plan
- terraform apply

**Comment by manicminer** [comment]
Thanks for the report @MayuriD89. We'll look to fix this in the docs.
