### ISSUE TITLE
Error: Invalid resource type

### ISSUE THREAD

**Issue by nimblenitin** [hashicorp/terraform-provider-azuread#860]
Getting below error while trying to assign ad role to principal 
Error: Invalid resource type
│ 
│   on ../../modules/infrastructure/cloud-scanner-app/main.tf line 51, in resource "azuread_directory_role_assignment" "example":
│   51: resource "azuread_directory_role_assignment" "example" {
│ 
│ The provider hashicorp/azuread does not support resource type "azuread_directory_role_assignment".

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Threpio** [comment]
Hi there! Thanks for raising this issue.

Can you please provide your terraform snippet regarding these resources? 

Thank you

**Comment by nimblenitin** [comment]
Hey this was fixed once i bumped the provider version. Was something related to the version.
