### ISSUE TITLE
azuread_group - security type

### ISSUE THREAD

**Issue by pir8g33k** [hashicorp/terraform-provider-azuread#861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_group ( group types: Security)
Security groups are used to give group members access to applications, resources and assign licenses. Group members can be users, devices, service principals, and other groups.

Microsoft Security groups to be added on the terraform configuration

### Potential Terraform Configuration

  types                          = ["Security"] or 
  group_  types             = ["Security"]
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Threpio** [comment]
Hi there! Thanks for creating this issue.

There is already a flag to set a `azuread_group_resource` to be ` security_enabled = true`.

Please see here:
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group
