### ISSUE TITLE
azuread_application_certificate: start_date parameter accepts past date value for Symmetric key

### ISSUE THREAD

**Issue by chennagouda14** [hashicorp/terraform-provider-azuread#865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.0
provider registry.terraform.io/hashicorp/azuread v2.20.0

### Affected Resource(s)

* `azuread_application_certificate`

### Terraform Configuration Files

- In the below terraform configuration, the start_date specified is the past date for the symmetric key.

```
resource "azuread_application" "example" {
  display_name = "example"
}

resource "azuread_application_certificate" "example" {
  application_object_id = azuread_application.example.id
  encoding              = "pem"
  start_date            = "2022-08-01T00:00:00Z"
  end_date              = "2023-03-31T00:00:00Z"
  type                  = "Symmetric"
  value                 = file("symmetric_key_01.txt")
}

```

### Expected Behavior

- For Symmetric key (when type=”Symmetric”):
  - If the start_date specified is current date or future date, then terraform apply should be successful.
  - If the start_date specified for a symmetric key is **past date** then in this case, terraform apply should ideally throw an error.
  - The only applicable values for symmetric key start_date should be the current date and future date.

### Actual Behavior

- For Symmetric key (when type=”Symmetric”):
  - If the start_date specified for a symmetric key is **past date** then in this case, terraform apply does not throw an error. The provided **past date** value gets applied to the resource successfully.

Please find the below output of terraform apply executed on **17th Aug 2022**
![image](https://user-images.githubusercontent.com/90911826/185221648-81ca9e30-86b6-4a08-bf58-4c43595c8935.png)

**On Azure portal:**
 ![image](https://user-images.githubusercontent.com/90911826/185221764-c468d1ff-2818-4ded-a986-89447e3658b6.png)

On the azure portal, we can see that the start date mentioned for the symmetric key is the past date.

**Can you please confirm if this is a bug or it is by design?**

### Steps to Reproduce

1. `terraform apply`

### References

- Terraform reference
   https://registry.terraform.io/providers/hashicorp/azuread/2.20.0/docs/resources/application_certificate

**Comment by manicminer** [comment]
Hi @chennagouda14, thanks for reporting this. As this behavior is permitted by the API, this is not considered a bug. Thanks!
