### ISSUE TITLE
SAML attributes and claims

### ISSUE THREAD

**Issue by anwickes** [hashicorp/terraform-provider-azuread#868]
Hi all, I know this question was already asked and closed under here (https://github.com/hashicorp/terraform-provider-azuread/issues/821) however I see that we now have the following resources available to us.

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/claims_mapping_policy
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_claims_mapping_policy_assignment

I'm wondering if anyone has had any experiences with adding saml claims and attributes via this method and if they have some examples. I'm trying to replicate the following:

```
New Claim

Name: nameidentifier
Namespace: http://schemas.xmlsoap.org/ws/2005/05/identity/claims
Name identifier format: Email address
Source: Attribute
Source attribute: user.onpremisessamaccountname


Group Claim

All groups
Source attribute: sAMAccountName
customize group claim name: groups
```

Thanks all, 
Adam

**Comment by anwickes** [comment]
For anybody else wondering this, the following seems to have done the job for me.

```
[
          {
            "Source": "user",
            "ID": "onpremisessamaccountname",
            "SamlClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
          },
          {
            "Source": "user",
            "ID": "mail",
            "SamlClaimType": "email"
          },
          {
            "Source": "user",
            "ID": "country",
            "SamlClaimType": "country"
          },
          {
            "Source": "user",
            "ID": "groups",
            "SamlClaimType": "groups"
          }
]
```

**Comment by manicminer** [comment]
@anwickes We appreciate the feedback, however as we use GitHub issues for tracking bugs and feature requests, not to provide support, I'm going to have to close this.

I recommend joining our community Slack to get in contact with other provider users - instructions are in the project readme.
