### ISSUE TITLE
Bug: service_principal_password doesn't create a password

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azuread#871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.27.0
```

### Affected Resource(s)

* `azuread_service_principal_password`

### Terraform Configuration Files

```hcl
resource "azuread_application" "test" {
  display_name = "test"
}

resource "azuread_service_principal" "test" {
  application_id = azuread_application.test.application_id
}

resource "azuread_service_principal_password" "test" {
  service_principal_id = azuread_service_principal.test.object_id
}
```

### Expected Behavior

An Azure service principal client secret is created for the app registration.

### Actual Behavior

Terraform output says a secret is created, but the secret is not found via state file or the Azure portal.

### Important Factoids

`azuread_application_password` **does** create a client secret for the application. No note of `azuread_service_principal_password` being deprecated.

**Comment by manicminer** [comment]
@mclacore I believe you are looking for the azuread_application_password resource, as service principal passwords are no longer visible in the portal.

**Comment by mclacore** [comment]
When did that change? What's the difference?

**Comment by manicminer** [comment]
I don't recall exactly when, but application credentials were introduced several years back and I think the service principal credentials blade was removed from the portal sometime in 2018. I would recommend reading [this Azure AD help article](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) for background information on how applications and service principals interact in different scenarios.
