### ISSUE TITLE
Support internal notes field for azuread_application

### ISSUE THREAD

**Issue by Crono1981** [hashicorp/terraform-provider-azuread#889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unless I'm mistaken, there's currently no way to set the content of "internal notes" field for a registered application. For reference, this field appears in Azure's GUI under the "Branding & properties" subsection.

### New or Affected Resource(s)

* azuread_application

**Comment by ezequielan** [comment]
Hello,
we have a case of use and need this feature, please :)
