### ISSUE TITLE
Support federated identity credential for user-assigned managed identities

### ISSUE THREAD

**Issue by dhirschfeld** [hashicorp/terraform-provider-azuread#900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Similar to https://github.com/hashicorp/terraform-provider-azuread/pull/705 but for User-Assigned Managed Identities.

### New or Affected Resource(s)

I think this would be a new resource?

Not sure of the  best name, `azuread_managed_identity_federated_identity_credential` is a bit of a mouthful 😅 

### Potential Terraform Configuration

I'll leave that up to the experts!

### References

* https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust-user-assigned-managed-identity?pivots=identity-wif-mi-methods-azcli
* https://github.com/Azure/azure-workload-identity/issues/325#issuecomment-1264419354

**Comment by jkroepke** [comment]
There is already a PR https://github.com/hashicorp/terraform-provider-azurerm/issues/18617

**Comment by dhirschfeld** [comment]
Closing as I assume this has been resolved by [#19199](https://github.com/hashicorp/terraform-provider-azurerm/pull/19199).

If there is anything to do here this can always be reopened.
