### ISSUE TITLE
documented permissions for azuread_group_member should account for group ownership.

### ISSUE THREAD

**Issue by kewalaka** [hashicorp/terraform-provider-azuread#909]
The documentation states that:

> When authenticated with a service principal, this resource requires one of the following application roles: Group.ReadWrite.All or Directory.ReadWrite.All

This is correct but appears to be incomplete.  

An alternative is to grant the service principal ownership rights over the group.  This allows for Terraform to manage group membership over specific groups rather than "all".

See https://github.com/kewalaka/tfSample-azureadmembership

**Comment by manicminer** [comment]
Hi @kewalaka, thanks for raising this. Group permissions are complicated, can vary by tenant/configuration, and are at times, buggy. Unfortunately this is why we don't currently elaborate on the required permissions. Having the `Groups.ReadWrite.All` app role or the Groups Administrator directory role are known to work for all users, at this time working out more granular permissions is an exercise for the practitioner and for official documentation.

**Comment by kewalaka** [comment]
thanks for the feedback @manicminer, understand the position and all good.  

Regarding the lack of an owner role, I think that would be undesirable (same problem, too large blast radius).  In many orgs I see an approach where an 'identity' team owns AD and manages the creation of the group and setting the owner (e.g. using azuread_groups), this can then be delegated to consumers who use azuread_group_member to manage membership.  

I'd agree the approach does look a little fragile since you wouldn't expect to be able to modify membership without an API consent (I actually didn't expect it to work).  IMO a better way would be if Microsoft allowed you to put scopes on Graph API roles, but that's a whole different discussion.

Happy with closure.

**Comment by manicminer** [comment]
FWIW I believe this is an area that is being worked on by Microsoft, so we may see more granular or otherwise improved permissions for applications in future.
