### ISSUE TITLE
azuread_application data source "api" block appears to be a list with 1 element rather than a single element

### ISSUE THREAD

**Issue by SeanKilleen** [hashicorp/terraform-provider-azuread#917]
In [the documentation for the data source for `azuread_application`](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/application), I see:

> The following attributes are exported:
>     [api](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/application#api) - An api block as documented below.

I was attempting to reference a list item of oauth2_permission_scopes:

`data.azuread_application.REDACTED_api.api.oauth2_permission_scopes[index(data.azuread_application.REDACTED_api.api.oauth2_permission_scopes.*.value, "Security.Read")].id`

I saw the following error:

> Can't access attributes on a list of objects. Did you mean to access attribute "oauth2_permission_scopes" for a specific element of the list, or across all elements of the list?

Taking the cue from the error, Updated my reference from `.api.oauth2_permission_scopes` to `.api[0].oauth2_permission_scopes` and my called succeeded as expected.

So there seems to be a mismatch between the stated documentation and the actual behavior. I'm not sure which one should be modified. Does the `azuread_application.api` always contain a list of 1 element? Or will it occasionally have multiple? 

If this is confirmed to be a docs issue I'm happy to make the associated update in a PR; just not sure how to confirm it.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.3.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
+ provider registry.terraform.io/hashicorp/azurerm v3.16.0

### Affected Resource(s)

* Datasource `data.azuread_application`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I should be able to call `data.azuread_application.APP_NAME.api.oauth2_permission_scopes[index]`

### Actual Behavior

I have to call `data.azuread_application.APP_NAME.api[0].oauth2_permission_scopes[index]` (the `api[0]` is the unexpected change.)

**Comment by manicminer** [comment]
Hi @SeanKilleen, thanks for reporting this. This is an implementation detail of Terraform in general where blocks are not singular attributes but are represented as lists, even when the block can only have one instance. You'll find the same across all Terraform providers. Accordingly, I think this probably doesn't warrant coverage in the provider documentation, although there may be a case for mentioning this in general Terraform documentation (if it isn't already covered somewhere).

**Comment by SeanKilleen** [comment]
@manicminer thanks for clarifying this! I wasn't aware of that convention. 👍
