### ISSUE TITLE
Reintroduce `azuread_application_app_role` / decouple `required_resource_access` under `azuread_application`?

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [hashicorp/terraform-provider-azuread#924]
### Description

Currently in a situation where `required_resource_access` in `azuread_application` prevents creation of let's say apps A, B, C with a, b, c roles and having all apps cross-reference each other circularly. 

Afaik current dynamic solutions would rely on monkey patching... Which is not ideal.

So is it possible to have decoupled resource `required_resource_access` under `azuread_application`? 

With a separate applications' required_resource one can create a batch of apps and then cross-link them totally at most. 

### New or Affected Resource(s)
* something new like `azuread_application_required_resource`
* bring back old `azuread_application_app_role` if it's related?

### Potential Terraform Configuration
```terraform
resource "azuread_application" "apps" {
   for_each = { ... }
   ...
}

resource "azuread_application_required_resource" "apps-resources" {
   depends_on = [ azuread_application.apps ]
   for_each = { ... }
   app_id = ...
   resource_app_id = ...
   resource_access {
      id   = ...
      type = ...
    }
}
```

**Comment by manicminer** [comment]
Hi @ZeChArtiahSaher, thanks for raising this request. Splitting up the application resource into discreet virtual resources is something we are considering for the next major version of the provider. This definitely falls into that category and as such I'm going to mark this accordingly, and we'll consider adding a resource for `required_resource(s)`.

**Comment by pdebuitlear** [comment]
Does this relate to/overlap with  #1001 ?

**Comment by michelefa1988** [comment]
Following

**Comment by Dzeneralen** [comment]
Is there a recommended approach when dealing with app registrations and scopes/roles? Currently I'm stuck with cyclical references as one app reg references another one. 

Would love some direction if someone has solved the issue with creating the app registrations first and then assigning scopes/roles afterwards. So far I've only been successful in granting admin consent but not the actual roles and scopes.

**Comment by manicminer** [comment]
@Dzeneralen At this time there is no native workaround for cases where cyclical references occur within an app manifest. However, we're looking to resolve this in the near future with the introduction of some new resources.

**Comment by manicminer** [comment]
We'll be introducing some new resources in the next release including `azuread_application_app_role` and `azuread_application_api_access` (decoupled `required_resource_access` from the `azuread_application` resource).
