### ISSUE TITLE
(azuread_conditional_access_policy) Support for `disableResilienceDefaults`

### ISSUE THREAD

**Issue by teesana** [hashicorp/terraform-provider-azuread#931]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft has recently added a new session control to Conditional Access Policies called "Resilience defaults", and a new field on Conditional Policies called `disableResilienceDefaults`. We have a case where we do in fact want to disable them. It would be nice to be able to set that through terraform.

### New or Affected Resource(s)

- `azuread_conditional_access_policy`

### Potential Terraform Configuration

```hcl
resource "azuread_conditional_access_policy" "CA-disable-resilience-defaults" {
  display_name = "Session Policy - Disable resilience defaults"
  state        = "enabledForReportingButNotEnforced"

  conditions { ... }

  session_controls {
    disable_resilience_defaults = true
  }
}
```

### References

- https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccesssessioncontrols?view=graph-rest-1.0
- https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/resilience-defaults

**Comment by manicminer** [comment]
Closed in error
