### ISSUE TITLE
Ability to set "Writeback enabled" on azuread_group resources

### ISSUE THREAD

**Issue by tomasmota** [hashicorp/terraform-provider-azuread#934]
Perhaps I am missing something, but I could not find the ability to set the writeback property on azure ad groups in the documentation. This is something that is supported in the api and the UI, can this be set with the provider in some other way?

**Comment by tomasmota** [comment]
I would like to implement this, but need some advice on how to structure it.

This option takes in two parameters, which map to this payload in the client:
```
"writebackConfiguration": {
    "isEnabled": true,
    "onPremisesGroupType":  UniversalSecurityGroup
},
```

I can imagine two ways this could look like in the group resource:

``` hcl
# Option 1
resource "azuread_group" "group" {
  display_name = "MyGroup"

  writeback_enabled      = true
  on_premises_group_type = "UniversalSecurityGroup"
}

# Option 2
resource "azuread_group" "group" {
  display_name = "MyGroup"

  writeback {
    enabled             = true
    onPremisesGroupType = "UniversalSecurityGroup"
  }
}
```

when setting only IsEnabled, the type seems to default to what makes sense for the group type.

**Comment by manicminer** [comment]
@tomasmota Thanks for taking a look at this. Taking into account the other group properties, I'm inclined to prefer the first option (top-level properties) with the naming `onpremises_group_type` to match the existing properties.
