### ISSUE TITLE
Unable to create Azure AD Application with readwrite.ownedby permissions

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform-provider-azuread#939]
Linking back to a similar issue:

https://github.com/hashicorp/terraform-provider-azuread/issues/116

This is still not working for me, I've upgraded to 2.30.0 AzureAD, and the service principal which is trying to create the Azure AD app IS in the list of owners (as the documentation states is required). The documentation also states that this still "may" not work.

What is the timeline for this being supported in a reliable way?

│ Error: Could not create application
│
│   with module.azuread_application_test_create.azuread_application.ad_application,
│   on ../modules/azuread_application/azuread_application.tf line 1, in resource "azuread_application" "ad_application":
│    1: resource "azuread_application" "ad_application" {
│
│ ApplicationsClient.BaseClient.Post(): unexpected status 403 with OData
│ error: Authorization_RequestDenied: Insufficient privileges to complete the
│ operation.

Thanks,
Wayne

**Comment by manicminer** [comment]
Hi @waynejnicklin, thanks for reporting. However this is an API issue and not something the provider has any control over. Additionally it's possible that permissions are applied differently depending on your tenant settings and other opaque factors. We specify the owner when creating an application, and this is all we can do.

Accordingly, I'm going to close this and recommend opening an Azure support ticket to diagnose your issue further.

**Comment by waynejnicklin** [comment]
We have tested this using Postman calling Graph API directly, with the exact same service connection, and this works OK and is able to create new applications and amend existing ones.

It's just through the Terraform code that this is not working and giving me the 403 error.

**Comment by waynejnicklin** [comment]
It seems to only be an issue when we set the mapped_claims_enabled property to true. This issue has also been raised here:

https://github.com/hashicorp/terraform-provider-azuread/issues/914
