### ISSUE TITLE
Import existing AAD into Terraform HCL

### ISSUE THREAD

**Issue by ytimyno** [hashicorp/terraform-provider-azuread#943]
**Description**
A blocker of Terraform adoption when managing AAD is the lack of support to, more than importing the existing AAD state, generate the configuration file that matches it.

Is there any plans to make this available? Would be a massive contribution. Or if there is any tool providing this level of functionality.

Thanks
y

**Comment by Threpio** [comment]
No. There are no plans within this module to support the 'reverse-engineering' or generation of an AzureAD HCL file from your current context.

This is not supported or presented by any terraform module that I am aware of (happy to be proven wrong). Note that there are a bunch of tools that claim to be able to reverse engineer and yet none have been made publically available.

**Comment by ytimyno** [comment]
Fair enough! I was looking at things like Azure Terrafy (techcommunity [post 1](https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-terrafy-import-your-existing-azure-infrastructure-into/ba-p/3357653), [post 2](https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azure-terrafy-and-azapi-terraform-provider-previews/ba-p/3270937?WT.mc_id=modinfra-566685-apedward)).

Are there any blockers for this kind of reverse engineering? Do you have any concerns?

Thanks!

**Comment by Threpio** [comment]
I have not seen that tool before but have written things as tools for work like that in the past. Maintaining a reverse engineering tool is not the easiest thing in the world.

There is no problem with others building this kind of reverse engineering but it should not live within the AzureAD terraform module.

**Comment by manicminer** [comment]
Thanks for raising this. As @Threpio mentions, this need has historically been filled by community tools and to my knowledge is not a function of Terraform at this time.
