### ISSUE TITLE
Feature enhancement for AzureAD directory role assignment

### ISSUE THREAD

**Issue by lyndon678** [hashicorp/terraform-provider-azuread#958]
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description
Azure AD allows multiple role assignable security groups to be associated with a directory role. The azuread_directory_role_assignment resource currently doesn't reflect that possibility. The used principal_object_id property should be able to accept a list instead of only a string.

### New or affected resource(s)
- azuread_directory_role_assignment

### Potential Terraform configuration
```
resource "azuread_directory_role" "Security-Reader" {
  display_name = "Security Reader"
}

resource "azuread_group" "osg_security-operations-member" {
  display_name            = "osg_security-operations-member"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}
resource "azuread_group" "osg_cloud-manager-member" {
  display_name            = "osg_cloud-manager-member"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}

resource "azuread_directory_role_assignment" "secops_Security-Reader" {
  role_id = azuread_directory_role.Security-Reader.template_id
  principal_object_id = [azuread_group.osg_security-operations-member.object_id,
    azuread_group.osg_cloud-manager-member.object_id]
}
```

### References
- https://learn.microsoft.com/en-us/azure/active-directory/roles/groups-concept

**Comment by andrewdcraig** [comment]
👍🏻

**Comment by manicminer** [comment]
Hi @lyndon678, thanks for reporting this. In this case you would need to use multiple `azuread_directory_role_asignment` resources, as each resource is for managing a role assignment for a single principal. For example:

```hcl
resource "azuread_directory_role" "Security-Reader" {
  display_name = "Security Reader"
}

resource "azuread_group" "osg_security-operations-member" {
  display_name            = "osg_security-operations-member"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}
resource "azuread_group" "osg_cloud-manager-member" {
  display_name            = "osg_cloud-manager-member"
  security_enabled        = true
  assignable_to_role      = true
  prevent_duplicate_names = true
}

resource "azuread_directory_role_assignment" "security-operations_Security-Reader" {
  role_id             = azuread_directory_role.Security-Reader.template_id
  principal_object_id = azuread_group.osg_security-operations-member.object_id
}

resource "azuread_directory_role_assignment" "cloud-manager_Security-Reader" {
  role_id             = azuread_directory_role.Security-Reader.template_id
  principal_object_id = azuread_group.osg_cloud-manager-member.object_id
}
```
