### ISSUE TITLE
azuread.user

### ISSUE THREAD

**Issue by Benliu987** [hashicorp/terraform-provider-azuread#961]
I have asked Microsoft that 'division' can not be set in AAD anymore, but I can see 'division' in terraform. Can I use that as user's property? Or you guys wants to delete it?
---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by Threpio** [comment]
Which version of Terraform AzureAD are you using? 

I cannot see this attribute in the current/Latest version.

**Comment by manicminer** [comment]
This field has not been removed. It is [still present](https://learn.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-1.0) and such removal would be a breaking change and unlikely to happen without a deprecation period.
