### ISSUE TITLE
Azuread.user

### ISSUE THREAD

**Issue by Benliu987** [hashicorp/terraform-provider-azuread#962]
I found that there is a property called 'extension attributes' in the user of aad. Does terraform support to use this attribute?
---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by Threpio** [comment]
The terraform azuread module does not currently support this attribute.

**Comment by manicminer** [comment]
If you'd like to request this feature, please open a new issue using the template provided. Thanks!
