### ISSUE TITLE
Add support for clientApplications in azuread_conditional_access_policy

### ISSUE THREAD

**Issue by antonvdl** [hashicorp/terraform-provider-azuread#985]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for clientApplications in azuread_conditional_access_policy to support Managed Identity policies.
clientApplications is already available in v1 of the Microsoft Graph API

### New or Affected Resource(s)

* azuread_conditional_access_policy

### Potential Terraform Configuration

```hcl
resource "azuread_conditional_access_policy" "limit_app_to_ip" {
  display_name = "Limit application to IP"
  state        = "enabledForReportingButNotEnforced"

  conditions {
    client_app_types = ["all"]

    applications {
      included_applications = ["All"]
    }

    locations {
      included_locations = ["All"]
      excluded_locations = [azuread_named_location.trusted_location.id]
    }

    users {
      included_users = ["None"]
    }

    service principals {
      included_service_principals = [azuread_service_principal.service1.id]
      excluded_service_principals = []
    }
  }
  grant_controls {
    operator          = "OR"
    built_in_controls = ["block"]
  }
}
```

### References
https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-1.0

**Comment by benoit74** [comment]
I'm working on it
