### ISSUE TITLE
Tags not working for azuread_service_principal

### ISSUE THREAD

**Issue by ThisIsRichardWork** [hashicorp/terraform-provider-azuread#986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

2.33.0

### Affected Resource(s)

azuread_service_principal

### Terraform Configuration Files
```
     azuread = {
      source = "hashicorp/azuread"
      version = "2.33.0"
    }
 

resource "azuread_service_principal" "asp" {
  application_id               = azuread_application.aa.application_id
  app_role_assignment_required = false
  use_existing                 = true
  tags = [
    "CreatedBy_Terraform",
    "AssetID_${var.asset_id}"
  ]
  
}
```

### Debug Output
```
      + tags                         = [
          + "AssetID_1234",
          + "CreatedBy_Terraform"
        ]
      + type                         = (known after apply)
      + use_existing                 = true

      + feature_tags {
          + custom_single_sign_on = (known after apply)
          + enterprise            = (known after apply)
          + gallery               = (known after apply)
          + hide                  = (known after apply)
        }
```
### Expected Behavior

Tags strings should be created on the resource.

### Actual Behavior

No strings are listed in the tags section for the resource. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Why is the feature_tags shown in the output when they are not ref in the code

### References

* #0000

**Comment by Threpio** [comment]
Feature tags for an Azure Service Principal are not a 'tag' that is applicable for all other resources. 

Feature tags are additional features that are available for the Azure Service Principles and unless defined we take the return from Azure after creation.

The Azure portal is currently down but when it is back up I will take screenshots of where this information can be found in the portal.

**Comment by manicminer** [comment]
Thanks for opening this issue @ThisIsRichardWork. As @Threpio noted, tags here are actually more like feature labels and are not for your own use. I will look at updating the documentation to make this clearer.

**Comment by ThisIsRichardWork** [comment]
We are currently using tags as a label, so are you telling us that Terraform is not going to support tags as a label on service prinicipal and we should add the labels using powershell?

**Comment by ThisIsRichardWork** [comment]
Agreed, we are not using them as label not tags.  In the ticket I included how we are using them as a list of strings.

**Comment by manicminer** [comment]
Hi @ThisIsRichardWork, it's not that the provider doesn't support this - looking at the diff excerpt you supplied, the provider is trying to set the values you specified and I don't see any evidence of a bug here. `feature_tags` is a computed field and so you will always see it in a diff, whether you have specified it or not.

This field has loaded values and is specifically used, by Azure, for configuring behaviors on the service principal, which is why we do not recommend using it for user-supplied tag values.

**Comment by ThisIsRichardWork** [comment]
When we create the following the "Tags" or Labels are not created in azure.  We can use powershell of the API to create the "Tags", I just saw that the docs show that this is a function of Terraform.  If the TAGS attubute is not supported then we will find another way to create the tags.

resource "azuread_service_principal" "asp" {
  application_id               = azuread_application.aa.application_id
  app_role_assignment_required = false
  use_existing                 = true
  tags = [
    "CreatedBy_Terraform",
    "AssetID_${var.asset_id}"
  ]

}
