### ISSUE TITLE
azuread_application - support the description property (#977)

### ISSUE THREAD

**Issue by farwind** [hashicorp/terraform-provider-azuread#989]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by farwind** [comment]
i dont see any update in terraform documentation in regards to mentioned added property, it's not mentioned there anywhere, did someone miss the update on the documentation by any chance ?

**Comment by manicminer** [comment]
Thanks for the headsup @farwind, looks like the documentation got missed. The property is there, just not documented - we'll fix this asap.
