### ISSUE TITLE
Better support for multiple applications with same name from azuread_application datasource

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-azuread#997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Trying to use a datasource to look up an azuread_application by name and receiving this error:

```
 Error: Multiple applications found
│ 
│   with module.foo.data.azuread_application.this,
│   on .terraform/modules/.../datasources.tf line 1, in data "azuread_application" "this":
│    1: data "azuread_application" "this" {
│ 
│ Found multiple applications matching filter: "displayName eq
│ 'myapp'"
```

Problem is that we have more than one application with the same name. I think some of our apps have been deleted, only one appears in searching in portal.azure, but they remain in the catalog, and the deletedDateTime is null for all of them. The Graph API returns all 2 or 3 apps, so I'm not sure how to distinguish the "real" one, except for the creation date being the latest. 

Therefore I would like to be able to return a single app with the most recent created date, in the event that there are more than one app found by name. 

### New or Affected Resource(s)

* data.azuread_application

### Potential Terraform Configuration

TBD?

**Comment by Threpio** [comment]
This is an interesting issue and I am unaware that Azure would return multiple applications in the case that they are not visible within the portal and had been deleted/inactivated.

I would propose adding an additional argument along the lines of: 
```
data "azuread_application" "example" {
   display_name = "This Duplicate Application"
   return_latest_only = true
}
`
``

Would we want this to throw an error or exception if it only returns a single application and we expected multiple? Is there a situation where two different active applications would be required and working?

**Comment by manicminer** [comment]
@gtmtech Thanks for reporting this. As far as I am aware, deleted applications should not be returned by the API, and in fact when testing it just now I do not observe this behavior. I suspect you that replication delay (aka eventual consistency) may have been at play when you observed this? If indeed the API is returning deleted applications, this is most definitely an API bug and should be reported as such to Microsoft.

I have thought about this and I do not believe such a workaround would be suitable for a data source. Whether you order by date, by name or some other property, nothing prevents someone creating another application and manipulating, either intentionally or accidentally, the behavior of your Terraform module - which would simply proceed without warning you or giving you any indication that it had adopted a different application. Such a feature would inevitably lead to inconsistent and unpredictable behavior, both of which are behaviors we probably don't want to attribute to Terraform.

Accordingly, whilst I appreciate your suggestion, I'm going to close this issue as we likely will not plan to add such a feature to this, or any other data source.
