### ISSUE TITLE
Add data

### ISSUE THREAD

**Issue by Benliu987** [hashicorp/terraform-provider-azuread#998]
I have many user data in AAD. But what if I don't want to code them in data one by one, what should I do? Could the module make that possible?

**Comment by Benliu987** [comment]
I mean I want the user resource become user datasource.

**Comment by Threpio** [comment]
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users

There is a data source that returns multiple users. You can specify `return_all = true` to return all users. 

Does that answer your question?

**Comment by Benliu987** [comment]
Thank you for your answer! I know the article you have sent, but what I want is that I don't have to input all the emails. Terraform will automatically generate all the User Data for me. And I have a little question here, the Name for the data-sources is "Users", what if I need to use the user separately?

**Comment by Threpio** [comment]
There is no way to generate the AzureAD User blocks/code in terraform I am afraid. 

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/user is the only resource for single users and so a module for them will need to be written in your terraform code. 

A similar request was from issue: #943

**Comment by Threpio** [comment]
If you use the `users` data source you can then specify an output that is an array of users.

Something like: 
```
data "azuread_users" "users" {
   return_all = true
}

output "all_users" = data.azuread_users.users.users
```

Might work to give you all the data as an output. I have not tested the above code.

**Comment by Benliu987** [comment]
I tried your code. It should be:
```

data "azuread_users" "users" {
  return_all = true
}

output "users" {
  value = data.azuread_users.users.users
}
```
And I guess you misunderstood me. I have already coded all the users as resources. I would like to make them to be data-sources in order to call the users data in groups.

**Comment by Threpio** [comment]
You can reference a user's fields as a new data source. 

If you assign those users as part of their code as members of a group then you can use the Group data source to reference all of them?

Maybe if I better understood your problem here I could help more but I need more context.

**Comment by manicminer** [comment]
@Benliu987 Thanks for opening this issue. You may find [this tutorial](https://developer.hashicorp.com/terraform/tutorials/it-saas/azure-ad) on managing users and groups useful. However, we use this issue tracker for primarily tracking bugs and feature requests for the AzureAD provider, and instead ask that you direct your questions to our [community resources](https://www.terraform.io/community). Accordingly, I'm going to close this issue but if you find a potential bug, or if you have a feature request for the maintainers, please feel free to open a new issue using one of the issue templates provided.
